### ISSUE TITLE
MathML title with Jaws 2020 causes stability problems in Thoriumk

### ISSUE THREAD

**Issue by GeorgeKerscher** [edrlab/thorium-reader#1000]
We have started to test the Advanced Mathml title 1.2.3. Testing went well with NVDA. However, when testing with Jaws 2020 George experienced stability issues. Prashant confirmed that when using ctrl+page down to move to the section 090, that Thorium crashed. George had this same problem initally, but now Thorium immediately crashes. George is testing with 1.2.0 and with 1.3 alpha 1.476f. other titles seem to behave OK. I also tried to navigate with the table of contents, and was able to get to sections, and it did not read much of anything. I could tab and hear one or two items.

**Comment by danielweck** [comment]
Merging issue to https://github.com/edrlab/thorium-reader/issues/1709
