### ISSUE TITLE
Add a shortcut to show the current page and resume navigation

### ISSUE THREAD

**Issue by nvdaes** [edrlab/thorium-reader#1004]
To find out the current print page, screen reader users need to move the cursor to navigation and then try to find the previous position. It would be useful a modal which maybe open with a shortcut and close with Escape to know where we are in the book. Reading system tests require at least to know the current section (heading) and page. Headings can be found out throught Elements list dialog, for example in NVDA, but info about pages is tricky to find out.

**Comment by danielweck** [comment]
The nearest preceding page break (i.e. as authored in HTML files, and usually reflected in the "page list" of the EPUB3 navigation document as well) is given just below the "go to page" functionality at the bottom of the navigation panel (CTRL-N keyboard shortcut if my memory serves me well). In a future revision of Thorium, there will be a "where am I" modal popup dialog to quickly summarize the reading / listening context.

**Comment by nvdaes** [comment]
danielweck commented 2 hours ago 

> The nearest preceding page break (i.e. as authored in HTML files, and usually reflected in the "page list" of the EPUB3 navigation document as well) is given just below the "go to page" functionality at the bottom of the navigation panel (CTRL-N keyboard shortcut if my memory serves me well).

This is right.

> In a future revision of Thorium, there will be a "where am I" modal popup dialog to quickly summarize the reading / listening context.

Thanks, this will be useful.

**Comment by ways2read** [comment]
In 1.6.0-alpha.1.473359159 the current page number is shown in brackets (parenthesis) after the Go to button in the Navigation menu.

If there is no current page number it is shown as two brackets with nothing between, thus: ()

With NVDA and Narrator default settings, this page information is silent.

Some suggestions for improvement:

- some reading systems place the current page number in the edit box, and a shortcut to go directly to it is helpful (for screen reader users and other keyboard users). Ctrl G is a commonly used combination. 
- if the text must exist after the Go to button as in the current design, it could helpfully display "Current page: 12" or similar
- if there are no page numbers, then perhaps this part of the UI should not appear. Alternatively, it could say "No page numbers" instead of "()"

**Comment by nvdaes** [comment]
It would be great if the page number could be placed in the label of
the edit box. In this way, the edit box would remain empty, which
would be better for some users so we don't need to delete the current
number, and we could read it with the screen reader, for example
pressing NVDA+tab to read the focused element, or even with NVDA+f7
selecting form fields radio button.

2021-01-12 13:50 GMT+01:00, Richard Orme <notifications@github.com>:

**Comment by danielweck** [comment]
The "current page" UI label and the "goto page" UI input text field have recently changed in a Pull Request related to PDF support. This will be merged soon into the develop branch, at which point we will review this as per your recommendations. Thank you very much!

**Comment by danielweck** [comment]
Note to devs: `src/renderer/reader/components/ReaderMenu.tsx` and `reader.navigation.currentPage`
PR: https://github.com/edrlab/thorium-reader/pull/1285

**Comment by nvdaes** [comment]
Great. BTW, recently I read something about keystrokes to search
previous and next, though I'm not sure. I looked at the shortcut keys
wiki page, but this was updated in Octover. When this needs to be
updated, I'll try to translate it into Spanish and share it.
Thank so much to you!

2021-01-12 16:57 GMT+01:00, Daniel Weck <notifications@github.com>:

**Comment by danielweck** [comment]
> I read something about keystrokes to search previous and next, though I'm not sure. I looked at the shortcut keys wiki page, but this was updated in Octover. When this needs to be updated, I'll try to translate it into Spanish and share it.

Thank you Noelia! <smile>

I updated the English wiki page:

https://github.com/edrlab/thorium-reader/wiki/Keyboard-shortcuts

Below the line that says:

`CTRL` + `f` (`FocusSearch`): in reader window, moves the keyboard focus to the publication-wide search text input

... I added:

`SHIFT` (optional) + `F3` (`SearchPrevious` / `SearchNext`): in reader window, when the publication-wide search text input is open, finds the previous / next match

and:

`SHIFT` (optional) + `CTRL` + `G` (`SearchPreviousAlt` / `SearchNextAlt`): same as above (alternative keyboard shortcut)

**Comment by nvdaes** [comment]
> Thank you Noelia!
> 
> I updated the English wiki page:
> 
> https://github.com/edrlab/thorium-reader/wiki/Keyboard-shortcuts
> 
> Below the line that says:
> 
> `CTRL` + `f` (`FocusSearch`): in reader window, moves the keyboard focus to the publication-wide search text input
> 
> ... I added:
> 
> `SHIFT` (optional) + `F3` (`SearchPrevious` / `SearchNext`): in reader window, when the publication-wide search text input is open, finds the previous / next match
> 
> and:
> 
> `SHIFT` (optional) + `CTRL` + `G` (`SearchPreviousAlt` / `SearchNextAlt`): same as above (alternative keyboard shortcut)

Hi Daniel, thanks for your work on this amazing app! I've updated the spanish wiki page with your changes following your guidance. For readability it's available in HTML (with lang="es") at <https://nvdaes.github.io/epub7>
Here's the markdown file compressed as .zip, so you can edit the spanish wiki for this repo.
[Keyboard-shortcuts-(Spanish).zip](https://github.com/edrlab/thorium-reader/files/5810842/Keyboard-shortcuts-.Spanish.zip)

**Comment by danielweck** [comment]
Thank you! The Spanish wiki is now up to date: https://github.com/edrlab/thorium-reader/wiki/Keyboard-shortcuts-(Spanish)

**Comment by nvdaes** [comment]
Thanks Daniel for updating the spanish wiki page.

**Comment by danielweck** [comment]
> In 1.6.0-alpha.1.473359159 the current page number is shown in brackets (parenthesis) after the Go to button in the Navigation menu.
> 
> If there is no current page number it is shown as two brackets with nothing between, thus: ()
> 
> With NVDA and Narrator default settings, this page information is silent.
> 
> Some suggestions for improvement:
> 
>     * some reading systems place the current page number in the edit box, and a shortcut to go directly to it is helpful (for screen reader users and other keyboard users). Ctrl G is a commonly used combination.
> 
>     * if the text must exist after the Go to button as in the current design, it could helpfully display "Current page: 12" or similar
> 
>     * if there are no page numbers, then perhaps this part of the UI should not appear. Alternatively, it could say "No page numbers" instead of "()"

"Goto page" improvements in this Pull Request (the CTRL-G keyboard shortcut is already allocated to the "find next" command in the "publication search" feature, but we can use another key):
https://github.com/edrlab/thorium-reader/pull/1319

**Comment by danielweck** [comment]
Noelia, I added a new keyboard shortcut to the wiki:
https://github.com/edrlab/thorium-reader/wiki/Keyboard-shortcuts

```
* `SHIFT` + `CTRL` + `p` (`FocusReaderGotoPage`): in reader window, moves the keyboard focus to the "goto page" section in the navigation panel
```

I added this immediately below `FocusReaderNavigation`.

**Comment by danielweck** [comment]
Richard, Noelia, I tested the improved UI with VoiceOver on MacOS and it seems fine. Feel free to suggest improvements.

**Comment by nvdaes** [comment]
I will download the latest pre-release and will test it with NVDA.. I can test also daisy books from ONCE library if yoo proride guidance. They are in zip format. Should I change the extension?

**Comment by danielweck** [comment]
Daisy3 digital talking books are supported (not Daisy2.02). Not sure about NIMAS extension / variants. All 3 types are supported: Text-only, Full Text and Audio (synchronised), and Audio-only. The filesets must be zipped with the .daisy extension. We will try to relax this requirement in a future release, including allowing opening unzipped Daisy filesets (e.g. from the OPF package file).
Support for Daisy2.02 is in early design stages.

**Comment by nvdaes** [comment]
OK, I'm not sure about DAISY format used by ONCE. I'll see.


2021-01-15 22:22 GMT+01:00, Daniel Weck <notifications@github.com>:

**Comment by ways2read** [comment]
Ah, OK. 

See example 4 at http://kb.daisy.org/publishing/docs/navigation/pagelist.html)

Following the example for an inline page break marker works in other EPUB reading systems. In Thorium the navigation works, but the current page number is not reported.

However, adding  `epub:type="pagebreak"`  means the page number is displayed.

**Comment by danielweck** [comment]
The discussion thread in this issue has become unproductive and confusing. I filed a separate issue for the EPUB pagebreak / pagelist problem, now fixed: https://github.com/edrlab/thorium-reader/issues/1597
The "where am I" feature was actually requested in an older issue: https://github.com/edrlab/thorium-reader/issues/570
So I am now closing this one (the conversation thread remains accessible, of course, for future reference)
