### ISSUE TITLE
Localization / l10n: Thorium info files English and Spanish contain up to date list of supported languages, other locales need updating

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1007]
See this PR to see when the info Markdown file was updated for English and Spanish: https://github.com/readium/readium-desktop/pull/1006

**Comment by llemeurfr** [comment]
Is this issue still true?

**Comment by nvdaes** [comment]
The readme.md file is not updated. Maybe difficult to mention the available languages, but in this case maybe better to ommit all them?

**Comment by llemeurfr** [comment]
The readme will be updated for the 1.5 release, I think that it's good to have a list of languages there for teasing newcomers, even if this means we have to maintain it. Thanks Noelia. 

Re. the "More information" window, as we are inside the app itself and the Settings show the list of available languages, we should delete this list, which is not so interesting here.

**Comment by nvdaes** [comment]
OK, thank you

**Comment by danielweck** [comment]
Fixed.
