### ISSUE TITLE
Question: could you add translations for the wiki of this repo?

### ISSUE THREAD

**Issue by nvdaes** [edrlab/thorium-reader#1019]
One of the major problems for the adoption of certain technologies like epub or good reading systems maybe the lack of translated documentation.
@danielweck , do you think we could translate the [article about shortcuts](https://github.com/readium/readium-desktop/wiki/Keyboard-shortcuts)?

**Comment by nvdaes** [comment]
Sorry @danielweck . I didn't see that you added the locale label. I will translate the keyboard commands into Spanish tomorrow. Thanks.

**Comment by nvdaes** [comment]
I have translated the keyboard shortcuts document. Imo, this could be translated in GH pages, since I don't know a clean way to include non English files in wikis (for instance using the HTML attribute).
I will share this on spanish mailing lists in case someone wants to provide feedback. I have translated some keynames and commands descriptions, which may not be understood in Spanish, since this maybe useful to manage the keyboard shortcuts editor.
Feedback is appreciated.

**Comment by nvdaes** [comment]
[Keyboard-shortcuts.es.txt](https://github.com/edrlab/thorium-reader/files/4742202/Keyboard-shortcuts.es.txt)

**Comment by nvdaes** [comment]
The attached file is in markdown format, just changed extension to attach it here.

**Comment by danielweck** [comment]
This is great, thank you Noelia!
I created a separate Spanish Wiki page alongside the English one:
https://github.com/edrlab/thorium-reader/wiki/Keyboard-shortcuts-(Spanish)

Could you please append the following (this is new in the upcoming Thorium release):

* `CTRL` + `1` (`AudioPrevious`): in reader window, calls the "previous" command for audio (TTS or EPUB3 Media Overlays readaloud, or "rewind" for audiobooks)
* `CTRL` + `2` (`AudioPlayPause`): in reader window, calls the "play" or "pause" toggle commands for audio (TTS or EPUB3 Media Overlays readaloud)
* `CTRL` + `3` (`AudioNext`): in reader window, calls the "next" command for audio (TTS or EPUB3 Media Overlays readaloud, or "forward" for audiobooks)
* `CTRL` + `4` (`AudioStop`): in reader window, calls the "stop" command for audio (TTS or EPUB3 Media Overlays readaloud, or "pause" for audiobooks)

**Comment by nvdaes** [comment]
Hi Daniel, this is great! I will append this in a few hours today.
PS: I also discovered small issues (not important) regarding NVDA used
with Thorium and mentioned @edrlab. I have an app module of NVDA
created by me that may fix them. I was waiting for the new release to
send a pull request to NVDA so developers can review it.

2020-07-07 16:05 GMT+02:00, Daniel Weck <notifications@github.com>:

**Comment by nvdaes** [comment]
Hi Daniel, wiki cannot be edited. I'm commenting to see if I can find the attach button again

**Comment by nvdaes** [comment]
Nota para desarrolladores: [este PR](https://github.com/readium/readium-desktop/pull/958) introdujo soporte para atajos de teclado configurables en Thorium.

* `CTRL` + `F10` (`FocusMain` - llevar el foco al contenido principal): en las ventanas del lector y la biblioteca, desplaza el foco del teclado a la zona de referencia "principal" (en la vista del lector, esta zona se encuentra justo antes del marco que muestra el contenido de la publicación).
* `CTRL` + `t` (`FocusToolbar` - llevar el foco a la barra de herramientas): en las ventanas del lector y la biblioteca, desplaza el foco del teclado a la barra de herramientas horizontal superior, justo antes del enlace "pasar a" (que por sí mismo desplaza el foco a la zona de referencia "principal").
* `CTRL` + `n` (`FocusReaderNavigation` - llevar foco a navegación del lector): en la ventana del lector, desplaza el foco del teclado al panel de navegación (tabla de contenido, marcadores, etc.).
* `CTRL` + `s` (`FocusReaderSettings` - llevar foco a configuración del lector): en la ventana del lector, desplaza el foco del teclado al panel de opciones de configuración (preferencias de usuario para mostrar el contenido de la publicación).
* `CTRL` + `b` (`ToggleBookmark` - cambiar estado de marcador): en la ventana del lector, cambia el estado del marcador (se produce una notificación de modo que los lectores de pantalla informen del cambio).
* `CTRL` + `F11` (`ToggleReaderFullscreen` - cambiar estado de pantalla completa del lector): en la ventana del lector, cambia el estado de pantalla completa.
* `CTRL` + `i` (`OpenReaderInfo` - abrir información del lector): en la ventana del lector, cuadro de diálogo modal emergente con información de la publicación (en una futura versión de Thorium, podría usarse para una función similar en la ventana biblioteca).
* `CTRL` + `w` (`CloseReader` - cerrar lector): en la ventana del lector, cierra la ventana y vuelve a la vista de biblioteca.
* `CTRL` + `f` (`FocusSearch` - llevar foco a búsqueda): en la ventana de biblioteca, desplaza el foco del teclado al cuadro de entrada de texto para buscar en el estante local o en la fuente OPDS (en una futura versión de Thorium, podría usarse para una función similar en la ventana del lector).
* `CTRL` + `left` o `right` - control + izquierda o derecha (`NavigatePreviousOPDSPage` / `NavigateNextOPDSPage` - navegar a página OPDS anterior o siguiente): en  la ventana biblioteca, para fuentes OPDS, activa los enlaces de paginación anterior o siguiente.
* `CTRL` + `comma` o `period` - control + coma o punto (`NavigatePreviousOPDSPageAlt` / `NavigateNextOPDSPageAlt` - alternativa para navegar a página OPDS anterior o siguiente): igual que lo anterior (atajo de teclado alternativo).
* `CTRL` + `SHIFT` + `ALT` (excepto en MacOS) + `left` o `right` - izquierda o derecha (`NavigatePreviousChapter` / `NavigateNextChapter` - navegar a capítulo anterior o siguiente): en la ventana del lector, se desplaza al "capítulo" anterior o siguiente (elemento de "spine" en orden de lectura de la publicación). Observa que el foco del teclado se desplaza automáticamente a la zona de referencia "principal", que está justo antes del marco que muestra el contenido de la publicación (exactamente igual que cuando se sigue/activa un enlace de la tabla de contenido).
* `CTRL` + `page up` o `page down` - control + retroceso o avance de página (`NavigatePreviousChapterAlt` / `NavigateNextChapterAlt` - alternativa para navegar al capítulo anterior o siguiente): igual que lo anterior (atajo de teclado alternativo).
* `left` o `right` - izquierda o derecha (`NavigatePreviousPage` / `NavigateNextPage` - navegar a la página anterior o siguiente): en la ventana del lector, se desplaza a la "página" anterior o siguiente (o unidad de desplazamiento, si la paginación está desactivada).
* `CTRL` + `comma` o `period` - control + coma o punto (`NavigatePreviousPageAlt` / `NavigateNextPageAlt` - alternativa para navegar a página anterior o siguiente): igual que lo anterior (atajo de teclado alternativo).
* `CTRL + 1` (`AudioPrevious` - anterior en audio): en la ventana del lector, invoca el comando "anterior" para audio (texto a voz, lectura en voz alta en EPUB3 con multimedia o "retroceder" en audiolibros).
* `CTRL + 2` (`AudioPlayPause` - reproducir o pausar audio): en la ventana del lector, invoca los comandos para "reproducir" o "pausar" audio (texto a voz o lectura en voz alta en EPUB3 con multimedia).
* `CTRL + 3` (`AudioNext` - siguiente en audio): en la ventana del lector, invoca el comando "siguiente" para audio (texto a voz, lectura en voz alta en EPUB3 con multimedia o "avanzar" en audiolibros).
* `CTRL + 4` (`AudioStop` - detener audio): en la ventana del lector, invoca el comando "detener" audio (texto a voz, lectura en voz alta en EPUB3 con multimedia o "pausar" en audiolibros).

**Comment by nvdaes** [comment]
[Keyboard-shortcuts.es.txt](https://github.com/edrlab/thorium-reader/files/4886343/Keyboard-shortcuts.es.txt)

**Comment by nvdaes** [comment]
I have attached the file. The button to select files seems not to be labelled properly and sometimes, at least in some comments, is not easy to find for me using NVDA. Hope this helps.

**Comment by danielweck** [comment]
Brilliant, I updated the Wiki. Thank you very much (on behalf of the Spanish-speaking community)

**Comment by nvdaes** [comment]
Thank you! The only issue is that HTML lang is set to English and screen readers have to deactivate pronnounciation based on language. I investigated but I cannot find a way to set the lang attribute for wikis on GitHub. Hope they fix it.
Many thanks. I will aknowledge you on mailing lists of spanish community.

Enviado desde mi iPhone

**Comment by nvdaes** [comment]
I will share the link to the spanish translated keyboards shortcuts on a spanish website about NVDA where I have posted some articles about epub. I will paste the contents of the wiki article so that people can read it with appropriate pronounciation in Spanish.
The website is at
https://nvdaes.github.io
Thanks @danielweck.
