### ISSUE TITLE
Display a clear message when an encrypted EPUB is imported

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1021]
This is what appears when a developer tries to import a .EPUB which has been encrypted by lcpencrypt, with no embedded license in the package: 
"the files seem to be generated okay, but when I try to open them I get this error `This page contains the following errors: error on line 1 at column 1: Document is empty. Below is a rendering of the page up to the first error.`"

It means that the encryption information in encryption.xml is not taken into account and the publication is treated as if it was in clear. 

We should get the following message instead: 
"No means of decryption were found in this encrypted publication. As a consequence the publication cannot be processed".

**Comment by panaC** [comment]
https://github.com/readium/readium-lcp-client/blob/764b28f5f4d879f771be7e727cf4a79ac0d62d9f/src/third-parties/rapidjson/error/en.h#L34

**Comment by danielweck** [comment]
Is this really an end-user problem, or just a situation that developers may encounter during tests?
