### ISSUE TITLE
Large audiobook import => no UI feedback + "API" timeout in console (but eventually ... successful import)

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1030]
To reproduce, test with "Crimson Fairy Book LPF" (`Lang_Crimson_Fairy_Book.lpf`) from:

https://github.com/w3c/publ-tests/tree/master/test_content/audiobooks

...but remember to unzip, then re-zip the resources in order to fix the incorrect top folder. See: https://github.com/w3c/publ-tests/issues/36

**Comment by danielweck** [comment]
Note that W3C `*.lpf` format is converted during import, so this certainly contributes largely to the processing time, but we must also check that importing Readium Web Pub Manifest `*.audiobook` files provides minimum UI feedback, and no API timeout.

**Comment by panaC** [comment]
what UI do you want ? A simple toastInfo when lpfConvert has finished and passes the relay to importPublication ?

**Comment by panaC** [comment]
what takes the most time is a double copy of the zip archive. We can flag it to user between them

**Comment by danielweck** [comment]
Note: this PR https://github.com/readium/readium-desktop/pull/930
adds a spinner indicator in the top-right corner during API background operations.

**Comment by panaC** [comment]
what do we do with this issue ? @danielweck @llemeurfr

**Comment by danielweck** [comment]
The console API timeout is only seen at development time, so I guess that's okay. The GUI progress indicator provides minimum feedback, so let's close this issue as it is not really actionable at this stage. We can always create a more narrow-focused issue later down the line, if long-running operations in Thorium remain problematic from a UX perspective.
