### ISSUE TITLE
See double page of Epub Book

### ISSUE THREAD

**Issue by jeanneaud** [edrlab/thorium-reader#1040]
When I open a book, I can only see one page. Is it possible to see the left page and the right page at the same time?
I work with a Mac OS 10.11.6 and I have Thorium 1.3.1-alpha.1.2316.
![Capture d’écran 2020-05-06 à 20 22 31](https://user-images.githubusercontent.com/64921024/81213908-61d04080-8fd7-11ea-8262-6240ac0f1fa9.png)
![Capture d’écran 2020-05-06 à 20 22 40](https://user-images.githubusercontent.com/64921024/81213909-63016d80-8fd7-11ea-8d2e-5142aa29f25e.png)

**Comment by danielweck** [comment]
Thank you for your feedback!
This is a known limitation. We will implement support for fixed-layout page spread shortly.

**Comment by jeanneaud** [comment]
Ok thank you, I close the issue.

**Comment by danielweck** [comment]
If you don't mind, I would like to keep the issue open. Strictly-speaking this is a feature that will be implemented in another component (separate GitHub repository), but users inevitably file issues here in the Thorium project. Plus, your screenshots illustrate the problem very nicely :)

**Comment by jeanneaud** [comment]
Ok, thank you.

**Comment by GijsbertNoordam** [comment]
Some additional information that might be of use. There is a [EPUB 3 Samples Project github project ](https://idpf.github.io/epub3-samples/) with example files including a testfile that perfectly illustrates the issue logged here. This file, ["Page Blanche"](https://github.com/IDPF/epub3-samples/releases/download/20170606/page-blanche.epub), is an extract of a fixed layout document, using XHTML spine items that embed bitmaps. On Readium (the Chrome Extension) the file displays as would be expected (including the correct application of page-spread-left and page-spread-right in the spine of the opf document): 
![image](https://user-images.githubusercontent.com/44704552/82022907-aa4dc500-968d-11ea-8460-8a97b35242d0.png)
However on Thorium, this is not (yet) supported as illustrated below:
![image](https://user-images.githubusercontent.com/44704552/82023499-aa01f980-968e-11ea-8e45-b6d5773ff936.png)
![image](https://user-images.githubusercontent.com/44704552/82023562-bbe39c80-968e-11ea-9721-d12d95031d33.png)
Hopefully, this additional information can act as a modest contribution to resolving the issue.
