### ISSUE TITLE
in DEV mode, and automated CI builds, JsonDown DB filesystem store grows indefinitely, causing massive performance hit during serialization

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1072]
In the console: `readium-desktop:main:saga:persist end of persist reduxState in disk` between 2-3 seconds lag, due to 250MB `data.json` files (total 1.5GB in my Thorium `db-DEV`).
So, another incentive to move away from JsonDown, as part of our review of LevelDown in general.

**Comment by danielweck** [comment]
This issue is EXTREMELY problematic, for us as developers, but also for users who like to use the latest automated builds, that is to say when JsonDown (which is really just a JSON serialization and file-saving technique based on an old version of MemDown / RedBlackTree memstore) is used instead of the native LevelDB library LevelDown (which causes problems when compiling on TravisCI, thus why we disabled it in the first place, and used the "dev mode" JsonDown instead).

I have spent some time debugging this with a Windows users who ; like me on MacOS ; had 1.5+GB `db` folder inside `c:/Users/name/AppData/Roaming|Local/EDRLab.ThoriumReader/`, which in turn caused massive lag (1-2 seconds) each time the reading location was saved, which occurs everytime the user interacts with the HTML documents, such as when expanding HTML `details` elements, etc.

**Comment by panaC** [comment]
🔥

**Comment by danielweck** [comment]
Some arguments to eliminate JsonDown from this project:
It is based on an old version of MemDown:
* https://github.com/toolness/jsondown/blob/996411e4d4aa6471384666c0557cc7aa8d820e1e/package.json#L16
* https://github.com/Level/memdown/blob/v1.4.1/memdown.js

...and Abstract-LevelDown too:
* https://github.com/toolness/jsondown/blob/996411e4d4aa6471384666c0557cc7aa8d820e1e/package.json#L23
* compared with the latest MemDown: https://github.com/Level/memdown/blob/7126df10c9ae2a860fc59105e777576509c810ee/package.json#L31

Also note that modern MemDown declares `snapshots` support in the AbstractLevelDown manifest (which makes sense as the RedBlackTree operates on safe snapshot ... which may partly explain why JsonDown seems to grow indefinitely in size, although this may be due to PouchDB upstream in the persistence layers?):
* https://github.com/Level/memdown/blob/7126df10c9ae2a860fc59105e777576509c810ee/memdown.js#L159-L163
* https://github.com/Level/abstract-leveldown#db--abstractleveldownmanifest
* https://github.com/Level/supports#features

**Comment by danielweck** [comment]
I am experimenting with replacing JsonDown with SQLite in both dev and CI builds (Travis, Appveyor). Note that SQLite is actually a recommended adapter for PouchDB: https://pouchdb.com/adapters.html

**Comment by danielweck** [comment]
* Travis: https://travis-ci.org/github/edrlab/thorium-reader/builds/696254636
* Appveyor: https://ci.appveyor.com/project/danielweck/thorium-reader/builds/33398978

**Comment by danielweck** [comment]
Full code diff for working CI builds with new SQLite3 database backend (PouchDB store adapter): https://github.com/edrlab/thorium-reader/compare/e665456558bb7163ab840bd4d8861a8f53f4d775...07269237817ac7eed8be374fc506697add81ff33
