### ISSUE TITLE
OPDS download is broken with Gutenberg feed

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1075]
http://m.gutenberg.org/ebooks.opds/

(see https://readium2.herokuapp.com/opds-v1-v2-convert/http%3A%2F%2Fm.gutenberg.org%2Febooks.opds%2F )

```
[2]   readium-desktop:main#services/downloader oauth +0ms
[2]   readium-desktop:main#services/downloader NotFoundError { message: 'document not found' } +1ms
```

**Comment by danielweck** [comment]
See `"href": "https://www.gutenberg.org/ebooks/11.epub.noimages"`
in https://readium2.herokuapp.com/opds-v1-v2-convert/http%3A%2F%2Fm.gutenberg.org%2Febooks%2F11.opds

The download link itself is valid, and the downloaded EPUB can be added to the library successfully, and read too:
https://www.gutenberg.org/ebooks/11.epub.noimages

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/blob/39c31d6767e88b0d30edfd12311e29090d931f93/src/main/services/downloader.ts#L124

**Comment by danielweck** [comment]
ah yes, this is probably normal (db document not created yet).
other downloads work from feedbooks opds, so must be something else...

**Comment by panaC** [comment]
`  readium-desktop:main#services/downloader request error:  Error: certificate has expired
[2]     at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
[2]     at TLSSocket.emit (events.js:210:5)
[2]     at TLSSocket._finishInit (_tls_wrap.js:794:8)
[2]     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
[2]   code: 'CERT_HAS_EXPIRED'
[2] } +348ms`

**Comment by panaC** [comment]
https://stackoverflow.com/questions/20433287/node-js-request-cert-has-expired

**Comment by danielweck** [comment]
Related issue? https://github.com/edrlab/thorium-reader/issues/1083

**Comment by danielweck** [comment]
Yep, Gutenberg server suffers from the same certificate expiry problem as EDRLab's LCP server.

```
Common name: USERTrust RSA Certification Authority
Organization: The USERTRUST Network
Location: Jersey City, New Jersey, US
Valid from May 30, 2000 to May 30, 2020
Serial Number: 13ea28705bf4eced0c36630980614336
Signature Algorithm: sha384WithRSAEncryption
Issuer: AddTrust External CA Root
```

https://www.sslshopper.com/ssl-checker.html#hostname=https://www.gutenberg.org

**Comment by danielweck** [comment]
See full discussion thread in the LCP Slack channel: https://app.slack.com/client/T5Y1G1KBP/C7DASDKT6
