### ISSUE TITLE
LCP passphrase dialog (ok), but toast "publication cannot be open" (not ok)

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1084]
![Screenshot 2020-06-08 at 18 58 19](https://user-images.githubusercontent.com/625201/84064195-264fda00-a9ba-11ea-9103-8cedcc0c848b.png)

**Comment by panaC** [comment]
Yes , Indeed , because there are many error level conditions, not easy to handle

**Comment by danielweck** [comment]
Right, the error cascade in this case is a bit tricky to handle as "side effects" in Redux Saga.
