### ISSUE TITLE
Increase the spaces between paragraphs

### ISSUE THREAD

**Issue by Bruneux** [edrlab/thorium-reader#1100]
I saw in the preferences options to change the spaces between words, lines, etc., but not between paragraphs.

Is it possible to do this, or would it be possible to implement it?

Thanks

**Comment by danielweck** [comment]
Hello, this sounds like something that ReadiumCSS ( https://github.com/readium/readium-css/ ) would help solve. @JayPanoz to the rescue! :)

**Comment by JayPanoz** [comment]
Indeed. It’s already available in ReadiumCSS (`paraSpacing`), [see docs](https://readium.org/readium-css/docs/CSS12-user_prefs.html#paragraphs-formatting)

So that could be implemented in a similar fashion as all these others advanced settings.

**Comment by danielweck** [comment]
Indeed, and this ReadiumCSS parameter (as are all of them) is in fact exposed in `r2-testapp-js`:

<img width="1565" alt="Screenshot 2020-07-01 at 17 58 08" src="https://user-images.githubusercontent.com/625201/86271384-b1408080-bbc4-11ea-86e7-8189ce07902b.png">

**Comment by llemeurfr** [comment]
The action is to add paragraph spacing to the Thorium UI.
