### ISSUE TITLE
Rendering issue in image + textbox exported from InDesign

### ISSUE THREAD

**Issue by gregoriopellegrino** [edrlab/thorium-reader#1104]
Hi,
when in InDesign CC 2020 I group an image with its caption (a text-frame) the export in EPUB is:

```
<div class="_idGenObjectLayout-1">
	<div id="_idContainer009" class="_idGenWritingDirection-1">
		<div id="_idContainer007" class="Cornice-di-testo-di-base">
			<p class="didascalia">Pietra di confine con la scritta «Oropa» nel bosco di Fontanelle annesso alla cascina Simonetto sotto la proprietà di Giovanni Battista Garrone nel XVIII secolo. (Archivio Virginia Gozzi Brayda)</p>
		</div>
		<div id="_idContainer008">
			<img class="_idGenObjectAttribute-1" src="image/00.jpg" alt="" />
		</div>
	</div>
</div>
```

With the following CSS:
```
#_idContainer007 {
	height:59.53px;
	left:0px;
	overflow:hidden;
	position:relative;
	top:213px;
	width:360.00px;
	z-index:1;
}
#_idContainer009 {
	display:inline-block;
	height:272px;
	position:relative;
	width:360px;
}
#_idContainer008 {
	height:212.60px;
	left:0px;
	position:relative;
	top:-60px;
	width:360.00px;
	z-index:0;
}
img._idGenObjectAttribute-1 {
	height:100.00%;
	min-width:100%;
	width:100.00%;
}
div._idGenObjectLayout-1 {
	text-align:center;
}
```

The issue is that Thorium cuts part of the caption:
![image](https://user-images.githubusercontent.com/5065125/85848893-464d0f00-b7aa-11ea-87d6-23aaf417a9ca.png)

I can send you a test file privately.

**Comment by danielweck** [comment]
Hello, thank you for the report!
Is that on Mac, Windows, Linux?
Would you mind checking with `r2-testapp-js`? ( https://github.com/readium/r2-testapp-js/releases )
I am asking because in the test app, ReadiumCSS is totally deactivated by default (and can be turned on/off from the configuration panel), so this may allow us to reduce the problem down to a ReadiumCSS style.

**Comment by gregoriopellegrino** [comment]
In `r2-testapp-js` works better.

**Comment by danielweck** [comment]
I'm pretty sure this is a ReadiumCSS "issue" ( https://github.com/readium/readium-css/ ), but I will investigate the style cascade in `r2-testapp-js` just to see what rule is causing the overflow.

So, @gregoriopellegrino could you please share the EPUB with me? Thanks!

CC @JayPanoz

**Comment by JayPanoz** [comment]
Yeah, at first sight their markup + styling for figures got an awful lot worse in CC 2020 – which I thought couldn’t be possible given how bad it already was. I’m guessing the combo of `div id` + absolute/relative positioning + `inline-block` may be a lead.

**Comment by danielweck** [comment]
Closing as not fixable in Thorium. Probably needs details fleshed out in ReadiumCSS https://github.com/readium/readium-css/
