### ISSUE TITLE
Crash report Mac OS v1.3.1-alpha.1.2500

### ISSUE THREAD

**Issue by mutterback** [edrlab/thorium-reader#1109]
On Thorium prerelease for Mac OS v1.3.1-alpha.1.2500

Was attempting to go back to the library page from reading a book. Here's the message: 

An error has occurred in readium-desktop:main:saga:reader:readerCLoseRequestFromIdentifier

        Error message:
        Object has been destroyed

**Comment by panaC** [comment]
Hello,

I can't reproduce it. Can tell you more about how the crash happened ?

**Comment by danielweck** [comment]
I occasionally experience this error, but it is very rare so I guess it is due to some weird edge-case timing issue during the tear-down of the Electron BrowserWindow?

**Comment by danielweck** [comment]
I am closing this issue as it is not actionable, however we are of course continuously running tests to identify and squash such border-case bugs.
