### ISSUE TITLE
New user here, how do you make annotations, in 1.3.1-alpha

### ISSUE THREAD

**Issue by Aheadz** [edrlab/thorium-reader#1111]
I am running a KDE plasma environment and for the life of me cant figure out how to make annotations

**Comment by danielweck** [comment]
Thank you for your feedback. Annotations are not implemented yet, sorry for the confusion.

We are planning - in the not-too-distant future - to implement support for user-highlighted document selections and user-authored annotations. This will be similar to bookmarks.

We are also working on a "search" feature at the moment, which shares some technical underpinnings (i.e. highlighting of ranges of text, previous/next navigation in the linear list of items):
https://github.com/edrlab/thorium-reader/pull/1057
