### ISSUE TITLE
TTS Readaloud: playback rate is not visible in night theme

### ISSUE THREAD

**Issue by ways2read** [edrlab/thorium-reader#1115]
Choose Night theme, start readaloud, then guess your playback rate! the dropdown menu is visible (though it may be the wrong colours?) but the value is not when the speech is active.

**Comment by CircularKen** [comment]
Also the 'more information' and 'less information' labels for fixed layout nav bar are black on black in Night theme.

**Comment by danielweck** [comment]
Thank you Ken. I posted a separate issue: https://github.com/edrlab/thorium-reader/issues/1135
