### ISSUE TITLE
Implement text search within an ebook

### ISSUE THREAD

**Issue by PhilippeBruno** [edrlab/thorium-reader#1116]
Ctrl + F does not allow searching within an ebook. It is a very important feature.

**Comment by panaC** [comment]
#1049 #1057 #1086 

We move forward 🚀

**Comment by danielweck** [comment]
You are right Philippe, and we agree, the search feature is very important :)

Pierre made great progress in this PR, but we now need to finalise it (there are performance issues with large search results, and the GUI needs improving):

https://github.com/edrlab/thorium-reader/pull/1057

This will be released in version 1.5 (i.e. after the imminent v 1.4).

**Comment by llemeurfr** [comment]
This feature was added in v1.5, which was released yesterday.

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/pull/1086
