### ISSUE TITLE
For some ePubs, cover image appears in bookshelf but not in open book

### ISSUE THREAD

**Issue by PhilippeBruno** [edrlab/thorium-reader#1117]
I do have some ePubs for which the cover page is visible in the bookshelf but not when I open the book. It is a minor annoyance, but since other readers are showing it properly, I suspect it is a bug in Thorium. Titles and/or ePubs can be provided privately upon request.

**Comment by panaC** [comment]
can you make some screen capture of bookshelf and book opened with the bug. please.

**Comment by PhilippeBruno** [comment]
<img width="691" alt="Thorium_s66it6KEGG" src="https://user-images.githubusercontent.com/36426806/87542796-8e58a680-c671-11ea-979c-0e9463059558.png">
<img width="692" alt="Thorium_BFnVUUqvMJ" src="https://user-images.githubusercontent.com/36426806/87542869-a9c3b180-c671-11ea-88ab-774ccc9efcb3.png">

**Comment by panaC** [comment]
I don't think it's a thorium bug. I think it's the content of your epub.
I'd rather let @danielweck tell you more

**Comment by PhilippeBruno** [comment]
I hate to say this, but when I open it in ADE, I see the cover inside the book as well.
![image](https://user-images.githubusercontent.com/36426806/87546174-1a210180-c677-11ea-87c3-cb97536172bd.png)

**Comment by danielweck** [comment]
Thank you for reporting this. I strongly suspect Thorium correctly lays out the EPUB “spine items”, by skipping the “cover image” XHTML document which is likely marked with the `linear=no` attribute.

Maybe I am wrong though, so could you please check the package OPF to confirm? I am happy to do this if you share the EPUB with me.

Thanks!

**Comment by PhilippeBruno** [comment]
You are right for this specific title. The cover item in the spine is indeed marked with the `linear=no` attribute. I will check with the other books that failed to display their cover page in Thorium and get back to you. If they are all marked like the above, we're all good.
