### ISSUE TITLE
Cannot read property 'Ready' of undefined (bad / obscure LCP error reporting)

### ISSUE THREAD

**Issue by CircularKen** [edrlab/thorium-reader#1121]
There are currently three Fixed Layout EPUBs in this OPDS feed https://d2g.dita.digital/opds/collections/10048
Two have LCP encryption applied, one does not.

When accessing in Mac Thorium 1.3.0 I can import and access all three (after giving the correct LCP passphrase where required.)

When accessing in Mac Thorium 1.3.1-alpha.1.2515 I can successfully open the one without LCP encryption but can't open the two with LCP encryption, instead I see the error message -
<img width="363" alt="image" src="https://user-images.githubusercontent.com/17338941/87698180-08c91980-c78b-11ea-93dc-6d3cd8f53ac7.png">

Have also tested with reflowable EPUBs with LCP encryption applied and seeing the same results.

**Comment by danielweck** [comment]
Hello Ken, the automated Thorium builds created by the continuous integration servers (Travis and Appveyor) do not support LCP-protected publications.

I am sorry that the error message is not clear, to be honest I do not even know what that means :)

We are aware that some errors are not cascaded optimally when transiting via the many layers of abstractions in the code. In our tests we did notice that fatal LCP errors are particularly obscure.

**Comment by CircularKen** [comment]
That's is good to know. OK, I will proceed in the anticipation that the LCP protection will work again in the next major release.
