### ISSUE TITLE
Useless confirmation on import

### ISSUE THREAD

**Issue by PhilippeBruno** [edrlab/thorium-reader#1129]
When dropping an EPUB on Thorium, a dialogue box prompts to confirm the import. It is quite useless and an extra step for no good reason... unless, when a user answers 'no', Thorium would simply open the file without adding it to its database, which is unfortunately not the case.

**Comment by danielweck** [comment]
I agree. Deleting mistakenly-imported publications is easy enough.
Perhaps there should be an easy way to cancel current imports of very large publications which take excessive amount of time to load? (especially when drag+drop numerous files onto the library window)

**Comment by PhilippeBruno** [comment]
👍

**Comment by ways2read** [comment]
+1

**Comment by llemeurfr** [comment]
After team discussion, the dialog box will open if there are more that N publication to import. N will be set on the build.

**Comment by panaC** [comment]
disable confirmation from n publications that will be imported.

if less than n publication : the confirmation will be disabled
else : the confirmation will be enabled
