### ISSUE TITLE
Add support for alerts in braille

### ISSUE THREAD

**Issue by nvdaes** [edrlab/thorium-reader#1134]
When pressing control+b, sometimes bookmarks are added, but this is not the case when we have added a bookmark previously. This is reported as an audible alert, but we can read just in braille or maybe inaccessible also for deaf blind people.
A region invisible for sighted users or a dialog available for everybody to see recent notifications maybe useful for this, similar to the aside region in ace-gui, which can be reviewed with the cursor and is easily reachable, to know when a book is being checked and other notifications.

**Comment by danielweck** [comment]
I agree, we can do much better.

Thorium used to have "toast" popup / slide-in notifications (ARIA live regions assertive or polite, I cannot remember), but they were ill-designed and annoyingly interruptive, obscuring part of the user interface at the worst moments during user interactions. There was also the issue of concurrently-displayed native system notifications.

**Comment by nvdaes** [comment]
Thanks. This will be a great improvement if it can be implemented.

2020-07-30 10:33 GMT+02:00, Daniel Weck <notifications@github.com>:

**Comment by danielweck** [comment]
Duplicate issue: #1134
