### ISSUE TITLE
MacOS: Window menu / Menu bar

### ISSUE THREAD

**Issue by CircularKen** [edrlab/thorium-reader#1137]
As a Mac user I find it unusual for the Window menu to be hidden underneath the Application menu.

<img width="476" alt="image" src="https://user-images.githubusercontent.com/17338941/88702618-79fdba80-d103-11ea-91e6-7dcfda76ce42.png">

It took me a while to find it and most Mac users would expect it to be in the main menu bar.

<img width="412" alt="image" src="https://user-images.githubusercontent.com/17338941/88702899-e8db1380-d103-11ea-8eb2-3f34ba3508b3.png">

**Comment by panaC** [comment]
you're right

**Comment by danielweck** [comment]
Code reference: https://github.com/edrlab/thorium-reader/blob/2ad37fa8d4753c308b6d39b3f7c9439e09d93447/src/main/menu.ts#L154-L270
