### ISSUE TITLE
Feature request: add ability to save location on demmand

### ISSUE THREAD

**Issue by nvdaes** [edrlab/thorium-reader#1139]
Screen reader users may use the same cursor to read the book and to interact with menus in the app. Location is saved when reader is closed, but sometimes we may want to save it before open the navigation menu or, for example, if notifications are placed in the main window of the app, not in a modal dialog.
Possible alternatives are:
1. Press a keystroke to save the current location, so we can reach it later by pressing `control+f10, tab` and then activate the link.
2. Add settings to configure the behavior for screen reader user, in the same way this has been done to configure the visual appearance.

**Comment by llemeurfr** [comment]
Hello @nvdaes, I struggle understanding the exact feature you'd like to obtain. The "last reading location" is set by the last position of a cursor, which for sighted people is usually set via a mouse click, and for people using screen reader is inferred from a reading position driven by the screen reader itself (if I have it right).  When you use keystrokes to activate a menu (for instance), isn't the last reading location set on the segment of text the screen reader just left?

**Comment by nvdaes** [comment]
Thanks for your interest. If we activate a link of the table of contents, bookmark, etc., or if we press control w to close the book, or alt f4, the position is saved and we can go ther pressing control f 10 then tab. But if we press control n to explore the navigation menu, and then escape or the buttons to close the menu since we wanted just explore it without going to a bookmark or section of the TOC, the cursor remains in the position of the menu, and we cannot move to the last reading position. If we press control f10, then tab and enter to move to the last rading position, the cursor will move to the latest saved position, that is, the position saved when the book was closed previously or the position corresponding to the latest activated bookmark, link, etc.
We can use bookmarks for this, but sometimes maybe useful just a keystroke to save the position without dealing with bookmarks, that have to be activated from the navigation menu.
This can be also useful if we want to explore the chapter or search a sentence but later coming back to a precise position. BTW, the way to reach the latest saved position (control f10, then tab and then enter to activate de frame) is not documented and this maybe very useful.

Enviado desde mi iPhone

**Comment by danielweck** [comment]
We can now close this issue as extensively discussed and addressed in (notably) this issue : https://github.com/edrlab/thorium-reader/issues/1594
