### ISSUE TITLE
distorted svg content near pagination breaks 

### ISSUE THREAD

**Issue by pkra** [edrlab/thorium-reader#1143]
I regularly (but not always) encounter distortions in (inline) SVG content near pagination breaks.

The following screenshot contains a short extract repeated several times to demonstrate the problem.

![svgDistortion](https://user-images.githubusercontent.com/426686/89776608-8c67f300-db0a-11ea-8854-92b2cbdd585c.png)

Towards the bottom of each "page", there are two inline svg images (after "only if") which are distorted - you can compare them to other locations in the same screenshot.

This only happens with pagination and near "page breaks"; it can be worked around by readers, e.g., by changing the font-size or viewport in a way that "moves" the svg content away from the pagination break.

The screenshot was made with Thorium 1.4 and is hopefully reproducible with [svgbug.zip](https://github.com/edrlab/thorium-reader/files/5050490/svgbug.zip). But I've seen this behavior in basically any version of Readium/Thorium I've tested in the past few years -- it might be a browser bug but I don't know enough about the pagination mechanism to reproduce it.

**Comment by danielweck** [comment]
Thank you for reporting this, Peter. I assume this is MathJax embedded / authored in the publication, not injected by Readium / Thorium?

Note that Thorium / Readium apply CSS Columns to the HTML document in order to emulate "pagination", and if I am not mistaken `readium-css` does not seem to apply any "trick" styles that would somehow explain the distorted SVG:

https://github.com/readium/readium-css/blob/583011453612e6f695056ab6c086a2c4f4cac9c0/css/dist/ReadiumCSS-before.css#L614-L635

+ @JayPanoz

**Comment by danielweck** [comment]
PS: it would be interesting to see what CSS styles from MathJax take precedence in the cascade over ReadiumCSS's own styles. Just in case the resulting combination of MathJax + ReadiumCSS styling causes issues.

**Comment by pkra** [comment]
Thanks @danielweck.

>  I assume this is MathJax embedded / authored in the publication, not injected by Readium / Thorium?

In this example, the SVG was created using mathjax-node. But I've seen it with SVGs build with other tools as well.

> Note that Thorium / Readium apply CSS Columns to the HTML document in order to emulate "pagination",

I thought so but wasn't able to create a standalone example using just CSS columns.

> it would be interesting to see what CSS styles from MathJax take precedence in the cascade over ReadiumCSS's own styles.

I'm not sure if this refers to the styles in the sample file but just in case: all css can be removed from the sample file without fixing the problem.

**Comment by JayPanoz** [comment]
Yeah I’m wondering whether it could somehow be related to the `*-break-inside: avoid`. From experience, while it’s working fine in most cases, it’s also been the cause of some super obscure rendering issues. 

@pkra Do you remember [this issue you reported in Blitz](https://github.com/FriendsOfEpub/Blitz/issues/29)? And I’m pretty sure I heard of (yet) another oddly similar one in the last year i.e. rendering issue when using this declaration and the element happened to be at the end of the column.

**Comment by pkra** [comment]
Thanks @JayPanoz. 

>  I’m wondering whether it could somehow be related to the *-break-inside: avoid. From experience, while it’s working fine in most cases, it’s also been the cause of some super obscure rendering issues.

I just now tried to add overrides (` -webkit-column-break-inside: auto!important;` etc) to the sample file, without any effect.

> @pkra Do you remember this issue you reported in Blitz? 

I do but I didn't think it could be related.

**Comment by pkra** [comment]
I think I've finally been able to reproduce the issue on Chrome directly without any special CSS (except columns) - I'm not sure why I failed before, possibly it's just the "right" sample. 

I'll have to work out the details and file an issue on the Chromium tracker (and add a link to that here).

**Comment by pkra** [comment]
@danielweck @JayPanoz would you have a second to check if https://codepen.io/pkra/pen/qBZOaNW reproduces the issue for you on "plain" Chrome?

**Comment by JayPanoz** [comment]
Yep can confirm. 

Chrome: 

![Capture d’écran 2020-08-11 à 11 59 10](https://user-images.githubusercontent.com/12599652/89884747-3f4b5600-dbca-11ea-8149-3acb211a7374.png)

Safari (for comparison):

![Capture d’écran 2020-08-11 à 11 59 54](https://user-images.githubusercontent.com/12599652/89884766-44100a00-dbca-11ea-84d7-0a5693fc6666.png)

Don’t quote me on that but I believe at some point Chrome diverged from Webkit re. the multicol implementation (at the time they removed CSS regions if I’m not mistaken) so at least that should explain the discrepancy here.

**Comment by pkra** [comment]
Thanks, @JayPanoz! Much appreciated!

**Comment by pkra** [comment]
Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1115029

**Comment by pkra** [comment]
FYI this has been confirmed as an upstream bug; unfortunately, it will have to wait for Blink's block fragementation rewrite as part of LayoutNG.

**Comment by danielweck** [comment]
Thank you very much for keeping us updated, Peter.
We regularly check Electron releases to ensure that Thorium doesn't lag behind Chromium updates, so hopefully not too long until this SVG bugfix makes its way into Thorium Reader :)
