### ISSUE TITLE
Unwanted scroll on app focus after ALT+TAB switch

### ISSUE THREAD

**Issue by mahpooya** [edrlab/thorium-reader#1147]
Hello.
I use to open epub with thorium and open audio book with kmplayer, so i can read and listen to audiobook at the same time.
But sometimes when i switch to kmplayer (using ALT+TAB) to pause audio and going back to thorium, scroll position get lost, somewhere above where i was reading appear a green outline box and i lost concentration of reading.
Is it a bug or a feature that does not work correctly?
Because it is very annoying!

**Comment by danielweck** [comment]
It does sound like an annoying unwanted behaviour indeed. Clearly a bug with focus handling in the Chromium webview / iframe.

**Comment by huylv** [comment]
Is there any plan to fix this? It's really annoying when alt-tab'ing back and forth between book and IDE to learn some programming.

**Comment by danielweck** [comment]
Thank you for bringing this up again. We'll look into it, at least to try to figure out what is going on.

**Comment by danielweck** [comment]
I am unable to reproduce this bug in Thorium 2.1.0, closing.
