### ISSUE TITLE
Warning (or auto upgrade) when new versions are available

### ISSUE THREAD

**Issue by gregoriopellegrino** [edrlab/thorium-reader#1149]
I think it would be very useful to have a warning at the start of the application suggesting the user to update if a new version is available.

This is because development is continuous and there is a risk of using older versions.

**Comment by danielweck** [comment]
Indeed. However particular care must be taken so that the UX is adapter to specific distribution channels, for example Windows Store versus installer executable, and perhaps in the future also Mac App Store (in addition to DMG), and maybe some Linux alternative too (in addition to AppImage and Debian package).

**Comment by gregoriopellegrino** [comment]
Right... Or maybe a link and then the webpage (based on OS, etc.) redirects the user to the right place.

**Comment by gotson** [comment]
You should have a look at [Conveyor](https://www.hydraulic.dev/)

**Comment by danielweck** [comment]
Proper sophisticated solutions include:

* https://www.electron.build/auto-update.html
* https://hydraulic.dev/blog/8-packaging-electron-apps.html

... but for now we will just display a message and a hyperlink to the download website (GitHub releases). There will be a `latest.json` file committed to the `develop` branch (accessible publicly with a simple fetch GET request from the NodeJS Electron main process). The TypeScript / Javascript code will compare the semantic versions which will determine whether or not to prompt the user to update. TODO: detect Windows Store deployment to avoid nagging the user with an irrelevant update link ... although I would argue that the release notes alone are worth reading and there is always a delay for Store downloads compared with direct downloads from GitHub).

**Comment by danielweck** [comment]
Will be fixed via https://github.com/edrlab/thorium-reader/pull/2158
