### ISSUE TITLE
Empty footnotes

### ISSUE THREAD

**Issue by gregoriopellegrino** [edrlab/thorium-reader#1150]
Hi,
I'm testing an EPUB 3 made with Bookalope (@jenstroeger), with no errors reported by epubcheck.

The notes and footers are structured as follows:
```
<a href="footnotes.xhtml#fn-1" id="fn-1" epub:type="noteref" role="doc-noteref">[1]</a>
```
```
<aside epub:type="footnote" role="doc-footnote" aria-label="Footnote 1" id="fn-1">
      <p class="p"><a href="chapter-1.xhtml#fn-1" role="doc-backlink">[1]</a> P. De Benedetti, Ciò che tarda avverrà, Qiqajon, Magnano (BI) 1992, pp. 23–27.</p>
</aside>
```
Clicking on them Thorium 1.4.0 shows me an empty pop-up.

![image](https://user-images.githubusercontent.com/5065125/90626060-b9a75600-e21a-11ea-95e7-82cda9de4cf4.png)

If needed they can send the file privately by email.

**Comment by jenstroeger** [comment]
@gregoriopellegrino, can you try this in the Books application on Mac? I saw the same behavior there and had fixed it. Looking through the code log, I think I found the fix whose commit message is:
```
The popup's content seems to be the content of the element that the
footnote link targets, which was the link inside of the footnote <aside>
element. So, the popup showed just the target's link content, but not
the footnote. Fix: hoist the id into the <aside> itself.
```
Maybe that helps… 🤔

**Comment by gregoriopellegrino** [comment]
In the mac Books application it works correctly:

![image](https://user-images.githubusercontent.com/5065125/90627449-3e46a400-e21c-11ea-850f-97abf181f54b.png)

**Comment by danielweck** [comment]
Thank you for reporting this bug!
Would you mind privately sharing the EPUB with me so I can test it?

**Comment by jenstroeger** [comment]
@danielweck, you can use this [footnotes.epub.zip](https://github.com/edrlab/thorium-reader/files/5096214/footnotes.epub.zip) as a small test ebook. Note that footnotes 1, 2, 3 are not rendered in a popup at all (looks like navigation jumps into the _Footnotes_ chapter), and footnote 4 causes an empty popup.

**Comment by danielweck** [comment]
Note to self: I must publish an updated R2 navigator package which contains the bugfix (edge case) for DOM IDs that are present in the currently document wrongly assumed to be the footnote targets.

**Comment by danielweck** [comment]
Similar (same?) issue: https://github.com/edrlab/thorium-reader/issues/1212

**Comment by danielweck** [comment]
Fix now integrated in Thorium https://github.com/edrlab/thorium-reader/commit/ef817803c8bf595e26752b98c378d20d6e07fade
