### ISSUE TITLE
Debian version - Error: Import failed for the publication path

### ISSUE THREAD

**Issue by bohwaz** [edrlab/thorium-reader#1156]
Tried to open a .LCPL file with Thorium 1.4.0 on Debian and got this error: 

```
Error: Import failed for the publication path : /tmp/9782072797019.lcpl
```

Here is the content of that file:

```
{"provider":"https://www.edenlivres.fr","id":"04c71325-6d7a-4fa2-8788-0b28cc52ceef","issued":"2020-09-01T14:02:04Z","updated":"2020-09-01T14:02:04Z","encryption":{"profile":"http://readium.org/lcp/profile-1.0","content_key":{"algorithm":"http://www.w3.org/2001/04/xmlenc#aes256-cbc","encrypted_value":"Do4As5tgIWKJpI5LmUUm0aUxLrwkFeSt6YOrWn6lCXpygFbyGtDoKuto9UV9f/aCcYyzv7AgqDyut8YvF7dx3Q=="},"user_key":{"algorithm":"http://www.w3.org/2001/04/xmlenc#sha256","text_hint":"Quel est le nom de votre premier animal de compagnie ?","key_check":"D1TRoYm9oo9/9a6uqco9Kpyuck6EV1KHOL/UxUXA6tb5V9ccyTQf9XwvLGtzTRf7P6fQ3+23Dax+cFVMore7sQ=="}},"links":[{"rel":"hint","href":"https://pnb-dilicom.centprod.com/v3//pnb-numerique/errors/lcpHelpLinkError.html","type":"text/html"},{"rel":"status","href":"https://www.edenlivres.fr/api/lcp/04c71325-6d7a-4fa2-8788-0b28cc52ceef/status","type":"application/vnd.readium.license.status.v1.0+json"},{"rel":"publication","href":"https://lcpserver1.s3.amazonaws.com/66ae3fda-ee3d-40c3-84d8-dac917a43c93","type":"application/epub+zip"}],"user":{"id":"5f438be47dd3950fddb123962f841cf97b804631b75f7c18c73ac805"},"rights":{"start":"2020-09-01T14:02:04Z","end":"2020-09-29T14:02:03Z"},"signature":{"certificate":"MIIDLTCCAhWgAwIBAgIJAPW+t2rKTCYZMA0GCSqGSIb3DQEBCwUAMEIxEzARBgNVBAoTCmVkcmxhYi5vcmcxFzAVBgNVBAsTDmVkcmxhYi5vcmcgTENQMRIwEAYDVQQDEwlFRFJMYWIgQ0EwHhcNMTkwNjExMTEyMDMzWhcNMjEwNjEwMjM1OTU5WjBRMRMwEQYDVQQKEwplZHJsYWIub3JnMSYwJAYDVQQLEx1SZWFkaXVtIExDUCBMaWNlbnNlIFByb3ZpZGVyczESMBAGA1UEAxMJRGUgTWFycXVlMIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQAP9rhIWJAm9axSIdkp57KcT25+2NopulRceyl/m5R+sQw+rQ7TBZ4hs7V2uORPF0JBs5c6haT0Gb+wPhl5mhoJXYBVW4A/KN+pcfDGTOuQ9qbx5b5ia3TGKkgFdGOi77kFRTpbLPDcy1vpw23wzj1b7W5sIaRtNYtvqP3i1+BGhvSJEmjgZ4wgZswHwYDVR0jBBgwFoAU3Fz8k+Qfn+6wuupSCyvKUlzgyYcwHQYDVR0OBBYEFI7VE4P28KvUWiYeox5QC8sqzjRdMA4GA1UdDwEB/wQEAwIHgDAJBgNVHRMEAjAAMD4GA1UdHwQ3MDUwM6AxoC+GLWh0dHA6Ly9jcmwuZWRybGFiLnRlbGVzZWMuZGUvcmwvRURSTGFiX0NBLmNybDANBgkqhkiG9w0BAQsFAAOCAQEAFTQQHzibJEXF8AbqpUklngJ5JDx8pn+fAas0wzE+nUNDVaqTGTrAA51mVOjo/vYZe/bz9qps2ZQXiSfLMUBH7mdf/+2Ks0ix3zM12Sy/BKy+zmibtXGcVqvF2FBy31hpFowmGnD+2e45c4nbaikVRktv7SvNEA+LQKYh+AJsWKjBrBL9L9lj6xczkoWXxtYiMGjEPZnofb2Rf93XcZ8nOqt7IaDTFZ4/Ncy+0eoZKVhdTmk3G0C4yflqxR/tFVuIK6YFQIHKF6LKQ1wYGxKONqQxRDaMSbJuR9DWtM++jXZtodQZc4yfsT/gJLLTnDCETMha6aYf+QtwEvnsdHPJpA==","value":"AQG/T6DG2X+h57z8AbxsOcC8DBe0HwBwys4qdQ0fnv3gzLj965K0Dp3gu6P8RSEBSWxgP/KhwZd9j3ym/jbaWcgMAU8qSHiPCdcHy7V7txxeM0/mZztrq3sUh71cWoZq+v8+tfXwgFY8aE2xs5o4u67g74X1ZCQNBHtwKKiFQjI2Mkpv","algorithm":"http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256"}}
```

Let me know if I can provide more useful info.

**Comment by danielweck** [comment]
The official build of Thorium v1.4 should support LCP publications just fine. Would you be able to privately share the passphrase to your license, so I can troubleshoot at my end?

**Comment by llemeurfr** [comment]
After a quick discussion between team members, which version of Thorium 1.4 are you using? the official release (from the Windows store or from Github releases) or the latest CI build? The latter does not have LCP activated.

**Comment by llemeurfr** [comment]
On Thorium Reader 1.4 official and on an LCP compliant mobile app I am request the passphrase (that I don't know), which seems to indicate that the import is ok.

**Comment by bohwaz** [comment]
Just used the link for the debian installer from https://www.edrlab.org/software/thorium-reader/

```
% thorium --version
1.4.0
```

is there another installer that should be used?

**Comment by danielweck** [comment]
The download links on the EDRLab website directly point to:
https://github.com/edrlab/thorium-reader/releases/tag/v1.4.0

Both the Debian package and AppImage have been tested with LCP publications before release. 

If you don’t mind, please share the EPUB passphrase with me in private, and I will be able to troubleshoot your publication on Mac, Windows and Linux (Ubuntu variant).

**Comment by bohwaz** [comment]
I'm confused as to what passphrase you mean as I don't get to that stage at all, it fails and doesn't ask me for anything.

I re-downloaded the deb file from your link and its the same as the one I used to install:

```
% md5sum EDRLab.ThoriumReader_1.4.0_amd64*
697258f886eba50a62c374d229a52bf9  EDRLab.ThoriumReader_1.4.0_amd64 (1).deb
697258f886eba50a62c374d229a52bf9  EDRLab.ThoriumReader_1.4.0_amd64.deb
```

So it seems I got the correct version.

I downloaded the LCPL file from my local library, if that may help?

**Comment by danielweck** [comment]
I am a little bit puzzled by the filepath in your error message “/tmp/9782072797019.lcpl”. Is this the actual location of the LCP license file you are trying to load in Thorium? (e.g. web browser temporary download?)

**Comment by bohwaz** [comment]
Yes that's where I store browser downloads.

**Comment by llemeurfr** [comment]
The version of Thorium is good then. Re. your issue, it is like if the app was not able to fetch the publication from https://lcpserver1.s3.amazonaws.com/66ae3fda-ee3d-40c3-84d8-dac917a43c93. Can you try getting this file manually from your PC?

**Comment by bohwaz** [comment]
Same result.

```
% thorium ./66ae3fda-ee3d-40c3-84d8-dac917a43c93 
Error: Import failed for the publication path : /tmp/66ae3fda-ee3d-40c3-84d8-dac917a43c93
% md5sum 66ae3fda-ee3d-40c3-84d8-dac917a43c93 
fab1d50de5c56d863126b76acf7b48e2  66ae3fda-ee3d-40c3-84d8-dac917a43c93
```

When I unzip the file, everything looks like a normal EPUB, except content of HTML files is encrypted obviously.

**Comment by llemeurfr** [comment]
Sorry I wasn't clear. The test was to check the content server was accessible from your location. 

To test the import of an LCP protected EPUB file into Thorium, you'll have to unzip the .epub, add the .lcpl as "license.lcpl" into the META-INF directory and zip the resulting content (not the parent directory of this content) as a .epub. 

I have no Debian PC here therefore cannot test Thorium on Debian myself; but Daniel did such a test.

**Comment by bohwaz** [comment]
I tried with that handcrafted EPUB and had the same error…

Readium can read all my unencrypted EPUBs perfectly fine, so not sure what's going on here, but I'm gonna quit trying with Readium as I found the book unencrypted on another website.

Thanks for your help.

**Comment by panaC** [comment]
have you tried to drag and drop the .lcpl in the thorium window ?

**Comment by bohwaz** [comment]
Same result...

**Comment by danielweck** [comment]
I am able to open the LCP license with Thorium on MacOS (i.e. the EPUB is downloaded successfully and stored in the bookshelf ... naturally I am not able to open the publication without the passphrase).

However the license has been returned:

```
This book can't be read because the LCP license has been returned.

Start: September 1, 2020 3:02 PM
End: September 3, 2020 1:31 PM
```
<img width="992" alt="Screenshot 2020-09-03 at 14 00 50" src="https://user-images.githubusercontent.com/625201/92118094-ea2bea00-eded-11ea-90b6-3b5b9c0c4a40.png">

**Comment by bohwaz** [comment]
Yeah I just returned the book  today as there is no use holding it for nothing.

**Comment by llemeurfr** [comment]
thanks for the tests you made (you're from France is't it?). We'll continue investigating on what can be wrong with the Debian version of Thorium Reader.

**Comment by bohwaz** [comment]
yes, let me know if you need anything else.

**Comment by danielweck** [comment]
I have just tested Thorium 1.4 (official Debian package and AppImage) in my Xubuntu Linux distribution (VirtualBox VM). Same outcome as decribed for MacOS https://github.com/edrlab/thorium-reader/issues/1156#issuecomment-686473466

The license correctly triggers the EPUB download, the publication is imported successfully in the bookshelf, but the "license expired" error message is displayed (as expected).

Could you please give details about your Linux distribution? Sometimes, GlibC is not supported, but in this case an error is typically immediately raised on application launch, such as: `/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_thoriuYcfDhl/resources/app.asar.unpacked/node_modules/leveldown/build/Release/leveldown.node)`

**Comment by bohwaz** [comment]
I don't have that kind of error in the terminal.

I'm using Debian buster.

```
% dpkg -l libc6
ii  libc6:amd64    2.28-10      amd64        GNU C Library: Shared libraries
```

![screenshot-diyIRPSq2g](https://user-images.githubusercontent.com/584819/92128231-7d6f1a80-ee02-11ea-9415-87acd1524ea7.jpg)

Is there a debug flag I can enable to understand what's going on?

**Comment by bohwaz** [comment]
![screenshot-uCcYEo7Z8C](https://user-images.githubusercontent.com/584819/92130595-346c9580-ee05-11ea-9370-cde944ea34df.jpg)

Works perfectly fine with unencrypted EPUBs at least ;)

**Comment by danielweck** [comment]
Related issue: https://github.com/edrlab/thorium-reader/issues/1029
