### ISSUE TITLE
The bottom character disappear a little when opening a vertical book in paginated mode

### ISSUE THREAD

**Issue by peaceroad** [edrlab/thorium-reader#1163]
Vertical books may not be fully supported yet, but I report.
For example, the following vertical book.

- https://idpf.github.io/epub3-samples/30/samples.html#kusamakura

Opening it in paginated mode, the bottom character disappeared a little like the attached image. (The same thing happened in other books.)

![thorium-examples-kusamakura-bottom](https://user-images.githubusercontent.com/1066782/92434906-fd6afb00-f1db-11ea-9a1b-19f1d4688b4b.jpg)

In the scroll bar area, it seems that the characters are hidden. (The following is the same book opened in scrollable mode.)

![thorium-examples-kusamakura-bottom-scrolled](https://user-images.githubusercontent.com/1066782/92434910-02c84580-f1dc-11ea-974c-971203b5ae34.jpg)

p.s.
In scrollable mode, the scroll bar and the bottom character touch each other, so I think it difficult to read the book.

**Comment by danielweck** [comment]
Hello, thank you for reporting. Yes, both paginated and scrolled views are broken for CSS Vertical Writing Mode (VWM) and Right To Left (RTL) direction / page progression. Sorry about that, we need to spend time figuring out what broke in the CSS cascade (several months ago, this used to work reasonably well).

**Comment by danielweck** [comment]
Merging issue https://github.com/edrlab/thorium-reader/issues/959
