### ISSUE TITLE
Adjust the line spacing for items in table of contents

### ISSUE THREAD

**Issue by peaceroad** [edrlab/thorium-reader#1164]
Depending on the system font, I find it difficult to read if the item in the table of contents has multiline. (Lines are too close.) It is good if the line spacing is adjusted.

**Comment by danielweck** [comment]
Hello, is this problem specific to Japanese characters?

**Comment by peaceroad** [comment]
About this table of contents display. I feel that the line spacing is narrow not only in Japanese but also in English.

 I think it would be easier to read if the line spacing was a little wider.

![image](https://user-images.githubusercontent.com/1066782/95044211-d4c21c80-0719-11eb-84b9-5259999f4b4c.png)

![image](https://user-images.githubusercontent.com/1066782/95044218-d8ee3a00-0719-11eb-9068-cbf2a89019e1.png)

**Comment by danielweck** [comment]
Moving this to v1.6 (v1.5 has just been released).
I experienced the same reading discomfort with line spacing inside the search results (new feature).
