### ISSUE TITLE
Display the Primary Entry Page of a W3C Publication

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1166]
W3C Publications (and especially Audiobooks) define the notion of Primary Entry Page (PEP), and HTML page which introduces the publication.  It may or may not contain a TOC. 

It would be good to give to Thorium users the possibility to display this page on-demand.

**Comment by panaC** [comment]
the PEP must be included in the resource list https://www.w3.org/TR/audiobooks/#audio-pep. But in resource list https://www.w3.org/TR/audiobooks/#audio-resourcelist there is no 'rel' content that identifies the PEP.

**Comment by panaC** [comment]
Not a priority, I remove my assignment.
There is a blocking point about how to identify the Primary Entry Page.

**Comment by danielweck** [comment]
@llemeurfr Laurent, Is this still relevant or is this a part of the W3C audiobook specification that is not necessary at this moment? (I am concerned about allocating resources for this if there are no end users / beneficiaries)

**Comment by llemeurfr** [comment]
There are no W3C Web Publications in the wild. W3C Audiobooks, when packaged, don't have a PEP. And if Web Publications appears some days, a reader based on Readium Web would be the best tool for playing with it.

Therefore let's close this issue.
