### ISSUE TITLE
W3C Publications: the title of the html Primary Entry Page may be used as a title for the publication

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1167]
This is essentially useful if the manifest is embedded in the PEP. In this case the html PEP has a title, why forcing the manifest to have a title also?

In this case the language and direction set in the html PEP are valid for the content of the manifest also.

**Comment by danielweck** [comment]
@llemeurfr  Laurent, Is this still relevant or is the W3C specification effectively a theoretical exercise at this juncture? (I am concerned about allocating resources for this if there are no end users / beneficiaries)

**Comment by llemeurfr** [comment]
Same reason for closing it as in #1166.
