### ISSUE TITLE
Scrolling stops at the end of a chapter [enhancement]

### ISSUE THREAD

**Issue by jellebakker96** [edrlab/thorium-reader#1189]
Right now you have to use the arrows at the bottom to go to the next chapter. I would expect that the default would be for a person to simply keep scrolling to go to the next chapter. I suspect that how it is implemented right now is the intended behaviour, but I was wondering if a setting could be added which allows a person to use the scroll wheel to go to the next chapter instead of having to use the arrows at the bottom of the screen. Because using these arrows to change the chapter interrupts the reading experience.

**Comment by s-kocher** [comment]
I agree, the current behavior is very confusing having to mix mouse (wheel or use of vertical scroll bar) + keyboard to progress in a book.

**Comment by danielweck** [comment]
Fixed via https://github.com/readium/r2-navigator-js/commit/99122d21159c899e7f0960dbfc69d946dfe601c3
(this will be included in the next Thorium build)
