### ISSUE TITLE
Missing "back" button after following hyperlink

### ISSUE THREAD

**Issue by PhilippeBruno** [edrlab/thorium-reader#1198]
When one follows an hyperlink in an EPUB that takes you, for example, to the glossary at the end of the book, there is not "back" button to take you where you were before clicking on hyperlink. This is very annoying.

**Comment by danielweck** [comment]
Merging issue https://github.com/edrlab/thorium-reader/issues/1624

**Comment by elcste** [comment]
This is a great addition!

However, I just tried it, and I find the icons confusing. The |◄  ►| icons remind me of [media controls](https://en.wikipedia.org/wiki/Media_control_symbols#Symbols:~:text=Skip%20to%20the%20start%20or%20previous%20file/track/chapter) makes me think the button will either take me to the beginning/end of book or chapter. 

Personally I think standard arrows (←, →) would be a better choice. I think they are still distinguished enough from the page back/forward buttons (⟨ , ⟩) on the right side

**Comment by danielweck** [comment]
Otherwise, as you suggested, here is a screenshot with standard left/right arrows (the vector graphics viewport is a big large by default, but we can scale the icons down):

<img width="1552" alt="Screenshot 2022-10-17 at 12 17 24" src="https://user-images.githubusercontent.com/625201/196163964-d43a07e3-df23-4610-82c6-3b5dc1ed4da0.png">

**Comment by danielweck** [comment]
@llemeurfr @gautierchomel @panaC could you please look at above 3x screenshots and let me know which one you prefer? :) Thank you

**Comment by PhilippeBruno** [comment]
> For reference, here is a screen capture of the originally-proposed arrows:
> 
> <img alt="Screenshot 2022-10-17 at 12 19 48" width="1552" src="https://user-images.githubusercontent.com/625201/196164350-68c1eab8-17da-484f-a6dc-e98be1de1ddd.png">

The media control buttons are a no-go for me.

**Comment by PhilippeBruno** [comment]
> Otherwise, as you suggested, here is a screenshot with standard left/right arrows (the vector graphics viewport is a big large by default, but we can scale the icons down):
> 
> <img alt="Screenshot 2022-10-17 at 12 17 24" width="1552" src="https://user-images.githubusercontent.com/625201/196163964-d43a07e3-df23-4610-82c6-3b5dc1ed4da0.png">

I like the simple arrow, but I question the design a bit... (1) Why 2 buttons? A back and a... forward ? (2) I am not sure I would place the button in the lower left corner as you did. What not in the bar above, more or less like with a browser?

**Comment by gautierchomel** [comment]
+1 for standards arrow (now that "go back to the library" has it's own picto).

**Comment by llemeurfr** [comment]
I agree that the simple left / right arrows are the best. 

Re. @PhilippeBruno's remark about the forward button, it was a discussion between us during our last engineering call; the consensus is to test it and see ; it allows going back too far and changing mind. 

I Also agree that keeping the arrows on the bottom keeps them alive when full screen, which is good, as @elcste suggested. 

The main issue with this is IMO that the differentiation with prev / next page is not visually obvious. 
Having more information like is the OverDrive app would be great in this aspect, but the feasibility of such feature must first be discussed.

**Comment by danielweck** [comment]
I updated the SVG icons with the standard left/right arrows (scaled down a bit). I also enabled the navigation history buttons in fullscreen "zen" mode.
See 4501cd1e2e03c32680cfa72afd729229ee39dee6
