### ISSUE TITLE
The window disappears if opened on a secondary monitor in a different position

### ISSUE THREAD

**Issue by jacoporinaldi** [edrlab/thorium-reader#1201]
I tried to look for previousely opened issues but i was unable to find any.
This issue can be reproduced easily with the following steps:

- Open the app, move the window on a secondary screen
- Close the app
- Disconnect the second monitor OR move it via screen settings on another position (if it was above the main monitor, move it on the right, left or bottom)
- Open the app again

The window will not be reachable until the screen is either connected/moved again on the same position or the user settings are deleted manually. 

A similar issue can be found for Github desktop app ( [/desktop/desktop/issues/2107] ).

**Comment by danielweck** [comment]
@panaC Food for thoughts: I think these types of issues in Thorium could be mitigated by using the small `electron-window-state` lib which makes the window position/dimensions/maximise/minimise/etc. state persistent in a JSON file, and which validates incoming state by checking out-of-bounds coordinates for connected external monitor(s) and/or current screen resolution. The GitHub Desktop app uses this as well.

References:

https://github.com/mawie81/electron-window-state/blob/master/index.js

https://github.com/desktop/desktop/pull/7541

**Comment by panaC** [comment]
i don't think it's a great idea to integrate this small lib. We already save the window bound in redux persistence. But maybe we can ensure that the bounded window is visible on the display : 
https://github.com/mawie81/electron-window-state/blob/master/index.js#L57-L60

**Comment by danielweck** [comment]
The advantage of an external JSON file for the specific case of window placement is that end-users can delete a single file in order to recover access to the app (i.e. if the window suddenly disappears out of view, and all other options to make it reappear have been exhausted). As it stands now, the entire `EDRLab.ThoriumReader` folder must be deleted in order to restore the default window position / dimensions. Just a thought.

**Comment by danielweck** [comment]
...but, JSON file vs. Redux / Database persistence is a distinct topic. The issue of window "state" restoration/validation can be addressed in our current codebase by adopting the code logic from `electron-window-state`, whilst preserving Thorium's existing persistence mechanism.
