### ISSUE TITLE
Popup for epub:type="endnote" shows generated code as plain text

### ISSUE THREAD

**Issue by duenckel** [edrlab/thorium-reader#1212]
Hi,

I have found a bug in Thorium Windows Version 1.4.0.

Instead of the referenced endnotes, the popups shows generated code as plain text:

![thorium_bugreport_epub-type_endnote](https://user-images.githubusercontent.com/3939051/95959220-7a544a80-0e02-11eb-8458-aa07e82e78f9.png)

This code does not appear in the EPUB HTML and is probably generated by Thorium.

```
<div id="r2-footnote-for_fn_elNr-1-49-1-2-1-2-18-3-3" class="r2-footnote-container r2-no-focus-outline" tabindex="0" autofocus="autofocus"><a     epub:type="noteref" role="doc-noteref" href="footnotes1.xhtml#fn_elNr-1-49-1-2-1-2-18-3-3" class="" style="">[*]</a></div>
```

Here is the EPUB HTML source code for the endnotes reference:

```
<p class="lastInSequence no_indent">... Künftige, nachdem die Dispensation<span class="fussnote" id="fn_elNr-1-49-1-2-1-2-18-3-3"><a epub:type="noteref" href="footnotes1.xhtml#fn_elNr-1-49-1-2-1-2-18-3-3" role="doc-noteref">[*]</a></span> von der Zensur ...</p>
```

And here is the EPUB HTML source code for the endnotes content:

```
<ol>
    <li aria-label="Fußnote 7" class="fussnote" epub:type="endnote" id="fn_elNr-1-49-1-2-1-2-18-3-3" role="doc-endnote">
        <div class="fussnotenzaehler" hidden="hidden">
            <p class="firstInContainer lastInContainer firstInSequence lastInSequence">
                <a epub:type="referrer" href="chapter48.xhtml#fn_elNr-1-49-1-2-1-2-18-3-3" role="doc-backlink">*</a>
            </p>
        </div>
        <div class="fussnoteninhalt">
            <p class="firstInContainer lastInContainer firstInSequence lastInSequence">Freilassung</p>
        </div>
    </li>
</ol>
```

Can you please look into the issue?

Best regards,
Björn

/cc @tofi86

**Comment by danielweck** [comment]
Hello, thank you very much for reporting this bug, with such level of detail. Much appreciated.

The "popup footnote" panel shows the source as a fallback when XHTML parsing fails. Could you please privately share the EPUB with me so I investigate?

**Comment by danielweck** [comment]
Wait, are your notes contents in the different HTML document than the originating hyperlink?
If so, Thorium does not support external "popup footnotes" but the hyperlink should be followed into the targeted document, instead of just showing a useless popup panel.

**Comment by danielweck** [comment]
See related issue: https://github.com/edrlab/thorium-reader/issues/1150#issuecomment-678421901

**Comment by duenckel** [comment]
> If so, Thorium does not support external "popup footnotes" but the hyperlink should be followed into the targeted document, instead of just showing a useless popup panel.

I agree.
And following the hyperlink into the targeted document would be a perfectly fine fallback solution in my opinion.

**Comment by danielweck** [comment]
Could you please privately share the EPUB with me, so I can run tests and be sure to actually fix the bug you describe? Thank you.

**Comment by duenckel** [comment]
> Could you please privately share the EPUB with me, so I can run tests and be sure to actually fix the bug you describe? Thank you.

Yes sure.
I have sent the EPUB to your GMail account.

**Comment by danielweck** [comment]
Thank you, I tested your EPUB to verify that the bug is indeed fixed. I am in the process of publishing the updated Readium packages. The automated Thorium builds will immediately include the bugfix. The next official Thorium release (v1.6) will include the bugfix (before Christmas).

**Comment by duenckel** [comment]
Awesome!
Thank you for looking into it so quickly :-)

**Comment by danielweck** [comment]
Fix now integrated in Thorium https://github.com/edrlab/thorium-reader/commit/ef817803c8bf595e26752b98c378d20d6e07fade

**Comment by danielweck** [comment]
Follow-up fix: https://github.com/edrlab/thorium-reader/commit/3b0ad13e77326ff3cd4fefcddcbcf3c4bb5ed620
