### ISSUE TITLE
 in-document publication-wide text search: keyboard shortcuts for previous/next

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1214]
CTRL-F ... we need F3 / Shift-F3 as well, but only when the search popup panel is mounted in the React DOM (as opposed to CTRL-F which is always available).

**Comment by danielweck** [comment]
Code reference:

https://github.com/edrlab/thorium-reader/blob/4882c83330c800becf5e9950af6873b50e9236e2/src/common/keyboard.ts#L88-L105

**Comment by elcste** [comment]
If it's possible to add multiple shortcuts for the same action, I suggest adding Ctrl+G and Ctrl+Shift+G as well.

These are standard for the GNOME desktop (see https://developer.gnome.org/hig/stable/keyboard-input.html).

Chrome on Linux uses these shortcuts (https://support.google.com/chrome/answer/157179)

Firefox: has both F3/Ctrl+G and Shift+F3/Ctrl+Shift+G (https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#firefox:linux:fx83)

**Comment by danielweck** [comment]
I added support for an alternative to `(SHIFT) F3`: `(SHIFT) CTRL G`.
https://github.com/edrlab/thorium-reader/commit/e518c1d998cab84efd6d5b7ce88440f218958d8c
