### ISSUE TITLE
PDF pagination overflow counter: when reaching last page, continue to click "next" button, then observe that "previous" button must be clicked as many times to return into the page flow

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1215]

**Comment by danielweck** [comment]
Note that this bug does not exist when going backwards and reaching the first page.

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/blob/develop/src/renderer/reader/pdf/webview/pdfReader.ts#L531-533

the page counter limit isn't capped.

**Comment by panaC** [comment]
the question is how to find the pdf number of pages ?
