### ISSUE TITLE
The smallest dimensions for the reader window are still too big (smaller would be useful for testing/emulating EPUB layout on small mobile devices displays)

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1223]
Potential problem: UI design is currently non-responsive, the top toolbar in particular overflows to the right, and the popup modal dialogs do not shrink adequately (lots of padding whitespace).

**Comment by SimonPRH** [comment]
Hello! Just bumping this as it remains a considerable barrier to full-time use of Thorium for my use case. At the moment the default window size is quite awkward and there is no way to set the aspect ratio to that typical of a tablet, e-reading device or smartphone.

**Comment by llemeurfr** [comment]
A fully responsive layout is a long term project. We'll address it when we make a full rework on the UI. 
Thorium reader is after all a desktop app.
