### ISSUE TITLE
Green box appears around some HTML elements after resizing window

### ISSUE THREAD

**Issue by SimonPRH** [edrlab/thorium-reader#1225]
When resizing the UI, often an element on the page (not always the same one each time) gets a green box around it. This happened on all books I checked.

Thorium 1.5, MacOS Mojave, EPUB 3 compliant reflowable files.

<img width="912" alt="Screenshot 2020-10-15 at 16 17 11" src="https://user-images.githubusercontent.com/69913645/96150253-1c0e9100-0f02-11eb-9014-9656eb62bfc8.png">

**Comment by danielweck** [comment]
Hello Simon, the green rectangle should disappear after one second or so. It is the focus outline for hyperlink targets.

**Comment by SimonPRH** [comment]
Hi Daniel. Is it intended behaviour that this happens even when the page was accessed by simple page turns, rather than a hyperlink? I didn't click any hyperlinks here, I just scrolled through the book. I can definitely imagine getting confused messages from people asking why transient green boxes are appearing in their books! It makes sense to happen when a hyperlink is clicked, but this wasn't that.

Thanks!

**Comment by danielweck** [comment]
Indeed. I will see what I can do.

**Comment by danielweck** [comment]
In recent Electron / Chromium releases there has been a CSS regression bug with the animation used to make the outline disappear. I have disabled the declarative implementation and we are now resorting only to the imperative / programmatic approach to temporarily highlight / outline hyperlink targets in loaded documents.
