### ISSUE TITLE
Full screen video stretches in Window

### ISSUE THREAD

**Issue by nitrokevin** [edrlab/thorium-reader#1234]
I have an ePub FXL which has buttons which open a video, if I click the video control to make it full screen then on Windows the video is stretched vertically to fit the space, whereas the Mac version scales it up in proportion

**Comment by danielweck** [comment]
Thorium is based on Electron / Chromium, and I suspect that this behaviour cannot be fixed at the application level. This sounds like a Windows-specific integration bug at the level of Electron / Chromium. It may also be related to how the HTML5 video element is authored at the source (i.e. integrated in the markup by content creators) ... but again I don't see how Thorium's own code could influence the fullscreen behaviour, in this instance. I am closing this issue as "no fix", but please feel free to comment further just in case there are new findings.
