### ISSUE TITLE
[Linux package] Icon's path is "0x0" (electron-builder issue?)

### ISSUE THREAD

**Issue by ghost** [edrlab/thorium-reader#1241]
##### SUMMARY
In the prebuilt Linux .deb package by EDRLab, the icon's path is "0x0":
`/usr/share/icons/hicolor/0x0/apps/thorium.png`

The path is probably invalid as KDE's application launcher won't show the icon. The path should have been "1024x1024".

From [this electron-builder document](https://www.electron.build/icons):
> Linux icon set will be generated automatically based on the macOS `icns` file or common `icon.png`.
> Or you can put them into the `build/icons` directory if you want to specify them yourself. The filename must contain the size (e.g. `256x256.png`) of the icon. Recommended sizes: 16, 32, 48, 64, 128, 256 (or just 512).

**Comment by jloqfjgk** [comment]
This bug is still present in v1.7.0.

**Comment by danielweck** [comment]
Merged issue: https://github.com/edrlab/thorium-reader/issues/1721

App icon is missing when Thorium is in the Ubuntu dock. But the app icon appears correctly when Thorium is running.

![Screenshot from 2022-07-13 23-04-28](https://user-images.githubusercontent.com/104021043/178785604-98138eb0-7d46-4cf1-a93d-2639791045cf.png)

**Comment by panaC** [comment]
I seems this PR fixed the issue. Can you confirm for me on your side ?

**Comment by elcste** [comment]
The icon appears properly now in Ubuntu 22.04 with the latest dev version deb package.

**Comment by panaC** [comment]
many thanks @elcste

**Comment by danielweck** [comment]
Thank you for confirming so quickly, @elcste :)
