### ISSUE TITLE
[Linux package] Incorrect category in .desktop file

### ISSUE THREAD

**Issue by jloqfjgk** [edrlab/thorium-reader#1242]
##### SUMMARY
In the prebuilt Linux .deb package by EDRLab, `thorium.desktop` has the following line:
`Categories=Development;`
Thorium Reader is not an application for development, and `Office` category seems more appropriate. [1]

Maybe `package.json` should be patched like this?
```
--- a/package.json
+++ b/package.json
@@ -210,7 +210,8 @@
       "desktop": {
         "MimeType": "application/epub+zip"
       },
-      "executableName": "thorium"
+      "executableName": "thorium",
+      "category": "Office"
     },
     "mac": {
       "category": "public.app-category.developer-tools",

```

[1] https://specifications.freedesktop.org/menu-spec/latest/apa.html#main-category-registry

**Comment by danielweck** [comment]
Thank you for reporting this!
I agree with your suggestion change.

https://www.electron.build/configuration/linux
=>
https://specifications.freedesktop.org/menu-spec/latest/apa.html#main-category-registry
=>
`Office`
