### ISSUE TITLE
Rendering issue around some margined block text in vertical layout.

### ISSUE THREAD

**Issue by kitanic** [edrlab/thorium-reader#1245]
Hi.
I found bad layout result in vertical book. 
source: http://umetake.d.dooo.jp/kindle/download/Miserables.epub
Environment: Thorium-1.6.0-alpha.1.323935906

This problem seems to occur when the screen is small or the text is large with paged mode. The central block of text has margin indentation by div. When a line break occurs in the block, it causes an overlap with subsequent text. 

The shot below corresponds to the range from id="kobo.97.1" to id="kobo.119.1" of 0006.xhtml in EPUB Package. (8/59 6% on above shot)

OK shot:
<img width="1442" alt="ok" src="https://user-images.githubusercontent.com/3982249/97673063-785edc80-1ace-11eb-9fb1-952d5b60668f.png">

Invalid shot: Flowed text overlaps with subsequent paragraph.
<img width="1360" alt="invalid" src="https://user-images.githubusercontent.com/3982249/97673071-7ac13680-1ace-11eb-86f3-058877bc4c11.png">

**Comment by danielweck** [comment]
Thank you very much for reporting the issue, and for providing a test/sample EPUB to reproduce the bug. We are in fact already aware of the broken support for RTL (Right To Left) and VWM (Vertical Writing Mode) documents. Related issues:
https://github.com/edrlab/thorium-reader/issues/139
https://github.com/edrlab/thorium-reader/issues/959
https://github.com/edrlab/thorium-reader/issues/327

**Comment by danielweck** [comment]
I suspect that the bug you found is an edge case in ReadiumCSS, which applies certain styles that break the text flow under certain border conditions (e.g. viewport size). That being said, it could just be a Chromium bug as well. Let us know if you see a pattern in the CSS debugger / Web Inspector.

CC @JayPanoz

**Comment by kitanic** [comment]
Hmm. 
I'm not a web engineer so I don't know if I can provide accurate information. 

Anyway, I'm attaching the Web Inspector results when viewed in Safari Chrome. This picture is purely displaying the source HTML in the EPUB package and does not incorporate Readium-CSS.

Additionally, I have try to insert column-width property in <body> manually, this dose *not* cause any problems. 

Does this give you a hint?

Safari:
<img width="1585" alt="safari inspector" src="https://user-images.githubusercontent.com/3982249/97681129-22446600-1adb-11eb-9b2d-112b0dbdd369.png">

Chrome:
<img width="1227" alt="chrome inspector" src="https://user-images.githubusercontent.com/3982249/97681157-240e2980-1adb-11eb-81b0-4855551bc9de.png">

**Comment by kitanic** [comment]
I've probably found cause of problem so I'll tell you.

I tried to modify --RS__maxMediaHeight to 1000vw in my test html, this makes correct result. So I think it's because the size of div is limited by max-width in ReadiumCSS-before. I don't know what the right value to put here is for me, but I think the cause is right in this.

**Comment by danielweck** [comment]
Merging into duplicate issue https://github.com/edrlab/thorium-reader/issues/959
