### ISSUE TITLE
Missing keyboard shortcut to jump to end/beginning of EPUB

### ISSUE THREAD

**Issue by PhilippeBruno** [edrlab/thorium-reader#1247]
A keyboard shortcut to take the reader straight to the end or the beginning of an EPUB would be a welcome addition. A use case follows.

Often, when preparing a list of references for academic work, one needs to quickly locate the copyright page of a book. Whilst PDF ebooks pretty much all put the copyright page in the same order as the printed book (ie. a few pages from the cover page), EPUBs sometimes put it at the very end of the document. So when one is unsuccessful locating the copyright information at the beginning of the EPUB, it would be nice to be able to jump to the end of the EPUB using a keyboard shortcut. Now, one has to click towards the end of the progress bar at the bottom to jump near the end.

**Comment by danielweck** [comment]
Fixed via: https://github.com/edrlab/thorium-reader/pull/1341

Feature: goto begin/end of publication, using CTRL HOME/END keyboard shortcuts, or shift-click on left/right arrow button icons.
