### ISSUE TITLE
review hash path logic. it doesn't work with an exploded epub

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#1249]
https://github.com/panaC/thorium/blob/29341f0804d620d2dfe803e17991d1fe92bf0946/src/main/redux/sagas/api/publication/packager/packageLink.ts#L103-L104

**Comment by danielweck** [comment]
Is the code comment "crc32 check failed // how to fix this ?" still valid at this point?
https://github.com/edrlab/thorium-reader/blob/dee5e3ec4e25e7ba1abb18e2d79a3f12cf0e62e7/src/main/redux/sagas/api/publication/packager/packageLink.ts#L107

**Comment by panaC** [comment]
replace with #1298
