### ISSUE TITLE
2-page spread fixed-layout FXL splits or overlaps when resizing window

### ISSUE THREAD

**Issue by CircularKen** [edrlab/thorium-reader#1265]
The appearance of a double page spread page is unusual when resizing the window. It splits or overlaps see video here https://www.dropbox.com/s/3kihkaiq8b8qfkw/Split_and_overlap.mp4?dl=0

Suggest waiting until the window has finished being resized before applying the change?

**Comment by danielweck** [comment]
oh that looks nasty. agreed.
there is a loading “mask” to temporarily hide webview contents until interaction is ready, but there is no such mechanism for window resize.
would you mind privately sharing this EPUB with me? I am surprised by the resize “lag”, and I would love too be able to run tests at my end.

**Comment by CircularKen** [comment]
It is not particular to that file. Happens for all FXL with full bleed backgrounds.
Here is one I can publicly share https://www.dropbox.com/s/7sbbg1j7cm4barr/Defining_reading_order.epub?dl=0

**Comment by danielweck** [comment]
This was fixed (tested in Thorium 2.1.0)
