### ISSUE TITLE
Home screen evolution

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1273]
In the home screen, we'll find, from top to bottom: 

"Recently added" (the max 5 publications of all types added since less than a month and not yet opened)
"Resume reading EPUB" (max 5 last open publication)
"Resume reading PDF"
"Resume reading Audiobook"
"Resume reading Divina"

and of course the section is absent if empty.

An "All books" link is added at the right of each section, to remind the user that he can go to the page listing all his books. This will later be refined when a selection by type (EPUB, PDF ...) is available in the user catalog screen.

**Comment by danielweck** [comment]
Hello Laurent, PR is now merged: https://github.com/edrlab/thorium-reader/pull/1292
...however I must say 5 publications per horizontal strip of cards is a small number (it was 10 before). Have a try (develop branch, or automatic CI releases if you don't have time to build yourself), and see what you think :)

**Comment by llemeurfr** [comment]
ok I see; we could go up to something like 8 or even go back to 10. 

After all, at least for the first list (recently added) some people load ebooks in a batch and the limitation in time will avoid having a long list most of the time.  
And for the other lists, I suppose that some people read more than 5 books simultaneously. What we're missing is a way to know that a book has been fully read and should disappear from these lists.

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/pull/1292#pullrequestreview-564316236 :)
