### ISSUE TITLE
OPDS browser UI: regression, looks all mangled

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1288]
I'm not sure that this is because of the view components:
https://github.com/edrlab/thorium-reader/tree/develop/src/renderer/library/components/opds

...or some backend code (e.g. `r2-opds-js` or Thorium's own data converters)

**Comment by panaC** [comment]
I cannot reproduce this issue on the latest develop branch.

everything looks good

**Comment by llemeurfr** [comment]
First analysis, the culprit is in r2-opds-js and strikes on OPDS 1 feeds. 1.0.27 is ok, but after that it doesn't. 

There was a package upgrade in https://github.com/readium/r2-opds-js/commit/c9a54c7a7753e2bc61789bb1a700c944d9326cf9, which may be the cause of the issue.

**Comment by danielweck** [comment]
* `npm install r2-opds-js@1.0.27`
* `cat node_modules/r2-opds-js/package.json | grep -I version`
* `SKIP_TYPESCRIPT_CHECK=1 npm run start:dev`

https://github.com/readium/r2-opds-js/compare/v1.0.27...v1.0.28

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/commit/7680952c9843f1fcb110bea4864996e110ca0cbd

See https://github.com/readium/r2-opds-js/blob/develop/CHANGELOG.md#1032
