### ISSUE TITLE
Feature: configurable network proxy HTTP request agent

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1314]
https://github.com/edrlab/thorium-reader/blob/e518c1d998cab84efd6d5b7ce88440f218958d8c/package.json#L253

https://github.com/edrlab/thorium-reader/tree/develop/src/main/network
=>
https://github.com/node-fetch/node-fetch#custom-agent

Suggestions:

https://github.com/insightfuls/better-https-proxy-agent

https://github.com/TooTallNate/node-https-proxy-agent

https://github.com/snoguchi/node-fetch-with-proxy

https://github.com/zjael/simple-proxy-agent

Note that some LCP/LSD HTTP requests are created in the `r2-lcp-js` package independently of Thorium's own code (i.e. LSD fetch, and register, return, renew):

https://github.com/readium/r2-lcp-js/tree/develop/src/lsd

**Comment by danielweck** [comment]
Related issue: https://github.com/edrlab/thorium-reader/issues/1323

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/commit/5b095fcec33edce32fdc066474954ac4605de91a

I'm closing the issue. feel free to reopen it

**Comment by danielweck** [comment]
I agree with closing this issue for now. There was one feature request from a user (technical person) to enable the configuration inside Thorium of HTTP proxy (which we could technically implement via an Agent in our NodeFetch HTTP client).
However this does not seem to be a high priority (no further feedback).
