### ISSUE TITLE
PDF import fails with `npm run start` (production build)

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1316]
`Error: Setting up fake worker failed: "Cannot find module './pdf.worker.js'`

**Comment by danielweck** [comment]
Note that PDF.js in the reader view works fine, it is just the main process PDF engine that fails (cover extraction)

**Comment by danielweck** [comment]
May the cause of the problem is the removal of the WebPack directives in the recent PDF PR:
https://github.com/edrlab/thorium-reader/pull/1285/files#diff-cfeca5fe445b380fe778f93376efbad44f6797e5841ac22ca0c25a913e1ee71e

**Comment by danielweck** [comment]
I wonder if this is a problem with `pdf.js-extract` https://github.com/edrlab/thorium-reader/blob/0d9e15c745804c5815b0373adbac6f1b6081fa96/src/main/pdf/manifest.ts#L10

**Comment by danielweck** [comment]
I've just tested with Thorium 1.5 (MacOS DMG from the GitHub releases), importing PDF works.
However this is not exactly like using `npm run start` so a proper test would consist in building the 1.6 DMG and test that instead.

**Comment by danielweck** [comment]
I built the 1.6 DMG, fails to import PDF (rendering okay if PDF is already packaged in WebPublication, which indicates that the `pdf.js-extract` code fails)

**Comment by panaC** [comment]
do you think it's the issue https://github.com/edrlab/thorium-reader/commit/e1f16b2c3112a96470d3e6049fb094cd66be1233 ?

**Comment by panaC** [comment]
https://github.com/ffalt/pdf.js-extract/compare/0.1.4...0.1.5

**Comment by panaC** [comment]
`pdf.js-extract@0.1.4` fixed the issue on my side.
