### ISSUE TITLE
"about Thorium" auto-generated EPUB is displayed in "all books" library section

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1318]
![Screenshot 2021-01-15 at 17 04 54](https://user-images.githubusercontent.com/625201/104756908-50d5f280-5754-11eb-9b8b-acfa8dfc7265.png)

**Comment by danielweck** [comment]
Follow-up to  https://github.com/edrlab/thorium-reader/pull/1199

**Comment by danielweck** [comment]
Code ref: https://github.com/edrlab/thorium-reader/pull/1199/commits/21cbc996d724ab0eb0f44dcbca66dd00a329600c#diff-d4db05d42f627e1c8c9aa60553e74ad304334d03684ce3c95812f600e1c042f2

**Comment by llemeurfr** [comment]
Having this as an ebook in the catalog was planned. But not Having a proper title and cover was not planned.

**Comment by danielweck** [comment]
This "special" EPUB is hidden in the "home" library screen, which is good (in my opinion). I personally think it should be totally hidden, including in the "all books" library view. This should only be accessible via the "about Thorium" button, I feel strongly :)

**Comment by llemeurfr** [comment]
mmmh ok I follow you @danielweck on this. Let's hide the ebook from the "all books" library view also.

**Comment by panaC** [comment]
issue : https://github.com/edrlab/thorium-reader/blob/be531025720e7eaf5a9f3d7c5f46cf8e24040d5b/src/main/api/catalog.ts#L94-L95

**Comment by panaC** [comment]
need to filter from the root
https://github.com/edrlab/thorium-reader/blob/be531025720e7eaf5a9f3d7c5f46cf8e24040d5b/src/main/redux/sagas/api/publication/findAll.ts#L11
