### ISSUE TITLE
PDF: print feature is not disabled in Mozilla PDF.js viewer (CTRL-P, or COMMAND-P, or SHIFT-CTRL-P)

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1320]
...this is problematic from a UX standpoint, but also because of LCP protection / DRM license rights.

**Comment by panaC** [comment]
https://github.com/edrlab/pdf.js/blob/cb33c84e554af6b4680a4ea6b7a327a8e01a1aa0/web/viewer.js#L2335

**Comment by panaC** [comment]
https://github.com/edrlab/pdf.js/blob/cb33c84e554af6b4680a4ea6b7a327a8e01a1aa0/web/viewer.js#L1038
