### ISSUE TITLE
Cannot add catalogs in v1.6.0-alpha.1.488741793

### ISSUE THREAD

**Issue by nvdaes** [edrlab/thorium-reader#1321]
Steps to reproduce:

1. Press the Catalogs button.
2. Press the Add catalog button.
Result: The catalog cannot be added. Instead, this error is shown:

< Error A JavaScript error occurred in the main process
Uncaught Exception:
Error: Invalid package c\Users\User\AppData\Local\Programs\EDRLab.ThoriumReader\resources\app.asar
    at createError (electron/js2c/asar.js:126:17)
    at Object.fs.lstat (electron/js2c/asar.js:257:23)
    at electron/js2c/asar.js:294:33
 
Should I delete some folder? Anyway, I suppose that this should be done automatically without manual actions from users.

**Comment by nvdaes** [comment]
Also, I cannot delete imported publications. I'll try to delete appdata folder.

**Comment by danielweck** [comment]
@panaC and I are aware that the database size grows indefinitely in some cases, could you please verify the size of your app data Thorium folder before deleting it?

**Comment by nvdaes** [comment]
Oh sorry, I deleted it before reading your message. But I cannot add catalogs. Anyway, for other aspects like go to page and search, they work well. A more detailed documentation or demos will be also useful.

**Comment by danielweck** [comment]
What catalog are you trying to add? an OPDS feed?

**Comment by nvdaes** [comment]
Yes, I tried to add an OPDS feed. Also, on my spanish mailing list for
NVDA, a user has reported that in 1.5 he cannot add this catalog:
https://textos.info/opds

He can instead add an atom catalog provided by text.info.


2021-01-16 12:44 GMT+01:00, Daniel Weck <notifications@github.com>:

**Comment by nvdaes** [comment]
Sorry, I said:

> He can instead add an atom catalog provided by text.info.

And the correct URL is textos.info

2021-01-16 12:48 GMT+01:00, nvdaes <notifications@github.com>:

**Comment by nvdaes** [comment]
Finally I can add catalogs, after pressing escape several times to
skip the JavaScript error dialog. I can add this catalog:

http://www.feedbooks.com/books/top.atom?category=FBFIC019000

Seems to be an atom feed, not opds?

2021-01-16 13:00 GMT+01:00, nvdaes <notifications@github.com>:

**Comment by nvdaes** [comment]
I'm not sure, but sometimes I get Uncaught Exceptions trying to
perform a search in publications by pressing control+f. Maybe related
to opening dialogs? This is the shown message. I can also search terms
after pressing escape several times to discard the errors:

> A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: One-time callback was called more than once
    at failure
(C:\Users\User\AppData\Local\Programs\EDRLab.ThoriumReader\resources\app.a...:2320582)
    at Request.<anonymous>
(C:\Users\User\AppData\Local\Programs\EDRLab.ThoriumReader\resources\app.a...:2321581)
    at Request.emit (events.js:223:5)
    at Request.onRequestError
(C:\Users\User\AppData\Local\Programs\EDRLab.ThoriumReader\resources\app.a...:4758465)
    at ClientRequest.emit (events.js:223:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

2021-01-16 18:40 GMT+01:00, nvdaes <notifications@github.com>:

**Comment by danielweck** [comment]
>  Seems to be an atom feed, not opds?

OPDS 1.x feeds are based on the Atom XML syntax.
OPDS 2.x use JSON syntax

**Comment by danielweck** [comment]
The "TypeError: One-time callback was called more than once" is an obscure bug that we do not fully understand (the error message comes from somewhere deep in a library dependency, not from Thorium's codebase)

**Comment by nvdaes** [comment]
Thanks. Let me know if you want me to open a new issue for the errors when trying to perform a search please, or if it is not needed.

Enviado desde mi iPhone

**Comment by nvdaes** [comment]
Thanks, I do not observe it in version 1.-5 installed from the store.

Enviado desde mi iPhone

**Comment by danielweck** [comment]
Official releases use a different database backend, I bet the error comes from this.

**Comment by danielweck** [comment]
Follow-up issue about OPDS / failing network requests: https://github.com/edrlab/thorium-reader/issues/1323

**Comment by nvdaes** [comment]
Daniel, thanks for your comments. I'll update the article about
thorium with the OPDS provided in this repo, and I'll ost a comment
there mentioning this issue.
I'm talking about:
https://nvdaes.github.io/epub7

2021-01-18 12:59 GMT+01:00, Daniel Weck <notifications@github.com>:

**Comment by danielweck** [comment]
Thank you Noelia <smile>
The problem with the https://textos.info/opds URL is that it is in fact not the final URL that resolves the OPDS feed, due to HTTP redirections. In itself, this is not problematic, however what currently trips Thorium is the transition from a secure HTTPS URL to an unsecure HTTP one ... and finally to a secure one ( https://textos.info/opds -> http://www.textos.info/opds -> https://www.textos.info/opds -> https://www.textos.info/catalogo.atom )

**Comment by nvdaes** [comment]
Thanks for your great explanation!

2021-01-18 13:25 GMT+01:00, Daniel Weck <notifications@github.com>:
