### ISSUE TITLE
EDRLab's PDF.js fork is out of date

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1322]
Culprit:
https://github.com/edrlab/thorium-reader/commit/603c65cef4ebfec9fb3492e99cf923feeb2b0c51

@panaC  can you please update the upstream / authoritative fork of PDF.js maintained by EDRLab:
https://github.com/edrlab/pdf.js/blob/gh-pages/web/viewer.js

Remember to update the README in Thorium as well:
https://github.com/edrlab/thorium-reader/tree/develop/src/resources/lib/pdfjs

**Comment by panaC** [comment]
i don't have access !

**Comment by danielweck** [comment]
Sorry, I did not notice this :)
You are now a contributor (same GitHub settings as the Thorium repository)

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/commit/be531025720e7eaf5a9f3d7c5f46cf8e24040d5b
and via https://github.com/edrlab/pdf.js/commit/7a7c7979332a6523457b50a1e875c4547309c921
