### ISSUE TITLE
Error "callback was called more than once"

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1327]
Also reported here:
https://github.com/edrlab/thorium-reader/issues/1321#issuecomment-761764165

On Thorium 1.5 (Windows Store official release), as well as 1.6 alpha builds (on Windows too).

`TypeError: One-time callback was called more than once`

> The error occurs as soon as you type anything into the search bar, it does not actually matter what the search term is in this case.

![image](https://user-images.githubusercontent.com/625201/105008173-caa9fc80-5a30-11eb-93ce-b122c14f56f2.png)

Possibly related:
https://github.com/edrlab/thorium-reader/issues/406

**Comment by danielweck** [comment]
Related issue: https://github.com/edrlab/thorium-reader/issues/999

**Comment by danielweck** [comment]
![grafik](https://user-images.githubusercontent.com/24251362/78713908-43fdb600-791b-11ea-83e0-8d7d37738d77.png)

**Comment by danielweck** [comment]
I am not able to reproduce this bug on my Windows computer, via `npm run start` (production build which uses LevelDown database backend / PouchDB adapter, instead of SQLite3)

**Comment by llemeurfr** [comment]
More information from the user: The problematic epub file contains hyperlinks, audio and video. It is exported as a FIXED LAYOUT epub from the latest version of InDesign.
It works no problem on Apple Books and Adobe Digital Editions on a mac.
However, it does not work on Adobe Digital Editions on our PC. It also throws an error.

**Comment by danielweck** [comment]
I am happy to try the offending EPUB at my end.

**Comment by danielweck** [comment]
Sorry, I already tested this 600MB+ EPUB.

**Comment by panaC** [comment]
from https://github.com/edrlab/thorium-reader/issues/1432#issue-853458795

While trying to open an EPUB, I got the following error:

A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: One-time callback was called more than once
  at failure

![Thorium_F4dpsjY5Ug](https://user-images.githubusercontent.com/36426806/114032375-40608000-984a-11eb-962e-3683042df91b.jpg)

Problematic EPUB emailed privately to Daniel Weck.

**Comment by danielweck** [comment]
Closing because of lack of reproducibility. @PhilippeBruno would you be so kind as to attempt to reproduce this bug with Thorium 1.7? (either from the Windows Stored, or via the installer)

**Comment by PhilippeBruno** [comment]
Hi Daniel, prior to updating Thorium, I tested the two EPUBs and sure enough, I got the same JavaScript error.

Then, I installed v1.7.1-alpha.1.842238767 and I no longer experienced the JavaScript error, so I think you nailed it.

As a side note, I did notice, though, that the update DID NOT fix the briefly flashing cover page problem I reported some time ago.

**Comment by inpacked** [comment]
![jib,rf](https://github.com/user-attachments/assets/49c28d85-48e2-45b3-ab6a-fe0f0c65cd84)

The error occurs just for no reason

"Error
A JavaScript error occurred in the main process
Uncaught Exception:
Error: WebSocket is not open: readyState 0 (CONNECTING)
at WebSocket.send
(C: Asers\Aprew\AppDatalLocal/Programs\HighStonelresources\app.asarinode_modul....13) at LogModule.ping
(C: \Users\Andrew\AppData local/Programs\Highstonelresourceslapp.asarlsrc\modules....21) at Timeout. onTimeout
(C: Users\Andrew/AppData local/Programs|HighStone resourceslapp.asar/srclmodules....22) at listOnTimeout (node:internal/timers:559:17)
at process. processTimers (node:internal/timers: 502:7)
ΟΚ"

**Comment by danielweck** [comment]
hello, your screenshot shows an error message for an application named "HighStone" ... normally this would be EDRLab.ThoriumReader

**Comment by inpacked** [comment]
Hi, how do I fix this?

**Comment by danielweck** [comment]
Where did you download this "HighStone" application? This is not Thorium.

**Comment by inpacked** [comment]
To be honest, I do not even know what kind of application it is, why it is needed and what it does.

**Comment by inpacked** [comment]
I have deleted this application, I hope the error will not appear again
