### ISSUE TITLE
"about Thorium" auto-generated EPUB fails to create on Windows

### ISSUE THREAD

**Issue by sukiletxe** [edrlab/thorium-reader#1328]
v1.6.0-alpha.1.495798844
Steps:
1. Open Thorium.
2. Press on "More information", just after version number.

Expected: The information should show.
Actual: 3 error dialogs show.

1.

Uncaught Exception:
Error: Invalid package c\Users\sukil\AppData\Local\Programs\EDRLab.ThoriumReader\resources\app.asar
    at createError (electron/js2c/asar.js:126:17)
    at Object.fs.lstat (electron/js2c/asar.js:257:23)
    at electron/js2c/asar.js:294:33
    at processTicksAndRejections (internal/process/task_queues.js:76:11)

2.

Uncaught Exception:
Error: Invalid package c\Users\sukil\AppData\Local\Programs\EDRLab.ThoriumReader\resources\app.asar
    at createError (electron/js2c/asar.js:126:17)
    at Object.fs.lstat (electron/js2c/asar.js:257:23)
    at electron/js2c/asar.js:294:33
    at processTicksAndRejections (internal/process/task_queues.js:76:11)

3.

Uncaught Exception:
Error: Invalid package c\Users\sukil\AppData\Local\Programs\EDRLab.ThoriumReader\resources\app.asar
    at createError (electron/js2c/asar.js:126:17)
    at Object.fs.lstat (electron/js2c/asar.js:257:23)
    at electron/js2c/asar.js:294:33
    at processTicksAndRejections (internal/process/task_queues.js:76:11)

**Comment by danielweck** [comment]
I am observing this error in dev mode:
<img width="590" alt="Capture" src="https://user-images.githubusercontent.com/625201/105030562-e1aa1800-5a4b-11eb-941f-154e4e4084a7.PNG">

**Comment by danielweck** [comment]
Follow-up to https://github.com/edrlab/thorium-reader/issues/1325

**Comment by danielweck** [comment]
I am not able to reproduce the error in MacOS, I suspect Linux is fine too. @panaC could you please check at your end? (make sure to delete Thorium's config folder so that the "about" EPUB is re-generated)

**Comment by danielweck** [comment]
Note the double / duplicate file path concatenation in my screenshot. This is probably just a misuse of `path.join()` or some other filesystem APi in Windows.

**Comment by danielweck** [comment]
@panaC have you been able to reproduce this bug on your Windows machine?

**Comment by panaC** [comment]
i haven't yet any windows machine. I will see next week

**Comment by danielweck** [comment]
Another report:
![image001](https://user-images.githubusercontent.com/625201/106577003-bccaa000-6535-11eb-806b-425dae92b098.png)
This is a blocker for the 1.6 release.

**Comment by danielweck** [comment]
I'm working on this. Quite a few small fixes in the call chain (file path and URL syntax issues)

**Comment by panaC** [comment]
I'm working on it since this morning :)
call me !

**Comment by danielweck** [comment]
Thanks for fixing this Pierre. Follow-up PR: https://github.com/edrlab/thorium-reader/pull/1370
