### ISSUE TITLE
PDF display automatic does not seem to work

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1334]
![Capture d’écran 2021-01-20 à 14 55 36](https://user-images.githubusercontent.com/14943186/105184520-b7ca2180-5b2f-11eb-9497-377b6aa5cc37.png)

On a large screen, with Display / Automatic I still have only one page set, where two pages are ok.

**Comment by panaC** [comment]
"Automatic" isn't automatic at all, it's hard coded seems to me

**Comment by llemeurfr** [comment]
The definition of "Automatic" (defined in the EPUB context) is that the reading app chooses 1 or 2 "pages" depending the width available on screen. The details are in the hands of the app.

**Comment by panaC** [comment]
pdfjs viewer has an automatic resize attached to the window's 'resize' event.

It's difficult to implement automatic columns based on window size because pdfjs viewer was not designed for this.

I propose to disable "automatic" mode for the pdf.

**Comment by llemeurfr** [comment]
ok for disabling the "automatic" mode and let the user choose between 1 and 2 columns.
