### ISSUE TITLE
lcpl: expired licence when end date over 2050

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#1355]
https://github.com/edrlab/thorium-reader/blob/cf04170d65959b66cef906f3cbe362d8dbbd73c0/src/main/redux/sagas/api/publication/import/importLcplFromFs.ts#L67-L69

**Comment by panaC** [comment]
```
{"provider":"https://www.edrlab.org","id":"e4be9f04-4bc4-4dea-bf8a-f1c66e4e5cf3","issued":"2021-02-01T09:21:22Z","encryption":{"profile":"http://readium.org/lcp/profile-1.0","content_key":{"algorithm":"http://www.w3.org/2001/04/xmlenc#aes256-cbc","encrypted_value":"xW8yJmX9Yh9g5Xo6LkKYMiqfUmaufPO3T625ptoAJgnvhNZYI0YgO2WD2McK0kACah9oY99wpzskF3JHGhyhzw=="},"user_key":{"algorithm":"http://www.w3.org/2001/04/xmlenc#sha256","text_hint":"Ton livre préféré","key_check":"DH9bLffRkWXNBdjRPeBv0mzOOPSoN/4YJbZ5VTAdrDYToVpzF8fDugosdHNYZstQvn9krqy1YZdQNqjbynRSlQ=="}},"links":[{"rel":"hint","href":"https://front-prod.edrlab.org"},{"rel":"status","href":"https://lsd-prod.edrlab.org/licenses/e4be9f04-4bc4-4dea-bf8a-f1c66e4e5cf3/status","type":"application/vnd.readium.license.status.v1.0+json"},{"rel":"publication","href":"https://lcp-prod.edrlab.org/contents/6fbca352-13f7-424c-b93d-0d752df738bc","type":"application/epub+zip","title":"moby-dick","length":1646451,"hash":"33a41df3ae98c40fc4cc16e96052bd41db207c45fbfe7439009795f7e3c0df7c"}],"user":{"id":"7b61b202-33b3-4129-b2b5-16eac65c70bf","email":"wMm/cSG9WxDprN3ytrHfy+PB5QlpE10xnVQ2QtAEqXQsgffg/olOGXkiZr8Gs/PN","name":"iuZVBaFJqjT4v6lMLAlUmEKG2wPOp3kurCItlyq6vtw=","encrypted":["email","name"]},"rights":{"print":2,"copy":50,"start":"2021-02-01T09:21:13Z","end":"2050-02-23T09:20:00Z"},"signature":{"certificate":"MIIDODCCAiCgAwIBAgIJAO5wGoN7S9PxMA0GCSqGSIb3DQEBCwUAMEIxEzARBgNVBAoTCmVkcmxhYi5vcmcxFzAVBgNVBAsTDmVkcmxhYi5vcmcgTENQMRIwEAYDVQQDEwlFRFJMYWIgQ0EwHhcNMTkwMzI2MTc0NTE1WhcNMjEwMzI1MjM1OTU5WjBcMRMwEQYDVQQKEwplZHJsYWIub3JnMSYwJAYDVQQLEx1SZWFkaXVtIExDUCBMaWNlbnNlIFByb3ZpZGVyczEdMBsGA1UEAxMURURSTGFiIFRlc3QgUHJvdmlkZXIwgZswEAYHKoZIzj0CAQYFK4EEACMDgYYABAHBjgjfztMPkm8Qjq74rkZ48ZPG3uj5+anHtlWHK6IuJtiNbsPMEmXOoaSdqNaoMvK9IrMYptv+RI52wXi8eikuHwFWmKy2BX9JC6mGVG10cizsU/j4pYoDAte76I3NZ8Dkdm9kMo0JpQ6/Fbw69DDRxDnZetExUMPCWCZlo+k2ANXDN6OBnjCBmzAfBgNVHSMEGDAWgBTcXPyT5B+f7rC66lILK8pSXODJhzAdBgNVHQ4EFgQUClSIBtrmOCvKHacKnNKCBFyhLKIwDgYDVR0PAQH/BAQDAgeAMAkGA1UdEwQCMAAwPgYDVR0fBDcwNTAzoDGgL4YtaHR0cDovL2NybC5lZHJsYWIudGVsZXNlYy5kZS9ybC9FRFJMYWJfQ0EuY3JsMA0GCSqGSIb3DQEBCwUAA4IBAQAzVI5SMRg9qHwo2ZPvhi780lEOJ3vebNzCmuSQYDtOI2/gpLkXvsK3On+G7SweTCI9jOzCB0AsCTvbImsk2jG3fkpXwe7jstlAopqjuzwDW4pFdL3Go8pvDM4tAMqKzW8zSjNJPhBAolB60/WQUxM4JkK5caHUJfEbspAl0GHsueFxgDJuJz4tVhPSi79JQQguz9CamBHicMpC+/wTBEzluEtO0HQj/J3YcBlM+PdHJqCHgKdp6N/kKxkdTVKTLsjGH7sqKzUt3MqMnfi5n7BWhfUYWdu4sluZ52l14f43gogbEkITLLynSOMfLkW2Won3+3TSHODkGSpicXS3+Beg","value":"ATWlo1qHEKZDpVpddu5Ah9Gao5aQ6f+Z//wwiRf3pFT5o8dDibv/daclvBJW3SWNzWkEm6dENU16rmMUulQkiCBlAQ5EiqTlpknZvQL/7BvWlKOrtQsDdvJnEvJ3REBS2Amo3XRFn+AeC/OB8nsIT43koR941NfiY4M913udk1sDvk50","algorithm":"http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256"}}
```

**Comment by panaC** [comment]
`moment("2050-02-23T09:20:00Z").unix() == 1612171273` 
should be `new Date("2050-02-23T09:20:00Z").getTime() / 1000 == 2529220800`

**Comment by panaC** [comment]
why unlockPublication return 11 ?

https://github.com/edrlab/thorium-reader/blob/cf04170d65959b66cef906f3cbe362d8dbbd73c0/src/main/services/lcp.ts#L624-L736

**Comment by danielweck** [comment]
After spending some time diffing files manually, I found the exact `date.h` used in LCP lib:
https://github.com/HowardHinnant/date/blob/3c3ba6890648b7c4adcfdf082a4c3803d22f5a21/include/date/date.h

Code diff with their `master` branch:
https://github.com/HowardHinnant/date/compare/3c3ba6890648b7c4adcfdf082a4c3803d22f5a21...master#diff-0b69f38c40f39535998f884bf75dab9500e3d9a7cfa977d60111fac7f4005d52

I found these references to `2038`:
https://github.com/HowardHinnant/date/pull/153#issuecomment-304702008
https://github.com/HowardHinnant/date/issues/397#issuecomment-426024220

That being said, `Botan::X509_Time` could be the culprit:
https://github.com/randombit/botan/blob/2.3.0/src/lib/asn1/asn1_time.h#L19

See:

https://github.com/randombit/botan/blob/4ed2f03e18b472fa7388f975a2b4976a56cdeacc/src/lib/utils/calendar.cpp#L65-L67

https://github.com/randombit/botan/blob/4ed2f03e18b472fa7388f975a2b4976a56cdeacc/src/tests/data/dates.vec#L13-L16

**Comment by danielweck** [comment]
`Botan::X509_Time.to_string()` produces `YYYYMMDDHHmmssZ` instead of `YYMMDDHHmmssZ` for 2050 year date, thus the broken alphanumerical comparison.

Example:
* `210201140725Z` NOW
* `210201092113Z` LICENSE START (`2021-02-01T09:21:13Z`)
* `20500223092000Z` LICENSE END (`2050-02-23T09:20:00Z`)

=>“nowDate > endDate”

**Comment by danielweck** [comment]
Better compare: https://github.com/randombit/botan/blob/2.3.0/src/lib/asn1/asn1_time.h#L38

**Comment by danielweck** [comment]
Special `2050`+ case:

https://github.com/randombit/botan/blob/9474deacd67433908dec38a409892a334aab679d/src/lib/asn1/asn1_time.cpp#L67-L74




`m_tag = (m_year >= 2050) ? GENERALIZED_TIME : UTC_TIME;`

https://github.com/randombit/botan/blob/9474deacd67433908dec38a409892a334aab679d/src/lib/asn1/asn1_time.cpp#L31

**Comment by danielweck** [comment]
Note that Botan versions > `2.3.0` evolved with different code organisation (`master` branch links):

https://github.com/randombit/botan/blob/master/src/lib/asn1/asn1_time.cpp

https://github.com/randombit/botan/blob/4ed2f03e18b472fa7388f975a2b4976a56cdeacc/src/lib/asn1/asn1_obj.h#L316-L389

**Comment by danielweck** [comment]
We have to make sure string comparisons are replaced for `X509_Certificate.start/end_time()` as well:
https://github.com/randombit/botan/blob/2.3.0/src/lib/x509/x509cert.h#L119-L129

**Comment by danielweck** [comment]
I have fixed the bug in the LCP lib. Thorium 1.6 will immediately integrate the updated lib for Electron v11. Other existing deployments will have to be updated separately (e.g. other Thorium forks, possibly with different Electron versions, but also iOS and Android mobile apps, and fringe integrations with special builds for Unix, Mac and Windows)
