### ISSUE TITLE
OPDS text/html description shows raw markup instead of rendered HTML

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1376]
![unnamed](https://user-images.githubusercontent.com/625201/108027750-953e0200-7022-11eb-8932-dc258635d3cf.jpg)

**Comment by llemeurfr** [comment]
The chosen solution is to sanitize the html. The resulting HTML can therefore be written into a DOM element.

**Comment by danielweck** [comment]
Thanks for the RFC Laurent.  The problem is that the RWPM JSON model is less feature-complete than OPDS1/Atom, specifically we are loosing content-type, and XML/XHTML namespaces (i.e. we store a simple string of characters).

**Comment by llemeurfr** [comment]
> specifically we are loosing content-type, and XML/XHTML namespaces (i.e. we store a simple string of characters).

I believe we don't need to keep the XHTML namespace here and can consider that any tagging is html based. The only thing to keep in mind is that if Atom content is xhtml, it is not escaped in the content field.

**Comment by danielweck** [comment]
Fixed via https://github.com/readium/r2-opds-js/commit/e0e87058307157a0c6f13255a3f1e4d2aa2e7a70

<img width="1187" alt="Screenshot 2021-05-12 at 19 42 54" src="https://user-images.githubusercontent.com/625201/118027864-53d79d00-b35a-11eb-9c76-3b35a9307456.png">

**Comment by danielweck** [comment]
<img width="1174" alt="Screenshot 2021-05-12 at 19 46 56" src="https://user-images.githubusercontent.com/625201/118028303-d5c7c600-b35a-11eb-9d57-5581e0a12ee6.png">
