### ISSUE TITLE
Cannot add PDF files that are named in non-ASCII characters. 

### ISSUE THREAD

**Issue by peaceroad** [edrlab/thorium-reader#1381]
In Thorium reader 1.6, PDF files named with non-ASCII characters cannot be added.

```
PDF.js v2.8.18 (build: 1d017b3b4)
Message: Unexpected server response (0) while retrieving PDF "pdfjs-extract://C:\Users\k_taka\Downloads\%E3%81%93%E3%81%AE%E4%B8%96%E7%95%8C%E3%81%AE%E8%AC%8E.pdf".
```

**Comment by danielweck** [comment]
Well-spotted, thank you!

**Comment by danielweck** [comment]
I can reproduce on MacOS:

`node -e "console.log(decodeURIComponent('%E3%81%93%E3%81%AE%E4%B8%96%E7%95%8C%E3%81%AE%E8%AC%8E'));"`
=>
`この世界の謎`

```
PDF.js v2.8.18 (build: 1d017b3b4)
Message: Unexpected server response (0) while retrieving PDF "pdfjs-extract:///Users/danielweck/Downloads/500GB/EPUBs/PDF/%E3%81%93%E3%81%AE%E4%B8%96%E7%95%8C%E3%81%AE%E8%AC%8E 480496.pdf".
```

**Comment by danielweck** [comment]
Related PR: https://github.com/edrlab/thorium-reader/pull/1385/

**Comment by danielweck** [comment]
Hello, I implemented a fix which reliably works on MacOS. Could you please test on your Windows Japanese computer, using the latest "alpha" build:
https://github.com/edrlab/thorium-reader/releases
Thank you!

Developer note:
The problem originated from Electron `registerFileProtocol()` which was only partially decoding the URL, so I used a double-encoding technique to recover the original unicode file path reliably.
I tested with filenames that combine Unicode characters, whitespace characters, percent characters used in strings that look like URL escape sequences but that should absolutely not be decoded, as they make the verbatim file path (notably, slash which is of course a file path segment separator), or just as simple non-escaping percent characters which typically cause `decodeURIComponent()` to crash.

**Comment by peaceroad** [comment]
Sorry! I forgot to reply. 
In version 1.7, I was able to add a PDF with Japanese file name on my computer (Windows).
I think PDFs are still necessary, especially for books with complex layouts. Also, there is still a need for PDFs that have the same page numbers and layout in all environments (if the paper book was created first.)
Thanks for this fix.
