### ISSUE TITLE
Typo in passphrase dialog box

### ISSUE THREAD

**Issue by k-davey** [edrlab/thorium-reader#1386]
Thorium 1.6 - the prompt for passphrase dialog box currently says: "Forgot you're passphrase?" 
Should say: "Forgot your passphrase?"

(Also, the encoding used for the hint displayed in this dialog box isn't URL-friendly... "/" becomes "&#x2F;")

![thorium 1 6 preview_passphrase_dialog](https://user-images.githubusercontent.com/79282777/108418448-e9014480-71f6-11eb-816e-cdf8d8336c6b.png)

**Comment by danielweck** [comment]
Hello, the typo comes from the LCP license, not Thorium.

**Comment by danielweck** [comment]
Hello again, regarding how the textual hint encodes the URL: I'm not sure, could you please share the license (no need for the passphrase, just the small JSON license file with .lcpl extension)

**Comment by danielweck** [comment]
Oh my apologies, I spoke too quick. You are absolutely right, here is the typo: 
https://github.com/edrlab/thorium-reader/blob/c1ac3db7b23b04cbf2769e7940d043417fa4e1bf/src/resources/locales/en.json#L144

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/commit/163d989a40c6f3d58fef374f04c93d95e184858b
