### ISSUE TITLE
CSS styling of heading tags not respected

### ISSUE THREAD

**Issue by ThomasR128** [edrlab/thorium-reader#1387]
Couldn't find anything in the issues list, so here goes:

Thorium 1.5 on Mac OS X 10.11.6

CSS styling of heading tags <h#> is not respected. Tried this with several conforming ePubs that have passed epubcheck 4.2.4 with no issues.

Example: [John Muir, My First Summer in the Sierra](https://standardebooks.org/ebooks/john-muir/my-first-summer-in-the-sierra), compatible ePub

Relevant XTHML snippet from chapter-1.xhtml:

`			<h2 epub:type="title">
				<span epub:type="z3998:roman">I</span>
				<span class="epub-type-subtitle" role="doc-subtitle" epub:type="subtitle">Through the Foothills with a Flock of Sheep</span>
			</h2>
`

Relevant CSS snippet from core.css:

`h1,
h2,
h3,
h4,
h5,
h6{
	font-variant: small-caps;
	hyphens: none;
	adobe-text-layout: optimizeSpeed; /* For Nook */
	adobe-hyphenate: none;
	-webkit-hyphens: none;
	-epub-hyphens: none;
	-moz-hyphens: none;
	-epub-hyphens: none;
	page-break-after: avoid;	
	-webkit-column-break-after: avoid;	 /* For Readium */
	break-after: avoid;
	page-break-inside: avoid;	
	-webkit-column-break-inside: avoid;	 /* For Readium */
	break-inside: avoid;
	text-align: center;
	margin-top: 3em;
	margin-right: 0;
	margin-bottom: 3em;
	margin-left: 0;
}`

Expected result (screen shot from iBooks. Apple Books on iOS shows same rendering): `font-variant: small-caps;`

![Captura de pantalla 2021-02-20 a las 14 20 55](https://user-images.githubusercontent.com/64253366/108596754-5512b280-7387-11eb-8db2-1d14a9dc5e75.png)

Thorium displays normal font variant:

![Captura de pantalla 2021-02-20 a las 14 22 04](https://user-images.githubusercontent.com/64253366/108596761-622fa180-7387-11eb-8436-f2e81ec88cfe.png)

**Comment by danielweck** [comment]
Indeed, the screenshot below is with the "Georgia" typeface in both Thorium and Books.app on MacOS:

<img width="1680" alt="Screenshot 2021-02-22 at 15 37 05" src="https://user-images.githubusercontent.com/625201/108730919-ec147180-7523-11eb-9eac-295dd15d5ccb.png">

**Comment by danielweck** [comment]
And here's the culprit: `font-variant: none;` in ReadiumCSS due to `letter-spacing`.

https://github.com/readium/readium-css/blob/583011453612e6f695056ab6c086a2c4f4cac9c0/css/src/modules/user-settings-submodules/ReadiumCSS-letterSpacing_pref.css#L19

<img width="986" alt="Screenshot 2021-02-22 at 15 40 31" src="https://user-images.githubusercontent.com/625201/108731381-6d6c0400-7524-11eb-8105-a340b607b7f4.png">

**Comment by danielweck** [comment]
I am moving this issue to ReadiumCSS (I cannot do this using GitHub's "transfer" feature, so I will do it manually)

**Comment by danielweck** [comment]
See: https://github.com/readium/readium-css/issues/102

**Comment by ThomasR128** [comment]
Great, thanks. Robbing Peter to pay Paul, sort of… :)
