### ISSUE TITLE
Navigation blocked on Test Suite 130

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#139]
The [EPUB Test Suite 130](http://epubtest.org/epubs/epub30-test-0130-20160116.epub) is intended to test support for RTL languages, especially Japanese (but also Hebrew and Arabic).  
On the alpha1 version, one cannot go further than pagination-rtl-30 IF the window size does not allow for the full page to appear (in my cas, the default size of the window is so that the last image does not appear immediately). In this case, the left key and click don't react anymore. If the size of the window is larger, I can go on page pagination-rtl-40 but no further.

**Comment by danielweck** [comment]
Note that these Right To Left tests seem to pass fine when ReadiumCSS column-based pagination is deactivated (the viewport lays out reflowable content using a traditional "web browser" scrollbar, either horizontal or vertical depending on the writing mode).
This is not necessarily a bug in ReadiumCSS (probably not, in fact), but an integration issue with `r2-navigator-js`, which has not been updated yet to support the new Vertical Writing Mode and RTL styles provided by ReadiumCSS.

**Comment by JayPanoz** [comment]
See also https://github.com/readium/r2-testapp-swift/issues/6 and https://github.com/readium/readium-css/wiki/Internationalization,-pagination-and-user-settings#triggering-the-correct-page-progression-direction

Quite a lot to do in the navigator, especially for `vertical-rl` so please feel free to come back to me if you have any question/doubt.

**Comment by danielweck** [comment]
bug triage: obsolete.
