### ISSUE TITLE
[DEV] string | undefined

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#1396]
https://github.com/edrlab/thorium-reader/blob/15b628a49a941901109cf2c5151828d0dca3b0d1/src/main/converter/opds.ts#L137

**Comment by danielweck** [comment]
The `indirectAcquisitionType` property is already optional:

https://github.com/edrlab/thorium-reader/blob/15b628a49a941901109cf2c5151828d0dca3b0d1/src/common/views/opds.ts#L92

So is this really a bug?
(sorry if I misunderstood your issue description)

**Comment by danielweck** [comment]
By the way, `indirectAcquisitionType?: string | undefined;` is redundant, it should be `indirectAcquisitionType?: string` (especially with `strictNullChecks`)

**Comment by panaC** [comment]
I'm closing this issue
