### ISSUE TITLE
[DEV] should return undefined type

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#1397]
https://github.com/edrlab/thorium-reader/blob/15b628a49a941901109cf2c5151828d0dca3b0d1/src/main/converter/opds.ts#L84

**Comment by danielweck** [comment]
Yep:
https://github.com/edrlab/thorium-reader/blob/15b628a49a941901109cf2c5151828d0dca3b0d1/src/main/converter/opds.ts#L155
