### ISSUE TITLE
[DEV] IOpdsAuthView methods could be undefined

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#1399]
https://github.com/edrlab/thorium-reader/blob/15b628a49a941901109cf2c5151828d0dca3b0d1/src/main/converter/opds.ts#L417-L425

**Comment by danielweck** [comment]
1) In your issue title: "methods" or "properties"?
2) Can you please explain what the bug is, so that this issue is actionable. Do you mean "TODO: must add safeguards / sanity checks when potentially-undefined properties of the `IOpdsAuthView` interface are used"? Or something else?

**Comment by panaC** [comment]
I'm closing this issue. not actionable
