### ISSUE TITLE
OPDS authentification dialog: when cancelled, go back to feed root (not 401 page)

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1405]
When the login form appears, if I select cancel, I'm looping in a 401 error which redirects me to the form.

**Comment by panaC** [comment]
is it the same behaviour when you press the escape key ?

**Comment by llemeurfr** [comment]
when pressing the escape key I'm back to the 401 page, and do not "loop" to the login popup. 

Which is still no perfect from a UX perspective, as I would expect being sent back to the catalog (I must select the back arrow to get there).

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/pull/1252/commits/1db8c41bfaad5cb505713b8366ddaaab59081098

**Comment by panaC** [comment]
@danielweck how to wire the cancel button ? with the type name ?

**Comment by danielweck** [comment]
I have fixed this. Commit coming soon...

**Comment by llemeurfr** [comment]
I don't see any button appearing in the pop-up. Escape works.

**Comment by panaC** [comment]
there are 2 buttons cancel and login

https://github.com/edrlab/thorium-reader/blob/c5d1060f3a96f0a470dfafdc34537fa922499c44/src/main/redux/sagas/auth.ts#L847-L848

**Comment by danielweck** [comment]
I am not able to reproduce the problem. Laurent, can you see the cancel button in your tests?

<img width="1060" alt="Screenshot 2021-03-16 at 14 48 01" src="https://user-images.githubusercontent.com/625201/111329064-ba944f00-8666-11eb-9095-3562716453e4.png">

**Comment by panaC** [comment]
the cancel doesn't work. I agree with you @llemeurfr  :)

**Comment by llemeurfr** [comment]
Details: when I hit cancel, the modal is closed, I'm back to the "unauthorized 401" screen and the modal opens again ... infinite loop if the user doesn't move elsewhere. 
I think what needs to be done is that if the user selects cancel (or espace), he is redirected to the OPDS catalog.

**Comment by panaC** [comment]
not as easy to implement, I'm looking for a workaround

**Comment by danielweck** [comment]
> not as easy to implement, I'm looking for a workaround

router history?
