### ISSUE TITLE
EPUB 3 FXL, fit to width

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1406]
EPUB 3 fixed layout pages are presented is **fit to page** mode. When the writing is small compared to the screen size, reading can become cumbersome. This is especially true with comics. 

It would be good to add for EPUB 3 FXL a feature we developed for PDF, i.e. an affordance which allows selecting fit to page vs fit to width. Because computer screens are in landscape mode and individual pages are in portrait mode, these two modes seem sufficient for making readers happy.  

In fit to width mode, the user would just scroll vertically to move through the page(s), just like in the PDF case.

**Comment by danielweck** [comment]
Duplicate of https://github.com/edrlab/thorium-reader/issues/1228
?

**Comment by danielweck** [comment]
Related issue: https://github.com/edrlab/thorium-reader/issues/578

**Comment by llemeurfr** [comment]
Yes, duplicate of #1228, let's merge both.
