### ISSUE TITLE
OPDS auth window title is not human-readable / human-friendly

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1409]
OPDS1 https://api.deslibris.ca/api/feed

<img width="1679" alt="Screenshot 2021-03-02 at 18 39 07" src="https://user-images.githubusercontent.com/625201/109697919-b6583400-7b86-11eb-9469-709b66bfe075.png">

OPDS1 http://www.feedbooks.com/catalog.atom

<img width="1679" alt="Screenshot 2021-03-02 at 18 27 03" src="https://user-images.githubusercontent.com/625201/109697926-ba845180-7b86-11eb-8cca-e9d891a54563.png">

**Comment by panaC** [comment]
auth title come from the opds feed 

https://github.com/edrlab/thorium-reader/blob/8536a0a2feeb98f410ac3c4f98febb2c6b15575b/src/main/redux/sagas/auth.ts#L403

**Comment by panaC** [comment]
what is the actionable item in this PR ?

**Comment by danielweck** [comment]
In the screenshots, the titles are "api.deslibris.ca," and "Document Realm," (note the comma suffix, and the not-humand-friendly strings). What can we do to improve this? (e.g. remove the useless titles, replace them with something else?)

**Comment by danielweck** [comment]
* OPDS1 https://api.deslibris.ca/api/feed

`curl -v https://api.deslibris.ca/api/feed/shelf`
=>
HTTP header `www-authenticate` : `Basic realm="api.deslibris.ca"`

* OPDS1 http://www.feedbooks.com/catalog.atom

`curl -v https://www.feedbooks.com/user/bookshelf.atom`
=>
HTTP header `www-authenticate` : `Basic realm="Document Realm"`

**Comment by danielweck** [comment]
https://github.com/edrlab/thorium-reader/blob/27f1588b342e26520dd174986783719899a50f34/src/main/services/opds.ts#L188

https://github.com/edrlab/thorium-reader/blob/27f1588b342e26520dd174986783719899a50f34/src/main/redux/sagas/auth.ts#L398-L404

https://github.com/edrlab/thorium-reader/blob/27f1588b342e26520dd174986783719899a50f34/src/main/redux/sagas/auth.ts#L649

**Comment by danielweck** [comment]
Fixed implementation screenshots (the term "Login" in the title/heading is translated, not hard-coded):

<img width="1141" alt="Screenshot 2021-06-16 at 07 57 50" src="https://user-images.githubusercontent.com/625201/122172378-98ce8200-ce78-11eb-8eda-019a4b166637.png">
<img width="1141" alt="Screenshot 2021-06-16 at 07 57 34" src="https://user-images.githubusercontent.com/625201/122172412-9c620900-ce78-11eb-86c5-12d9e8b6d733.png">

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/commit/8adaaf6809cb4590b9202f5e6fa661475be4491d
