### ISSUE TITLE
OPDS auth window fails for Feedbooks OPDS2 feed (seems okay for OPDS1) | Feedbooks HTTP 400

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1410]
OPDS1 http://www.feedbooks.com/catalog.atom

<img width="1679" alt="Screenshot 2021-03-02 at 18 26 56" src="https://user-images.githubusercontent.com/625201/109698264-25358d00-7b87-11eb-8d0a-e03bd039a5cc.png">

<img width="1679" alt="Screenshot 2021-03-02 at 18 27 03" src="https://user-images.githubusercontent.com/625201/109698280-29fa4100-7b87-11eb-8ae1-600770c806c0.png">

OPDS2 https://catalog.feedbooks.com/catalog/index.json

<img width="1679" alt="Screenshot 2021-03-02 at 18 26 34" src="https://user-images.githubusercontent.com/625201/109698305-3088b880-7b87-11eb-9fe5-83dfce25ad1f.png">

<img width="1679" alt="Screenshot 2021-03-02 at 18 26 22" src="https://user-images.githubusercontent.com/625201/109698340-37afc680-7b87-11eb-8619-ade4115c1546.png">

**Comment by danielweck** [comment]
@HadrienGardeur would it be possible for the Thorium development team to get a test account at Feedbooks in order to verify our auth implementation with OPDS1 and OPDS2 feeds? (sorry if you are the wrong person to ask)
Thank you!

**Comment by danielweck** [comment]
I am able to reproduce this "bug" with Thorium 1.7

**Comment by panaC** [comment]
https://catalog.feedbooks.com/user/authentication

https://catalog.feedbooks.com/user/login_oauth -> http Error 400

**Comment by danielweck** [comment]
Just to be sure, it would be good to try Feedbooks authenticated access (OPDS1, not OPDS2 which seems to fail that the `oauth` URL) by creating an account:
https://authorize.feedbooks.com/user/register

**Comment by danielweck** [comment]
This is working fine now, I have just tested it. Perhaps some improvements / fixes in the Feedbooks backend?
