### ISSUE TITLE
Adding a bookmark on a PDF changes color to both bookmark and Page fit or width buttons

### ISSUE THREAD

**Issue by jacoporinaldi** [edrlab/thorium-reader#1422]
As from the title, when adding a bookmark in a PDF both buttons appear to be clicked. 
In the screenshot i provided i simply added a bookmark in a random position. Clicking on the "page fit or width" button seems to not change its colour.
![Screenshot (22)](https://user-images.githubusercontent.com/72013644/110966605-b827b180-8355-11eb-8b40-86a6a910eb07.png)

**Comment by panaC** [comment]
thanks to report this 

error: 
https://github.com/edrlab/thorium-reader/blob/746b2416658f759083130fa1f82975f2bc368887/src/renderer/reader/components/ReaderHeader.tsx#L395
