### ISSUE TITLE
Layout behaviour doesn't work properly for pdf

### ISSUE THREAD

**Issue by jacoporinaldi** [edrlab/thorium-reader#1423]
Once the Layout is switched on "scrollable" inside a pdf it can't be switched again. Trying to switch to "paginated" isn't working properly. 

How to reproduce it:
- Open a PDF
- Change layour to scrollable
- Try to change it again to paginated. It will be stuck in scrollable mode

**Comment by llemeurfr** [comment]
i was able to reproduce it, thanks for this bug report, this seems to be a regression as we tested it during the development.

**Comment by panaC** [comment]
the pdf reader that we use (aka pdf.js) doesn't have a paginated mode. So, it is a fake paginated mode. You can switch to the epub reader to have a real paginated mode.

**Comment by llemeurfr** [comment]
The "paginated" mode is indeed a hack, as PDF.js does not support it natively. We're thinking about removing it as it does not bring added comfort to users (the "scrollable" view is also usable with the keyboard -> some sort of "paginated" view).

**Comment by danielweck** [comment]
In my opinion: we should remove the "layout" section ("scroll" and "paginated" radio icons buttons).
The "columns" section is very useful (1 or 2). The "fit-width" / "fit-height" icon button in the toolbar is super useful too.

**Comment by jacoporinaldi** [comment]
Actually i just checked again and the zoom is not working if the "paginated" mode is active, hence neither "fit-width" nor "fit-height" is behaving properly. If you are planning to remove the "paginated" mode i guess it won't be an issue anymore but if you will keep it a good idea might be to disable the zoom feature when an user is in said mode.

**Comment by danielweck** [comment]
Decision based on UX tests: keep only scrollable mode, remove the layout section as the paginated mode does nothing positive (only disables zoom)
