### ISSUE TITLE
Add faster playback speeds for audio

### ISSUE THREAD

**Issue by martinpub** [edrlab/thorium-reader#1427]
Hi,

At the Swedish Agency for Accessible Media, we are following the development of Thorium closely, and are also looking at using it internally.

We received feedback from our talking book producers that they would like faster playback speeds than 2x, as much as up to 3x. We think this might be something that end-users can benefit from as well, as many experienced talking book/audiobook readers like to be able to speed the playback up quite a bit.

Hope this makes a proper feature request, please consider it for future development.

Thanks!

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/commit/08fba0c6f1a6c50cdb15dc9e321392791b10325b

**Comment by martinpub** [comment]
Thanks a lot @danielweck!

**Comment by danielweck** [comment]
You are welcome. I tested this with a few TTS voices (as expected, not all synthetic voices sound good when played at higher speech rates). The scale is also used for pre-recorded audio (i.e. EPUB3 Media Overlays, DAISY3 Digital Talking Books books)

**Comment by martinpub** [comment]
Excellent! I think this will be much appreciated (main use case for us is prerecorded audio) in MTM production testing.
