### ISSUE TITLE
Thorium auto-generated EPUB "about / info", make sure diff XHTML to re-generate if necessary (CRC?)

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1447]

**Comment by panaC** [comment]
upgrade the ABOUT_BOOK_TITLE_PREFIX on each about change

https://github.com/edrlab/thorium-reader/blob/a47e73f4f339e7436bcf08a84ea6f704b17508d3/src/common/constant.ts#L8/

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/pull/1458
