### ISSUE TITLE
Feature request : Keep TOC panel opened

### ISSUE THREAD

**Issue by s-kocher** [edrlab/thorium-reader#1449]
It will be nice to be able to pin the TOC panel so TOC panel stays opened when clicking on a TOC entry.

Moreover, using a different style on the current TOC entry where the content is currently will be nice too (example : use bold for actual entry vs other entries in non bold).

It is useful when exploring a book to be able to jump fast from different TOC entries.

**Comment by llemeurfr** [comment]
Currently, when the user select a display setting (e.g. Theme), the panel is not closed immediately.  
We could either add a pin button to the ToC panel as proposed, or do for the ToC as for other panels, i.e. not closing it immediately and let the user click elsewhere to close it. But in the can we may have an accessibility issue (an extra action for blind people). 

As we'll review the UX/UI in the coming months with an app designer, we'll think about that in the scope of this global review. 

Thanks for the idea!

**Comment by danielweck** [comment]
Proposal: single vs. double click, and key modifier on enter key (shift control). Will implement for v1.7+

**Comment by llemeurfr** [comment]
I'm not a fan of double click on what is in fact a link. I'd personally prefer to keep the default behavior as-is (one click on a ToC entry or return key means move to the entry and close the panel), and add a modifier for sighted users via the cmd/ctrl + click). 
I don't forsee blind users willing to stay in the ToC panel afeter they have selected an entry, because the screen reader cannot do much if the panel is not closed.

**Comment by panaC** [comment]
behaviour:
- click on a toc element -> the menu remains open
- keypress (enter) -> the menu closes

**Comment by danielweck** [comment]
@llemeurfr I see that you "thumbed-up" @panaC 's above comment in the discussion thread, but this contradicts your own suggestion in the previous comment. Furthermore, this is a UX breaking change, I think it will confuse users.

**Comment by danielweck** [comment]
Note that the breaking UX change in the merged PR now makes the bookmarks navigation inconsistent with TOC, landmarks, and search.

**Comment by panaC** [comment]
I used the same logic as search menu. We can apply it on landmarks and bookmarks too

**Comment by danielweck** [comment]
I disagree. The merged PR implementation is a breaking UX change which will confuse users (they will think it is a bug, not a feature), and anyway it contradicts Laurent's own suggested UI design. The proposal was to align the search interface with the other navigation sections (TOC, landmarks, bookmarks). Keeping the nav panel open should not be the default, it should be the optional / alternative mode (with key modifier, or double click)

**Comment by panaC** [comment]
feel free to revert my commit and implement your solution. I thought this is the best fixes.

**Comment by danielweck** [comment]
This is not "my solution", it is Laurent's own proposal :)

**Comment by llemeurfr** [comment]
Effectively it was not my proposal; the solution Pierre tried is trying to align the panel behaviour in different contexts: display modifications; search; and now ToC, bookmarks, landmarks. Aligning behaviours is good UX design, this is why I put my thumb up -> accepting the move. 

So let's discuss what can confuse users and what an be the best solution then. 
Alignment 1: in each case, a click on the panel closes the panel immediately. In this case the behaviour of display modifications is changing (and will confuse users); same for the search panel.
Alignment 2: in each case, a click on the panel does not close the panel immediately.  In this case the behaviour of Toc, bookmarks and landmarks is changing (and will confuse users). 

What is best then?

**Comment by danielweck** [comment]
> In this case the behaviour of display modifications is changing (and will confuse users)

Sorry, I do not understand this statement. The only clickable navigation lists / hyperlinks are: ToC, landmarks, bookmarks, and search (and only “search” implements a different interaction pattern, which we need to fix in order to harmonise the UX with the pre-existing navigation lists). Am I missing something?

**Comment by llemeurfr** [comment]
> Am I missing something?

All modifications of theme, font & size, layout, alignment ...

**Comment by danielweck** [comment]
But these are not hyperlinks, they don’t obey a navigation logic. Display settings are a completely separate concern. I wasn’t even aware that this was under consideration, did we receive user feedback that suggested the current UX should be changed?

**Comment by llemeurfr** [comment]
No, we didn't. But we don't only react to customer feedback, we also try to streamline the UX. You're right that the display panel does not contain hyperlinks, still it is a panel like the navigation one.

**Comment by llemeurfr** [comment]
So, the question is: are these to types of panel (navigation and display) different enough to make logical a UX difference? I'm open on this one.

**Comment by danielweck** [comment]
> still it is a panel like the navigation one

I disagree, the slide-out right-hand-side modal overlay panels contain a variety of user controls organised per distinct logical groups. The "display settings" panel contains user controls such as radio boxes, checkboxes, sliders, pull down lists / options selectors, which are UI affordances that convey totally different expectations to the "navigation" panel (which encapsulates TOC, Bookmarks, Landmarks, Search results, Goto page). The latter is very disctinctly about navigation (i.e. going from one place to another), the former is about exposing user-configurable options (in this context, it makes no sense to immediately close the panel upon selection).

Laurent, could you please explain exactly what you have in mind, and either Pierre or I will implement the desired UX. At any rate, the merge PR introduces a breaking change that is contrary to your original design brief.

**Comment by llemeurfr** [comment]
I understand the division you're making between the behaviours of the "display" vs "navigation" panel. 

After some thinking, let's keep my initial preference for the navigation panel (ToC, bookmarks, landmarks): a simple click or return key closes the panel, a cmd/ctrl click leaves it open. 

The last piece of discussion we must have then is: do we align the search panel with this behaviour?

**Comment by danielweck** [comment]
The "search results" fall into the same category as other "hyperlinks" navigation lists. It was my fault for implementing the search results section differently than the other existing UI controls. We need to fix this. It will be a small breaking change given that not many users rely on the search tool (recent feature, slightly incomplete).

**Comment by panaC** [comment]
I like this solution. But anyway. I let you both discuss.

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/pull/1512

**Comment by danielweck** [comment]
@s-kocher the UX implementation compromise is that both mouse click and keyboard enter on hyperlinks (TOC, landmarks, search results) and buttons (bookmarks, goto page) close the navigation panel (i.e. this is the default behaviour), but when the shift+alt key modifiers are active, the navigation panel remains open. Detection is double-click currently fails (likely due to single click event taking precedence) so for now only the shift+alt keyboard modifiers work. Note that the control keyboard modifier cannot reliably be used in Windows, Mac and Linux due to being reserved for context menu popup (i.e. alternative to right click event of pointing device / mouse). I hope this helps. Please feel free to comment further here about this feature. Thank you!

**Comment by s-kocher** [comment]
@danielweck I tested, it works as described but : 
- 2 keys shortcut is not very user friendly when browsing a document through the TOC (having pressing 2 keys for a certains amount of time during document exploration)
- this shortcut <kbd>shift</kbd> + <kbd>alt</kbd> is a very bad choice for Windows users since it can switch the keyboard layout among the different languages declared in language bar : https://support.microsoft.com/en-us/topic/switch-between-languages-using-the-language-bar-1c2242c0-fe15-4bc3-99bc-535de6f4f258), so for example, on a Windows set to french, switching between french with azerty keyboard layout and english with qwerty keyboard layout, many users may not be aware of that and suddenly their keyboard will send the wrong key (Q instead of A, W instead of Z etc), even if user is aware about that, not perfect to check we currently are on the wrong language / keyboard layout because of our actions in Thorium.

Ideally : keep TOC open, not grey the content area, toc not overlapsing the content area, in fact, like when TOC panel is displayed in Adobe Reader is probably the ideal UI to have without having to use some shortcut and opened panel that overlapse document and make the background grey.
But I understand this ideal solution is not easy in Thorium because of some UI choices, accessibility topics etc.
