### ISSUE TITLE
trycatch helper improvement (return caught error / rejection)

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1461]
https://github.com/edrlab/thorium-reader/blob/edff799091a4b0081c232df377c6d27717f828ba/src/utils/tryCatch.ts#L1-L48

proposal:

```js
async function tryCatch<T>( promise: Promise<T> ): Promise<{ err: Error } | { res: T }> {
  try {
    return { res: await promise };
  } catch (err) {
    return { err };
  }
}
```

**Comment by panaC** [comment]
It is really useful ? this is a simple helper for my personal usage. Feel free to rename their functions and create a new one if you want. Doesn't matter

IMHO

**Comment by danielweck** [comment]
Closing. Error reporting is a general concern, not a specific problem to address in these utility functions.
