### ISSUE TITLE
Does not respond to Page Down key.

### ISSUE THREAD

**Issue by MarjaE2** [edrlab/thorium-reader#1465]
Tried Thorium 1.6.0 for the Mac. Thorium should probably respond to page up/down as well as the left and right arrows.

**Comment by danielweck** [comment]
The CTRL + page up/down keyboard shortcut is currently allocated to previous/next "chapter" navigation (well, "spine item" in EPUB parlance, to be precise ... or more generically: document in the linear reading order).
See wiki page: https://github.com/edrlab/thorium-reader/wiki/Keyboard-shortcuts

I think that raw page up/down without key modifier would conflict with the keyboard shortcut reserved for the native scrollview, I'm not 100% sure (depends on MacOS, Windows, Linux variants).

We would be very happy to hear your recommendations / suggestions though, nothing is set in stone at the moment, with respect to keyboard interaction.

**Comment by MarjaE2** [comment]
Page Down seems to work in 1.7.0.

I often run into focus trouble. It may be that I couldn't get focus the previous time and could this time.

**Comment by danielweck** [comment]
Thank you for your feedback. I am closing this issue now, but feel free to report back again, any time.
