### ISSUE TITLE
MathJax ne fonctionne pas

### ISSUE THREAD

**Issue by civodulab** [edrlab/thorium-reader#1467]
Lorsque je coche MathJax rien ne se passe.
![mathjax_bug01](https://user-images.githubusercontent.com/24477170/117947514-8d83b600-b310-11eb-9b68-3484cf26273c.JPG)

**Comment by danielweck** [comment]
Hello, duplicate (fixed) issue: https://github.com/edrlab/thorium-reader/issues/1390

Note that the fix will be included in `v1.7` (coming very soon, probably by the end of this week):
https://github.com/edrlab/thorium-reader/commit/eae3b70ff9033da7f6b2e30da84d7713da60d392

In the meantime, could you please try one of the "latest" releases?
https://github.com/edrlab/thorium-reader/releases

Thank you :)
