### ISSUE TITLE
The SUID sandbox helper binary was found, but is not configured correctly.

### ISSUE THREAD

**Issue by aef** [edrlab/thorium-reader#1472]
After upgrading from 1.6.0 to 1.7.0 .deb package on Debian GNU/Linux 10 with `Linux 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux` when starting the desktop entry for Thorium, nothing happens.

When executing /opt/Thorium/thorium in a terminal I get the foillowing message:

`[19162:0519/181711.773203:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Thorium/chrome-sandbox is owned by root and has mode 4755.`

**Comment by danielweck** [comment]
Well, that's an interesting one!
Have you tried the AppImage?

**Comment by Yodo13** [comment]
I do not have any knowledge on the workings of the Thorium reader, but perhaps my observation sheds light on this issue:

I got exactly the same error message when trying to run an AppImage (not Thorium) on a Debian-based distribution (MX Linux) with the 4.19 kernel. Installing a recent kernel eliminated the problem.

**Comment by aef** [comment]
I upgraded to the backports kernel `Linux 5.10.0-6-amd64 #1 SMP Debian 5.10.28-1 (2021-04-09) x86_64 GNU/Linux` and that actually solved the problem. Thanks for the help.
