### ISSUE TITLE
File type association - Ask for Consent!

### ISSUE THREAD

**Issue by opusforlife2** [edrlab/thorium-reader#1474]
Hi. I just installed this application to try it out temporarily. To my horror, upon installing, it trampled all over my chosen file type associations and took over all the extensions it could open.

This is really annoying automatic behaviour that no app should do. After uninstalling, all those file types were orphaned, and I had to select default apps for them all over again.

Please make the file type association process ask for user consent, preferably letting the user choose which file types to associate and which ones to leave to their current choices.

**Comment by dardoor** [comment]
Yeah no kidding, it even associates with .zip files.
It also installs itself in a non-standard location on Windows (C:\Users\...) instead of Program Files.

But I guess such practices are to be expected from Electron apps...

**Comment by swanknight** [comment]
I couldn't agree more, I just uninstalled it because of this issue. 
There should be a way to choose which extensions that should be associated with it.

**Comment by llemeurfr** [comment]
We understand your concern and will correct that asap. I'm looking for some reference paper about best UX practices in this field, on Windows, MacOS, Linux. Pointers appreciated.

**Comment by danielweck** [comment]
Related issue:
https://github.com/edrlab/thorium-reader/issues/1468#issuecomment-856139158
(ZIP file extension association)

**Comment by danielweck** [comment]
Note that Thorium delegates file extension associations to Electron Builder:
https://www.electron.build/configuration/configuration#PlatformSpecificBuildOptions-fileAssociations
(in other words, there is very little to configure)

**Comment by danielweck** [comment]
Thorium currently registers itself as a handler for the following file extensions: `epub`, `epub3`, `pdf`, `daisy`, `opf`, `webpub`, `audiobook`, `lcpl`, `lcpa`, `lcpdf`, `lcpaudiobook`.

https://github.com/edrlab/thorium-reader/blob/5ccb8f1cbc438379ea3a15581cf69cc5ab2d9908/package.json#L155-L211

**Comment by opusforlife2** [comment]
@danielweck If it's an all-or-nothing sort of situation, then maybe avoid file type association entirely? Users can manually register it as per their preferences.

**Comment by danielweck** [comment]
Message from duplicate issue:
https://github.com/edrlab/thorium-reader/issues/1473
@raxelbrof 

Hi,

Feedback request: Please remove the claim of .opf files from Thorium's info.plist

.opf is not a file any user should be interacting with, so there is no purpose in it being a clickable launcher of Thorium. Currently installing / using 1.7 is assigning Thorium's icon to all of them.

Even if we get-info on the file and manually associate it with a text editor, and associate all .opf files with our chosen editor, the Thorium icon sticks around in Finder, and any app showing a file listing, requiring a Launch Services Database rebuild to clear it out.

1.6 did not claim .opf as a file type for itself, it would be better if 1.7 onwards didn't, either.

edit: Worse still, the icon Thorium uses, is the application's icon, not a Thorium-specific Document Icon. That's a pretty fundamental thing - files openable by an app, should not have the same icon as the app itself. But that said, Thorium should not be claiming file types that are not proprietary to Thorium itself.

Thanks.

**Comment by llemeurfr** [comment]
I'm in favor of "releasing" .opf, because everyone who edits EPUBs needs to be able to open them in a text editor; and there are many of them. And as the raxelbrof says, .opf is not a publishing format.

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/commit/6617b1165ce700bf3a8322e90fbfabd8ef5efd02
(removed PDF and OPF file extensions handling, in addition to ZIP which was already previously removed)
