### ISSUE TITLE
readaloud on Linux

### ISSUE THREAD

**Issue by pkra** [edrlab/thorium-reader#1481]
The readaloud feature fails for me on Linux (I believe for lack of available speech synthesis voices). Is there a way to enable it?

**Comment by danielweck** [comment]
Hello Peter, would you mind running a test with Chromium (or Google Chrome) web browser? Please open a Web Speech TTS test page such as:
https://eeejay.github.io/webspeechdemos/

**Comment by danielweck** [comment]
Another test page: https://codepen.io/matt-west/pen/wGzuJ

**Comment by danielweck** [comment]
And another one: https://embed.plnkr.co/plunk/WjmlDnxcXX5dqlQI

**Comment by danielweck** [comment]
Ah, I finally found the Mozilla demo :)
https://mdn.github.io/web-speech-api/speak-easy-synthesis/

**Comment by pkra** [comment]
Thanks, Daniel. Speech synthesis works fine for me using Chrome but Chrome ships its own proprietary voices. I don't have Chromium to test right now but IIRC it doesn't ship any voices. 

I'm aware that electron doesn't provide voices either, see https://github.com/electron/electron/issues/586. I played around with some of the suggestions from guest271314 from that thread (I'm on Ubuntu 20.10 right now and have, e.g., installed espeak) but that didn't change Thorium's behavior.

**Comment by danielweck** [comment]
I wonder if Thorium should force `app.commandLine.appendSwitch('enable-speech-dispatcher')` (`--enable-speech-dispatcher` on the command line when invoking Thorium's executable).

**Comment by pkra** [comment]
Ah! Thanks for the pointer, Daniel. I had overlooked the part about using --enable-speech-dispatcher on electron. Now it works (well sort of but that'll be a separate issue). Maybe this issue can help to provide some documentation.
