### ISSUE TITLE
Feature Request: Option to skip to next paragraph instead of next sentence in Text to Speech

### ISSUE THREAD

**Issue by nandakishore2009** [edrlab/thorium-reader#1488]
It would a nice feature to include a option for specify whether to skip to the **next paragraph** or to the **next sentence** on text to speech next button.

**Comment by danielweck** [comment]
I agree that being able to configure this would be nice.
The "top-level" Text-To-Speech utterances created by Thorium are based purely on XHTML markup structure, for example indivisible `p` paragraphs that contain only text (or alternatively, text interspersed with non-significant flow markup fragments such as `u` or `strong` elements).
Thorium not only aims to create non-fragmented TTS utterances (i.e. naturally-flowing speech), but also to avoid unnecessarily long units of speech.
To achieve this design goal, there is also "sub-level" utterance creation via sentence detection based on syntactical constructs (e.g. punctuation), using the `sentence-splitter` library ( https://github.com/azu/sentence-splitter ).
I propose that sentence detection can be turned off. This will not only improve performance for users who opt-in, but it will also mean that whole indivisible paragraphs (as per XHTML markup) will be spoken as-is, rendered as single units of speech by the TTS engine. These spoken utterances may therefore be very long with some EPUBs (for example, I personally tested XHTML documents that contain huge paragraphs, nearly an entire "page" / screen worth of content) ... but as this feature would be optional, I think it would be an acceptable trade-off.
What do you think?

**Comment by nandakishore2009** [comment]
Yes, that seems like a great plan.
My feature request was to have the option for TTS skip to next paragraph, similar to the the obsolete Microsoft Edge epub reader, instead of next sentence. Also I find it that in Thorium, during transition between each sentence in a paragraph, the delay is uncomfortable long when your are playing the TTS in high speed(3.0).


**Below is the Microsoft Edge epub reader. Here, you can see the smooth TTS flow between each sentence (with less delay), and half way I press the next button to go to the next sentence. (_PS: don't forgot to unmute the video_)**

https://user-images.githubusercontent.com/24523188/120834603-dda50f80-c580-11eb-89f5-2e0c68c90433.mp4

**In thorium, you can see the uncomfortable long TTS delay between each sentences and if I want to skip to the next paragraph (nearing the end of the paragraph), I have to press the next button multiple times** 

https://user-images.githubusercontent.com/24523188/120834639-e990d180-c580-11eb-9407-969031ae6138.mp4

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/commit/8a9807bca7d34c05d9719d823ae55bbf2a250478

There is now an additional option in the "readaloud" section of the slide-out configuration panel in the reader window (TTS split text). The sentence detection is activated by default but can be disabled using this setting.
There is now an alternative keyboard shortcut for previous/next TTS navigation commands, as well as the shift+alt keyboard modifiers when clicking on the corresponding UI buttons => this skips detected sentence fragments inside major HTML elements (e.g. paragraph that contains plain text which is broken down into individual sentences based on punctuation).
