### ISSUE TITLE
JavaScript Error while trying to open EPUB from another application

### ISSUE THREAD

**Issue by PhilippeBruno** [edrlab/thorium-reader#1492]
I was working on a literature review and decided to keep track of the various documents with a mind map using XMind. I figured it would be a neat idea to attach links to my PDFs and EPUBs to the various nodes of my mind map. I thought that when double clicking a link, it should open the attached file. Please note the file is not embedded; only a link to the full path of the file is saved with each node (another reason in favour of not storing EPUBs in your own DB repository). When I double click a link to a PDF, it opens in default PDF viewer without any problem. However, when I double click a link to an EPUB, bang!

![image](https://user-images.githubusercontent.com/36426806/120056926-4fbfa680-c00d-11eb-8df2-c2ee220b39b0.png)

If I click on OK, the book opens but there is an empty Thorium window behind it that opens too:

![image](https://user-images.githubusercontent.com/36426806/120056997-eb511700-c00d-11eb-8e30-12aca10948f6.png)

The EPUB is still readable. The only problem is the loud warning sound, the error message and the "ghost" Thorium window.

I tried creating a shortcut in Windows to the EPUB to see if I could reproduce the problem, but it just opened the EPUB without any error. I then tried creating a link to an EPUB in OneNote and it opened the same EPUB without any error. Why is it not working with XMind?

**Comment by PhilippeBruno** [comment]
Oh boy I feel stupid... I just discovered that if I single click the small Thorium icon that appears on the node after I add a link to an EPUB, it works perfectly. It is the double click that causes that. However, for the PDF, we can either single or double click and there is no error message.

I assume there is still something going on like Thorium is complaining because it is not fully opened yet when it receives another command to open the same title twice...

Regardless, it would be interesting to know what is going on a figure out how to fix it.

I decided to investigate a bit more prior to posting. I wrote a tiny AutoHotkey script that opens the same EPUB twice in a row:

run test.epub
run test.epub

And sure enough, I am getting the same error as in my previous post. So it is really the fact that Thorium is asked to open an EPUB while it is still loading the first one.

**Comment by panaC** [comment]
Thank you very much for all your investigation 👍 
This is indeed a race condition. And not easy to fix.
I will see that.

**Comment by panaC** [comment]
On mac OS : I cannot reproduce your issue. I made a script to open several epub and it's works. No race condition !

**Comment by panaC** [comment]
got it  !
![image](https://user-images.githubusercontent.com/3198865/120799438-0ad0ce00-c53f-11eb-9244-a931635d95b0.png)

I investigate

**Comment by PhilippeBruno** [comment]
> On mac OS : I cannot reproduce your issue. I made a script to open several epub and it's works. No race condition !

Can't you boot your Mac in Windows mode? I am not a Mac guy, but I see lots of developers doing this...

**Comment by PhilippeBruno** [comment]
> I investigate

Fantastic!

**Comment by danielweck** [comment]
> Can't you boot your Mac in Windows mode? I am not a Mac guy, but I see lots of developers doing this...

I think you are referring to BootCamp. I personally don't use dual-boot partitions on my Mac, instead I run Windows and Linux in a Virtual Machine host (VirtualBox). I also have a "proper" Windows laptop, which I use for testing only.
