### ISSUE TITLE
Embedded videos not playing in Thorium

### ISSUE THREAD

**Issue by clapierre** [edrlab/thorium-reader#1498]
Unable to play the videos embedded in this EPUB, clicking the play button 

This same EPUB works fine with Vitalsource's Bookshelf, but when we click on the links to the video's all we hear with assistive technology is "Buffering" and nothing happens.

[Phonetic_typing_tutorial V3.epub.zip](https://github.com/edrlab/thorium-reader/files/6600809/Phonetic_typing_tutorial.V3.epub.zip)

**Comment by danielweck** [comment]
Hello Charles, the videos do not play either in Google Chrome (reminder: Thorium relies on the Chromium web browser engine, by virtue of being an Electron app)
 Could you please confirm at your end by unzipping the EPUB container and by opening `EPUB/text/ch002.xhtml` directly in your installed web browser(s)?
Personally I observe on MacOS that the videos fail to play in Chrome, but seem to play okay in Firefox and Safari (albeit with some audio glitches)

**Comment by clapierre** [comment]
Confirmed thanks @danielweck.  Is there any video format that works with Thorium?  Perhaps they could convert the .mp4's into another format.

**Comment by danielweck** [comment]
This looks like an encoding issue that trips Google Chrome / Chromium ... nothing we can solve directly in Thorium. Ideally the videos should be reencoded to work on all major web browsers, otherwise a bug report should be filed in the Chromium project.
