### ISSUE TITLE
TTS skips inline svg with aria-label

### ISSUE THREAD

**Issue by pkra** [edrlab/thorium-reader#1501]
An inline SVG with aria-label is skipped during TTS. 

Both img with alt and inline svg with title element work (albeit differently).

**Comment by pkra** [comment]
Here's a minimal example [svg.zip](https://github.com/edrlab/thorium-reader/files/6622921/svg.zip)

**Comment by pkra** [comment]
From the screenshots at https://github.com/edrlab/thorium-reader/issues/1502, I'm guessing that readaloud grabs the textContent of the SVG.

I realize that this leads down the rabbit hole of accname computation but aria-label seems to be a relatively simple case.

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/commit/8a9807bca7d34c05d9719d823ae55bbf2a250478

Thanks Peter for reporting the bug and for providing a sample EPUB, much appreciated!

**Comment by pkra** [comment]
Thanks so much for taking the time to fix this, @danielweck!

**Comment by pkra** [comment]
I've tested the EDRLab.ThoriumReader_1.7.1-alpha.1.942445102_amd64.deb build and confirm the fix.
