### ISSUE TITLE
TTS on linux shows "raw" page while voicing

### ISSUE THREAD

**Issue by pkra** [edrlab/thorium-reader#1502]
Following up on https://github.com/edrlab/thorium-reader/issues/1481#issuecomment-849032595

On Linux (with --enable-speech-dispatcher), the visual rendering changes during voicing.

Without TTS:

![image](https://user-images.githubusercontent.com/426686/121336274-a5eced80-c91b-11eb-90fb-54d36bcc3182.png)

With TTS

![image](https://user-images.githubusercontent.com/426686/121336356-b8ffbd80-c91b-11eb-8312-163829c86d79.png)

This does not happen, e.g., on Windows.

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/commit/8a9807bca7d34c05d9719d823ae55bbf2a250478

Thank you Peter for reporting this, and for providing screenshots that demonstrate the issue.

**Comment by pkra** [comment]
Thanks so much for taking the time to fix this, @danielweck!

**Comment by pkra** [comment]
I've tested the EDRLab.ThoriumReader_1.7.1-alpha.1.942445102_amd64.deb build and confirm the fix.
