### ISSUE TITLE
Create an easy way to add an OPDS feed to Thorium

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1506]
Currently, the addition of an OPDs feed is tedious and for geeks only: one has to know the URL of an OPDS feed, copy/paste it, name it manually and validate. 

The new use case is: 
 - A user has a Readium-based app installed (desktop or mobile). 
 - A bookseller or public library adds a button to its website, labelled as "Add the catalog to your Readium app" (*) or equivalent.
 - The user clicks on the button provided on the website. 
 - The Readium app is triggered, catches the URL and name of the OPDS feed, automatically adds it to the list of feeds, opens the catalog.  

This can be achieved via what is called "OPDS callback", with a button attached to a URL of type `opds://`.

The same technique will be used in the scope of a OPDS "catalogs" feed, i.e. a list of OPDS feeds in which a user can choose one or more feeds to add to the app. See #1336. 

(*) I'm using the Readium brand here for marketing purpose. The scope could be wider  but - IMHO - non-Readium apps will hardly implement this.

**Comment by HadrienGardeur** [comment]
I recommend opening a discussion in https://github.com/opds-community/drafts/discussions

**Comment by llemeurfr** [comment]
I'm ok with that. After a generic technique is agreed there, we'll study here its integration in Thorium.

**Comment by danielweck** [comment]
Useful links:
* https://github.com/opds-community/drafts/discussions/47
* https://github.com/opds-community/drafts/issues/16
* https://opds.io/callback.html

**Comment by danielweck** [comment]
Note that Thorium already implements a CLI OPDS handler:
https://github.com/edrlab/thorium-reader/blob/7230ca9ab0d3d967469a8c52784d266fdd686641/src/main/cli/process.ts#L68
https://github.com/edrlab/thorium-reader/blob/7230ca9ab0d3d967469a8c52784d266fdd686641/src/main/cli/service.ts#L80-L86

Thorium is a single-instance app, so launch requests via CLI, OS-level "open with ..." / "double click in file explorer", and custom URL protocol handlers are all passed through to a brand new app instance or an existing one (which may already display the library window, or reader window(s), or both types of windows). Consequently, when the "import OPDS URL if not already registered, and browse OPDS feed / publication" action is triggered, there must be some reconciliation of the various possible UI states (e.g. when a reader window is opened without the library window, the former must be put into the background, the latter into the foreground and switched to the OPDS "catalog" tab for browsing a feed or viewing a publication info).
