### ISSUE TITLE
CSS page-break-before not supported

### ISSUE THREAD

**Issue by apgrover** [edrlab/thorium-reader#1510]
## Summary
```page-break-before: always``` does not appear to break “pages” in the viewport.
## Scope
Observed in Thorium for PC/Mac v1.6.0
## Expected
```page-break-before: always``` separates content to next viewport page.
<img src="https://user-images.githubusercontent.com/14042519/122103839-0af58700-cde5-11eb-9118-5c8622cd138f.png" width=70% />

## Observed
```page-break-before: always``` does not appear to separate content onto different viewport pages.
<img src="https://user-images.githubusercontent.com/14042519/122103858-1052d180-cde5-11eb-97f1-0703b4f7132b.png" width=70% />

### HTML
```
    <div class="pagebreak">
        <p class="dg dk">Consectetur non sit non sed amet dolore</p>
        <p class="dt"><span class="dk">Dolore</span> sit</p>
    </div>
    <div class="pagebreak">
        <p class="dt">Ipsum tempora</p>
        <p class="gd">—Ipsum tempora</p>
        <p class="dt">Ipsum tempora</p>
        <div class="gd">—Ipsum tempora</div>
    </div>
```
### CSS
```
.pagebreak {
    page-break-before: always;
}
```

Sample file available upon request.

**Comment by danielweck** [comment]
Hello, Thorium uses a Chromium webview to render EPUB XHTML content documents, and 

Related issue? https://github.com/readium/readium-css/issues/52

**Comment by apgrover** [comment]
@danielweck Thank you for reviewing this issue! We're looking forward to additional findings on this.

**Comment by JayPanoz** [comment]
@danielweck 

> We just apply CSS Column styling so I would expect page-break-before: always to be observed.

Correction: CSS multicol doesn’t obey `page-break-*` but `(-prefix-)column-break-*` – [and it’s been for a long time](https://github.com/readium/readium-shared-js/issues/127) 😅

Page-break

![always](https://user-images.githubusercontent.com/12599652/122761029-112fab80-d29c-11eb-8083-3a567cf66a53.png)

Column-break

![prefix-prop](https://user-images.githubusercontent.com/12599652/122761062-1bea4080-d29c-11eb-8404-24db3ac25b51.png)

Now to the bad news: even with the newer (and abstracted) [`break-*` properties](https://developer.mozilla.org/en-US/docs/Web/CSS/break-before), the value has to be explicitly set to `column` – `always won’t work` – at least in some browsers. Did not check the spec so I can’t tell whether that is the expected implementation or not. 

When you switch from `always` to `column` for `break-before` it now works: 

![col-value](https://user-images.githubusercontent.com/12599652/122761133-2efd1080-d29c-11eb-9ae0-b5f3d6e07ffb.png)

IOW if you ever want to support `page-break` you’ll have to polyfill.

**Comment by danielweck** [comment]
Let's close this issue as "cannot fix", due to browser support the appropriate CSS syntax must be used. Thorium or ReadiumCSS will not implement polyfills for incomplete features of the open web platform. We simply rely on Chromium's available support.
