### ISSUE TITLE
Thorium can't read aloud a book using Text-to-Speech in addition to pre-recorded audio clips 

### ISSUE THREAD

**Issue by geovls** [edrlab/thorium-reader#1515]
I have a smil file where some text elements have an audio sibling element and some of them don't have. 
Thorium reads aloud the text elements with the pre-recorded audio but doesn't use TTS to read aloud the rest of them (those who don't have pre-recorded audio)

**Comment by llemeurfr** [comment]
Hi @geovls, Thorium is not programmed to complete by TTS "holes" in media overlays (*). Leaving "holes" is an authoring decision, that a reading app should not override. 

TTS is a feature provided by the app to bring audio accessibility to all ebooks, even those which don't have synchronised audio media attached. 

We don't intend to change this behaviour, therefore I'll close this issue now.  Don't hesitate to report other issue you may see in the app, we'll be happy to treat it the best we can.

(*) this is the name given to the text-audio synchronisation via smil in EPUB.

**Comment by danielweck** [comment]
Hello!
I am afraid Thorium does not support "filling the gaps" with TTS / synthetic speech when pre-recorded audio narration is missing in a EPUB3 Media Overlays publication:
https://www.w3.org/publishing/epub/epub-mediaoverlays.html#sec-text-to-speech
Do you know other reading systems that do?
Thank you!

**Comment by geovls** [comment]
Hello @danielweck!
Readium supports "filling the gaps" with TTS / synthetic speech when pre-recorded audio narration fragments are missing. 
(By the way, according to Thorium site, Thorium Reader is based on the set of open-source chrome-less modules, a toolkit named Readium Desktop).

**Comment by llemeurfr** [comment]
@geovls, Readium is not a product, it is a Foundation and a "product line". To get details, please read https://www.edrlab.org/software/. I don't remember ReadiumJS "filling the gap".

**Comment by danielweck** [comment]
> I don't remember ReadiumJS "filling the gap"

@llemeurfr the "old" Readium SDK implements this lesser-known part of the EPUB3 Media Overlays specification. In fact I believe it is the only implementation that supports this fringe feature, and as far as I know content authors / creators do not rely on it given its lack of support.

**Comment by geovls** [comment]
@llemeurfr i forgot to mention that Readium for Chrome is the product that supports "filling the gaps".  Readium for Chrome is the Chrome browser extension configuration of ReadiumJS. I haven't used ReadiumJS on other platforms so i can't say if the "filling the gaps" feature is supported there.

**Comment by danielweck** [comment]
@geovls thank you for your clarifications.

Note that the Chrome "extension" is actually a Chrome "app" (as per Google's terminology / technical framework), so it is now officially deprecated and it may be completely disabled by Google's web browser, any time from now on:
https://developer.chrome.com/docs/apps/migration/

Google already removed the Readium Chrome "app" from the Web Store search results, but the direct link still works:
https://chrome.google.com/webstore/detail/readium/fepbnnnkkadjhjahcafoaglimekefifl

<img width="1293" alt="Screenshot 2021-06-23 at 12 15 48" src="https://user-images.githubusercontent.com/625201/123087912-018ba080-d41d-11eb-937c-fa4b16230da3.png">

Also note that despite its popularity the Readium Chrome "app" was not really a "product" in the sense that it was only backed up by a small open source community. At the time, the Readium Foundation was focusing on supporting Readium SDK integrators - mostly Android / iOS native apps, and some hybrid apps based on the "cloud / web" reader (aka ReadiumJS).

**Comment by llemeurfr** [comment]
ok, so the "old" REadium SDK seems to be the only implementation of https://www.w3.org/publishing/epub3/epub-mediaoverlays.html#sec-text-to-speech (which is a SHOULD). 

Which leads to the question for @geovls: what is the source of the smil files you have, with text nodes without corresponding audio? is it files you've created?

**Comment by danielweck** [comment]
Spec. discussions: https://github.com/w3c/epub-specs/issues/1745#issuecomment-872098946

**Comment by danielweck** [comment]
Related discussion: https://github.com/w3c/epub-specs/issues/2397#issuecomment-1212924986
