### ISSUE TITLE
Search broken in v1.7.1-alpha when book opened by double-clicking on EPUB in Windows File Explorer

### ISSUE THREAD

**Issue by PhilippeBruno** [edrlab/thorium-reader#1517]
I was running v1.7.1-alpha.1.842238767 since about mid May and did not notice it until today, but the search feature does not return any result, even for words present on the displayed page, when the book is opened by double-clicking on the EPUB in Windows File Explorer. However, if one returns to bookshelf and goes back to very same book, the search feature works again.

![Thorium_FJxzjG7PIB](https://user-images.githubusercontent.com/36426806/122570357-acfdb500-d019-11eb-9b7b-6d28caa17544.jpg)

If Thorium is launched by itself, i.e. without double-clicking on an EPUB, and a book from the bookshelf is opened, the search feature works well.

![Thorium_m4SFQncEzO](https://user-images.githubusercontent.com/36426806/122570420-bbe46780-d019-11eb-8968-d3865d63341a.jpg)

I downloaded v1.7.1-alpha.1.949738250 this morning and it still does not work normally. So I cannot tell at what point in time it stopped working, but it seems the search has been broken for a few versions, at least as far back as v1.7.1-alpha.1.842238767.

**Comment by danielweck** [comment]
Very strange!

I am unable to reproduce this behaviour on MacOS with Thorium 1.7.1
https://github.com/edrlab/thorium-reader/releases/tag/v1.7.1

I tried with the app already open, or the app closed (then double-click from Finder / file explorer, or "open with..." menu).

**Comment by PhilippeBruno** [comment]
It is indeed very strange. Try it on your Windows machine... I can systematically repeat the bug every time.

**Comment by PhilippeBruno** [comment]
I just tried on a totally different Windows machine that had the v.1.6.1-alpha.1.736604465 already installed and I experienced the exact same problem.

**Comment by PhilippeBruno** [comment]
If I open Thorium and drop the EPUB on it, the search works.

**Comment by panaC** [comment]
I can reproduce this issue with the latest nightly build too

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/pull/1541
Thank you Pierre! (@panaC )
