### ISSUE TITLE
Suggestion: Highlight current chapter in Navigation > Table of Contents drop down

### ISSUE THREAD

**Issue by PhilippeBruno** [edrlab/thorium-reader#1521]
Would there be a way to either highlight (using a bold font perhaps) the highlight the current chapter in the Navigation > Table of Content or show it at the bottom of the screen somewhere?

**Comment by danielweck** [comment]
Hello, this is now implemented via https://github.com/edrlab/thorium-reader/commit/16d52d14782009d05167ec34971c17ea81cb0e9e

This feature includes both a visual indicator, and screen reader / keyboard accessible interaction which places the focus directly on the identified heading that corresponds to the nearest preceding location in the document to the current reading location.

The existing CTRL+N shortcut remains, which only opens the navigation panel, doesn't focus on the TOC tree (whereas the new one with additional SHIFT modifier key brings the focus to the current heading).

@nvdaes Note that there is now a new keyboard shortcut documented in the English Wiki ( https://github.com/edrlab/thorium-reader/wiki/Keyboard-shortcuts ). See:

* `SHIFT` + `CTRL` + `n` (`FocusReaderNavigationTOC`): in reader window, moves the keyboard focus to the navigation panel, but more specifically into the table of contents, and if possible at the detected heading  / closest to the reading location.
