### ISSUE TITLE
Fixed layout : cannot zoom

### ISSUE THREAD

**Issue by awissam** [edrlab/thorium-reader#1528]
hi
i have a fixed layout ePub done on InDesign. is there any workaround to zoom on text in thorium?
thx

**Comment by awissam** [comment]
anyone please?

**Comment by danielweck** [comment]
Hello, a "zoom" feature for fixed-layout publications will be released soon :)

**Comment by awissam** [comment]
is there a version for ios? android?

**Comment by danielweck** [comment]
Thorium is a "desktop" application for Linux, Mac and Windows.

**Comment by danielweck** [comment]
Duplicate of: https://github.com/edrlab/thorium-reader/issues/1228
