### ISSUE TITLE
Fixed-Layout hairline gap in spine when zoomed

### ISSUE THREAD

**Issue by raxelbrof** [edrlab/thorium-reader#1543]
Hi,

Just giving 1.7.2's zoom function a test, and noticing in my fixed-layout books with edge-to-edge images, that Thorium is opening a 1px / hairline gap at the spine when using the zoom-in function, which isn't the best outcome.

Each page viewport is width=740, height=1132
Images contained are width=1480, height=2264px

![spine-gap](https://user-images.githubusercontent.com/64583201/133372968-cde637b2-383f-4a9e-8683-7752e4c14b39.png)

**Comment by danielweck** [comment]
Thank you for reporting this! (tricky to solve, due to imprecision of CSS 2D transform (scale + translate) on the Electron webview controls :(

**Comment by raxelbrof** [comment]
So your suspicion would be it's not the pages themselves, but a gap opening between the separate webviews(?) used to make the double page spread?

**Comment by danielweck** [comment]
yes.

**Comment by danielweck** [comment]
Having looked at the current rendering stack and CSS "pixel" alignment precision when applying compound scale and translations transforms, I am afraid this is a "no fix". Let's see if more users report such rendering issues, and of course we will attempt to address the problem if the demand is high.
