### ISSUE TITLE
ruby in navigation documents

### ISSUE THREAD

**Issue by murata2makoto** [edrlab/thorium-reader#1545]
Thorium now renders both base and ruby without parentheses surrounding ruby.  This is not easy to read and, in rare cases, completely changes the meaning.

I recommend (1) rendering base only, and (2) rendering both base and ruby with surrounding parentheses added.

**Comment by danielweck** [comment]
Thank you for reporting this :)

Support for CJK / Ruby / Vertical Writing Mode + Right To Left progression is very rudimentary is Thorium (notably in paginated documents, but I am sure there are other cases where Thorium falls short of delivering).
In fact there is no special treatment of Ruby decorations, so my guess is that there may be some incorrect ReadiumCSS configuration or implementation. CC @JayPanoz FYI

We will look into it, but could you please provide a test EPUB so we can reproduce the bug? Thank you :)

**Comment by murata2makoto** [comment]
Sorry for my belated reply.  JDC will discuss today.

**Comment by murata2makoto** [comment]
Here is [an example EPUB](https://1drv.ms/u/s!An5Z79wj5AZBkahc40c2qAbgzKr0UQ?e=h75sLB).  JDC will soon prepare a collection of EPUB publications as a test suite.

**Comment by danielweck** [comment]
Moving/collating issue to https://github.com/edrlab/thorium-reader/issues/959
