### ISSUE TITLE
Thorium | Bug | Screenreader on Windows reads underscores at chapter beginning (»Unterstrich«)

### ISSUE THREAD

**Issue by typopaul** [edrlab/thorium-reader#1556]
`Thorium 1.7.2 – Windows 10`

When screenreader feature is used on Windows, it reads two underscores on chapter beginnings. 
See example video for this behavior here: https://www.loom.com/share/eeefb3c9df984c43bf6512516c206ca6

The code of the XHTML file, which is seen in the video is the following.

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">

<head>
	<title>Höhenlage</title>
	<link href="../css/idGeneratedStyles.css" rel="stylesheet" type="text/css" /><link href="../css/styling.css" rel="stylesheet" type="text/css" />
</head>

<body id="ch-110-gender.xhtml" lang="de-DE" xml:lang="de-DE">
	<div class="Einfacher-Textrahmen">
		<h1 id="_idParaDest-1">01 | Screenreaderausgabe bei Gender-Zeichen</h1>
		<p class="FT_2_Abs">Das ist ein Beispielsatz für Verleger:innen und Lektor_innen und weitere Interessent*innen zur Feststellung der Sprachausgabe. AutorInnen und Leser/-innen werden bestimmt auch Interesse daran haben. Hier noch zum Vergleich: Verlegerinnen, Lektorinnen, Interessentinnen, Leserinnen.</p>
    </div>
</body>
</html>
```

**Comment by danielweck** [comment]
Hello, this is actually a feature in Thorium, albeit not a well documented one.
This special link is injected to enable quick jump to the last known referenced element in the rendered publication document, for example the target of a hyperlink from the table of contents (or bookmark, or goto page, etc.)
This is also a necessary feature with screen readers who struggle to focus into the embedded webview / rendered publication document when following hyperlinks. When they fail, they just land at the top of the document, not at the actual link target in the HTML document. So a single tab into the special underscore link makes it possible to jump to the desired / previously-addressed location.

**Comment by typopaul** [comment]
Ah! Thank you for the explanation, @danielweck. It helps a lot. 👍
