### ISSUE TITLE
Text to speech not working under Linux

### ISSUE THREAD

**Issue by bitsgalore** [edrlab/thorium-reader#1570]
I just downloaded the Thorium 1.7.2 Appmage package, and noticed that the text to speech feature doesn't seem to do anything. After pressing the "play" button I see this, but I don't actually hear anything (progress bar at bottom of page also doesn't move):

![thorium-tts](https://user-images.githubusercontent.com/1014449/136820226-364a79af-7098-4fa6-b044-6c87d950eb5d.png)

OS: Linux Mint 20.1 Ulyssa
Thorium version: 1.7.2
Install method: AppImage

**Comment by bitsgalore** [comment]
Thanks @danielweck. I just launched Thorium with `--enable-speech-dispatcher`, but that didn't make any difference. However, out of curiosity I opened a few of the TTS demos you mentioned in  [issue 1481](https://github.com/edrlab/thorium-reader/issues/1481), and noticed that even though they all work fine in Firefox (my default browser), they don't work at all in Chromium! So I supposes something odd is going on with the Chromium rendering engine on my system.

**Comment by danielweck** [comment]
> Well, apparently an Electron app can safely use this code `app.commandLine.appendSwitch('enable-speech-dispatcher');` ... but I am concerned about applying this flag without understanding the possible side effects.
https://github.com/edrlab/thorium-reader/commit/e79fa0398e54119306ac75ee3ef192b6463533fc
