### ISSUE TITLE
The opds-feed previously provided in the readme of this project has disappeared, how should I find them again?

### ISSUE THREAD

**Issue by cary-rowen** [edrlab/thorium-reader#1572]
As the title says, or how should I find more opds subscriptions.
Thanks!

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/blob/7a2a4852d09e411f07fd956dee0d57e572354129/README.md

history : https://github.com/edrlab/thorium-reader/commits/develop/README.md

https://github.com/readium/r2-streamer-js/blob/develop/docs/opds.md

I hope it will help you. I'm closing the issue.

**Comment by cary-rowen** [comment]
This solved my problem perfectly, thank you very much.
