### ISSUE TITLE
Ruby annotations and read aloud

### ISSUE THREAD

**Issue by ways2read** [edrlab/thorium-reader#1576]
When there is text with ruby annotations both the base and the ruby annotations are spoken. This results in a poor user experience with words/phrases effectively read twice.

It needs validation from native speakers, but I believe the base text should be passed for narration and the annotations should be ignored.

**Comment by murata2makoto** [comment]
[This upcoming W3C note](https://github.com/w3c/ruby-t2s-req) is very relevant.
