### ISSUE TITLE
Vertical position of highlighting issue with EPUBs in Thorium Reader

### ISSUE THREAD

**Issue by togregg** [edrlab/thorium-reader#1579]
The vertical position of highlighting of text while reading as well as search results is off by several lines with EPUBs in Thorium Reader 1.7.3. If an EPUB has a CSS stylesheet where a div contains this rule:

  div {      margin: 1.75em 0;   }

it will result in the vertical position of the highlighting appearing below the actual location of the text in the EPUB. 

Tested with:

- Windows 10 Enterprise (64-bit) Version 2004 (OS Build 19041.685)
- macOS Big Sur Version 11.6
- Thorium Reader 1.7.2 and 1.7.3

 Steps to demonstrate the issue:

1. Create a Word document with a paragraph that will render as an EPUB with around 10 or more lines of text
2. Save the Word document
3. Create a CSS stylesheet (div_margin.css) that contains only this rule:   div {      margin: 1.75em 0;   }
4. Activate the WordToEPUB daisy.org plug-in (I used WordToEPUB version 1.0.7+2108142)
5. Click on the “Advanced mode” button
6. Click on the “Styling” tab
7. Browse to choose the div_margin.css CSS stylesheet created above 
8. Click the “OK” button
9. Click “Close” once WordToEPUB is finished (the EPUB has been created)
10. Open the newly created EPUB in Thorium (we tested in v1.7.3) with Thorium’s default settings
11. Click the “Activate Text to Speech” button and note that the highlighting is vertically offset to be lower than it should be.
12. Stop the Text to Speech
13. Search for “the”
14. Note that the highlighting for search results is also offset: 
![image](https://user-images.githubusercontent.com/92333167/137807251-47b4270c-bf86-4f7c-930b-09a11943df45.png)

Here is a video demonstrating the vertically offset highlighting bug in Thorium v1.7.3:
- [https://iu.mediaspace.kaltura.com/media/t/1_875p2ghv](https://iu.mediaspace.kaltura.com/media/t/1_875p2ghv)

Attached to this Issue request are the files used to demonstrate the vertical offset highlighting bug:
- [thorium_highlighting_bug_2021_10_12.docx](https://github.com/edrlab/thorium-reader/files/7368527/thorium_highlighting_bug_2021_10_12.docx)
- [thorium_highlighting_bug_2021_10_12.docx](https://github.com/edrlab/thorium-reader/files/7368541/thorium_highlighting_bug_2021_10_12.docx)

**Comment by danielweck** [comment]
Hello, thank you very much for reporting this bug with such useful level of detail. Would you mind sharing an EPUB file that exhibits this problem?
Thank you! Regards, Daniel

**Comment by togregg** [comment]
Hi Daniel,

The original post was supposed to include the EPUB file. You can access it from the below link:

- [thorium_highlighting_bug_2021_10_12.epub](https://slashtmp.iu.edu/files/download?FILE=togregg%2F50901KWHfHn)

The password is thoriumepub

Sincerely,

Tomas
