### ISSUE TITLE
Unordered lists appear as ordered from v1.7.2

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1580]
Reported by prcvi.org

Unordered &lt;ul> lists with bullet markers display as ordered lists with number markers in Thorium. That happens in v. 1.7.2 and 1.7.3, but not in v. 1.7.

![image002](https://user-images.githubusercontent.com/14943186/137981499-c260d79b-4dd9-49d2-b5e6-71f4008ec5ed.png)
1.

**Comment by danielweck** [comment]
Are you able to reproduce this with version 1.8?

**Comment by danielweck** [comment]
Hello again, any chance we could obtain a sample EPUB so we can test a reproduction of this bug? (sounds like ReadiumCSS, but it could be something else altogether)

**Comment by danielweck** [comment]
Closing due to lack of test EPUB.
