### ISSUE TITLE
Menu button for books in the Grid View do not have book specific labelling in Thorium Reader 1.7.3

### ISSUE THREAD

**Issue by togregg** [edrlab/thorium-reader#1583]
When accessing the menu option button for a book in the grid view of My Books, each instance is labelled as Menu by a screen reader. This is true for viewing All Books or Resume Reading list of books. If you pull up the Forms Field list in JAWS, the Elements list in NVDA or the Forms Controls in VoiceOver, each instance of the menu button is labelled the same. This means if there are 5 books in the bookshelf, you see the word Menu five times and don’t know which book it is associated with in Thorium Reader.

Tested with:

- Windows 10 Enterprise (64-bit) Version 20H2 (OS Build 19042.1237)
- macOS Big Sur Version 11.6
- JAWS Professional Edition Version 2021.2107.12 ILM
- NVDA Version 2021.2
- VoiceOver

Steps to demonstrate the issue:
1. Make sure you have several EPUB books added to Thorium Reader (in the examples below there were 5 books in Resume Reading)
2. Launch your screen reader program
3. Launch Thorium Reader
4. Select My Books 
5. Select Grid View
6. Access the forms/elements navigation list from your screen reader:

JAWS

- Press Insert + F5 to bring up the Forms list
- Press down arrow until you get to Menu button
- Note the list of menu buttons, all 5 with the name menu

![image](https://user-images.githubusercontent.com/92333167/139950641-9756f657-63db-40f5-9a9c-cb07770f22ad.png)

NVDA

- Press Insert + F7 to open the Elements list window in NVDA
- Press Alt + B to go to Buttons
- Press Tab to get to the tree view of buttons
- Press up arrow until you get to Menu; collapsed
- Note the list of menu buttons, all 5 with the name menu

![image](https://user-images.githubusercontent.com/92333167/139950951-80620eac-c5a7-4401-b5f3-3e137fc3784f.png)

VoiceOver

- Press Control + Alt + U to access the navigation rotor
- Press the Right arrow until you get to the Form Controls menu
- Press down arrow until you get to Menu collapsed button
- Note the list of menu buttons, all 5 with the name menu

![image](https://user-images.githubusercontent.com/92333167/139951265-b1cc6274-cab6-452e-9af9-9ec61f5a10f1.png)

**Comment by danielweck** [comment]
Thank you very much for your detailed report, much appreciated! 👍 

Yes, the keyboard-driven UI structure is not great, due to this disconnect between the cover image and the menu item pairs.

**Comment by togregg** [comment]
Is this on the roadmap to fix since it is an issue with grid view and impacts navigation with a screen reader?

**Comment by danielweck** [comment]
Hello, could you please inform whether this has been fixed for you in Thorium v1.8? Thank you very much.

**Comment by togregg** [comment]
Hi Daniel,

The issue is not fixed and still persists in v 1.8.0 on macOS and Windows.

Example in macOS
![Screen Shot 2022-01-21 at 1 21 38 PM](https://user-images.githubusercontent.com/92333167/150583374-c517ffc2-fc2c-4c8f-8ad8-5179a8d27d1b.png)

Example in WIndows
![Screen Shot 2022-01-21 at 1 54 18 PM](https://user-images.githubusercontent.com/92333167/150584151-60c16bcb-a497-4371-abef-1d802fa27c6e.png)

**Comment by togregg** [comment]
Can this be left opened until we can confirm that it is fixed in the v2.0.0 release?

**Comment by danielweck** [comment]
Hello, issues are closed as soon as fixes land in the develop branch, and the automated Thorium builds for V2 are available on GitHub to test the improvements. 
Let us know if you still experience accessibility or usability issues, please. Thank you :)

**Comment by togregg** [comment]
@danielweck Tested with the latest alpha for v2.0.0 from last week and the issue looks to be fixed.
