### ISSUE TITLE
internal xlinks in SVG are not working after 1.6 version

### ISSUE THREAD

**Issue by fbrzvnrnd2** [edrlab/thorium-reader#1584]
After 1.6 the internal xlinks in SVG are not working anymore.

For example: 
`<a xlink:title="link interno" xlink:href="../Text/studenti_4.xhtml"><text transform="matrix(1 0 0 1 76 183.4)">Il concetto di “rischio”</text></a>
`
In 1.5 I can click "Il concetto di “rischio" and jump to studenti_4.xhtml page. After 1.6 the xlinks are not working anymore

**Comment by danielweck** [comment]
This could be due to several different factors. Could you please share (privately) an EPUB that exhibits the problem? Thank you.

**Comment by danielweck** [comment]
I am not able to reproduce this bug. Closing due to lack of feedback.
