### ISSUE TITLE
OPDS / Publication info dialog: author and publisher text are links, but do not display as obvious clickable links and not keyboard-focusable

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1585]

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/blob/0f2cb5c3aac46e88d247548d7568ab7a3a5eeaaf/src/renderer/common/components/dialog/publicationInfos/FormatContributorWithLink.tsx#L18 ?

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/blob/0f2cb5c3aac46e88d247548d7568ab7a3a5eeaaf/src/renderer/common/components/dialog/publicationInfos/FormatContributorWithLink.tsx#L36-L44

**Comment by danielweck** [comment]
This was fixed in the CSS refactor.
