### ISSUE TITLE
Book "info"  (in reader) not listing authors correctly

### ISSUE THREAD

**Issue by pkra** [edrlab/thorium-reader#1586]
For books with multiple authors, the bookshelf shows multiple authors while the "info" in the reader only shows one author -- and not necessarily the first one in the opf order.

Example:

[author-meta.epub.zip](https://github.com/edrlab/thorium-reader/files/7495934/author-meta.epub.zip) (zippe'd epub)

Bookshelf:

![screenshot from bookshelf, in particular authors are given as "B Author, A Author"](https://user-images.githubusercontent.com/426686/140721488-e7852811-7257-438c-b188-50d1d5beba72.png)

Reader => info:

![screenshot from reader's info panel, in particular authors are given as "A Author"](https://user-images.githubusercontent.com/426686/140721529-f443dba6-ca3f-4547-ac88-013ad7ff552b.png)

**Comment by panaC** [comment]
I cannot unzip the EPUB 

<img width="490" alt="image" src="https://user-images.githubusercontent.com/3198865/140722982-be17b95f-66b9-438e-a16f-9fed0e6bee84.png">

do you know why ?

**Comment by danielweck** [comment]
Well spotted, thank you Peter!

**Comment by danielweck** [comment]
@panaC use `unzip` from the command line

**Comment by danielweck** [comment]
MacOS Books.app :)
<img width="200" alt="Screenshot 2021-11-08 at 10 09 08" src="https://user-images.githubusercontent.com/625201/140723401-8f1eb0b6-0c05-47a5-8afb-864994da64c6.png">

**Comment by danielweck** [comment]
MacOS Books.app (list view):

<img width="863" alt="Screenshot 2021-11-08 at 10 10 17" src="https://user-images.githubusercontent.com/625201/140723575-ea74e50e-91fc-4ab4-97cc-9d2509c43d88.png">

**Comment by pkra** [comment]
> MacOS Books.app :)

Yup, that's incidentally where this started :smile: Definitely not good either but at least the first author as per manifest.

**Comment by danielweck** [comment]
MacOS Books.app "authors view":

<img width="1290" alt="Screenshot 2021-11-08 at 10 14 58" src="https://user-images.githubusercontent.com/625201/140724192-34b6fd20-83ab-4389-8476-33b2ff71d12c.png">

**Comment by danielweck** [comment]
> Definitely not good either but at least the first author as per manifest.

Indeed.

Useful implementation guide ("author" mapping, `refines`, etc.):

https://github.com/readium/architecture/blob/master/streamer/parser/metadata.md

**Comment by pkra** [comment]
> Useful implementation guide ("author" mapping, refines, etc.):
> 
> https://github.com/readium/architecture/blob/master/streamer/parser/metadata.md

Thanks. The page doesn't appear to say much about multiple contributors but I may have missed that part. (Though I'm not sure if your comment was a suggestion for authoring.)

**Comment by danielweck** [comment]
Ah no, this is a doc for reading system developers :)
