### ISSUE TITLE
Feature request:  default settings for all books and allow to edit title (metadata)

### ISSUE THREAD

**Issue by cocoonkid** [edrlab/thorium-reader#1590]
Feature request:  default settings for all books and allow to edit title

I would like to set for example the scroll settings for ALL my books at once and forever.
And also be able to edit titles which are sometimes not very coherent when importing.

This is really an amazing piece of art and software. 

The more I am wondering why these two basic features are not available or am I missing something?

**Comment by danielweck** [comment]
Hello!
By default, Thorium applies layout / formatting preferences to all publications. There is in fact a checkbox in Thorium's settings to activate a special mode that applies preferences on a per-publication basis (the term used is "session"). You can also reset preferences in the reader window (there is a button buried under the menu system, at the bottom of the stack).

As for editing / amending publication titles: that is an "interesting" feature, I had not heard this before :)

**Comment by cocoonkid** [comment]
Thank you :-).  I think I understood it now.

Looking forward to the editing feature, because unfortunately some books are having very weird names extracted from their epub or pdf metadata.

Cheers and love :-)

**Comment by danielweck** [comment]
As discussed internally, Thorium is a reading tool, we do not have the development resources to implement editing features such as some found in Calibre etc. (bookshelf / collection management utilities)
