### ISSUE TITLE
Linux, LCP, crash

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1592]
The attached screenshot corresponds to a fresh install of Thorium on Linux by a user. I happened the first time a .lcpl (testmode) was imported + the passphrase was entered. After relaunch of the app, entering the passphrase and reading the ebook was ok. 

The msg reads: 
An error has occured in readium-desktop:main:redux:sagas:win:reader:createReaderWindow
ERR-FAILED (-2) loading 'file:///opt/Thorium/resources/app.asap/-index_reader.html'

![UTF-8''Capture%20d%E2%80%99%C3%A9cran%20de%202021-11-25%2016-](https://user-images.githubusercontent.com/14943186/143473978-67085e78-b48f-455f-99f0-e875d70259b2.png)

**Comment by danielweck** [comment]
It would be interesting to know if this non-fatal bug occurs when double-clicking on the LCP license file (and if so with or without an existing instance of Thorium already launched, and if so in the main library window or with a reader window open), or drag-and-drop, or via Thorium's "open" file chooser.

**Comment by llemeurfr** [comment]
Triage, closed as not-reproductable.
