### ISSUE TITLE
GUI Colour contrast

### ISSUE THREAD

**Issue by spudthebud** [edrlab/thorium-reader#1600]
Using the Colour Contrast Analyzer,  I found the olour contrast is quite low, "Search" to background is 1.8 : 1  The search icon is also quite low

The image is of Thorium with the My Books toggle button selected, The image shows the word "Search" in the "Search by title" edit 
![image](https://user-images.githubusercontent.com/8799391/145199561-75cc9363-3766-4729-a44c-9c826c99d355.png)

**Comment by danielweck** [comment]
Thank you @spudthebud we will run the Javascript Deque Axe checker which is built into our development workflow (not automated, this has to be executed manually) to see if this is reported correctly.

**Comment by danielweck** [comment]
Fixed in Thorium 3 (GUI refactor)
