### ISSUE TITLE
Is the "main content" Region necessary? 

### ISSUE THREAD

**Issue by spudthebud** [edrlab/thorium-reader#1601]
I'm studying Thorium with the JAWS screen reader, although I imagine it's true for NVDA too. 

I'm looking at the use of regions to get my orientation.

I notice that in Reading View and Bookshelf View, there is a "main content" region within a "main content" main region. The only bit of content in the "main content" region is a line of text that says "main content".  I find this quite confusing.  

Here's a sketch:

Bookshelf view

"Main Content" main region (start)
.....  "main content" region (start)
..... ..... main content (static text)
..... "main content" region  (end)
..... Heading 2, Resume Reading
etc.
"Main Content" main region (end)

**Comment by danielweck** [comment]
Merge into issue https://github.com/edrlab/thorium-reader/issues/1598
