### ISSUE TITLE
Colour contrast, hover effect: Left and Right buttons

### ISSUE THREAD

**Issue by spudthebud** [edrlab/thorium-reader#1603]
The colour contrast between the left and right buttons and their background is quite low, at 1.8 to 1.
I used the Colour Contrast Analyzer developed by the Paciello Group

The following image shows the left and right buttons. 
![image](https://user-images.githubusercontent.com/8799391/145713091-c61387b9-31d4-42f4-8271-b370b28c8731.png)

Additionally there is no hover over effect with the mouse, as there is when the user tabs to it.

**Comment by danielweck** [comment]
Merging issue: https://github.com/edrlab/thorium-reader/issues/1600
