### ISSUE TITLE
Why does the sepia theme change the white of my image ?

### ISSUE THREAD

**Issue by civodulab** [edrlab/thorium-reader#1605]
Tested on a .png and .jpg image.
Sepia theme
![image](https://user-images.githubusercontent.com/24477170/146365985-c2d6ea7f-f919-43d4-a809-3545c9f729b5.png)
Night Theme
![image](https://user-images.githubusercontent.com/24477170/146366048-22907def-523b-43b4-9aee-96f54e4a6647.png)

**Comment by danielweck** [comment]
Hello, I think this is why:

https://github.com/readium/readium-css/blob/583011453612e6f695056ab6c086a2c4f4cac9c0/css/src/modules/ReadiumCSS-night_mode.css#L49-L72

**Comment by danielweck** [comment]
I transferred the issue to: https://github.com/readium/readium-css/issues/114
