### ISSUE TITLE
Import font : lost focus

### ISSUE THREAD

**Issue by civodulab** [edrlab/thorium-reader#1609]
When you type the name of a font, the focus goes away when it updates the name and the style.
Suggestion: Make the computer fonts appear in the list.
![image](https://user-images.githubusercontent.com/24477170/147054517-c8e711ed-c861-40b6-ba9f-995380aa14d0.png)

**Comment by danielweck** [comment]
I am unable to reproduce this in Thorium 2.1.0. Closing.
