### ISSUE TITLE
[audio mp3] Doesnt work in Mac and Win Thorium - V.1.7.3

### ISSUE THREAD

**Issue by dualpixel-digital** [edrlab/thorium-reader#1612]
Hi, everyone

Please, let me know if anyone else had this problem with MP3 files used in EPUB 3

In attached I send some prints
Sigil - with two different way to apply audio tag
Browser - I have tested from unzipped EPUB and preview HTML directly in Chrome. Works fine the audio file
Thorium - Dont have preview to audio file. Video file (MP4) works fine

![sigil](https://user-images.githubusercontent.com/55760305/148117566-336c580d-1744-4c16-a61f-f2fdaf825d5a.png)
![Browser](https://user-images.githubusercontent.com/55760305/148117573-37d51303-d22e-4784-a89b-84f5549c4f0b.png)
![thorium](https://user-images.githubusercontent.com/55760305/148117575-e0579f59-9b2a-4db6-aef3-4858ab605dae.png)

Here the link to downlioad the EPUB file
https://www.dropbox.com/t/Qv4cx3YiuYfTDXDu

All the best

**Comment by danielweck** [comment]
Hello, I am sorry for the late reply. In fact the DropBox link has just expired earlier today!! (before I had a chance to download the test file)
Could you please test again with Thorium's latest official build version 1.8.0 https://github.com/edrlab/thorium-reader/releases/tag/v1.8.0

**Comment by dualpixel-digital** [comment]
Hi, Thanks a lot for replay

I updated the Thorium but, the issue continues the same.

Here the EPUB file

https://www.dropbox.com/t/XJ1uPLoK2QyLRGUK

All the best

**Comment by danielweck** [comment]
Ah, this is a bug in ReadiumCSS: https://github.com/readium/readium-css/issues/94

I implemented a workaround, I will report back here when I am done testing.

**Comment by dualpixel-digital** [comment]
Hi,
Thanks!
Audio OK in this release!

Great

Att,
--

*Felipe Santos**Dualpixel Treinamentos e Serviços Digitais*

Acesse: www.dualpixel.com.br
Curta: www.facebook.com/dualpixel.cursos
Assista: DualpixelClass
<https://www.youtube.com/playlist?list=PL47ISohHocDkxhjXNIAqRXru3ba1PxPGC>
***@***.***_digital <https://www.instagram.com/dualpixel_digital/>
Ligue: (21) 2042.0922
*WhatsApp-me: (21) 98577-4875*



Em qui., 13 de jan. de 2022 às 16:37, Daniel Weck ***@***.***>
escreveu:
