### ISSUE TITLE
No audio controls for embedded wav files in 1.8.0 release

### ISSUE THREAD

**Issue by clapierre** [edrlab/thorium-reader#1615]
Regression.
This worked previously.
Here is a link to the DIAGRAM report where the Sonfication Chapter 3.5 has embedded audio which no longer shows the controls to play the audio.

[DIAGRAM_Center_2017-2020_Reports.epub](https://benetech.box.com/s/n4led18zyri0vhwlusnqpvuelbo7uvwv)

**Comment by clapierre** [comment]
Was incorrect EPUB, working fine.

**Comment by PedalHoppy** [comment]
This is happening to me - did you make a change in your file to get it to work?

**Comment by danielweck** [comment]
Hello @PedalHoppy this should work "out of the box" in Thorium now, there was a CSS bug in an older version. I have just checked Charles' EPUB (download link in his original post) with the latest official Thorium release (version 2.2) as well as with the latest build from our codebase.

**Comment by PedalHoppy** [comment]
Great thank you I was on 1.8 so I guess I will update first and see if that
solves it.

**Comment by PedalHoppy** [comment]
Nope that didn't do it - I just have a blank space where my player controls
should be.

**Comment by danielweck** [comment]
Would you mind privately sharing your EPUB please? ( daniel.weck@gmail.com )

**Comment by danielweck** [comment]
Thank you @PedalHoppy I have just pushed a fix, the automated build should be ready in a few minutes:
https://github.com/edrlab/thorium-reader/releases

The bugfix is a CSS override to ensure that width/height values for the HTML5 audio controls are reset to their original values (there is a weird CSS bug where the 100% height is collapsed to zero in some cases)

**Comment by PedalHoppy** [comment]
Awesome, thanks!
