### ISSUE TITLE
Text overlapping with 1.8.0 Regression Issue

### ISSUE THREAD

**Issue by clapierre** [edrlab/thorium-reader#1617]
I have a book from a Canadian Publisher where the text is now overlapping with the 1.8.0 release

Here is a screen shot with 1.7.3 version
![Screen Shot no text overlapping](https://user-images.githubusercontent.com/7736749/148811105-d3e7d8ab-788d-4e1d-8dbe-4b99d9a9f92d.png)

Here is the same page with 1.8.0
![Screen Shot text overlapping](https://user-images.githubusercontent.com/7736749/148811130-fee66ccb-2af3-42af-9edd-a4caf95260af.png)

**Comment by danielweck** [comment]
Hello Charles, this is a first! Would you mind sharing the EPUB? Thank you, Daniel

**Comment by danielweck** [comment]
Thank you for privately sharing the EPUB.

This is an authoring issue. There is a proprietary Apple file `META-INF/com.apple.ibooks.display-options.xml` that defines `<option name="fixed-layout">true</option>` but the standard OPF XML does not declare `<meta property="rendition:layout">pre-paginated</meta>` (see https://www.w3.org/publishing/epub3/epub-packages.html#layout ). The CSS styles do not correctly specify the width and height of the body. The viewport `meta` is not defined either (see https://www.w3.org/publishing/epub3/epub-contentdocs.html#sec-fxl-icb-html ).

Even Apple's own Books.app reading system (on MacOS) displays the text incorrectly, there are no margins, and the text is clipped.

My gut feeling is that this publication shouldn't be fixed layout at all.

I am closing this issue, but please feel free to post again and we will follow-up if necessary :)
Thank you for your feedback!

**Comment by danielweck** [comment]
I confirm that once the file `META-INF/com.apple.ibooks.display-options.xml` is removed, the publication renders fine.

**Comment by danielweck** [comment]
Screenshot of non-fixed layout rendition (Charles, this matches your own screenshots so I don't think I am making any "faux pas" regarding potential copyright issues):

<img width="1440" alt="Screenshot 2022-01-13 at 18 32 15" src="https://user-images.githubusercontent.com/625201/149388889-87c5d4a1-a88a-447f-80fa-25ef9c3acc43.png">

**Comment by clapierre** [comment]
Thanks Daniel, we will let the publisher know their mistake, and look for this in the future!
