### ISSUE TITLE
LCP: up-to-date license download when not required

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1618]
I have a license issued on:   
    `"issued": "2022-01-10T13:49:36Z",`

The status document has the following dates : 
    `"updated": {
        "license": "2022-01-10T13:49:36Z",
        "status": "2022-01-10T13:49:36Z"
    },`

As per the spec, the up-to-date license should not be downloaded, but it still seems to be fetched. I think it is because the up-to-date license is currently invalid and Thorium (1.7.3 and 1.8) goes into an infinite loop. I may be wrong but ...

I'll pass the license to the core developers ...

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/commit/f35ea3c6b69b248a22acdc5cbae80bcf90f17c53
