### ISSUE TITLE
Navigating back from a in-publication hyperlink jump (footnotes, etc.) - nav history? (back + forward buttons / keyboard commands)

### ISSUE THREAD

**Issue by spudthebud** [edrlab/thorium-reader#1624]
Using the JAWS screen reader (2021) with Thorium 1.8 to read an academic journal article, I encounter a problem.

The article has a table in the main text and a link to a table, as shown in this next image. 

![image](https://user-images.githubusercontent.com/8799391/150446623-c92025db-6eb2-4075-b3a0-d38077e1fb9b.png)

When I activate the table link, it appears in the visual interface that Thorium is presenting the table all on its own (see the image below). If this were a browser, it's like we've gone to a separate page the just shows the table.  There's nothing wrong with this.  

The problem is I can't get back to the main article. I try ALT + Left, which works in a browser, but no luck. Now I'm stuck on that page that only has the table.

I finally managed to get back by going to the Table of Contents and then clicking the abstract button. But that's really not intuitive, from my point of view.   It took me a while to figure it out after some exploring because "table of contents" only appears after pressing the navigation toggle button.

![image](https://user-images.githubusercontent.com/8799391/150446202-9bbe7fc6-8cd7-4be0-a8f7-114b27f6575f.png)

**Comment by danielweck** [comment]
Hello, you are correct, there is not "back" button (and its counterpart the "forward" button) like there is in web browsers. Therefore, when EPUB HTML documents are not authored with "back links" from footnote content or other types of hyperlinked notes, then the user must find their way back (not a good UX).
@panaC it looks like we should reactivate your pending / in-review Pull Request: https://github.com/edrlab/thorium-reader/pull/1200

**Comment by spudthebud** [comment]
Is there any kind of example ePub or test document that has back links that I could try out?

**Comment by danielweck** [comment]
You can try the Wasteland EPUBs from: https://idpf.github.io/epub3-samples/30/samples.html

Example HTML code:

- Note link:

https://github.com/IDPF/epub3-samples/blob/0b3e80553f509fbdfe591008cd7d1e804b24db54/30/wasteland-otf-obf/EPUB/wasteland-content.xhtml#L183-L184
```html
<div id="ln98">As though a window gave upon the sylvan scene<a epub:type="noteref" class="noteref" href="#note-14">*</a>
</div>
```

- Note content (with back link):
- 
https://github.com/IDPF/epub3-samples/blob/0b3e80553f509fbdfe591008cd7d1e804b24db54/30/wasteland-otf-obf/EPUB/wasteland-content.xhtml#L825-L827
```html
<div epub:type="rearnote" id="note-14">
<p><a href="#ln98">98.</a> Sylvan scene. V. Milton, Paradise Lost, iv. 140.</p>
</div>
```

Conversely, the Georgia EPUB does not contain backlinks, but in Thorium when the popup footnotes feature is activated note contents are displayed in a modal dialog which, when closed, restores the reading location at the calling site (i.e. note link). Here is a link to Georgia's HTML document (search for keyword "noteref" to find relevant hyperlink markup): https://github.com/IDPF/epub3-samples/blob/main/30/georgia-pls-ssml/EPUB/georgia.xhtml

**Comment by danielweck** [comment]
From https://github.com/edrlab/thorium-reader/issues/1198

When one follows an hyperlink in an EPUB that takes you, for example, to the glossary at the end of the book, there is not "back" button to take you where you were before clicking on hyperlink. This is very annoying.

**Comment by danielweck** [comment]
Issue was merged into https://github.com/edrlab/thorium-reader/issues/1198

**Comment by danielweck** [comment]
Was fixed via https://github.com/edrlab/thorium-reader/commit/a407d1669bde9dc904ce640150a5ab148976f12a
