### ISSUE TITLE
[Windows] can't build on Windows, divina-player tarball corrupted.

### ISSUE THREAD

**Issue by the-drunk-coder** [edrlab/thorium-reader#1625]
Hi,

I've been trying to build the thorium-reader (latest develop branch) on MS Windows (10/11), and it fails with the following error:

```
npm WARN tarball tarball data for
divina-player-js@git+ssh://git@github.com/readium/divina-player-js.git#4e1f859afb14b916923ec136af0284a72e22a990
(sha512-S3lZZVKHVDWfiEQpzeN1BrqxMTX9jbMAweIVsQjjbsJDDs72Y3gQMCiSLkREuhSjU4RyqeHklFOPO9CFCNNn4A==)
seems to be corrupted. Trying again.
```

I've tried `npm cache clean --force` and `npm cache verify`, but to no avail.

Curiously this doesn't happen on macOS, where I can build without problems.

I've been trying with the same node versions (node 16.13.2, npm 8.1.2) on both machines.

Does anyone have a hint for me?

Best,
N

**Comment by danielweck** [comment]
By the way, this is documented in the README: https://github.com/edrlab/thorium-reader/blob/develop/README.md#install-dependencies

**Comment by the-drunk-coder** [comment]
Thanks for the quick reply, sorry I missed that line 😅
