### ISSUE TITLE
keyboard characters y and n for yes/no cannot be used to eg. delete a book form My Books?

### ISSUE THREAD

**Issue by MyDK** [edrlab/thorium-reader#1635]
I cannot use 'y' and 'n' for 'yes' and 'no'?
In My Books view -  I choose the action button next to the cover img and 'Delete'
![image](https://user-images.githubusercontent.com/30153047/152535044-2d0ada82-43e3-4cf7-a18c-c8659736c1cc.png)
The delete window now opens:
![image](https://user-images.githubusercontent.com/30153047/152535273-7313b4af-ceab-4b5b-bdcc-2d9957c70bbe.png)
If I type 'y' now with my ordinary keyboard, I would think the file was deleted - but this doesn't happen. 
Instead keybord focus is activated and fixed on the close button, it seems. And I have to tab two times before focus sets on the 'yes' activation button and I can delete the file with enter.
Just an observation.

**Comment by llemeurfr** [comment]
There is a localisation issue if we decide to sue 'y' / 'n'.

**Comment by danielweck** [comment]
We will implement clearer ENTER focus outline (yes by default)

**Comment by danielweck** [comment]
We decided not to implement character key mnemonics due to complexity of multilingual labels (e.g. translated `yes` / `no` and their associated `y` / `n` quick access keys), but instead we fixed the behaviour of `enter` key (default form submission)
