### ISSUE TITLE
Missing option: space between paragraph

### ISSUE THREAD

**Issue by riiski** [edrlab/thorium-reader#1643]
When creating EPUB file I usually make some spacing on paragraphs with CSS margin-top or margin-bottom features. However Thorium on Desktop shows no spacing between paragraphs. 
I have read some Thorium code and I found that space between paragraphs is set to 0 initially. Is there any other option to create spacing with CSS?
As for Thorium, I think paragraph spacing option in setup should be available. For now it is just spacing between lines and characters here: 
![2022-02-24 08_06_25-Thorium - E  Knygos visiems_ Prieinamos skaitmeninės leidybos ekosistema](https://user-images.githubusercontent.com/7087900/155468897-45e39a4f-e43e-44a8-ab5a-a371d946c9f1.png)

**Comment by danielweck** [comment]
What version of Thorium are you using? The paragraph spacing is available, see screenshot:

<img width="1552" alt="Screenshot 2022-03-01 at 15 28 03" src="https://user-images.githubusercontent.com/625201/156197689-acee8727-74d5-412a-b223-42bef6c66390.png">

**Comment by danielweck** [comment]
The "paragraph spacing" user interface control was introduced in version 1.6 (one year ago):

https://github.com/edrlab/thorium-reader/releases/tag/v1.6.0

https://github.com/edrlab/thorium-reader/blob/develop/changelogs/CHANGELOG-v1.6.0.md

**Comment by danielweck** [comment]
I have closed the issue, but please feel free to post further comments if you are still experiencing problems with the latest version of Thorium :)
