### ISSUE TITLE
Notification toasts cover sidebar controls

### ISSUE THREAD

**Issue by elcste** [edrlab/thorium-reader#1644]
I've noticed that the notification toasts cover the sidebar controls. ("Sidebar" may not be the right word you use, but I mean the right side panel that includes things like the table of contents and settings.) For example, I often add or remove a bookmark, and then try to navigate using the table of contents, but the sidebar is covered up by the toasts making it hard to do:

![thorium-toast](https://user-images.githubusercontent.com/915687/155732003-58294c75-7dd3-404b-99aa-c4fb97a8ee66.png)

My suggestions:
- Move the toasts to be positioned just to the left of the sidebar
    - Possibly only when the sidebar is open?
- Or perhaps the toasts can be centered on the screen
    - This would only help with wide windows

**Comment by danielweck** [comment]
Thank you for filing this bug report. We agree, notification "toasts" should not obscure the user interface as they do now.

**Comment by danielweck** [comment]
Until a more complete toast design refresh (e.g. native OS notification), here is a UI improvement: added keyboard focus and mouse click handling (clipboard copy of message), overflowing text is now clipped, and the vertical toast stack is now re-positioned in lower-left corner of the application window (library and reader windows).
