### ISSUE TITLE
SAPI 5 TTS does not show up in Thorium v1.8.0

### ISSUE THREAD

**Issue by riiski** [edrlab/thorium-reader#1648]
Hi,
I tried v1.5.0 and it works (but I cannot select from the list) and reads in the language of the text. On v1.8.0 it does not show up in the list and by default tries to read in the language that is set by default on windows TTS. I use Windows 11.
This is the screen from v1.8.0. I can't select other TTS engines, only Windows TTS are available with what I have installed lately (EN and CZ):
![2022-03-02 08_17_48-Get Thorium Reader - Microsoft Store– „Google Chrome“](https://user-images.githubusercontent.com/7087900/156307843-7790f0f5-d69d-4acd-b33a-a3b7ea980dc3.png)

And this is screen of v1.5.0. It does not show list to select a TTS and it reads text in Lithuanian TTS. Text is also in Lithuanian language:
![2022-03-02 08_25_18-Thorium - E  Knygos visiems_ Prieinamos skaitmeninės leidybos ekosistema](https://user-images.githubusercontent.com/7087900/156307882-88d2df90-3ba6-449c-88cf-c7a7a6e2bf12.png)

**Comment by danielweck** [comment]
Thorium doesn't explicitly implement the TTS voice selection strategy, it relies entirely on the Chromium (web browser engine) Web Speech API which itself depends on the underlying operating system's technical exposition of voices (e.g. SAPi5)

As you have discovered, Microsoft Windows imposes an "artificial" limitation on the OneCore voices, as documented / described in other discussion forums. See related issues:

https://github.com/edrlab/thorium-reader/issues/1130#issuecomment-817209138

https://github.com/edrlab/thorium-reader/issues/1542#issuecomment-922020575

I am glad you found the regedit / registry trick.
I am closing this issue as this is not an actionable bug report in Thorium, but feel free to add further comments, please :)

**Comment by k-kolev1985** [comment]
So, am I to understand, that we cannot use SAPI5 in Thorium? Because for me only OneCore voices show in Thorium.

**Comment by riiski** [comment]
@k-kolev1985 It is usable. Configuration is the problem here.
