### ISSUE TITLE
[suggestion] Improve layout TOC

### ISSUE THREAD

**Issue by dualpixel-digital** [edrlab/thorium-reader#1656]
Hi,
I would like to make a suggestion for displaying the TOC.
I find the alignment of each item and the use of the gray box a little confusing, which is very spaced.

As an example I leave the summary of ADE

All the best
![toc copiar](https://user-images.githubusercontent.com/55760305/158850488-fa168400-3631-4c9b-a0c9-da3c348986ea.jpg)

**Comment by danielweck** [comment]
hello, I agree with you, the "tree"-like nature of the table of content (hierarchical list) is lost in its current visualisation style. I think the inconsistent text alignment adds to the confusion.

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/commit/c00764d46167c96633601b8d072b7360e0cc2abe
Note that the TOC hierarchical tree view remains "static" (i.e. no folding/expanding of tree nodes) as the component is included in an "accordion" type view which is already expandable (nested layout).
So this fix is an improvement but can be improved in future iteration. Feedback welcome.
