### ISSUE TITLE
[macOS] App icon is too big

### ISSUE THREAD

**Issue by huylv** [edrlab/thorium-reader#1664]
I just found out about Thorium reader. Clean and snappy, love it very much! Just a small thing is that the icon is a little too big.
<img width="544" alt="image" src="https://user-images.githubusercontent.com/2832672/161964653-65cd3e83-7981-4914-acdd-bf8b11b584d7.png">

**Comment by panaC** [comment]
https://www.electron.build/icons.html#macos

`Optional icon.icns (macOS app icon) or icon.png. Icon size should be at least 512x512.`

so I don't  know why the icon appears too big. Why MacOs doesn't scale the icon on the dock ?

**Comment by panaC** [comment]
I regenerate the icon thanks to cloudconvert.com 

before `file icon.icns` : 
`resources/icon.icns: Mac OS X icon, 1195351 bytes, "ic12" type` 

now `file icon.icns` : 
`resources/icon.icns: Mac OS X icon, 482529 bytes, "ic10" type` 

ic10 appear to be right format
https://fr.wikipedia.org/wiki/Apple_Icon_Image

**Comment by huylv** [comment]
Hi, is this issue really fixed? I just upgraded from 2.2.0 to 2.3.0 today and the icon is still exactly the same.

**Comment by danielweck** [comment]
Re-opening this issue, probably fixed by https://github.com/edrlab/thorium-reader/pull/2453
