### ISSUE TITLE
New Library view: fewer columns? 

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1666]
The new library view displays (and allows filtering among) different properties, currently 
- Title
- Author
- Language
- Tags
- Publisher
- Published on
- DRM
- Duration
- Description
- More information (a11y)

The table is therefore large, much more than a 13" screen. 

I propose to remove from this table (display and filtering) the following columns:
- Publisher
- Published on
- DRM
- Duration
- Description
- More information
Such information is, IMO, better placed in the ebook info panel.
But this is open to discussion before we release v2.0.  

What I thing is missing in this UX is:
- Type of publication -> ebook, audiobook
This information could be added as a small set of checkboxes before the table. 

There is also an open question about the interest of filtering by:
- Format of publication -> EPUB, DAISY, PDF, Divina, Audiobook

Note 1: a pure faceted filtering, like what is proposed by OPDS, is not possible with the component we're now using.  

Note 2: we won't add to the Thorium UX detailed accessibility filtering capabilities, like filtering reflowable vs fixed layout, access mode sufficient textual vs audio ... such filters are useful at the time a user buys / borrows an ebook, not anymore inside his reading app.

**Comment by llemeurfr** [comment]
After discussion with Daniel, we are thinking about 2 modes; simple and advanced. 
In the simple mode, the number of columns is restricted. Title, Author, Tags are there, a Last Reading Date. The addition of Language is open (depends on what space is available on a 13" screen). 
The Advanced mode is more analytical. 

The top icons, Grid and List, will have to be changed for a set of Simple and Advanced icons. It will be in a 2.1, as these are new labels to be localised

**Comment by danielweck** [comment]
Fixed via:
* https://github.com/edrlab/thorium-reader/commit/24ba9e21b6e5a10c518ba18a373904265c800856
* https://github.com/edrlab/thorium-reader/commit/2c4f2baa65d88a3978b1533daf4d862a2b4f5714
*
