### ISSUE TITLE
Unpredictable Jumps

### ISSUE THREAD

**Issue by psygo** [edrlab/thorium-reader#1675]
I'm using Thorium for a while and overall it's a great piece of software. However, there's a strange piece of behavior that bugs the shit out of me. Every time I switch programs, e.g. for taking notes, Thorium snaps back to the beginning of text &mdash; or a bookmark, but I'm not 100% sure.

In the video below, you can see an example. I basically switch back and forth between programs and things snap back up to the beginning of the chapter.

https://user-images.githubusercontent.com/11823725/163689291-37d30e32-c3f8-403a-a791-edcaa89de58e.mp4

One way I was able to get around that for some time was by clicking with the mouse on the page arrows, instead of using the keyboard arrows. Somehow Thorium was then understanding the click to recreate a bookmark for its scrolling mechanism? This seems to only work in a paginated view though. And it has the plus side of having to click with the mouse only once, the next clicks can be the keyboard arrows themselves.

**Comment by danielweck** [comment]
Hello, I managed to reproduce the bug in paginated mode when ALT-TAB in and out of Thorium's window (focus reset). I fixed the issue, thank you for reporting it! :)

**Comment by psygo** [comment]
Is the fix already available?

**Comment by danielweck** [comment]
Yes it is: https://github.com/edrlab/thorium-reader/releases/tag/v2.0.0
