### ISSUE TITLE
CSS colored background combi bug

### ISSUE THREAD

**Issue by MyDK** [edrlab/thorium-reader#1677]
My EPUB 3 publication uses some CSS on the 'body' tag and the 'section' tag, but Thorium does NOT present a colored background as I expected. So, I think there is a lack of support of some specific css combinations. My publication stylesheet is built upon Jiminis blitz styles which strips out a lot of default reader behaviour, so this might be the reason.
Here is how the EPUB publication is being presented by 3 different readers:

(1) As seen in **Thorium** Reader (wrong):
![ex-thorium](https://user-images.githubusercontent.com/30153047/164206931-1e0fa61d-3bbb-412b-9263-b7bc663366b5.PNG)

(2) In **Colobrio** web vanilla (correct):
![ex-colobrio-web-vanilla](https://user-images.githubusercontent.com/30153047/164206188-a11a0d2c-1b46-4eb7-9b73-28155648e41b.PNG)

(3) In **Adobe Digital Editions** (correct):
![ex-ade](https://user-images.githubusercontent.com/30153047/164206159-fcadda60-4f82-45c6-913d-571a7e5e9466.PNG)

And here is the neutral **file** (I have zipped the .epub) free of copyright contents, so you can see the css: 
[thorium-css-samplefile.zip](https://github.com/edrlab/thorium-reader/files/8520588/thorium-css-samplefile.zip)

**Comment by MyDK** [comment]
Oh! my css needed some **jigsaw** clean up!! Sorry!
Here is the file with a valid CSS file. Still same result after I removed duplicate rule and changed 'dimgrey' to a # color

[thorium-css-samplefile-better-css.zip](https://github.com/edrlab/thorium-reader/files/8520814/thorium-css-samplefile-better-css.zip)

**Comment by danielweck** [comment]
Hello, I tried your sample EPUB in Apple's Books.app, see the attached screenshot. Is this the expected rendering?

<img width="1378" alt="Screenshot 2022-04-21 at 13 03 02" src="https://user-images.githubusercontent.com/625201/164454200-728dded6-97fe-42f9-872c-60cfc6552e7d.png">

**Comment by danielweck** [comment]
Note that the `height: inherit` trick used for issue https://github.com/edrlab/thorium-reader/issues/1658
affects this too:
<img width="1032" alt="Screenshot 2022-04-21 at 13 07 00" src="https://user-images.githubusercontent.com/625201/164454786-64b67e07-12f8-4075-be48-5dffed483a43.png">

**Comment by MyDK** [comment]
> Hello, I tried your sample EPUB in Apple's Books.app, see the attached screenshot. Is this the expected rendering?
> 
> <img alt="Screenshot 2022-04-21 at 13 03 02" width="1378" src="https://user-images.githubusercontent.com/625201/164454200-728dded6-97fe-42f9-872c-60cfc6552e7d.png">
> 
> <img alt="Screenshot 2022-04-21 at 13 04 30" width="892" src="https://user-images.githubusercontent.com/625201/164454308-21a71aa6-9713-4bfa-a009-b92b79ed9177.png">

No. I expected grey color to cover the whole screen.

**Comment by danielweck** [comment]
Here we do again: https://github.com/edrlab/thorium-reader/issues/1824

**Comment by VijayShankar1** [comment]
if we provide a color in the body tag, than the whole background screen need to be have color. But in 2.1.0, scrollable view the landing screen only have colors, the area below the landing screens, don't have the background color. https://github.com/edrlab/thorium-reader/issues/1824
