### ISSUE TITLE
Thorium doesn't keep size in header tags (h1-h6)

### ISSUE THREAD

**Issue by dualpixel-digital** [edrlab/thorium-reader#1678]
Hi,

I have one more improvement/fix suggestion for the next release.

I have an alpha version of version 2, with debug option.

I would like to understand why Thorium doesn't respect the font-size value, in space in the h1-h6 tags?

Note the difference between the desired result (Readium) and the result of Thorium

Is there a best formatting practice in CSS to ensure text sizes are recognized?

![thorium-Title](https://user-images.githubusercontent.com/55760305/165653241-b25a0160-39d5-4337-b761-a370b64f641e.jpg)

![readium-Title](https://user-images.githubusercontent.com/55760305/165653244-932f02f7-274f-4764-8578-f83dfeab869d.jpg)

![DebugMode-Thorium](https://user-images.githubusercontent.com/55760305/165653245-33a0c537-04d7-4255-86d3-c91c297e2965.jpg)

**Comment by danielweck** [comment]
Thank you for reporting this issue. This is actually a known problem with ReadiumCSS, so I merged the issue there:
https://github.com/readium/readium-css/issues/112
