### ISSUE TITLE
simple telemetry on Thorium

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#1686]
We are going to implement a simple telemetry at application startup to send the hardware architecture, the os version, an application opening counter and the locale used.

This request is executed in startup phase of the application and has no impact on user experience and privacy.

On our side : we will collect these four data values in a sql table to create annual analytics.

To be defined:
 - application opening counter : 
   - reset at first January of the new year : it allows to create a gaussian of the use of Thorium reader by user.
 - os version and architecture : 
   -  useful to know the distribution of machines used
- telemetry https url : 
   - http request on https://telemetry.edrlab.org that goes to an EDRLab cloud function hosted on the GCP platform

**Comment by danielweck** [comment]
VIsual Studio Code (Electron app) uses https://github.com/microsoft/ApplicationInsights-node.js
Clearly overkill API surface, given Thorium's minimalistic use-case ... but worth mentioning nonetheless (they have open-source JS code to correctly extract OS information, GeoIP, Locale, etc.).

**Comment by danielweck** [comment]
Good read (French): https://www.cnil.fr/fr/cookies-et-autres-traceurs/regles/questions-reponses-sur-les-mises-en-demeure-de-la-cnil-concernant-lutilisation-de-google-analytics

**Comment by danielweck** [comment]
Informative article: https://blog.blether.chat/2022/08/03/gdpr-for-developers-by-example/
