### ISSUE TITLE
shelfs

### ISSUE THREAD

**Issue by aabotaiban** [edrlab/thorium-reader#1689]
how to create shelfs

**Comment by danielweck** [comment]
Hello, Thorium does not have a "customisable bookshelf" feature, but you can use the "tags" feature to add any number of arbitrary text labels for your chosen publications, which you can then use to filter the list of publications based on certain keywords. For example, you can combine tags to search for books that match "fiction" + "horror".

**Comment by danielweck** [comment]
PS: the latest official release is version 1.8, but there is a new bookshelf "table / grid" feature in the upcoming version 2.0, which you can already try from:
https://github.com/edrlab/thorium-reader/releases
