### ISSUE TITLE
Footnotes in text

### ISSUE THREAD

**Issue by dazrand** [edrlab/thorium-reader#1690]
Version 1.8.0 - does this version no longer hide properly formatted footnote in the regular text flow?  Have tried with Disable Footnotes checked and unchecked, but they always appear.

**Comment by danielweck** [comment]
Hello, the logic hasn't changed between versions, so this sounds like a bug. However, I would need to check with a problematic EPUB, are you able to share a file with me? (privately, if necessary)

**Comment by danielweck** [comment]
Note that footnote contents are hidden only if they are contained within an `aside` element, if I remember correctly.

Example:

https://github.com/IDPF/epub3-samples/blob/0b3e80553f509fbdfe591008cd7d1e804b24db54/30/georgia-cfi/EPUB/georgia.xhtml#L523-L526

https://github.com/IDPF/epub3-samples/blob/0b3e80553f509fbdfe591008cd7d1e804b24db54/30/georgia-cfi/EPUB/georgia.xhtml#L19

Counter example:

https://github.com/IDPF/epub3-samples/blob/0b3e80553f509fbdfe591008cd7d1e804b24db54/30/wasteland/EPUB/wasteland-content.xhtml#L742-L760

https://github.com/IDPF/epub3-samples/blob/0b3e80553f509fbdfe591008cd7d1e804b24db54/30/wasteland/EPUB/wasteland-content.xhtml#L56-L58

**Comment by danielweck** [comment]
Hello, I managed to reproduce the bug and I fixed it. Thank you for reporting the issue! :)
