### ISSUE TITLE
Test Thorium against new W3C tests

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1691]
Members of the W3C EPUB WG are creating a suite of test files for EPUB 3.3. They are maintained in https://github.com/w3c/epub-tests. 

Some tests don't pass on Thorium, see https://www.youtube.com/watch?v=Y9JNuofCGPA. 

It is time to pass the test suite on Thorium and report. It would also be good to test iBooks at the same time ;-)
We will choose to update Thorium is some cases, choose to remain non-compliant in other cases (so that some EPUB feature are deprecated), or ask for some modifications of the test suite in other cases (the tests are still WIP).

**Comment by danielweck** [comment]
Related PR at W3C GitHub: https://github.com/w3c/epub-tests/pull/157

**Comment by gautierchomel** [comment]
[Tests are located here](https://github.com/edrlab/thorium-reader-epub-tests/)

**Comment by gautierchomel** [comment]
Issue too general. Closing, will reopen atomic actionable issues.
