### ISSUE TITLE
When pressing open fullscreen mode, settings and navigation should close

### ISSUE THREAD

**Issue by elcste** [edrlab/thorium-reader#1699]
When pressing **open fullscreen mode**, **settings** or **navigation** should close if one is open because

* they are invisible in fullscreen mode
* but if one is open, then keyboard shortcuts for turning pages do not work.

I open find myself navigating using the ToC or bookmarks, or changing the theme, and then I open fullscreen mode to read but get "stuck" once I finish the page.

**Comment by elcste** [comment]
I see now this was mentioned (https://github.com/edrlab/thorium-reader/issues/1197#issuecomment-703870973), but it's not that bug's specific point.

**Comment by panaC** [comment]
good point !

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/blob/03b16f62c25351d7f0ffcb9281f28d58d0b46474/src/renderer/reader/components/Reader.tsx#L2086-L2088

https://github.com/edrlab/thorium-reader/blob/03b16f62c25351d7f0ffcb9281f28d58d0b46474/src/renderer/reader/components/Reader.tsx#L1778-L1785

**Comment by elcste** [comment]
Just tested and works great in the dev version! Merci !

I only wish I suggested it before the version 2.0 release :-)
