### ISSUE TITLE
OPDS catalog view should inform wich book is already downloaded

### ISSUE THREAD

**Issue by gautierchomel** [edrlab/thorium-reader#1703]
While browsing an OPDS catalog we have no information about books from the feed already downloaded and present in local catalog. 

If importing a file already in the local catalog, download process happens (download bar appears) then we get a notification _FileName was already imported_

A basic information should be given about books already downloaded.

**Comment by danielweck** [comment]
Yes, it is very frustrating not being able to cross-reference from the local bookshelf to the originating OPDS feed (if any), and vice-versa.

**Comment by panaC** [comment]
How to do that ? 

- with the acquisition links ? 
- with the publication uuid ? 
- with a publication hash ?
