### ISSUE TITLE
[question] where does thorium in linux actually save the book files ?

### ISSUE THREAD

**Issue by cocoonkid** [edrlab/thorium-reader#1713]
[question] where does thorium in linux actually save the book files ?

I tried to find it in the users home and in /opt/ but to no avail.
 

Installed with **https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=thorium-bin**

**Comment by panaC** [comment]
https://www.electronjs.org/fr/docs/latest/api/app#appgetpathname

check 'userData'
https://github.com/edrlab/thorium-reader/blob/fec61ed371d1616bfd0d230b5b072cd7e5b3970d/src/main/di.ts#L57

**Comment by gautierchomel** [comment]
On Debian 11 I found it at "Home/.config/EDRLab.ThoriumReader.
Hidden files have to be displayed.

![image](https://user-images.githubusercontent.com/107039498/174602390-51a0eb98-5640-44c8-a531-fab052c7db34.png)

**Comment by panaC** [comment]
`~/.config/EDRLab.ThoriumReader`

**Comment by cocoonkid** [comment]
Thanks so much...I must have made a mistake that neither find nor fd found it...
