### ISSUE TITLE
MathJax does not works on Debian 11

### ISSUE THREAD

**Issue by gautierchomel** [edrlab/thorium-reader#1714]
On Debian 11 with MathJax installed (all those packets : https://packages.debian.org/sid/source/mathjax) and MathJax option ticked in Thorium I can't get correct display. Am I missing something?

![image](https://user-images.githubusercontent.com/107039498/174623505-968958ad-b664-466c-a647-56f5641787aa.png)

**Comment by danielweck** [comment]
Hello, Thorium ships the MathJax library, no need to install it externally.
Could you please link to the EPUB test?
(have you tried on Windows and MacOS?)

**Comment by danielweck** [comment]
Hello Gautier, could you please confirm that you are able to reproduce this bug with Thorium's latest build:
https://github.com/edrlab/thorium-reader/releases/tag/latest-linux

**Comment by danielweck** [comment]
Okay so I think I know what the problem is (the MathJax NPM dependency broke during the Linux production build). I will check...
