### ISSUE TITLE
image zoom: allow additional zooming

### ISSUE THREAD

**Issue by pkra** [edrlab/thorium-reader#1719]
The image zoom in v2 (#1160) creates an overlay with the image alone. The image dimensions appear to be (at most) its inherent resolution (or dimensions in the case of SVG).

It would be great if users could to zoom in at this overlay stage.

**Comment by pkra** [comment]
Aside: the [v2 release notes](https://github.com/edrlab/thorium-reader/releases/tag/v2.0.0) state that `ctrl+click` activates the overlay but it seems to be `shift+click` (which I found out via the issue).

**Comment by danielweck** [comment]
I corrected the release notes, thank you!

**Comment by danielweck** [comment]
> It would be great if users could to zoom in at this overlay stage.

That's already possible, using SHIFT-click (if I remember correctly).

That being said, we are totally aware that the UX is currently a bit "wonky", to say the least (plus, additional zooming-in resets the position of the image in the upper left corner, so there are CSS bugs too).
The goal was to release a minimum viable feature that implemented the core mechanics required to "extract" an image into its own modal popup viewport. Through trial and error the SHIFT-click method appeared to be the least disruptive / least likely to introduce regression bugs with respect to other existing functionality.

**Comment by pkra** [comment]
I was going to guess this is due to the file being an SVG, possibly because it has an explicit width and height in its source.  Then again it does seem a little larger.

**Comment by pkra** [comment]
A basic UI (say, just a button with "fill screen") might be helpful for users.

**Comment by pkra** [comment]
Oh! I can repeat shift+click to zoom in.

Sorry for the noise. That was too hard to find out (for me) without guidance from the UI.

**Comment by pkra** [comment]
Ok, two more observations and I promise I'll stop.

* when shift+clicking a user has to hit the image to increase its size. Otherwise, the overlay closes. Is that intentional?
* users with magnifiers can get disoriented when the image jumps away after shift+click to further zoom in in the overlay.
