### ISSUE TITLE
[Ubuntu 22.04] App icon missing

### ISSUE THREAD

**Issue by perara-chen** [edrlab/thorium-reader#1721]
App icon is missing when Thorium is in the Ubuntu dock. But the app icon appears correctly when Thorium is running.

![Screenshot from 2022-07-13 23-04-28](https://user-images.githubusercontent.com/104021043/178785604-98138eb0-7d46-4cf1-a93d-2639791045cf.png)

**Comment by danielweck** [comment]
Duplicate, merging into https://github.com/edrlab/thorium-reader/issues/1241
