### ISSUE TITLE
Daisy book unzipped don't load on Windows 10

### ISSUE THREAD

**Issue by gautierchomel** [edrlab/thorium-reader#1724]
Sample file for testing : https://www.bones.ch/media/downloads-support/M312Ace/manuals/Handbuch_Daisy.zip

Steps to reproduce : 
* Unzip a Daisy book
* With Thorium _Add book_ button select `ncc.html` or `package.opf`

The file won't load. The same book zipped is imported correctly.

Occurs on Thorium 2.0 Windows 10 Pro x64 with Daisy2.0.2 and Daiiy3.

Unzipped Daisy books are correctly imported on OSX and Debian.

**Comment by panaC** [comment]
It should doesn't wors at all on any platforms. how does it works ? very strange

**Comment by panaC** [comment]
okay I understand now specific to daisy with .opf extension : 
https://github.com/edrlab/thorium-reader/blob/3b2c9c5a2babf908613dd54cbf819643c911f035/src/main/redux/sagas/api/publication/import/importPublicationFromFs.ts#L64-L67

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/blob/1a63c2fc6ee5b6a52a94af3a413643dbb3e802aa/src/main/storage/publication-storage.ts#L53-L74

https://github.com/edrlab/thorium-reader/blob/1a63c2fc6ee5b6a52a94af3a413643dbb3e802aa/src/main/storage/publication-storage.ts#L211-L286

@danielweck how does it works ? the daisy book is not fully imported, only the package.opf file ?

**Comment by danielweck** [comment]
the bug only occurs on windows ... I need to launch my virtual machine to check this out (it's a regression, this used to work)

**Comment by danielweck** [comment]
Duplicate: https://github.com/edrlab/thorium-reader/issues/1905
