### ISSUE TITLE
Windows: High-contrast mode: Some elements are not visible

### ISSUE THREAD

**Issue by k-kolev1985** [edrlab/thorium-reader#1726]
### Description
Under Windows, if a high-contrast theme is used, some of the elements in the UI of Thorium Reader are not visible. Examples of such elements are the buttons in the top toolbar and the button with actions for a book. See attached screenshots for examples.

### Steps to reproduce
1. Enable high-contrast mode in Windows 11, by doing the following:
1.1. Open Windows Settings (Windows+I).
1.2. Go to Accessibility ➡ Contrast themes.
1.3. From the "Contrast themes" combo-box, select any dark theme (e.g. "Night Sky").
1.4. Activate the "Apply" button.
2. Launch Thorium Reader.
3. If you don't have any books added, add at least one.
4. Observe how the button with the 3 vertical dots (the one that opens the menu for a book) is not visible.
5. Open for reading one of the added books.
6. Observe how the buttons in the toolbar on the top are not visible.

### Test environment
- Operating system: Windows 11 Pro version 21H2 (build 22000.795), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- Thorium Reader version: v2.0.0, installed from the Microsoft Store.

![2022-07-25_09-21-50](https://user-images.githubusercontent.com/4395934/180727350-e00aae04-a950-4b78-a3c8-b56019709bcd.png)
![2022-07-25_09-23-00](https://user-images.githubusercontent.com/4395934/180727354-3208961b-4fdd-4056-8126-a063f5fc0d17.png)

![2022-07-25_09-24-19](https://user-images.githubusercontent.com/4395934/180727358-b40ffac0-3db9-4b91-9921-1bed1401e664.png)
![2022-07-25_09-24-58](https://user-images.githubusercontent.com/4395934/180727364-5b82dbd9-ae4a-4470-b474-537abb45d465.png)
![2022-07-25_09-24-45](https://user-images.githubusercontent.com/4395934/180727362-c0a8c25c-15f7-47e1-9c9c-098cd30d523a.png)
![2022-07-25_09-23-46](https://user-images.githubusercontent.com/4395934/180727356-7055056f-cd6e-408f-b32b-d6b845c740c1.png)

**Comment by danielweck** [comment]
Duplicate, merging with https://github.com/edrlab/thorium-reader/issues/577
