### ISSUE TITLE
[DAISY][OPDS] What is the mime-type for a zipped daisy file ?

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#1729]
AVH wish to add these zipped daisy file inside an opds api but what mime-type do they need to adopt to meet the spec and open in Thorium ?

**Comment by panaC** [comment]
mime-type list:  https://github.com/edrlab/thorium-reader/blob/5e2dfe569a0915e479f560940b62168ad7e1fe38/src/utils/mimeTypes.ts
mime-type used in Thorium:  parsing https://github.com/edrlab/thorium-reader/blob/5e2dfe569a0915e479f560940b62168ad7e1fe38/src/utils/contentType.ts

**Comment by danielweck** [comment]
let's go for application/zip ... it's not used by other publication formats, and we already handle the generic .zip file extension with the assumption that it is daisy inside (2.02 or 3.0)
alternatively application/daisy+zip ... but this looks too much like a proper standard, which it isn't (as far as I understand)
