### ISSUE TITLE
Publication Search engine

### ISSUE THREAD

**Issue by clebeaupin** [edrlab/thorium-reader#173]
https://github.com/fergiemcdowall/search-index

**Comment by clebeaupin** [comment]
Use streamer to decrypt all data

**Comment by HadrienGardeur** [comment]
Search should return locators as well.

**Comment by panaC** [comment]
Do you mean text search inside publication with streamer search engine?

**Comment by llemeurfr** [comment]
Yes indeed. This is not an urgent task. We'll have first to look for the best search engine for node. Maybe a contributor will help us for this module.

**Comment by llemeurfr** [comment]
The work done by Irteza on Android, using a client side search engine call MarkJS, could be reused. 
Or the sqlite FTS engine when we move to sqlite as database for the project.

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/594

**Comment by danielweck** [comment]
WIP PR: https://github.com/edrlab/thorium-reader/pull/1057
(needs some UI fixes, notably React DOM virtualization or pagination strategy to improve rendering performance when displaying the navigable list of search results)
