### ISSUE TITLE
Swedish is no longer available as a language choice in 2.1.0

### ISSUE THREAD

**Issue by MTMJohan** [edrlab/thorium-reader#1734]
Hi,
Since 2.1.0 it’s no longer possible to choose Swedish in Setting --> “Language Choice”. 
Earlier versions did have it and it seems if you upgrade to 2.1.0 with Swedish selected it will remain as Swedish even though it’s not a selectable option in language setting.
A fresh install of 2.1.0 the default language is English and it’s not possible to chance it to Swedish.

![image](https://user-images.githubusercontent.com/104623707/186863139-84f340e6-acce-4d37-a3e3-53c494a5c8f0.png)

**Comment by llemeurfr** [comment]
Sorry for that Johan, we're looking a it asap.

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/commit/2a069eea14c728279d517b3c8effba079fe1552f#r82278943

**Comment by danielweck** [comment]
thank you Pierre, a stupid mistake on my part, probably copy/paste, sorry!!

https://github.com/edrlab/thorium-reader/pull/1688/commits/2209eea05f60ba7efd0a2f4b939105f27c152ece#diff-f035286f73b5baabb0a193e75e9d09c0ea3daf89ec2ee2bd1979e4fb00c31250
