### ISSUE TITLE
url protocol handling fails on windows 10 & debian 11

### ISSUE THREAD

**Issue by gautierchomel** [edrlab/thorium-reader#1736]
url protocol handling allows to open a file in Thorium from a browser using the thorium:// prefixed url.

url protocol handling not working on windows 10 & debian 11

exemples files : 
1. thorium://streamer.kvmai.com/pub/L3N0cmVhbWVyL21pc2MvZXB1YnMvY2hpbGRyZW5zLWxpdGVyYXR1cmUuZXB1Yg%3D%3D/manifest.json
2. thorium://ngnix-server-ncndadws4q-ey.a.run.app/public/Accessible_EPUB_3.epub
3. https://opds-auth-test-server-aplqpqv3wa-ey.a.run.app/

## On windows

1 and 2 : Catalogs tab view is opened and message is îCannot read properties of indefines (reading 'headers').
![image](https://user-images.githubusercontent.com/107039498/186869641-51060c03-6692-40ea-9b06-a4009b4311b9.png)

3 :  opds is displayed by Firefox, Thorium does not open

## On debian

1 and 2 : Thorium opens but nothing happens. No message is displayed.

3 : opds is displayed by Firefox, Thorium does not open

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/commit/1814b262f2e48324d59b9d3071e2a09a2cf0d5ea
