### ISSUE TITLE
[TTS] “Attack” time of the reader voice is too long

### ISSUE THREAD

**Issue by typopaul** [edrlab/thorium-reader#1816]
When using TTS in Thorium 2.1.0, the first word of a sentence/section is only audible from the second half and sometimes even not at all. It seems, that the screenreader needs some time to ”get started“ to be at full volume. Is this something that can be addressed in the Thorium Application itself?

**Comment by typopaul** [comment]
Additional info: This happens on macOS 12.4.

**Comment by danielweck** [comment]
Hello, Thorium does not explicitly implement sophisticated text to speech features such as volume control, prosody hints, pronunciation rules, etc. Both Thorium's own user interface and rendered third-party HTML content documents are read aloud by screen readers independently. Thorium occasionally supplies explicit semantic hints in its user interface (i.e. the role of certain controls within their component hierarchy) in addition to providing accessible textual labels. Audio glitches in the screen reader output is not something Thorium can address directly, I believe. I am closing this issue to keep the tracker "clean", but of course feel free to continue the conversation if needed, we will receive message notifications.
