### ISSUE TITLE
Fixed layout zoom feature, improve usability, scroll wheel up/down UX

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1825]
From @ImportTaste

https://github.com/edrlab/thorium-reader/issues/1228#issuecomment-1233338893

I would like to point out that using this feature is a bit inconvenient. You have to cycle through the zoom levels all the time by pushing the button, there don't seem to be any hotkeys for it, and there's only 4 zoom levels available: fit to window, 200%, 100%, 50%.

Ctrl + Mouse Wheel Up/Down is a pretty traditional way of zooming in and out, and Ctrl+0 is a pretty traditional way of resetting zoom level. Could we get these hotkeys, and maybe a way to configure what zoom levels we want to be available?

**Comment by danielweck** [comment]
Related issue: https://github.com/edrlab/thorium-reader/issues/578

**Comment by ConsiousGamer** [comment]
Please do something about the zoom, fixed zoom levels are bit annoying.

**Comment by ConsiousGamer** [comment]
Or atleast a shortcut key to adjust the zoom levels.

**Comment by danielweck** [comment]
Support for mouse wheel / trackpad touch gesture is already implemented when pointing the cursor over the zoom icon-button, but frankly the user experience is quite jarring due to throttling the scroll events (which are kinetic / subject to a decelerating curve with some input devices but not others) and because of additional debouncing of the actual FXL page refresh (white flash).
The upcoming version 2.2 of Thorium will ship with additional keyboard shortcuts to reset zoom: `CTRL` `0` (zero), `CTRL` `8` and `9` (zoom out and zoom in, respectively).
