### ISSUE TITLE
Evolution of "back to bookshelf" icon 

### ISSUE THREAD

**Issue by gautierchomel** [edrlab/thorium-reader#1826]
The arrow left icon used for "back to bookshelf" function is well known but as it is a left arrow, it may cause confusion with other arrow icon used. 

Proposal is to make evolve this icon without changing it totally. "Exit to app" icons looks appropriate for this (but mirrored horizontally)

![image](https://user-images.githubusercontent.com/107039498/190357514-fa7ee2da-669d-4dde-b6cf-8cf72e098c55.png)

**Comment by gautierchomel** [comment]
Adding a view after / before.

![image](https://user-images.githubusercontent.com/107039498/195807393-6e3dfc61-101e-4a21-895b-1e4b3e815f99.png)

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/commit/a407d1669bde9dc904ce640150a5ab148976f12a#diff-31f57f40709e3991fe2167bbf02ff0043c0b85f23c91097327033f0f390c0e2f
