### ISSUE TITLE
Localisation update, translations for Thorium 2.2

### ISSUE THREAD

**Issue by gautierchomel** [edrlab/thorium-reader#1849]
Dear contributors, Thorium 2.2 will be released around November 7, it has some new features that require translation. 

Following is an extraction of the changed and added values, you can get a similar but in context view of changes in the reference file en.json with the following command line : `git diff v2.1.0:src/resources/locales/en.json develop:src/resources/locales/en.json`

All features can be tested in the [latest continuous test builds](https://github.com/edrlab/thorium-reader/releases).

## 1 Change: *More info* becomes *Book details*
In the Book information panel (About this book), the *More info* section is now titled *Book details* wich correspond better to it content. 

* [line 75](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L75): "moreInfo": "Book Details",

### edit OPDS feeds
Thorium now allows users to edit OPDS feeds (name and adress). This triggers the followings added fields : 

* [line 112](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L112): "update": "Edit"
+ [line 207](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L207): "name": "Name:",
+ [line 208](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L208): "namePlaceholder": "Name",
+ [line 209](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L209): "title": "Edit an OPDS feed",
+ [line 210](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L210): "updateButton": "Edit",
+ [line 211](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L211): "url": "Link:",
+ [line 212](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L212): "urlPlaceholder": "Link"

### Accessibility information
A set of Accessibility metadata presents in epub files is now displayed. 
This information should not be translated word for word, expressions with meaning in local culturs should be priviliged. This first iteration could be a starting point for a localisation project in different countries as this is curently happening in France. 

+ [line 218](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L218): "textual": "TTS & Screen reader friendly"
+ [line 221](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L221): "alternativeText": "Contains alternative text",
+ [line 222](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L222): "displayTransformability": "Adaptable text and layout",
+ [line 223](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L223): "longDescription": "Fully described graphical ressources",
+ [line 224](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L224): "printPageNumbers": "Printed book pagination reference",
+ [line 225](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L225): "readingOrder": "Contains a reading order",
+ [line 226](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L226): "synchronizedAudioText": "Text & audio synchronised",
+ [line 227](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L227): "tableOfContents": "Contains a Table Of Contents"
+ [line 230](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L230): "flashing": "Flashing",
+ [line 231 "motionSimulation"](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L231 "motionSimulation"): "Motion 
simulation",
+ [line 232](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L232): "name": "Hazard:",
+ [line 233](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L233): "noFlashing": "No flashing",
+ [line 234](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L234): "noMotionSimulation": "No mo
tion simulation",
+ [line 235](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L235): "noSound": "No sound",
+ [line 236](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L236): "none": "None",
+ [line 237](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L237): "simulation": "Simulation",
+ [line 238](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L238): "sound": "Sound",
+ [line 239](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L239): "unknown": "Unknown"
+ [line 241](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L241): "conformsTo": "Conforms to:",
+ [line 242](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L242): "certifierReport": "Certifier report",
+ [line 243](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L243): "moreInformation": "More information",
+ [line 244](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L244): "name": "Accessibility",
+ [line 245](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L245): "noA11y": "No accessibility information available"

Discussion about the implementation can be found in the related issue [Display accessibility metadata](https://github.com/edrlab/thorium-reader/issues/1332). You may also be interested by more Informations about the [French localisation project Reporting the accessibility of digital books](https://edition-accessible.github.io/signalement/index.html).

### Jump back and forward
Thorium2.2 introduces a new way of navigating thru a book by keeping navigation history and allowing you to jump back and forward to a precedent navigation point, just as we are used to do in a browser. This two lines are labels for the corresponding buttons placed at the bottom left of the book browser window.

+ [line 321](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L321): "historyNext": "Jump forward",
+ [line 322](https://github.com/edrlab/thorium-reader/blob/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904/src/resources/locales/en.json#L322): "historyPrevious": "Jump back",

The discussion about implementation can be found in the issue [Navigating back from a in-publication hyperlink jump...](https://github.com/edrlab/thorium-reader/issues/1624)

## Thorium Localization (l10n) language translations

Information and discussions about localization and language translation process can be found in the [Thorium wiki l10n dedicated page](https://github.com/edrlab/thorium-reader/wiki/Localization-(l10n)-language-translations) 

Actual known contributors are : 
* @horus68
* @milliet
* @martinpub
* @Modeo147
* @naglis
* @jacoporinaldi
* @peaceroad
* @panaC
* @nvdaes
* @HadrienGardeur 
* @tofi86
* @terhol-celia
* @maitreya2019
* @cary-rowen
* @ThanatosDi
* @georgegach
* @sukiletxe

**Comment by martinpub** [comment]
Thanks for the notice @gautierchomel! Will have a look at the Swedish strings asap.

**Comment by nvdaes** [comment]
Thanks Gautier. I've created PR #1854 updating the spanish
translation, remarking some points for other spanish speakers and
contributors, in case they want to improve it.

2022-10-31 10:53 GMT+01:00, Gautier Chomel ***@***.***>:

**Comment by gautierchomel** [comment]
Here is a link to an [example epub file with all accessibility metadatas](https://github.com/edrlab/thorium-reader-epub-tests/blob/main/a11y_metadata.epub) so you can check how it looks like in Thorium.

**Comment by nvdaes** [comment]
After opening the provided EPUB in Thorium, I've changed a word in my
translation. If nobody has comments, for me it'sready to be merged.

2022-11-02 17:53 GMT+01:00, Gautier Chomel ***@***.***>:

**Comment by jacoporinaldi** [comment]
I hope to be in time for 2.2, i have updated italian translation and submitted my pull request.
Note i have included a tiny fix to a typo i found on the english file (ressources) that i fixed with resources.

**Comment by danielweck** [comment]
luckily I haven't started the 2.2 builds yet :)
thank you very much.
I will reconcilate the typos fixes

**Comment by cary-rowen** [comment]
Luckily not yet released 2.2 I can have Simplified Chinese translation ready within 24 hours as soon as possible.

**Comment by danielweck** [comment]
We're done for this round of edits :)
Thank you everyone.

**Comment by danielweck** [comment]
As usual, the wiki page contains the most up to date contributions:
https://github.com/edrlab/thorium-reader/wiki/Localization-(l10n)-language-translations
