### ISSUE TITLE
Missed character for UTF-8 hyphen (U+2010)

### ISSUE THREAD

**Issue by gregoriopellegrino** [edrlab/thorium-reader#1865]
Hi,
I realized that the UTF-8 hyphen (U+2010) character `-` is not correctly displayed by Thorium, neither in the GUI TOC nor in the text (with the default serif font, the default sans-serif font is ok).

<img width="1552" alt="Schermata 2022-11-09 alle 15 26 17" src="https://user-images.githubusercontent.com/5065125/200857060-8634c70e-a3ea-4cc7-9eef-7e6a060c0603.png">

<img width="1317" alt="Schermata 2022-11-09 alle 15 32 36" src="https://user-images.githubusercontent.com/5065125/200857593-38bae6c2-2237-4d23-857b-dadfc6b8127b.png">

**Comment by danielweck** [comment]
Hello thank you for reporting this bug. I am unable to reproduce the problem at my end, could you please send me a sample EPUB to test with? Thank you!

**Comment by danielweck** [comment]
Thank you for sharing the EPUB.
Unfortunately I am unable to reproduce the rendering bug shown in your screenshots with either the latest tester / developer build of Thorium downloaded from the GitHub releases, or even with the official v2.1 release which shipped with an older Chromium version (web browser engine). I tested on my laptop which runs the latest MacOS version (Ventura).
Could you please test on another computer? Are you able to reproduce on Windows / Linux as well as Mac?
