### ISSUE TITLE
Refine Conforms To display

### ISSUE THREAD

**Issue by gautierchomel** [edrlab/thorium-reader#1867]
Thorium 2.2 displays information about reading modes and accessibility features in the Book information panel as discussed in the [issue 1332](https://github.com/edrlab/thorium-reader/issues/1332). 

The [A11Y task force of W3C publishing community group ](https://github.com/w3c/publ-a11y/) is actually discussing updates to the [User Experience Guide for Displaying Accessibility Metadata 1.0](https://www.w3.org/2021/09/UX-Guide-metadata-1.0/principles/) with bases on the feedback received from France and Italy. 

The _Conforms To_ information is actually a technical information like _EPUB Accessibility 1.0 - WCAG 2.0 Level AA_ and maybe with time the users will take habit of it, but it looks important to have a more human readable information.

Proposal is to add a label to each key as follow: 
* No accessibility conformance declared 
* Basic accessibility (EPUB accessibility A)
* Sufficient accessibility (EPUB accessibility AA)
* Advanced accessibility (EPUB accessibility AAA)

Labels may change but the principle would stay. 

This implies to have 4 more localized labels, the existing _Conforms to_ staying in case an unknown conformance is found in this metadata field.

**Comment by llemeurfr** [comment]
related to #1332

**Comment by danielweck** [comment]
* https://w3c.github.io/publ-a11y/UX-Guide-Metadata/draft/techniques/epub-metadata/
* https://w3c.github.io/publ-a11y/UX-Guide-Metadata/draft/principles/

**Comment by gautierchomel** [comment]
Closing as a new version of the display guide has been released.
