### ISSUE TITLE
audiobooks: night theme playback speed select is white text on white background

### ISSUE THREAD

**Issue by jacoporinaldi** [edrlab/thorium-reader#1890]
As from the title, using Thorium 2.1.0 on Windows while on night mode, audiobooks' playback speed select is unreadable having white text on white background. 
![sample](https://user-images.githubusercontent.com/72013644/204251003-4b627f59-9b67-4b08-851b-89d0cb76ea1d.png)

**Comment by danielweck** [comment]
I am not able to reproduce this bug on MacOS, unfortunately I do not have access to a Windows computer at the moment. I will check again asap.

**Comment by danielweck** [comment]
This bug occurred in the TTS and Media Overlays selectors too (playback / speech rate, and voice chooser). Unlike on MacOS, on Linux and Windows the HTML select>option must be styled separately to enforce the colour theme.
