### ISSUE TITLE
Suggstion: Flatpak version and release on flathub

### ISSUE THREAD

**Issue by Nitrousoxide** [edrlab/thorium-reader#1895]
Flatpak is generally seeing a huge uptick as the app distribution method of choice for linux and it is distro agnostic. I know right now you have .deb releases, and of course you can always build it from source, but flatpak will let you control the dependencies you want installed and the baseline image your app is installed on so you can more easily ensure a standardized environment for it to run on while expanding the reach to more folks than just those running debian based OS's (or those who run it in a distrobox container)

Would it be possible include flatpak versions in your releases and to push your releases to flathub as well which is the main flatpak repo people turn to?

**Comment by danielweck** [comment]
Moved to https://github.com/edrlab/thorium-reader/discussions/1750
