### ISSUE TITLE
Display of accessibility information from OPDS 

### ISSUE THREAD

**Issue by gautierchomel** [edrlab/thorium-reader#1899]
Feedbooks now transports accessibility information thru OPDS feed following Readium Model. See https://www.feedbooks.com/recent.json?accessibility=accessibility_fully

However the information is not displayed by Thorium, instead we get the common _No accessibility information available_ mention. 

![image](https://user-images.githubusercontent.com/107039498/206215965-187fd287-b544-4ee9-95c7-8dc967641d2e.png)

**Comment by danielweck** [comment]
![Screenshot 2023-03-01 at 21 33 31](https://user-images.githubusercontent.com/625201/222278710-9a7df9ab-b389-4992-aa8e-486c0b1d9ecd.png)
![Screenshot 2023-03-01 at 21 51 29](https://user-images.githubusercontent.com/625201/222278712-e62ce6d3-9cf0-4979-97fc-b7de37f22c72.png)
![Screenshot 2023-03-01 at 21 55 16](https://user-images.githubusercontent.com/625201/222278715-947eec29-aed0-4c53-87a9-8eade3cf700f.png)
