### ISSUE TITLE
Notify the user with a clear message when trying to open a .acsm

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1903]
Some people try to open Adobe DRM licenses (.acsm) with Thorium. But Thorium does no support this old, buggy and soon deprecated DRM solution. 

The current error message is "The import of /home/johnny/Hentet/urllink.acsm failed. Error: end of central directory record signature not found".

Please change this for a **localized** message like "The import of /home/johnny/Hentet/urllink.acsm failed. Error: Thorium does not support such file. Be sure to download LCP licenses instead".

**Comment by llemeurfr** [comment]
Note: The only desktop application capable of supporting .acsm is ADE (Adobe Digital Edition). You can try it, this will be another good reason to stop using Adobe protected ebooks.

**Comment by sukiletxe** [comment]
> Error: Thorium does not support such file. Be sure to download LCP licenses instead

I would add "if available", or clarify that it uses Adobe DRM (maybe both?). That way we don't assume that the book has an LCP license, nor that the user knows how to open the book.

**Comment by danielweck** [comment]
Thorium already includes an error message for incorrect / unsupported file extensions. So, for now I propose that we avoid introducing DRM-specific messaging, but at the very least let's fix this bug by showing the following baked-in message:

> an error occurred, verify your file extension (.lcpl | .epub | .epub3 | .audiobook | .webpub | .lcpa | .lcpaudiobook | .lcpdf | .pdf | .lpf | .divina | .daisy | .zip | .opf | ncc.html)

**Comment by danielweck** [comment]
Note: there are several ways to import files into Thorium:
1) filesystem chooser, which by default excludes non-supported file extensions, but can be overridden by the user to attempt to import any arbitrary file type (I have now fixed the error message).
2) drag and drop, which also filters unsupported file types, but cannot be forced by the user (however there is a bug: missing error message ...  I fixed this bug by adding the same message as (1))
3) "open with" from the filesystem, which by default only associates supported file extensions with Thorium, but can be forced by the user (the error message is now the same as (1))
4) OPDS, which also filters out unsupported publication types (same error message as (1))
