### ISSUE TITLE
Long uncut strings like raw URLs overflows

### ISSUE THREAD

**Issue by gautierchomel** [edrlab/thorium-reader#1906]
See capture

![Capture-20230117103121-1880x484](https://user-images.githubusercontent.com/107039498/212889497-c754976a-ef3b-4e69-825b-c0a310b8f7c2.png)

And code:
```
<li class="nodisc"><cite class="references-ressources" lang="en-GB" xml:lang="en-GB">Danielsen, C. (2007). What it means to walk with a white cane. Braille Monitor. [En ligne] https://nfb.org/images/nfb/publications/bm/bm07/bm0702/bm070205.htm</cite></li>
<li class="nodisc"><cite class="references-ressources" lang="en-GB" xml:lang="en-GB">Davies, T. (2008). Audiﬁcation of ultrasound for human echolocation. (Unpublished doctoral thesis). [En ligne] https://uwspace_uwaterloo.ca/bitstream/10012/3878/1/TCDavies%20ﬁnal%20thesis%20August22.pdf</cite></li>
```

**Comment by danielweck** [comment]
... well, `&nbsp;` means  non-breaking space after all :)

<img width="1552" alt="Screenshot 2023-07-19 at 19 07 03" src="https://github.com/edrlab/thorium-reader/assets/625201/717382d3-0f41-4d1b-b8ff-a65a6795df35">
<img width="1552" alt="Screenshot 2023-07-19 at 19 07 27" src="https://github.com/edrlab/thorium-reader/assets/625201/1158fc59-54b0-4332-9eeb-f74ae62adaa8">
<img width="1552" alt="Screenshot 2023-07-19 at 19 08 38" src="https://github.com/edrlab/thorium-reader/assets/625201/38ad1aa2-4f74-45a3-b2b9-9b01f8b6f019">

**Comment by danielweck** [comment]
Issue moved to Readium CSS https://github.com/readium/readium-css/issues/129
