### ISSUE TITLE
FeatureRequest: Pin the Navigation pane

### ISSUE THREAD

**Issue by seaspeak** [edrlab/thorium-reader#1907]
Sometimes I need to skim over bookmarks or annotations. It has to keep opening the navigation bar/bookmark/scrolling  after clicking and jumping to a certain location.

**Comment by danielweck** [comment]
Hello, this feature is already implemented: SHIFT + ALT (OPTION on MacOS) key modifiers combined with click (mouse cursor / pointing device) or ENTER (keyboard).
This information is given in the project's Wiki page ( https://github.com/edrlab/thorium-reader/wiki/Keyboard-shortcuts ) but is this included in Thorium's official user-facing documentation? ( @gautierchomel )
