### ISSUE TITLE
Pin Linux baseline / minimum version to ensure GLIBC compatibility

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1910]
The "marketing" website currently states:
"Ubuntu 20.04 and newer (requires GLIBC 2.28+)"
https://www.edrlab.org/software/thorium-reader/

Due to hard GLIBC incompatibilities, the "newer" bit in the above sentence is correct for end-users, but not for developers / app builders (official Thorium as well as forks).

Thorium's GitHub Actions workflow is currently configured to build with `ubuntu-latest`, which (at the time of writing) maps to `22.04` (was still `20.04` not so long ago):

https://github.com/edrlab/thorium-reader/blob/1286716197a27520d2d8b750334fc3de9075fafa/.github/workflows/main.yml#L23

https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/

Similarly, Thorium release `2.2.0` for Linux (both AppImage and Debian package) was built on Linux Mint 21.1 (Vera) which derives Ubuntu 22.04 (Jammy Jellyfish):

https://github.com/edrlab/thorium-reader/releases/tag/v2.2.0

...problem on older systems: `Error: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.32' not found (required by lcp.node)`

So, we need to force the official releases and the automated builds to be compatible with older GLIBC versions, which means downgrading the build environment to a previous LTS Long Term Support Linux distribution (kernel `5.4` / Ubuntu `20.04` would be fine, upon initial investigation).

https://www.kernel.org/category/releases.html

Any of the Ubuntu `20.04` LTS (Focal Fossa) derivations would work, personally I run Linux Mint XFCE VMs for efficiency reasons:

https://linuxmint.com/download_all.php

Note that we inherit a technical constraint from Botan (we transitioned from `2.3.0` to `2.19.1` some time ago):

https://github.com/randombit/botan/wiki/Distros

So TODO is downgrade build env to previous LTS, check GLIBC linking requirement in generated LCP lib and Thorium Electron app, and test on latest LTS.

**Comment by jacoporinaldi** [comment]
Thank you Daniel, this is really helpful.

I do confirm my app based on Thorium 2.2 and built on ubuntu 20.04 (kernel 5.4.x) is working properly on the latest ubuntu versions (has been tested on archLinux based on kernel linux 6.1.1) while it is throwing said error on older versions.

I wonder if it might be possible to generate a standalone/static version of the LCP library? The app is actually stable, the only issue encountered is about the lcp.node file. A standalone library might be a bit heavier but it would include the required GLIBC version in itself.

**Comment by danielweck** [comment]
Well, `ldd --version` would probably need to match in the LCP lib as well as the Electron / NodeJS runtime...so I'm not sure if shipping a specific version of GLIBC (static object linking) in the binary / dynamic lib would work in practice.

The good news is that the NodeJS runtime appears to also require GLIBC 2.28 minimum, such as Red Hat Enterprise Linux (RHEL) 8, Debian 10, Ubuntu 20.04

https://nodejs.org/en/blog/release/v18.0.0/

**Comment by danielweck** [comment]
By the way, in addition to GLIBC compatibility >= 2.28, there is also (potentially, I haven't fully investigated this) libstdc++ >= 6.0.25, apparently  GLIBCXX_3.4.25 and GCC 8.1 +

**Comment by danielweck** [comment]
For GLIBC 2.28 compat, building with a Docker image of Debian Buster with NodeJS 18 is better than Ubuntu (18.04 was 2.27, 20.04 was 2.31 and 22.04 was 2.32).

**Comment by gsouf** [comment]
Getting an error with Thorium 2.2.0 on Debian 5.16 when I try to open an epub, ```The import of xxx.epub failed. Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/Thorium/resources/app.asar.unpacked/external-assets/lcp.node)``` is that related to this issue? Any way I can fix it? Thanks

**Comment by danielweck** [comment]
hello, the current workaround is to use an earlier version of Thorium. Note that official releases support LCP-protected publications, but automated developer / tester builds do not.

**Comment by danielweck** [comment]
The LCP lib is now compiled using a Docker image of Linux that includes a lower version of GLIBC
