### ISSUE TITLE
Clipboard text copy on Windows produces a URL ?

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#1911]
Tested on Mac OS: only the text is copied (CMD + C).
This reported issue seems to indicate that on Windows 10 there is a URL in the clipboard (CTRL + C):
https://github.com/edrlab/thorium-reader/issues/1908

**Comment by danielweck** [comment]
I am unable to reproduce this behaviour, I am afraid. I am on Windows 11. I tried pasting into different text editors (Visual Studio Code, Wordpad)

**Comment by danielweck** [comment]
Hello @seaspeak I am unable to reproduce the problem of a URL link being copied into the clipboard. Could you please describe the steps you are following? Please make sure to use a recent build of Thorium from this download page:
https://github.com/edrlab/thorium-reader/releases/tag/latest-windows

**Comment by seaspeak** [comment]
> Hello @seaspeak I am unable to reproduce the problem of a URL link being copied into the clipboard. Could you please describe the steps you are following? Please make sure to use a recent build of Thorium from this download page: https://github.com/edrlab/thorium-reader/releases/tag/latest-windows

Sorry I didn't describe this well. This only happens if you paste it in OneNote (Enable advanced option: "include link to source when pasting from the web") But I can't find the link information from my own tiny program of clipboard sniffer.

I was suggesting to use this information to let user locate certain paragraph in a book. I didn't report it as a bug.

**Comment by danielweck** [comment]
Thank you for clarifying. I am now closing this issue. Please refer to existing feature request #1733 for further discussions.

**Comment by seaspeak** [comment]
> Thank you for clarifying. I am now closing this issue. Please refer to existing feature request #1733 for further discussions.

I copied a word "conflict" in the Thorium and pasted it in Microsoft OneNote.
![image](https://user-images.githubusercontent.com/8821870/223705238-11b25643-f969-49cd-89dd-1af0ac99847b.png)
