### ISSUE TITLE
Pasted text copied from EPUB has no space between words

### ISSUE THREAD

**Issue by PhilippeBruno** [edrlab/thorium-reader#1916]
In my research, I often have to cite passages from ebooks. Every now and then, I stumble upon an EPUB from which I cannot properly copy and paste some selected text. In Thorium, the selected text seems normal, but when I paste it into another application like Word or even Notepad, the pasted text does not contain any space between the words.

At first, I thought it was the way some EPUBs were created, but as the problem repeated itself regularly, I started suspecting the problem came from Thorium. So I started inspecting the faulty EPUBs and the text in the HTML files inside does contain spaces between words. As a matter of fact, a little EpubToText utility I wrote many years ago always worked well on EPUBs that Thorium failed to properly copy text from.

If you simply read EPUBs onscreen, this peculiar bug goes unnoticed. However, as soon as you try to copy and paste some text from certain EPUBs (I am not sure what in those EPUBs triggers this bug), the pasted text whether it be the title, the author or a passage from the book is simply a huge block of characters without spaces between words and one has to manually reformat the text by adding spaces at the appropriate places.

To exemplify the problem I just described, the above paragraph (if selected and copied in Thorium) would be pasted as follows:

"IfyousimplyreadEPUBsonscreen,thispeculiarbuggoesunnoticed.However,assoonasyoutrytocopyandpastesometextfromcertainEPUBs(IamnotsurewhatinthoseEPUBstriggersthisbug),thepastedtextwhetheritbethetitle,theauthororapassagefromthebookissimplyahugeblockofcharacterswithoutspacesbetweenwordsandonehastomanuallyreformatthetextbyaddingspacesattheappropriateplace."

@danielweck , I'll privately send you a sample EPUB to witness first hand what I am talking about.

**Comment by danielweck** [comment]
I love weird bugs like this :)
Thank you for sharing.
I wonder if it is platform-specific.

**Comment by danielweck** [comment]
Hello, thank you for privately sharing the EPUB with me. I am able to reproduce the "bug" ... which unfortunately seems specific to Chromium, the web browser engine that powers Electron (and therefore Thorium), Google Chrome, Microsoft Edge, etc. The "collapsed whitespaces" problem does not seem to occur in Firefox and Safari (I only tried on my Mac OS laptop, but this seems conclusive enough). I tried tweaking some CSS whitespace directives, to no avail so far.

Technical details:

This is a pre-paginated publication that contains fixed-layout HTML documents (aka FXL EPUB).  Judging by the metadata, this publication was generated by Adobe InDesign, and I suspect that the HTML documents were created from individual PDF pages. Every single word in the documents' text is absolutely-positioned inside the page canvas. See screenshots:

<img width="1440" alt="Screenshot 2023-02-23 at 23 16 06" src="https://user-images.githubusercontent.com/625201/221053504-4c432b2c-fd2e-423a-9665-be998c829925.png">

<img width="1440" alt="Screenshot 2023-02-23 at 23 42 13" src="https://user-images.githubusercontent.com/625201/221056845-162d82bd-51b6-4283-b1b6-6a5c21d278cf.png">

**Comment by danielweck** [comment]
Using the Google Chrome web inspector, I tweaked the CSS style of paragraphs. The only values that cause the spaces to be preserved during copy-to-clipboard are:

* `white-space: break-spaces;`
* `white-space: pre;`
* `white-space: pre-wrap;`

All other possible values, including the authored style `white-space: nowrap;`, but also `revert`, `initial`, `unset` etc. have no effect.

I am afraid this looks like a bug that should be reported to the Chromium team. I have no bandwidth at the moment to create a reduced reproducible test case, so hopefully somebody else will :)

https://bugs.chromium.org/p/chromium/issues/list

In fact, it would be interesting to try copy/pasting from Windows with Microsoft Edge and other Chromium-based web browsers, just to confirm that Firefox and Safari do not suffer from this bug.

**Comment by PhilippeBruno** [comment]
On my Windows 11 machine, I tested with Edge, Chrome, Brave and Firefox. Firefox is the only one not affected by this bug.

**Comment by PhilippeBruno** [comment]
<img width="566" alt="image" src="https://user-images.githubusercontent.com/36426806/221066452-edd20ed4-a487-4f22-b38d-827ad16b9fea.png">

![image](https://user-images.githubusercontent.com/36426806/221066502-859487f9-cc7a-4286-a9a6-7b1efbaa293b.png)

**Comment by danielweck** [comment]
Thank you. This matches my findings (Brave is also Chromium / Blink -based).

**Comment by PhilippeBruno** [comment]
You're welcome. Keep in mind that it is not the only EPUB exhibiting this bug. I have encountered the same bug with several other EPUBs, but never bothered reporting it until now.

I personally find questionable the way the underlying HTML is created with every single word absolutely-positioned inside the page canvas, in particular since the layout of this book is not critical.
