### ISSUE TITLE
Brightness setting for text/background 

### ISSUE THREAD

**Issue by c0ldw1nd** [edrlab/thorium-reader#1917]
I really like the brightness setting in the Amazon Kindle Windows app.

White text/background is gradually greyified as you move the slider.

Would it be possible to implement and add this feature to Thorium Reader?

![grafik](https://user-images.githubusercontent.com/110848860/222105345-bf39bad2-b584-412c-a6fa-0dcc7d5f932d.png)

![grafik](https://user-images.githubusercontent.com/110848860/222105701-dfb31312-166e-44be-bc8a-019e6e08907d.png)
![grafik](https://user-images.githubusercontent.com/110848860/222105543-fe0fae61-9bf1-4434-9827-3428f8531945.png)

![grafik](https://user-images.githubusercontent.com/110848860/222105945-cf326ae5-530a-4cfe-9b40-fb8b9ea89c52.png)
![grafik](https://user-images.githubusercontent.com/110848860/222106115-85ec3961-a104-42b3-aa08-b6b401d8bbc2.png)

**Comment by danielweck** [comment]
This is a nice feature (I personally use it on my screens and readers), but based on my knowledge of the current software architecture, I would say that this functionality would require significant evolutions in how colour themes / schemes are implemented in Thorium, so I wouldn't hold my breath.
In my opinion a higher development priority would be to dark-ify the main library window (currently only the reader window supports a night mode), and whilst we're at it also support the sepia palette.
We are also aware of low-contrast issues which we will as soon as possible.

**Comment by danielweck** [comment]
related:
https://github.com/edrlab/thorium-reader/issues/1915
https://github.com/edrlab/thorium-reader/issues/1600
https://github.com/edrlab/thorium-reader/issues/577

**Comment by c0ldw1nd** [comment]
@danielweck 
Nice you like and use it too.
Thought so, it wouldn't be easy to implement.
Yeah, it's a nice feature but not a MUST.
Surely your priority planning is more important than some random guy asking for a new feature.
Would be great if I could use it some day in the future.

**Comment by danielweck** [comment]
>  Surely your priority planning is more important than some random guy asking for a new feature.

Thorium's list of priorities are largely influenced by user needs and feedback, so please never hesitate to post feature requests or suggestions here again!
But yes, it does ultimately come down to how much a small development team can do given finite time and budget :)

**Comment by danielweck** [comment]
Thorium 3 will introduce colour themes ... not quite like a linear slider for arbitrary background "brightness", but as good as it will get in Thorium in the foreseeable future. I am closing this issue as I expect new feature requests / suggestions will emerge based on the refactored GUI experience
