### ISSUE TITLE
Ignore accents when searching

### ISSUE THREAD

**Issue by justinm-bdeb** [edrlab/thorium-reader#1920]
The search functionality should ignore accents. It is expected behavior from people that speak languages that use accents that they are ignored when searching.  ``ö`` should match ``o`` and vice versa.

**Comment by danielweck** [comment]
Hello, thank you for reporting this. It is a known missing feature:
https://github.com/edrlab/thorium-reader/issues/1209
I am closing this issue to avoid duplicates.
