### ISSUE TITLE
User preferences for TTS - Read footnotes aloud?

### ISSUE THREAD

**Issue by LaZay** [edrlab/thorium-reader#1923]
This only nice to have.

So far, footnotes are not read aloud when TSS is activated. It would be nice to let people choose their own user preferences for TTS on this (as assistive technologies do for the blinds).

```
- epub:type=noteref, footnotes, footnote, endnotes, endnote
- role=doc-noteref, doc-footnote, doc-endnotes, doc-endnote
```

**Comment by danielweck** [comment]
Hello, thank you for reporting this.
I assume you are referring to "popup footnotes"? In other words, when the "popup" feature is deactivated (this is an opt-out setting in Thorium's configuration) the note contents are in fact spoken during TTS readaloud. The same applies to notes that are not marked as "popup" using any of the recognised `epub:type` / `role` attribute values.
Also note that "skippability" is currently not supported at all in Thorium's TTS readaloud (it is only implemented in EPUB3 Media Overlays playback)

**Comment by danielweck** [comment]
The point here is to automatically generate utterances for the note content before its appearance in the reading order, at the point of insertion of the note reference link.

**Comment by LaZay** [comment]
Thanks
