### ISSUE TITLE
Celtic Daily Prayer epub3 file won't open in Thorium Reader on Win 10 PC but works fine in Google Play Books on Android

### ISSUE THREAD

**Issue by Mike-DWN** [edrlab/thorium-reader#1926]
Celtic Daily Prayer Epub3 book purchased from Google (https://play.google.com/store/books/details/Northumbria_Community_The_Celtic_Daily_Prayer?id=3EJMDwAAQBAJ) works fine on my Android phone app 'Play Books' including playing the audio files.  I was using Adobe Digital Editions (downloaded from Adobe not from Microsoft store) on my Windows 10 desktop using very successfully last year but is suddenly stopped working and appeared to be corrupting Win10 so had to uninstall and reset my Win10 desktop.  I have been trying to find a windows app which would allow audio and Thorium looked to be a possible candidate but it won't load the document and comes up with an error message saying: "The import of C:\Users\mdwna\OneDrive\Books\CDP\Celtic Daily Prayer.epub failed. ParseError: Attribute � redefined".  Obviously with a purchased ebokk there's not much I can do now.  Any ideas / suggestions?

**Comment by gautierchomel** [comment]
Transferred the issue to the development repo.

**Comment by danielweck** [comment]
your EPUB is protected with a DRM (encrypted) that Thorium does not support, I am afraid.

**Comment by danielweck** [comment]
@Mike-DWN if you would like me to check my DRM assumption, feel free to privately share your EPUB `Celtic Daily Prayer.epub` ( daniel.weck@gmail.com )

**Comment by llemeurfr** [comment]
We hope that one day, Google will provide ebooks with the open LCP DRM and cut support for the obsolete Adobe DRM (Adobe Digital Edition is now dead). 
Emails from ebook users to Google Play Book support could help, maybe.
