### ISSUE TITLE
Bug: Default Window Sizing

### ISSUE THREAD

**Issue by IllWriteDocumentationLater** [edrlab/thorium-reader#1931]
**Current Behaviour:** 
There is an issue in Thorium where the reader will always open by default into a window size of like 800x600. 

It can be partially fixed by setting the Run option inside Properties to ‘Maximised’ ensuring the reader always opens to the desired size.
This results in another issue. While the window of the opened file matches the size of main widow; it will be opened off-centre.

Problem exists on both v2.2.0 and v2.3.0-aplha from here on Github.

**Expected behaviour:**
Thorium opening full screen or with the reader remembering the window size of the previous session.
Open files within Thorium and have the window be properly centred.

**Screenshots:**
_Default Window Size:_
![Normal Window](https://user-images.githubusercontent.com/116046640/226547391-600dedac-1f11-439d-9f25-c50d50cf5b37.png)

_Desired Sizing:_
![Proper size](https://user-images.githubusercontent.com/116046640/226546311-b49f8e1a-93d9-4d91-9713-a8d965cc409e.png)

_Off-centred Placement :_
![Off-Centre](https://user-images.githubusercontent.com/116046640/226546414-cf0ea97c-3029-4482-9515-89ff97d264d9.png)

_Properly Centred Placement:_
![Properly Centred](https://user-images.githubusercontent.com/116046640/226548130-ff683fe4-9e9e-4587-ba49-631bad85c4df.png)

**System Details:**
OS: Windows 10 19044
Resolution: 3840x2160

**Comment by danielweck** [comment]
I agree, the way window dimension / position is handled in Thorium is not great. The current system is also confusing when returning back to the "library" window from one of the opened "reader" windows.

**Comment by danielweck** [comment]
This is changing (hopefully for the better) in Thorium 3.0 which we are working on very actively. I am closing this issue as we need to work from feedback based on the refactored GUI
