### ISSUE TITLE
Numbers not aligned

### ISSUE THREAD

**Issue by civodulab** [edrlab/thorium-reader#1936]
Hello,
Why are the numbers not aligned (6 and 8) and of the same size (1 and 2)?
![chiffres](https://user-images.githubusercontent.com/24477170/227917332-56f8da30-205d-4c97-8d93-c355e59e6799.jpg)

**Comment by danielweck** [comment]
Hello, depending on the typeface, some characters may align differently relative to the font baseline. Thorium does not alter the default typographic conventions, as far as I know (to be precise, Readium CSS would be the component responsible for this in Thorium's software stack).
Do you know what font is displayed in your screen capture? By the way, you should be able to reproduce the exact same rendering outside of Thorium, for example in Google Chrome or Microsoft Edge (both Chromium-based), or even Mozilla Firefox, Apple Safari, etc.

**Comment by danielweck** [comment]
would you mind sharing the EPUB so I can investigate at my end? thank you ( daniel.weck@gmail.com )

**Comment by danielweck** [comment]
Ah, I think you are using this EPUB:

https://github.com/IDPF/epub3-samples/blob/0b3e80553f509fbdfe591008cd7d1e804b24db54/30/georgia-cfi/EPUB/georgia.xhtml#L17

==>

https://raw.githack.com/IDPF/epub3-samples/main/30/georgia-cfi/EPUB/georgia.xhtml

**Comment by danielweck** [comment]
Yes, the typefaces Old Style, Modern and Humanist cause the numbers to shift on their baseline (descent). See screenshots taken from Thorium:

<img width="657" alt="Screenshot 2023-03-27 at 13 37 01" src="https://user-images.githubusercontent.com/625201/227943128-bbcaa700-13ff-4f34-b554-b14cbab5d066.png">

<img width="657" alt="Screenshot 2023-03-27 at 13 37 16" src="https://user-images.githubusercontent.com/625201/227943133-9a99520b-7f27-42d0-ba77-becd8c689392.png">

<img width="657" alt="Screenshot 2023-03-27 at 13 37 32" src="https://user-images.githubusercontent.com/625201/227943135-db52ae0e-01ac-4c06-95c2-d171606a6c16.png">


Compare with another typeface:

<img width="657" alt="Screenshot 2023-03-27 at 13 36 46" src="https://user-images.githubusercontent.com/625201/227943080-9094e545-9d1e-4519-9829-ed366dddd1e8.png">

**Comment by civodulab** [comment]
I use the [Luciole font](http://luciole-vision.com/) and it does it too

**Comment by danielweck** [comment]
Firefox screenshots (Chrome identical):

On Mac OS "Modern" maps to Athelas:

<img width="708" alt="Screenshot 2023-03-27 at 13 53 05" src="https://user-images.githubusercontent.com/625201/227945229-8d9b552b-7267-42db-8a2c-d0b51a20f797.png">

"Old Style" maps to Iowa Old Style:

<img width="708" alt="Screenshot 2023-03-27 at 13 52 55" src="https://user-images.githubusercontent.com/625201/227945265-59f3f93e-3a60-48a3-8e1c-318d8f7e910d.png">

"Humanist" maps to Seravek:

<img width="708" alt="Screenshot 2023-03-27 at 13 54 34" src="https://user-images.githubusercontent.com/625201/227945465-9ae5144c-53cf-448b-878e-aedc3942eca6.png">

Using:

https://raw.githack.com/readium/readium-css/master/docs/utils/Typeface-tester.html

(from https://github.com/readium/readium-css/blob/master/docs/utils/Typeface-tester.html )

**Comment by danielweck** [comment]
Ok, I found the bug: Readium CSS sets `font-variant-numeric: oldstyle-nums proportional-nums;` on the `body` element.

https://github.com/readium/readium-css/blob/583011453612e6f695056ab6c086a2c4f4cac9c0/css/src/modules/ReadiumCSS-html5patch.css#L59

I am going to move this issue to the correct GitHub code repository.

Thank you!

**Comment by danielweck** [comment]
Issue migrated to: https://github.com/readium/readium-css/issues/124

**Comment by gautierchomel** [comment]
@civodulab Readium CSS forces old style numbers. This happens if they exists in the font set. 

You should be able to force use of aligned numbers with `font-variant-numeric: normal;`.

**Comment by civodulab** [comment]
Thanks a lot Gautier, it works.
