### ISSUE TITLE
Problem getting OPDS catalog feeds to work.

### ISSUE THREAD

**Issue by lostcowboy** [edrlab/thorium-reader#1943]
Hello, I just installed the Thorium Reader for Windows. I then went looking for OPDS catalog links and found this webpage [wiki.mobileread.com/wiki/OPDS#Online_OPDS_Catalogs](https://wiki.mobileread.com/wiki/OPDS#Online_OPDS_Catalogs) which has a lot of links. But I could not get them to work. I then went to [thorium.edrlab.org/docs/220_organizing/222_catalogs/](https://thorium.edrlab.org/docs/220_organizing/222_catalogs/) and out of the three OPDS catalog links on that webpage only one would work. I did notice that the error seems to be the same, Something about "Cannot read properties of undefined (reading 'headers')" 

Edit: I found the problem was on my computer! A program I use called AdGuard was messing up the connection. So just ignore this issue.

**Comment by danielweck** [comment]
Hello, I tested with the latest self-build of Thorium from the `develop` branch (automated builds are published at https://github.com/edrlab/thorium-reader/releases )

* https://gallica.bnf.fr/opds => "welcome" page with links, but no publications (this doesn't appear to be a Thorium bug, in the sense that I checked the OPDS feed with my web browser and I get the same result)
* http://edrlab.org/public/feed/opds-lcp.json => works fine (note that this requires a LCP-enabled build, so the automated releases will not open the EPUBs)
* https://www.feedbooks.com/catalog => ah, this link is incorrect, it should be https://www.feedbooks.com/catalog.atom (@gautierchomel could you please correct the link in the doc https://thorium.edrlab.org/docs/220_organizing/222_catalogs/ ) ... that being said, I think that the Feedbooks OPDS1 (Atom XML) catalog is broken anyway, it's all empty: https://catalog.feedbooks.com/catalog/index.atom
* https://catalog.feedbooks.com/catalog/index.json => this OPDS2 (JSON) catalog is not included in the Thorium doc, but it probably should (@gautierchomel :) ) ... that being said, I am seeing empty spaces in the feed, it used to be fuller. The "Free Books" section (public domain) still contains a huge selection though (I tested a few EPUBs, they work fine in Thorium).
* https://wiki.mobileread.com/wiki/OPDS#Online_OPDS_Catalogs => contains a few broken catalogs too
* https://github.com/readium/r2-streamer-js/blob/develop/docs/opds.md#a-selection-of-public-opds-feeds => a list of feeds "curated" by Thorium developers, only for testing edge cases (not for actual reading) ... there are also some broken feeds in there, we will have to clean up the list (again ;) )
