### ISSUE TITLE
Load whole e-book folder at once

### ISSUE THREAD

**Issue by Dragurashiphylax** [edrlab/thorium-reader#1944]
It would be really nice if I could load entire e-book folder at once, because loading all my books manually, one by one, takes time.

**Comment by danielweck** [comment]
Hello,
* You can drag and drop a folder onto the library window from your operating system's file explorer, it will be analysed recursively (i.e. subfolders will be scanned for publications too). This works on MacOS, I am not sure about Windows and Linux :)
* Alternatively you can select multiple files from your filesystem using your operating system's file browser (the files can be in different folders of the folder tree / hierarchy), then drag and drop the selected publications into Thorium's library window.
* You can also click on the "+" button in the user interface to open Thorium's file chooser, and from there you can select multiple files from folders, or choose all files in a folder using the operating system's shortcut CTRL/CMD+A or mouse selection.

Note that the "open with" context menu in the operating system's file explorer will open the reader window(s) for all selected publications, unlike the above methods which only import the files in Thorium's library.

**Comment by danielweck** [comment]
@gautierchomel ping, regarding the Thorium "docs":

https://thorium.edrlab.org/docs/

( https://github.com/edrlab/thorium-reader-doc/ )

**Comment by Dragurashiphylax** [comment]
Whoa, I didn't try that. Thanks a lot
