### ISSUE TITLE
GLIBC incompatibility

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1949]
From a user: so far I have not been able to open anything in Thorium reader. It looks like some kind of GLIBC incompatibility with my system.

Installed Thorium v2.2.0 on

Linux Mint 20.3, XFCE 64-bit desktop

I get this error when I try to open am lcpl file (only partially visible in window): 

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/Thorium/resources/app.asar.unpacke

**Comment by danielweck** [comment]
Duplicate issue (now closed): https://github.com/edrlab/thorium-reader/issues/1910
