### ISSUE TITLE
Page numbers do not display in EPUB generated from NIMAS

### ISSUE THREAD

**Issue by nicolegaines** [edrlab/thorium-reader#1958]
When EPUB is generated from NIMAS files using the DAISY Pipeline 2, the user can then navigate the EPUB by print book page number in Thorium V2.2.0, but the page numbers are not visible to the user.

The ability to navigate by page number would indicate that the page information is being retained in the EPUB but is just not visible.

In order to support the use case of students who are using EPUB as an alternative to hard copy textbooks, could we add a feature request that it be optional for the user to view the print page numbers in the EPUB?

Thanks!
Nicole Gaines
ngaines@aph.org

**Comment by danielweck** [comment]
I am closing this issue now as this feature has been available in Thorium for a long time, but please feel free to further comment so we can get down to the bottom of why your experience does not match the expected behaviour (I suspect there is a problem in the authored / generated publication)

**Comment by nicolegaines** [comment]
Hi, Daniel. Thanks for the response. Are you indicating that when I select Paginated layout in settings that the print book page numbers should be visible? I am finding that we can navigate to a specific page number, and Thorium will jump to a screen where the content on that page begins. But there is not a visual indication that there is a page break at that location. Is this something that would be configured in the CSS for the particular EPUB? Thanks!

Nicole
________________________________

**Comment by danielweck** [comment]
> But there is not a visual indication that there is a page break at that location. Is this something that would be configured in the CSS for the particular EPUB?

That is indeed the crux of the issue discussed in this lengthy thread https://github.com/edrlab/thorium-reader/discussions/1799 (feel free to chime in)
Thorium currently does not attempt to make authored "page breaks" visible in the publication's HTML documents, as this would likely break styling (e.g. inline vs. block-level) but also probably break structural integrity if we inserted HTML markup "in place". One possibility would be to draw indicators of page breaks inside the margin area, at a matching vertical line level. Thorium currently does not have such drawing tools at its disposal but we already implement visual annotations to highlight search results in an "inline" manner (this is a visual illusion as in fact we inject HTML markup in a non-disruptive manner at the very end of the document, which does not interfere with the referential integrity of the rest of the document for bookmark / etc. purposes)
