### ISSUE TITLE
I am not able to execute clone project 

### ISSUE THREAD

**Issue by SDVivek** [edrlab/thorium-reader#1962]
Hi,

I have cloned the repository from this link https://github.com/edrlab/thorium-reader.
Then I followed the Quick Start guide. 

I have checked the Prerequisites
In my system NodeJS  version v18.16.0
In my system NPM version 9.5.1

I have followed all the guidelines which mention in the repository link.

When I enter this command  
npm run start:dev 
I getting this result error -  npm ERR! Missing script: "start:dev"

I have tried this command also
npm start 
I getting this result error- npm ERR! Missing script: "start"

Pls, help me out.

Thank you.

**Comment by danielweck** [comment]
Hello, I assume you are referring to the README: https://github.com/edrlab/thorium-reader/blob/develop/README.md#quick-start

Are you sure you are executing the `npm run xxx` commands from inside the `thorium-reader` folder?

Are you on Windows? What terminal do you use? MS DOS, Powershell, GitBash?

**Comment by danielweck** [comment]
I am closing this issue as the GitHub codebase clones and compiles + runes fine in the project's supported platforms (Windows, Linux, MacOS).
Do not hesitate to continue the discussion here, we will see the notifications.
