### ISSUE TITLE
Borrow link gets called when publication info dialog is being opened

### ISSUE THREAD

**Issue by AndroCro99** [edrlab/thorium-reader#1964]
Hello,
I have publications that are available for loan so every publication has a link as:
"links": [
                {
                    "rel": "http://opds-spec.org/acquisition/borrow",
                    "href": "https://localhost:44331/api/opds/borrow?docId=344433",
                    "type": "application/opds+json",
                    "properties": {
                        "indirectAcquisition": [
                            {
                                "type": "application/vnd.readium.lcp.license.v1.0+json"
                            }
                        ]
                    }
                }
            ]
When clicking on publication in the publication feed it should open the publication info dialog and it does but it calls the borrow link as soon I click on publication in the feed without clicking the borrow button.

**Comment by AndroCro99** [comment]
Thorium version: v2.3.0-alpha.1, development branch clone

**Comment by danielweck** [comment]
Thank you for reporting this. I believe this behaviour originates from this code:

https://github.com/edrlab/thorium-reader/blob/5a4e6d72a81cb4a81e27b9f515e3e386d75bca34/src/renderer/common/redux/sagas/dialog/publicationInfoOpds.ts#L117-L123

==>

https://github.com/edrlab/thorium-reader/blob/5a4e6d72a81cb4a81e27b9f515e3e386d75bca34/src/renderer/common/redux/sagas/dialog/publicationInfoOpds.ts#L28-L93

Would it be possible to try your OPDS feed at our end? (is there a public or private HTTP URL we could use?)

**Comment by AndroCro99** [comment]
I sent you an email answering questions about testing and briefly describing our OPDS.

**Comment by danielweck** [comment]
The fallback cascade all the way down to:

```js
            this.convertFilterLinksToView(baseUrl, r2OpdsPublication.Links, {
                type: [
                    ContentType.AtomXml,
                    ContentType.Opds2,
                ],
            }),
```

...is way to permissive. The result should exclude `rel` `http://opds-spec.org/acquisition/*` already covered by `sampleLinkView`, `acquisitionLinkView`, `buyLinkView`, `borrowLinkView`, `subscribeLinkView`, `revokeLoanLinkView`, `catalogLinkView`, etc. (maybe even more exclusions!)

Ao, is the generic OPDS1(AtomXML) / OPDS2(JSON) fallback even necessary? Shouldn't this logic just strictly require `rel` `self` or `alternate`.

PS: not just `entrylinkView`, also:

https://github.com/edrlab/thorium-reader/blob/8a30bc3a5cefe792945730f3a0c71de3c4614f34/src/main/converter/opds.ts#L358-L369

**Comment by panaC** [comment]
I removed these two fallback, @AndroCro99 can you retry on the nightly build please.

**Comment by AndroCro99** [comment]
It is working, the borrow link isn't called without pressing the borrow button.
