### ISSUE TITLE
OPDS breadcrumb / start link problem

### ISSUE THREAD

**Issue by AndroCro99** [edrlab/thorium-reader#1967]
Hi,
I have OPDS catalog which first feed is a navigation feed to choose a library and when chosen it loads the feed (list of groups) for that library.
Start link is available only after choosing the library and its href is set to the library's first feed.
The problem is Thorium expects that start link links to the first feed of the OPDS catalog and automatically write name of catalog in breadcrumb even if the OPDS feed has a different title. 
My use case: First feed (choosing library) --> Second feed (library feed of groups) --> Third feed (publication list) 
Start link is not available in the First feed and when clicked in other feeds it links to the Second feed for the previously chosen library.
So the title in Breadcrumb should be the title of the second feed but thorium puts the title of the first feed when start button is pressed.
Third feed - before pressing start button
![image](https://github.com/edrlab/thorium-reader/assets/141128010/a2bf0873-9e11-4d1a-bda8-c6319024de1f)

Second feed - after pressing start button
![image](https://github.com/edrlab/thorium-reader/assets/141128010/42221333-e685-4838-b943-f2ccc76dd0ad)

After pressing start button breadcrumb should be {first feed}/{second feed} instead. It loads correctly the second feed but the breadcrumbs show wrong title.

**Comment by danielweck** [comment]
Thank you for reporting this. Just to be sure, what do you mean by "start button"?

I personally find the breadcrumb sequence confusing when exploring OPDS feeds, because it is effectively closer to a "navigation history" than to a clean hierarchical string of landmarks (i.e. containment relationship between heading levels). For example the breadcrumb fails to be helpful when reaching into the "search" link of OPDS feeds.

**Comment by AndroCro99** [comment]
![image](https://github.com/edrlab/thorium-reader/assets/141128010/9e56cd7b-a18c-4bff-8ff0-dd9313110035)
I call underlined home button start button. 
For me problem is that in some situations Thorium doesn't check if the feed has a title in metadata but writes the title of something that is expected in most cases. For example, when clicking the start button thorium expects the first feed of the catalog and writes its name even if href returns a different feed. The same story with search, I set the title to feed that search href returns but Thorium puts search query as title.

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/blob/558dc8a1b67d154ff9cad355a8f1f40df66ffeac/src/main/converter/opds.ts#L273-L275

**Comment by panaC** [comment]
we change the opds breadcrumb in the new designed Thorium 3.0. The release is coming soon, And you can already try it with the GitHub nightly build. Have a look
