### ISSUE TITLE
Thorium Windows NSIS installer automatically installs, should ask user confirmation

### ISSUE THREAD

**Issue by vivadavid** [edrlab/thorium-reader#1968]
Hi,

I've just installed version 2.3.0 and I've noticed a couple of things:

1. The programme installed itself without asking for my permission. It was automatic.
2. Version 2.3.0 didn't replace version 2.2.0 and, as a result, both versions are available on my PC at the same, each with its own library.

Also, as a separate topic, I read on the changelog that there were some improvements concerning zooming. I was hoping those changes concerned Epub3 with fixed layout, but I didn't notice any difference.

Thanks!

**Comment by danielweck** [comment]
> Version 2.3.0 didn't replace version 2.2.0 and, as a result, both versions are available on my PC at the same, each with its own library.

Interesting. Once again, is this with the Windows installer? (not the Windows Store?)

**Comment by danielweck** [comment]
> I read on the changelog that there were some improvements concerning zooming. I was hoping those changes concerned Epub3 with fixed layout, but I didn't notice any difference.

Try shift-click on images in your fixed-layout documents. With FXL publications the zoom feature requires the `shift` keyboard modifier, as otherwise the functionality causes visual alterations and changes the interaction which interfere with publisher styles and authored scripted activities.
If this doesn't work, then the images are authored using CSS background image which is not supported (they have to be "real" `img` HTML tags or SVG fragments).

We will update the documentation soon ... https://thorium.edrlab.org

**Comment by vivadavid** [comment]
Hi,

I'm sorry I wasn't clearer before. I was referring to the Windows version. Now I understand why I have two versions of the same programme because I must have installed 2.2.0 via Microsoft Store.

As for the silent installation, I did click on the installer on the file explorer but I was expecting a Continue button to proceed.

**Comment by danielweck** [comment]
> As for the silent installation, I did click on the installer on the file explorer but I was expecting a Continue button to proceed.

I am not a Windows user (I only build and occasionally test Thorium from my Windows 11 computer). Do you remember previous version of Thorium installer offering the option to continue or abort?

Thank you!

**Comment by vivadavid** [comment]
I can't remember how the installation took place with previous versions. It may well be the case that I've used the Microsoft Store version for a while.

However, I've just uninstalled both the Microsoft Store version and the other one and then I've run the installer for 2.2.0: it was also a silent installation.

If the user knows about the specific software, the silent installation might just come as a surprise, as Windows users are used to having to read some text and then clicking on _OK_ or _Continue_. However, if the user doesn't know about the software, this silent installation might feel suspicious.

This is, of course, just my opinion for what it's worth. My main reason for this thread was to inform that the new version hadn't replaced the previous one. I'm constantly installing and testing software and, to be honest, I had forgotten I was using the Microsoft Store version.

**Comment by danielweck** [comment]
> This is, of course, just my opinion for what it's worth.

Thank you, I think you are raising an interesting point.

I wonder if a simple tweak in the NSIS configuration (via Electron Builder) would fix this?

https://www.electron.build/configuration/nsis

**Comment by danielweck** [comment]
... I think adding a `license` field would achieve the desired outcome (i.e. user confirmation "I agree" vs. "Cancel").

https://www.electron.build/configuration/nsis#NsisOptions-license

![NSIS](https://github.com/edrlab/thorium-reader/assets/625201/8303fcf2-3dca-476c-b963-c6024042f655)

**Comment by vivadavid** [comment]
I think adding this would be quite useful! It would give the user peace of mind.

**Comment by danielweck** [comment]
I think we need both `oneClick` and `perMachine` set to `false`

https://www.electron.build/configuration/nsis

**Comment by danielweck** [comment]
yes I checked that too when I created the windows installer :)
(choice of global vs. local install, confirm run after install)
