### ISSUE TITLE
About dialogue doesn't display localized content for pt-PT

### ISSUE THREAD

**Issue by horus68** [edrlab/thorium-reader#1969]
When I hit the button for more information on Thorium Reader v2.3.0 
Thorium Reader v2.3.0 
interface set to pt-PT, UI ok, about just shows english version (both files has translations available in github)

About infos for pt-PT (or pt-BR) languages only shows in English (see file name on top "EDRLAB.ThoriumReader-2.3.0en") 
The presented info is for the en code not for pt-PT. 
Note: it works fine for Spanish (es).
![2023-08-03 17_15_04-Thorium - EDRLAB ThoriumReader-2 3 0en](https://github.com/edrlab/thorium-reader/assets/3055443/af8888e3-69ab-4ab7-99a8-6f922d3ddb04)

### Interface its proper translated:

![2023-08-03 17_18_31-Thorium - Meus livros](https://github.com/edrlab/thorium-reader/assets/3055443/251cc222-d9bf-42ff-8a52-8e5a0af025ef)

Thorium Reader v2.3.0 
Windows installer executable
Windows 11 - pt-PT

**Comment by danielweck** [comment]
Hello, thank you for reporting this, and sorry for the bug (looking into it).

I tested all languages and I observe the same problem with:

1) Dutch
2) Portuguese Brazil
3) Portuguese
4) Chinese Traditional
5) Chinese Simplified
6) Catalan
7) Galician
8) Basque
9) Greek
10) Bulgarian
11) Croatian

**Comment by danielweck** [comment]
Working:

1) English `en`
2) French `fr`
3) Finish `fi`
4) German `de`
5) Spanish `es`
6) Japanese `ja`
7) `ka`
8) Lithuanian `lt`
9) Italian `it`
10) Russian `ru`
11) Korean `ko`
12) Swedish `sv`

**Comment by danielweck** [comment]
I am puzzled ... the XHTML files exist in the codebase, but the WebPack copy instruction fails to duplicate them??

https://github.com/edrlab/thorium-reader/tree/develop/src/resources/information

https://github.com/edrlab/thorium-reader/blob/20aa64949f7ff22d131195f8aa38c8ebe0704711/webpack.config.main.js#L182-L189

**Comment by danielweck** [comment]
I found the bug. Fixing ...

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/commit/558dc8a1b67d154ff9cad355a8f1f40df66ffeac
