### ISSUE TITLE
OPDS - Return publication button

### ISSUE THREAD

**Issue by AndroCro99** [edrlab/thorium-reader#1970]
Is it possible to have a return publication button in OPDS publication information dialog?
I can't find rel value for link that signalizes that it is for returning the publication.

**Comment by danielweck** [comment]
With LCP DRM, there is a "return" feature built into the LSD:
https://readium.org/lcp-specs/releases/lsd/latest.html#34-returning-a-publication

...but in Thorium the "return" button is displayed only once the LCP-protected publication is downloaded into the bookshelf (i.e. after it has been borrowed and acquired locally).
