### ISSUE TITLE
Export issue on Windows, due to bad character in file name 

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#1975]
Borrow this book: https://archive.org/details/muybridgescomple01muyb/

Then export it. On a Mac you will obtain 
Muybridge's-Complete-human-and-animal-locomotion-/-all-781-plates-from-the-1887-Animal-locomotion.epub

But on a Windows PC you'll get an empty file with name
Muybridge's-Complete-human-and-animal-locomotion-

**Comment by danielweck** [comment]
https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file

reserved characters:
* `<` (less than)
* `>` (greater than)
* `:` (colon)
* `"` (double quote)
* `/` (forward slash)
* `\` (backslash)
* `|` (vertical bar or pipe)
* `?` (question mark)
* `*` (asterisk)

**Comment by llemeurfr** [comment]
The publication name is "Muybridge's Complete human and animal locomotion : all 781 plates from the 1887 Animal locomotion" and the exported file name is "Muybridge's-Complete-human-and-animal-locomotion-/-all-781-plates-from-the-1887-Animal-locomotion.epub".

For a reason, the ":" is translated to "/". Both are not welcome on Windows, but there is a transform somewhere that could be modified to remove the offending characters. 

A second user came today with the same problem.

**Comment by llemeurfr** [comment]
The request is therefore to 
1) avoid proposing file names with characters that are disallowed on Mac/Windows/Linux.
2) offer the user to change the proposed name before saving.
