### ISSUE TITLE
ODPS 2 facets, when used in sequence, the breadcrumbs keep growing

### ISSUE THREAD

**Issue by gotson** [edrlab/thorium-reader#1982]
I am implementing facets to filter publication feeds.

Here is a sample of my feed (publications omitted for clarity):

```json
{
  "metadata": {
    "title": "Animosity",
    "modified": "2023-08-22T14:07:11+08:00",
  },
  "links": [
    {
      "rel": "self",
      "href": "/opds/v2/opds/v2/series/0DBTWY6Z0KN3J"
    },
    {
      "title": "Home",
      "rel": "start",
      "href": "/opds/v2/catalog"
    },
    {
      "rel": "next",
      "href": "/opds/v2/series/0DBTWY6Z0KN3J?page=1"
    }
  ],
  "facets": [
    {
      "metadata": {
        "title": "Tag"
      },
      "links": [
        {
          "title": "abc",
          "href": "/opds/v2/series/0DBTWY6Z0KN3J?tag=abc",
          "type": "application/opds+json"
        },
        {
          "title": "def",
          "href": "/opds/v2/series/0DBTWY6Z0KN3J?tag=def",
          "type": "application/opds+json"
        }
      ]
    }
  ],
  "publications": []
}
```

Thorium shows the facets on the left alright:
<img width="679" alt="image" src="https://github.com/edrlab/thorium-reader/assets/2139133/a569935b-75b2-4d34-b744-8ef3fdadd3c2">

However, when using different facet one after the other, the breadcrumb list grows:

<img width="752" alt="image" src="https://github.com/edrlab/thorium-reader/assets/2139133/df4d97a0-e8d7-4064-bd82-dcc3d6394111">

Is that a Thorium issue, or a feed issue ?

**Comment by panaC** [comment]
Hello, I added user-interface and ui-critical labels. This will be re-examined in future design work

**Comment by panaC** [comment]
I'm closing the issue, duplicate with #2279
