### ISSUE TITLE
the possibilities of adding bulk ebooks to the library?

### ISSUE THREAD

**Issue by mhussaincov94** [edrlab/thorium-reader#1985]
hi,
would it be possible to have the ability of being able to add say a folder of ebooks to the bookshelf/ library?
maybe a browse button?
it would have to keep track of what publications have been added, which I believe this does.
I would be very greatful if you would considder my request.
thank you for such a great app!
this is accessible with orca the screen reader.
Majidb

**Comment by panaC** [comment]
Hello

Thank you for your interest in our application.

Have you taken a look at our documentation: : https://thorium.edrlab.org/docs/220_organizing/221_libraries/#add-a-book-or-books

we have already a browse button : like a **+** button.

**Comment by panaC** [comment]
I'm closing the issue, feel free to reopen it 👍
