### ISSUE TITLE
Update readme for correct Node Version 16->18

### ISSUE THREAD

**Issue by MikeTheAnomaly** [edrlab/thorium-reader#2018]
I was gonna make a pr but was tldr for pull request requirements. 
But anyways yeah the readme still says 16 when it should be 18. Same thing goes for npm version.

Thanks for all the hard work!

**Comment by panaC** [comment]
fixed with https://github.com/edrlab/thorium-reader/commit/a0e4cc12a9f1afeb28df5c8809847ac9c4cf9297
