### ISSUE TITLE
Unable to download the lcp-pdf file

### ISSUE THREAD

**Issue by chenjiefeng2001** [edrlab/thorium-reader#2024]
Thorium Reader version: **2.3.0**
System: Windows 11
CPU: 12700h
GPU: 3070 laptop
---
It can't download the lcp file, I can't find a setting to set the location of the download file
Error info: The import of *.lcpl failed. Error: download path undefined

**Comment by chenjiefeng2001** [comment]
When I Import the LCPL file which contained form the internet archive library. The Error occured :
---
The First Error::
```
下载01300c7b-211f-4adc-a71e-20dfe1ded196失败: [[AssertionError [ERR_ASSERTION]: http GET error: FetchError: request to https://archive.org/download/natriureticpepti0000unse/natriureticpepti0000unse.lcpdf failed, reason: connect ETIMEDOUT 104.244.46.9:443 (undefined) [https://archive.org/download/natriureticpepti0000unse/natriureticpepti0000unse.lcpdf]]]
```
---
And the it throw the secod error:
```
C:\Users\XXXXXX\Pictures\natriureticpepti0000unse.lcpl失败。Error: download path undefined
```

It looks like relate to the download file path definition. But I can'r find where could set the download path. I'm sure that my internet works well😊

**Comment by chenjiefeng2001** [comment]
> Can you please add precisions of the exact process you follow? is it a .lcpdf file that you are willing to import in the application? What is its supplier?

When I Import the LCPL file which contained form the internet archive library. The Error occured :
The First Error:
```
下载01300c7b-211f-4adc-a71e-20dfe1ded196失败: [[AssertionError [ERR_ASSERTION]: http GET error: FetchError: request to https://archive.org/download/natriureticpepti0000unse/natriureticpepti0000unse.lcpdf failed, reason: connect ETIMEDOUT 104.244.46.9:443 (undefined) [https://archive.org/download/natriureticpepti0000unse/natriureticpepti0000unse.lcpdf]]]
```
And the it throw the secod error:
```
C:\Users\XXXXXX\Pictures\natriureticpepti0000unse.lcpl失败。Error: download path undefined
```
It looks like relate to the download file path definition. But I can'r find where could set the download path. I'm sure that my internet works well😊

**Comment by chenjiefeng2001** [comment]
> > Can you please add precisions of the exact process you follow? is it a .lcpdf file that you are willing to import in the application? What is its supplier?
> 
> When I Import the LCPL file which contained form the internet archive library. The Error occured : The First Error:
> 
> ```
> 下载01300c7b-211f-4adc-a71e-20dfe1ded196失败: [[AssertionError [ERR_ASSERTION]: http GET error: FetchError: request to https://archive.org/download/natriureticpepti0000unse/natriureticpepti0000unse.lcpdf failed, reason: connect ETIMEDOUT 104.244.46.9:443 (undefined) [https://archive.org/download/natriureticpepti0000unse/natriureticpepti0000unse.lcpdf]]]
> ```
> 
> And the it throw the secod error:
> 
> ```
> C:\Users\XXXXXX\Pictures\natriureticpepti0000unse.lcpl失败。Error: download path undefined
> ```
> 
> It looks like relate to the download file path definition. But I can'r find where could set the download path. I'm sure that my internet works well😊

Perhaps this issue is related to thorium not being able to properly connect to the network through the proxy

**Comment by panaC** [comment]
> > > Can you please add precisions of the exact process you follow? is it a .lcpdf file that you are willing to import in the application? What is its supplier?
> > 
> > 
> > When I Import the LCPL file which contained form the internet archive library. The Error occured : The First Error:
> > ```
> > 下载01300c7b-211f-4adc-a71e-20dfe1ded196失败: [[AssertionError [ERR_ASSERTION]: http GET error: FetchError: request to https://archive.org/download/natriureticpepti0000unse/natriureticpepti0000unse.lcpdf failed, reason: connect ETIMEDOUT 104.244.46.9:443 (undefined) [https://archive.org/download/natriureticpepti0000unse/natriureticpepti0000unse.lcpdf]]]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And the it throw the secod error:
> > ```
> > C:\Users\XXXXXX\Pictures\natriureticpepti0000unse.lcpl失败。Error: download path undefined
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It looks like relate to the download file path definition. But I can'r find where could set the download path. I'm sure that my internet works well😊
> 
> Perhaps this issue is related to thorium not being able to properly connect to the network through the proxy

yes that seems to be the reason

**Comment by chenjiefeng2001** [comment]
> > > > Can you please add precisions of the exact process you follow? is it a .lcpdf file that you are willing to import in the application? What is its supplier?
> > > 
> > > 
> > > When I Import the LCPL file which contained form the internet archive library. The Error occured : The First Error:
> > > ```
> > > 下载01300c7b-211f-4adc-a71e-20dfe1ded196失败: [[AssertionError [ERR_ASSERTION]: http GET error: FetchError: request to https://archive.org/download/natriureticpepti0000unse/natriureticpepti0000unse.lcpdf failed, reason: connect ETIMEDOUT 104.244.46.9:443 (undefined) [https://archive.org/download/natriureticpepti0000unse/natriureticpepti0000unse.lcpdf]]]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And the it throw the secod error:
> > > ```
> > > C:\Users\XXXXXX\Pictures\natriureticpepti0000unse.lcpl失败。Error: download path undefined
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > It looks like relate to the download file path definition. But I can'r find where could set the download path. I'm sure that my internet works well😊
> > 
> > 
> > Perhaps this issue is related to thorium not being able to properly connect to the network through the proxy
> 
> yes that seems to be the reason

So it will be fixed in the next version of later? I think it should provide a path selector to let user select where to be storage. And allow user to use the proxy.

**Comment by llemeurfr** [comment]
I tried to download https://archive.org/download/natriureticpepti0000unse/natriureticpepti0000unse.lcpdf using Postman. The http response is 200 = ok; downloading the content (20 MB) took more than 2mn. The remote address was a 207.xxx, i.e. not the 104.xxx IP shown in the Thorium log. 
So yes it may be a proxy issue. 
We know we have such an issue in Thorium (#1904) and we will try to solve it in a future version.
