### ISSUE TITLE
Read Aloud Jumps to Start of File

### ISSUE THREAD

**Issue by dazrand** [edrlab/thorium-reader#2045]
Found an issue when an image has a blank alt attribute on an image, the user has the image selected, read aloud jumps its location to the start of the chapter. This does not occur if the image is not selected, nor does it occur when there is text in the alt attribute. Using Thorium 2.3.0 on macOS 14.1.2.

**Comment by danielweck** [comment]
I believe this was fixed in Thorium 2.4
