### ISSUE TITLE
Translators: Label changed in PR #2036

### ISSUE THREAD

**Issue by horus68** [edrlab/thorium-reader#2050]
Just for your information, there has been a label changed in PR #2036. You should consider updating your translations!
- Change "Export" function to "save-as file" from https://github.com/edrlab/thorium-reader/pull/2036

Details: The dialogue  
`"export": "Export", `
has been changed to 
`"export": "Save as",`

See src/resources/locales/en.json line 71
https://github.com/edrlab/thorium-reader/blob/develop/src/resources/locales/en.json#L71

And the diff file:
https://github.com/edrlab/thorium-reader/pull/2036/files#diff-da7119d1c8c008d685d71dd864febae06da76c518a53683034f8ec52fcece6d8R71:~:text=%22export%22%3A,as%22%2C

**Comment by danielweck** [comment]
That's correct, thank you. I am closing this issue just because there are many other labels to update in Thorium v3 (develop branch now, was in PR until recently)
