### ISSUE TITLE
Add compatibility for .MOBI File Format.

### ISSUE THREAD

**Issue by MonotoneDevelopment** [edrlab/thorium-reader#2058]
The .MOBI file format has already been reverse engineered multiple times, and seeing that this is a multipurpose reader, it should be able to easily compensate for the lack of support.

The best source I could find on designing a reverse-engineering tool is here:

[https://wiki.mobileread.com/wiki/MOBI](url)

Please make this a feature for compatibility, thanks

**Comment by panaC** [comment]
It’s not planned at all, we promote the epub3 format or any Readium Web Publication ( aka https://readium.org/webpub-manifest/ )

You can work on it on your own and make a Thorium fork if you want.
I’m closing the issue, feel free to reopen it if you have more suggestion.
