### ISSUE TITLE
Covers missing when browsing ebooksgratuits OPDS

### ISSUE THREAD

**Issue by horus68** [edrlab/thorium-reader#2068]
The book covers from a particular OPDS (the project "Ebooks libres et gratuits") do not shows when browsing the catalogue. 
Is this an issue related to the OPDS signal or with the books?
Using Thorium v2.3.0

OPDS from the project "Ebooks libres et gratuits"
Site https://www.ebooksgratuits.com
OPDS : https://www.ebooksgratuits.com/opds/
or https://www.ebooksgratuits.org/opds/

See the book Le roi des montagnes - Edmond About (from the OPDS: Catégories et genres / Aventures)
![2024-02-22 09_04_41-Window](https://github.com/edrlab/thorium-reader/assets/3055443/0fd2d8da-afe2-456f-a9df-4fe5fb91e10b)

When a book is added to the library the cover shows fine:
![2024-02-22 09_05_13-Window](https://github.com/edrlab/thorium-reader/assets/3055443/c06c5169-60fe-4628-bb2b-a06616a85bda)

Note: it works fine with other OPDS, as in 
https://www.atramenta.net/opds/catalog.atom

**Comment by panaC** [comment]
Hello, thanks for noticing that. It’s an issue with base64 data url encoding I think  : 

`<link type="image/png" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAqCAIAAACMZMq1AAAQzklEQVRYw81ZaXBcVXY+577X/XrfpG5Z++pVYBvLYMAb2AMYLxiMZzAYxmabmsrUkEwlmeRHwqSKpBgChIRhGzO4BswSiHFhwmrjhd3Y8r5J1mLtUku9qPd+y70nP54ky3jBpJhMulSqbun2feece77vO+dc5JzDD/FCRCK6xAXfufjSX7IQ4nvbCgDnWPBnc4AxdqlrRx9JRIDIEP9fOHCpGxEBkZbNEoDN6RScEwnAM87jJQRi/LN+MAcufWk+Fmv9z1d5Lh2ae11hw2yrzYYwcgj0A1r0ffPZMIzzR0sIRARE8z3pWtNLLzY/9biRTjumTqu67XZf/XRHdY3V4zFNt/u8kmz5v0+hCzhABABqMkkEisctdL1/5/b9v/5rPdxpYphAsZaXeWfNdhRNICDiovT6RWU/uukiifSnwgCejUUAEJwDQaK9rWvrFqWktPb2H0cO7j/ym3/U+jpRJiABAIg5vfPUUHsrAUMA5nT7Kspw8Y0mQV3IgfO+/yExQEQABCTC+xqbNzw7uG1bcNlyV2VVy9NPpU+dYBYCA4AhMAACYICMEAhQLrp5acXta4ixH9Cy/xULERFQ9PixY7/95/g3XzuqKt01tS0bnh36dJdcWEBqRg6EjESKJ4ZREsAAgQDINe3yyjVr7YEC/C4k/8lZCAFSfb0nnnws/tkOpaqqdPWdei4b3fmJs6zEv+jG8EdbJ6xYbZGl2IHGxInDYjiKSMztK7/jnqKr5qAs/zlIaLwDRPlUsuUPL4Y/eI+57KU/uVsAdL/2RyOdCq6+o3TVj4d2fOCvv6xy2Ypkb0//7t2dG/4j39sVWLCofOkyi8NxbmjHp5P5x+8bdXP9xdNyFMREgNj9wXvdr78CwgjNX2IvDLU9/+8U7QcQkiwzSTKXWazWwsmTtYG+bslqr5k69ecPeUpKgTGGKIgAgDEGCERERCNCgcCQmdTGRrWPCC5oGJFZqiAiIpIQgPitcODoApmIgIiESIcHut7+Ly0+JIdKKu9Z37Nrl9rXBTBiiGkJARBiorWt6YnH89H45F/9TfCKK0BigCiIhBAqV5OZhCEMr9OnWBQJJQBQNdXgusPmNLieyqYNoQdcAYtsBcKLBV8IwY18MmVzOZlsEURjbiBjY0cqw2hlNrTnq+SR/cC5f+asgoarej7+EECMxZBGEA5qPN668YXY3q+9c+cF5s7LRCPImMVmt3m9GT3z8an3WwabNK6W+cvLPBUVnhqNqyeHjmq6dnXlvGPhw63R5ngutmTS8rk118nsYrAhziOHDvVs+9BXN6lwzrWesjKGCIhCcDWZtjgcTJZHMEBC5KOxnvfeNaJDksdXcO08q8MhaCRANBJ5My6iZ9tH3a+/BpQ30onWDc8goGR31Ny9rmjW7HePv/3cvidT2rDEJCB0y546/1TVUE8nW6YGph8ZOPhN7+dWyTazdJZOuhAEFxI9zgFxYN/e4088Gv/8M8njDs5fGJxzjaNuisXjyXSeTpw4Pnn9va7KakQciUG6syPe+A0BKAWFofkLTEbCUWpCBEREosi+vdmTx3k2gQwyBw9kDhxCxjyzGmSbEk4OvHPiTQtYy501/dkeAXpaJA9H93IhpgcbfA7fV707ddLvmLZu9fQ7A84CiyRfBADhxsaTjz86/PluxnRIaeH33hncuV0pr7D4/Pm+PmLWmlW3mytlABAGT7S38lgMACxur7es7Lx6KvLa4EfvUiqOEgAwlAlRkKxMWLLcVVHVOHg4q2fWzrh/gqvkZORoz3Bnf7q3I9kesPvmlS/6omdHjufKXVULaxcXukISk8YKwfFaDZwLzmPNTcef/G2y6Zjzsvr0qRbMZ1HikE+ozUdVYFKgqGLdnfaSMhMPMghuZDLRA43CyAEDpbJastnPhyki1eDxAUSksSKUwFFZOWHBQovbnelNS2RZPm1lkbt4kX7D4HD4rWOvtg03V/qqgvaiWCYqQEwJXB50FCEgQ3YupZIQICja1HTsqSeiO7a5rppTe/8vsm2n4gf2RvftoVQckYPNW3rH2ikP/sxeEBilUUCRSWWPHwXOUZatoRCTZfpWm2bymcTk4nLJ6x3pbBABWMmqn/imTmMIAUfB8smrXIpbCGG32j0O77AaE8gdiiNmDA7m+hkwiTGZyQzPU3GYVBc9euTYbx+JfrqdocYkqXh2g/vWlYnu7p6PP25/8Xdaf1/tvffX/eIhZ6hobAeZEHU1x3MZMNmbczhXbkyDbZaiZatCc+czxkYAwtA/abLF7gCC2sK6usKJbsUNgASie7izJdpsBltGmYAAQDU0Qxgj231LsIiG29pOPvt09NMdIDRTUkgIEsLmcaOhinzONnHahOW32r2+MxYiyojIDS4Mg8jEK15ILdEqF8y8ovKGG6VxVQMyBgwRMOAsICAANH8Pa7FoLsyQEZDT4rEzR1ok01pa4zqcnf2m9fnh4VMbng9v/wjtDlIFajnTSkPT2je/1frCc1pfj+R0nH5jU6ZjXvnSZVan05RoGQC0dJprKgIBCZ7NnO8ExAghCULGkLEzGB+RFkBAoJFCn4B00jRSza8SESJDwIye1oV6Xnz1f7a7563X7aWl1qqaxJc7SMsBIue884P32zc8p4W70Ir51lPdbe2RLz4VANUrbpHtdgBgBCQMASgBEAmR72gTqko0ijEitMrMHyDTh1FOPfNjisSoz0IITty0GAgQUAZFBtlhcQCQxlWDG0SCzn4lWltOPfe0kUkVLr4xeM08AgBCrumnt75z4rFHMi2neM4QOQEyMInnO5qbn/rX8P5GruskBANAxeuSrAoAAoEWiaQHw6NdPIAApajU3zAHBAF8d62PiEQimU1EEmEBAgAMYVglRZEVAtC5LkB8ax9hGP1ffpE8etBWNCF45RyLTUECQFA7WjpfekYb6PYvXFDx4AMFNy9Bmw+EQKT86ebud7YY6RQAyUAkyRYcPf98bGhwzzfuVaXAEBEEY57LZgbq65NdXXDRsQMBEVA0E93dtu3owMHT8TYuuCCRNVIMGQLDM1E5K/vVeGxg53bgmuz2eGtrs/39ZiSMSJR53EppWc0DvwxdfXUuPBDesf30i8+pgz1gGMmDjbloRPH7ZRJCsliYLAECIBnx2NBnOyuW3qz19pIh0OYpu+U2e2Ew2dkF59LHeJYi0gxte9MHv298GoCGtajMJCAQJEbHSWB68q0jy0ej6ZPHkAgBZMVKJAiBgKzlFaHFS5Inj/gnTXQVFLiDQV9VdXZwsGfTBpHL6clYun/AVzuRIaLF7XFOqTf7cQQR3/tF86ZXMq3NwCzlq9eUL1kqKQqyi1WOSGRmvN8eWDnl9n+58ak7Lv+pRbKaApI3cirXBFCRs9hldcE4/DNk+UiEp9KII/XKyL8IlNKy4DXXguB6NkdcAJFst1csWSr7CxGJa5qRThGRDIiS0+W78uq+rW9TXkcG6tBA58sbeTzia7imbv0D5uBkRArO23MQpfr6jFzOV1M7v+b6yybMULla65nslF0qV62SLZIdTKsJElRdUOO3+8fO0eSrbDRCqkbjmyEEIkLZQlyo/YOtL74QnzvfVV2dH4rEPt3JUwkCQGRosQCijAxlqyUwcaLkcBn5BACg4Hygw1ZaPeUvfhmYOpUxRgDIRms7xDPzIiIEyMeiLS/+3tByM/7uH/Ky/l7TloMDezNaNi9UswwfVqNZnnHIzurARLtiH1NiNDGhayPlriSbx4gAIMDq9Uo2m5FIdm/eHP5sl7O8OB+J57r6ZUlDIovP7wiGGCIjAiJwVlR5GmYTkwmRiAuuo8NpmVAMiIJzIYQQZNIlCSGEEJxzwyDDyCcSTRtfat/0R7W3x+y9JJKz+ezJyJGsngLCdC5zOtZmkF7tnzir5EogPItBgdDs9QD0TDITiZgfBaItOIEpVltlWd1fPuStnzb8daOrrKz+139rrZ5IAJZQiT0UEpwzU03toVDJDUslu2s0zJDvbGn63b9Fjh0lgPHZaSoXMoYI2cHwiWef7vjD8zans3rtTxWPx+8K3DV7/W8WP7Z2+v122SkzSXA6ETvqVXx3zbi3sqCKnT16QQBnUTGz24GEGu4d/Hy3HouAqku+UGDGFVaHQ2SymZZmfWiAWZkej6baWsXwELO7ihZeZ/P6cWw0Lcly8cKF7voZBBZTrnguM7Tjw6OPPNz1ybZ8ZIh0wzxn4tzI53OD4e5du4888k+dL2/gmXRo6bLCOXPNrRxWR01RXX3RdLMqGch15Y30ouqbr61cwFACAC44kaBRYNlDRbLfB0Ck5nu3bun/+D2wOiruWldy3fVMktShWOSrPej0Fq64RcvrPVs264Nhe+3kCfMXMpsyUgsBACF6q6qr16473tqux/oABCJBPj20a7saGQpPnyVsNp7LpXu7e/fsSbc0pQ7sH245mTx6mJHhmn5l+S232T1uU5sFCd3QhzKDBukAIqZF6gtmXBGc0xPtHpAGAs4Cj8OjoA2AsmoWiGzBYODKa3uaT6BE2ZbjICsFi5bUrb/PVVKa7u6whgJVa+8Lzp1vcbmG9jeeevRhPaOU3bbaU1PLEM90ZMgYEJWvuCXd0d7y5JNM1khwQJIslDp8IHHosOyxA1f73nxl4L835wf69aG4hFxSGCssqV53f2jmFcgYjSpFNBP5vGMnFxwArWjNqJktTa9xMBhKPlugwFG4csodTsW19fjmhrLZC2oXlS5b0f/hVooPEnJmsXhnNrhLSgTnKMhaGCi5aUnB1GlqJtP51utGTg8tWVG35m6r02ny/lmTOcXlrlv/QLa3v3fzG8h0IA5ETGEMCPJpAMi1twEgk0FWZBDIXKFJf/X3lUuXy6NzIUEino2/dmjj0aH9QnAE4EAdqVY9oTEmISACQ8DWSLNFtvQO99YXXQ5EwYbZpavXdL38Euo50nL972721tZU3HATIKAkC8OIt7S0btrY/eprxbeumvTgzx3B4NgVkfTwww+PJ3XF7fFMrc/n1XR7B2h5MkUKzCEOosSYzACBuEWpqp780K9q19xl8/nM3kCQGEyF3zq0aUvTGxrPO2XPRO9lM0Kz6/xTJ3qnyWTRuIYMGGJfplfVtXtmPrCw9kcOq1O22dw1dflMPn2qhbScGu5PNjenwuFkV+fw/r35RKrvnbcj+/bU3fezSfc/4KutG6sjLzBeJ0r39fV+9H7Xu+8M72tEroLBxzoYQsbc7uLly8uWLC9ZcJ3sdI7VQqquvnnw1Y2HnilylC6uXVJTUFfkLPHb/QDAhRjKDnQnOne3fvLNwOdBW9E9Mx9cOm2lx+YhABACAFJdnR1vv9W1ZXOuq11kNLJarV67kcjJwaJAw6yqlSuLb1xqdTjMedbF7geEEIjINS3R2pI8eTzV26cNR0fGQyjZCgu8lVW+WXOcoSAC0OiwSZDgnO/p+LJjuG1GcUNd4US71T7+uoCAOOed0Y69XV8FHIVza+Y7rM7RcQcBESJq6Uz8+LFEe2u2+7ShqoDoqax0FpV4LpvuKi5BE2JnT+nwvNes5o4AQILrubyhqqNlBFnsdouioCQR0Xj7EFEIoXOdc65YFUQUJMyTNpXEJE0EyOkqQ1RkK8A5A0MAEoIbhp7NCc5RYorLyZg0Moo72/SR5+q6fsHblPPOVonE6NQSLnDpQkDjtI9GpBBAmNJrKiWd76FCEBEbl+Iw0kmBKVnnzjLwuy+6z/7She5gxhz4Vo6efwFDoO+4z6VLu8v5H81Tg6drQUybAAAAAElFTkSuQmCC" rel="http://opds-spec.org/thumbnail"/>`

**Comment by panaC** [comment]
Tested and solved in `develop` branch, I don't remember why, but it's fixed as far as I know :)

**Comment by danielweck** [comment]
The data image URL encoding seems to be supported at the parser level:

https://streamer.edrlab.org/opds-v1-v2-convert/https%3A%2F%2Fwww.ebooksgratuits.com%2Fopds%2F

Thorium 2.4.1 and 3.0.0-alpha.1 both show no cover images, but that's because they do not exist in the feed (they only exist at the root, which we only display textually, without images):

https://www.ebooksgratuits.com/opds/feed.php?mode=genre&id=2

https://www.ebooksgratuits.com/opds/
https://streamer.edrlab.org/opds-v1-v2-convert/https%3A%2F%2Fwww.ebooksgratuits.com%2Fopds%2Ffeed.php%3Fmode%3Dgenre%26id%3D2

<img width="1145" alt="Screenshot 2024-05-14 at 17 39 40" src="https://github.com/edrlab/thorium-reader/assets/625201/379fbf3a-cad0-4f32-b422-00d94c2fdaad">


<img width="1244" alt="Screenshot 2024-05-14 at 17 42 08" src="https://github.com/edrlab/thorium-reader/assets/625201/a76afa27-c54c-4b63-b09c-a0c98ecb6706">
