### ISSUE TITLE
Thorium Reader change reading font does not work as expected. H1 does not change.

### ISSUE THREAD

**Issue by riiski** [edrlab/thorium-reader#2073]
Hi,
I have noticed when changing reading fonts in Reader app on Windows that fonts does not change header font. Only "Duospace" font change headers (H1, h2, h3, ...).
In this pic you can see that paragraph font is changed while header font is the same:
![2024-03-05 10_59_27-Thorium - Balansas  Skanus maistas ir sveikos gyvensenos idėjos aktyviems žmonėm](https://github.com/edrlab/thorium-reader/assets/7087900/e0dc98ab-6938-4c8d-9ce6-097f8d57e545)

The code clearly shows that it is h1 header tag on xhtml file:
![2024-03-05 11_00_01-sfr2_balansas_v1 epub - epub3 0 - Sigil](https://github.com/edrlab/thorium-reader/assets/7087900/38d20d24-dc8b-4629-8a41-d02088bf759a)

And css values on the h1 tag:
![2024-03-05 11_00_19-sfr2_balansas_v1 epub - epub3 0 - Sigil](https://github.com/edrlab/thorium-reader/assets/7087900/5ea3cd25-8ca7-41af-9578-be93d1830577)

**Comment by danielweck** [comment]
Hello, thank you very much for reporting this issue. I transferred it in the ReadiumCSS project: https://github.com/readium/readium-css/issues/112
