### ISSUE TITLE
Add 'Mouse Buttons' to options when editing 'Keyboard shortcuts' in settings

### ISSUE THREAD

**Issue by qushot** [edrlab/thorium-reader#2075]
I want to set side buttons for 'NavigateNextPage' and 'NavigatePreviousPage' respectively.

**Comment by panaC** [comment]
You have to remap your mouse side button to a keyboard key sequence and then configure the keyboard shortcut in Thorium. 

Look at your mouse software or other mapping software.

I’m closing the issue, feel free to reopen it.
