### ISSUE TITLE
Not compliant with the style sheets used

### ISSUE THREAD

**Issue by CLnordcompo** [edrlab/thorium-reader#2078]
Here is the problem:
Thorium poorly manages the size of titles and intertitles.
It supports h1, h2, h3 tags and assigns a default size, depending on the size configured in user style sheets.
This is not the case for other e-readers (ADE, iPad, etc.).
Often implying that the same box title does not have the same rendering on the same work, the size depends on the level to which the box belongs.
I am attaching a snippet of epub, with corresponding CSS, illustrating the case.
[Test.zip](https://github.com/edrlab/thorium-reader/files/14633972/Test.zip)

Thanks in advance

**Comment by danielweck** [comment]
Thank you for your feedback and clear description of the problem. This is a known issue in ReadiumCSS, I am adding your comment to the correct GitHub repository.

**Comment by danielweck** [comment]
see https://github.com/readium/readium-css/issues/112
