### ISSUE TITLE
Feature request: add "infinite scroll" viewing mode

### ISSUE THREAD

**Issue by absolutelynothinghere** [edrlab/thorium-reader#2079]
While reading EPUB files in scrollable mode, transitions from one chapter to the next are sudden and jarring. Is it possible to implement an "infinite scrolling" option where chapters are displayed one after the other, without jumps? Thank you.

**Comment by danielweck** [comment]
Hello, I am afraid this is not on the roadmap and it would be a significant undertaking / departure from the current rendering model. We learned from our experience with a previous incarnation of Readium that there are several edge cases (e.g. font loading and rendering) that make it hard to reliably present reflowable documents in a contiguous smooth fashion. This is not technically impossible (we did in fact mitigate some of the unwanted behaviour / layout glitches) but the development and maintenance cost is just not justified at this point in time in the Thorium project.
