### ISSUE TITLE
No error messages in LCP renew toast notification just a json status printed

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#2085]
Renew spec : https://readium.org/lcp-specs/releases/lsd/latest#35-renewing-a-license

Maybe same error for the Return : https://readium.org/lcp-specs/releases/lsd/latest#34-returning-a-publication

The http code and Problem Details JSON is not parsed

**Comment by panaC** [comment]
https://readium.org/lcp-specs/releases/lsd/latest#31-handling-errors

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/blob/1917addafad34c58bbe1a26ff6cff08a089002e2/src/main/services/lcp.ts#L1141-L1176

**Comment by danielweck** [comment]
Hello @panaC was this fixed according to your LCP/LSD tests after the refactoring?

**Comment by danielweck** [comment]
Ping @panaC (see above message)

**Comment by panaC** [comment]
I will check
