### ISSUE TITLE
ability to adjust dark mode.

### ISSUE THREAD

**Issue by AommyPatty** [edrlab/thorium-reader#2087]
The text in Dark mode is still too bright for me. It'd be great if I could get a little bit darker of texts such as the picture below.
![image](https://github.com/edrlab/thorium-reader/assets/107844685/a8dbab80-f508-433c-8ba4-ced6bade21cc)

**Comment by danielweck** [comment]
Thorium 3 introduces additional colour themes. I am closing this issue and I expect further user feedback based on the GUI refactoring. Windows high-contrast support coming in 3.1 later this year.
