### ISSUE TITLE
supporting .m4b

### ISSUE THREAD

**Issue by Aces-and-Jacks** [edrlab/thorium-reader#2094]
.m4b is a audiobook format that's used by other readers but isn't supported here. At least when I tried importing one.

**Comment by danielweck** [comment]
I am afraid there are no plans to support M4B chapterised audio books. I am not aware of a pure Javascript (NodeJS) implementation of a parser / converter (metadata + audio codec) for this format, so best would be to transform the files outside of Thorium and import a compatible Readium "audiobook" (simple JSON publication manifest that puts together a track list with a table of contents)
