### ISSUE TITLE
HTML in footnotes does not render correctly

### ISSUE THREAD

**Issue by Kamik423** [edrlab/thorium-reader#2098]
When the footnote contains HTML-Structures like divs or spans it does not render correctly but display the HTML code instead.

![grafik](https://github.com/edrlab/thorium-reader/assets/16278233/2a79d274-dc2c-460c-b137-c50a866a5694)

**Comment by danielweck** [comment]
Hello, thank you for reporting this problem. HTML markup is supported in popup footnotes. The display of source code normally only occurs when the HTML XML is invalid (or to be precise: not well formed, syntactically-speaking).

Could you please share the EPUB so I can reproduce the problem at my end?

Thank you very much!

**Comment by Kamik423** [comment]
I uploaded a test EPUB [here](https://neu.cloud.pagina.gmbh/s/KzBEFHjwaRGcH5Q), this seems like valid XHTML to me.

**Comment by danielweck** [comment]
The Javascript / DOM error messages are:

`Error: Failed to execute 'insertAdjacentHTML' on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document`

`Namespace prefix epub for type on div is not defined`

**Solution**: add the following XML / XHTML attribute to the `html` root element of your HTML documents: `xmlns:epub="http://www.idpf.org/2007/ops"`.
