### ISSUE TITLE
[new GUI] regression? huge top/bottom padding in paginated view, not in scrolling view

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2100]
Is this an intentional design decision?
There is now lots of wasted vertical space in paginated mode, strangely not in scrolling mode:

<img width="1680" alt="Screenshot 2024-04-20 at 10 40 47" src="https://github.com/edrlab/thorium-reader/assets/625201/12b76ffa-b661-4e25-b2e1-d81982a2b255">

**Comment by danielweck** [comment]
<img width="1237" alt="Screenshot 2024-04-20 at 10 46 34" src="https://github.com/edrlab/thorium-reader/assets/625201/37da6338-62f6-49fc-ba44-6a01a267e782">

**Comment by arthur-lemeur** [comment]
This was a design decision made by Laurent. After a second look 100px might be a bit much, I'll change it to 75px in the next PR.
