### ISSUE TITLE
Add new keyboard shortcut for annotation in readerView

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#2111]

**Comment by danielweck** [comment]
TODO: CTRL+A is "select all", must find a different keyboard shortcut.

**Comment by panaC** [comment]
Sure, what do you propose ? Ctrl+N ?

**Comment by danielweck** [comment]
Fun fact: CTRL+M (even with additional SHIFT ALT/OPT and META/CMD on MacOS) seems to trigger some user controls, which really confused me when I was testing with the keyboard focus somewhere in the toolbar of icon-buttons.

Anyway, I pushed to `develop` a renaming of the keyboard shortcuts "keys" (for consistency with all the other ones), and I changed to Q for "quick", A for "annotation", Z for ... well, it's just next to Q and A on the keyboard and doesn't cause problems (unlike M) for "margin". That's all 3 with the SHIFT CTRL ALT/OPT modifiers, so not the easiest to hit but we know that Thorium's keyboard shortcut scheme is not great anyway (needs complete testing on Windows, Mac, Linux, with and without screen readers ... I am sure there are conflicts in the test matrix, in addition to anti-patterns or abuse of reserved semantics on some OS)
