### ISSUE TITLE
Raise an error message if an encrypted EPUB with no embedded license is side-loaded 

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#2114]
This should not happen, but we've seen in the wild an encrypted EPUB (the output of the LCP encryption tool) being available for download on a library website. Thorium accepts to open it, but display garbage on screen.

Thorium should instead show an error message like "This encrypted EPUB does not contain a required LCP license; it is therefore invalid."

**Comment by panaC** [comment]
https://github.com/readium/r2-shared-js/blob/528b889cfeadb5b775483be881d6c8a603a6ca70/src/parser/epub.ts#L246

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/pull/2637
