### ISSUE TITLE
[new GUI] regression: TTS captions mode is broken (nothing happens when I tick the checkbox), also skippability

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2121]
<img width="1383" alt="Screenshot 2024-05-02 at 22 01 43" src="https://github.com/edrlab/thorium-reader/assets/625201/3b5a9754-6941-492c-a72d-75df2ff55a06">

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/blob/834927c29e805ebe8933d7aa1663138dd62564d5/src/renderer/reader/components/ReaderSettings.tsx#L575

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/blob/834927c29e805ebe8933d7aa1663138dd62564d5/src/renderer/reader/components/ReaderHeader.tsx#L776

**Comment by panaC** [comment]
When i tick the checkbox `set_config` is dispatched : 

```{
  type: 'READER_SET_CONFIG_IN_RENDERER',
  payload: {
    align: 'auto',
    colCount: '2',
    dark: false,
    font: 'OLD',
    fontSize: '100%',
    invert: false,
    lineHeight: '0',
    night: false,
    paged: true,
    readiumcss: true,
    sepia: false,
    enableMathJax: false,
    reduceMotion: false,
    noFootnotes: false,
    pageMargins: '0.5',
    wordSpacing: '0',
    letterSpacing: '0',
    paraSpacing: '0',
    mediaOverlaysEnableSkippability: true,
    mediaOverlaysEnableCaptionsMode: true,
    ttsEnableOverlayMode: false,
    ttsEnableSentenceDetection: true,
    annotation_defaultColor: {
      red: 193,
      green: 234,
      blue: 197
    },
    annotation_defaultDrawType: 'outline',
    annotation_popoverNotOpenOnNoteTaking: false,
    annotation_defaultDrawView: 'annotation',
    theme: 'neutral'
  }
}
```

When i tick it again : 

```
{
  type: 'READER_SET_CONFIG_IN_RENDERER',
  payload: {
    align: 'auto',
    colCount: '2',
    dark: false,
    font: 'OLD',
    fontSize: '100%',
    invert: false,
    lineHeight: '0',
    night: false,
    paged: true,
    readiumcss: true,
    sepia: false,
    enableMathJax: false,
    reduceMotion: false,
    noFootnotes: false,
    pageMargins: '0.5',
    wordSpacing: '0',
    letterSpacing: '0',
    paraSpacing: '0',
    mediaOverlaysEnableSkippability: true,
    mediaOverlaysEnableCaptionsMode: false,
    ttsEnableOverlayMode: false,
    ttsEnableSentenceDetection: true,
    annotation_defaultColor: {
      red: 193,
      green: 234,
      blue: 197
    },
    annotation_defaultDrawType: 'outline',
    annotation_popoverNotOpenOnNoteTaking: false,
    annotation_defaultDrawView: 'annotation',
    theme: 'neutral'
  }
}
``` 

see the key `mediaOverlaysEnableCaptionsMode`

**Comment by danielweck** [comment]
Some logic was lost during the GUI refactor because there is TTS and MediaOverlays separately (originally):


https://github.com/edrlab/thorium-reader/blob/834927c29e805ebe8933d7aa1663138dd62564d5/src/renderer/reader/components/Reader.tsx#L2811-L2812

https://github.com/edrlab/thorium-reader/blob/834927c29e805ebe8933d7aa1663138dd62564d5/src/renderer/reader/components/Reader.tsx#L2693-L2694

https://github.com/edrlab/thorium-reader/blob/834927c29e805ebe8933d7aa1663138dd62564d5/src/renderer/reader/components/ReaderSettings.tsx#L568-L577

**Comment by danielweck** [comment]
Same with skippability which seems to have been badly ported during the GUI refactor:

https://github.com/edrlab/thorium-reader/blob/834927c29e805ebe8933d7aa1663138dd62564d5/src/renderer/reader/components/Reader.tsx#L2690-L2692

https://github.com/edrlab/thorium-reader/blob/834927c29e805ebe8933d7aa1663138dd62564d5/src/renderer/reader/components/ReaderSettings.tsx#L578-L587
