### ISSUE TITLE
[new GUI] Media Overlays audio playback speed selector does not select (but does activate the selected speed) works with TTS

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2122]
I can hear the speed change, but I cannot see the selected speed:

<img width="712" alt="Screenshot 2024-05-03 at 01 51 17" src="https://github.com/edrlab/thorium-reader/assets/625201/ffd65b7d-1e48-41e8-8f6f-8eceb65794e0">

**Comment by arthur-lemeur** [comment]
I cannot replicate this on develop. When I change the speed, I can hear it and see it, the select closes and the value in the input changes accordingly and when I open the list again I can see the check icon next to the current selected speed, same if I close the popover and open it back. Both in neutral and night modes.

**Comment by danielweck** [comment]
This bug only occurs with Media Overlays publications, works fine otherwise with TTS readaloud
