### ISSUE TITLE
low contrast popup modal dialog in dark mode

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2130]
it seems some dialogs have extra outline  / shadow to demarcate their perimeter from the inert background (e.g. in the reader view) but not all. Can this style be harmonised across the board?

<img width="773" alt="Screenshot 2024-05-03 at 20 21 45" src="https://github.com/edrlab/thorium-reader/assets/625201/42d3c599-520e-442a-a3b0-29aa2a1b4cca">

**Comment by panaC** [comment]
![image](https://github.com/edrlab/thorium-reader/assets/3198865/d660fa44-8e1f-481a-8acc-8c1e6efd2314)

fixed on develop

**Comment by danielweck** [comment]
Oh I like that visible outline :) Thank you @arthur-lemeur 
Can we have this beautiful and accessible contrasted style everywhere please (we're nearly there, to be fair ... well done!)
