### ISSUE TITLE
combo box with search, long text in option causes horizontal scroll 

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2131]
low priority, but just in case this can be fixed by adding clipping and ellipsis (+ tooltip / accessible full text)

<img width="839" alt="Screenshot 2024-05-03 at 09 33 41" src="https://github.com/edrlab/thorium-reader/assets/625201/45b664ef-471d-444f-a6d7-7f2434d9c06a">

**Comment by panaC** [comment]
![image](https://github.com/edrlab/thorium-reader/assets/3198865/e8b6f49c-0b9f-41b7-91d5-898bfa0520d3)


not yet resolved on develop
