### ISSUE TITLE
In language settings, Simplified Chinese and Traditional Chinese options are reversed

### ISSUE THREAD

**Issue by Dawn-K** [edrlab/thorium-reader#2134]
I think there is an ambiguity in the Chinese language in the language settings. `zh-cn` is `简体中文`, corresponding to `Simplified`. And `zh-tw` is `繁体中文`, corresponding to `Traditional`.

Now, the effect of selecting Chinese trad is as shown below. You can see that the title bars above are all in simplified Chinese:
![selecting Chinese trad.](https://github.com/edrlab/thorium-reader/assets/32976579/123a57d0-9809-4523-9c26-19282c90e5a0)

Now, the effect of selecting Chinese simp is as shown below. You can see that the title bars above are all in traditional Chinese:
![selecting Chinese simp](https://github.com/edrlab/thorium-reader/assets/32976579/0fca86ed-9d5a-48c3-b00d-a86116dcecf8)

**Comment by danielweck** [comment]
Thank you so much for reporting this bug! I think I corrected it, could you please confirm:

https://github.com/edrlab/thorium-reader/blob/9cc1b8eb202e55dc45ed5e73a02597d504fa5898/src/common/services/translator.ts#L179-L180
