### ISSUE TITLE
annotations and bookmarks can too easily be deleted (no undo/redo, no confirmation dialog)

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2138]
<img width="806" alt="Screenshot 2024-05-06 at 10 46 15" src="https://github.com/edrlab/thorium-reader/assets/625201/6e336648-4df4-4822-baaf-32511ca32ddd">

**Comment by llemeurfr** [comment]
Let's do the same as for tag deletion .

![Image](https://github.com/edrlab/thorium-reader/assets/14943186/6f1120a6-b0e9-4349-b393-78e1e16ffe28)
