### ISSUE TITLE
Annoying "do you want to save the session" user prompt ... what does it do, why as sometimes, not all the time??

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2140]
<img width="437" alt="Screenshot 2024-05-06 at 11 45 53" src="https://github.com/edrlab/thorium-reader/assets/625201/dc15523b-b217-4c91-a047-972bb95fd18a">

I do not understand this feature, so I suspect non-developer users will struggle too.
This seems to cause unnecessary friction in the experience as it forces users to make an obscure decision at the point of closing the application.
This feels just like the annoying "cookie banners" on the web ... in the end I just hit yes or no, it doesn't matter as long as the dialog closes :)

**Comment by danielweck** [comment]
@panaC I assigned you to this one as I believe you are the "session" expert ;)
If I remember correctly, in Thorium3 each publication maintains its own preferences, right? (colour theme, font size etc.)
in Thorium2 this was an opt-in feature which was already poorly understood ("activate session" in top-level library preferences + "save session" / "reset session" in reader menus)

**Comment by panaC** [comment]
I keep the session mode previously developed in Thorium, each reader window is independent and rely to the same global readerConfigState.

**Comment by panaC** [comment]
The steps : 

1/ add a new publication and open it, borrow the global readerConfigState
2/ set/update the readerConfig -> update the readerConfigState of the publication but **also** update the global readerConfigState
3/ now your publication has "forked" the readerConfigState and do not rely on it if you update it in an another publication
4/ update an another publication and do the change for your publication only
5/ add a new publication in Library and open it, readerConfigState will be to the state of any publication last changed.
6/ you have more than one publication opened and the library window so 3 windows, you want to close Thorium and close the libraryWin, Thorium will ask you if you "do you want to save the session" in a message box, 2 solutions :
- accept and click on yes : On next Thorium open, all 3 windows will be restored and your publications in your last state before the closing
- do not accept and click on no : so Thorium will close and save your 2 reader windows the state is saved and on the next open only library window will be open. Your publication state is saved.

**Comment by danielweck** [comment]
> 6/ you have more than one publication opened and the library window so 3 windows, you want to close Thorium and close the libraryWin, Thorium will ask you if you "do you want to save the session" in a message box, 2 solutions :
> 
>     * accept and click on yes : On next Thorium open, all 3 windows will be restored and your publications in your last state before the closing
> 
>     * do not accept and click on no : so Thorium will close and save your 2 reader windows the state is saved and on the next open only library window will be open. Your publication state is saved.

Ok, thank you for explaining. So this is about re-opening the reader windows that were previously open when the application was last closed.

Maybe this should be a global preference, just like some code IDEs, web browsers (no need to ask each time). By default, restore the reader windows because the assumption is: user mistakenly closed the library window (META+Q on MacOS typo ... I often do this so my code IDEs ask before closing ;) OR the user intentionally closed the app but probably will be happy to see the abandoned reader windows again on next launch ... if not, user can disable this default behaviour in settings.

Simple checkbox, ticked by default (boolean true): "Restore closed reader windows"

What do you think?

**Comment by panaC** [comment]
> > 6/ you have more than one publication opened and the library window so 3 windows, you want to close Thorium and close the libraryWin, Thorium will ask you if you "do you want to save the session" in a message box, 2 solutions :
> > ```
> > * accept and click on yes : On next Thorium open, all 3 windows will be restored and your publications in your last state before the closing
> > 
> > * do not accept and click on no : so Thorium will close and save your 2 reader windows the state is saved and on the next open only library window will be open. Your publication state is saved.
> > ```
> 
> Ok, thank you for explaining. So this is about re-opening the reader windows that were previously open when the application was last closed.
> 
> Maybe this should be a global preference, just like some code IDEs, web browsers (no need to ask each time). By default, restore the reader windows because the assumption is: user mistakenly closed the library window (META+Q on MacOS typo ... I often do this so my code IDEs ask before closing ;) OR the user intentionally closed the app but probably will be happy to see the abandoned reader windows again on next launch ... if not, user can disable this default behaviour in settings.
> 
> Simple checkbox, ticked by default (boolean true): "Restore reader windows"
> 
> What do you think?



> > 6/ you have more than one publication opened and the library window so 3 windows, you want to close Thorium and close the libraryWin, Thorium will ask you if you "do you want to save the session" in a message box, 2 solutions :
> > ```
> > * accept and click on yes : On next Thorium open, all 3 windows will be restored and your publications in your last state before the closing
> > 
> > * do not accept and click on no : so Thorium will close and save your 2 reader windows the state is saved and on the next open only library window will be open. Your publication state is saved.
> > ```
> 
> Ok, thank you for explaining. So this is about re-opening the reader windows that were previously open when the application was last closed.
> 
> Maybe this should be a global preference, just like some code IDEs, web browsers (no need to ask each time). By default, restore the reader windows because the assumption is: user mistakenly closed the library window (META+Q on MacOS typo ... I often do this so my code IDEs ask before closing ;) OR the user intentionally closed the app but probably will be happy to see the abandoned reader windows again on next launch ... if not, user can disable this default behaviour in settings.
> 
> Simple checkbox, ticked by default (boolean true): "Restore reader windows"
> 
> What do you think?

Personally, I think we need to debate the session process in a meeting with all the team

**Comment by panaC** [comment]
not an issue, more a discussion
