### ISSUE TITLE
Can't open LCP protected books

### ISSUE THREAD

**Issue by Hoppipollala** [edrlab/thorium-reader#2142]
I tried 2 different libraries, and I can't open LCP protected books. The error message : "Passphrase incorrect"

![Capture d’écran 2024-05-06 à 14 52 22](https://github.com/edrlab/thorium-reader/assets/22544556/2f9dd76b-1c53-4af2-979f-c3945ad25bc0)

![Capture d’écran 2024-05-06 à 14 55 13](https://github.com/edrlab/thorium-reader/assets/22544556/fd6be0df-8ece-423d-ad1d-59340e78dc3a)

**Comment by danielweck** [comment]
that's normal, dev / test builds do not support LCP. only official releases do.
