### ISSUE TITLE
keyboard tab cycling gets stuck in the upper left corner when reverse tabbing (SHIFT TAB)

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2148]
<img width="802" alt="Screenshot 2024-05-06 at 18 31 22" src="https://github.com/edrlab/thorium-reader/assets/625201/cd1b7848-f4ff-45cf-bbe7-2d19fe491d27">

**Comment by danielweck** [comment]
<img width="802" alt="Screenshot 2024-05-06 at 18 33 49" src="https://github.com/edrlab/thorium-reader/assets/625201/090431d9-e793-47e4-b70d-1638381d678f">

**Comment by panaC** [comment]
https://github.com/radix-ui/primitives/blob/b32a93318cdfce383c2eec095710d35ffbd33a1c/packages/react/dialog/src/Dialog.tsx#L397C11-L397C15

https://github.com/radix-ui/primitives/blob/b32a93318cdfce383c2eec095710d35ffbd33a1c/packages/react/focus-scope/src/FocusScope.tsx#L197

**Comment by panaC** [comment]
As far I know, I'm stuck on this issue

**Comment by panaC** [comment]
I need help @danielweck to solve this issue

**Comment by panaC** [comment]
https://github.com/radix-ui/primitives/issues/966

**Comment by danielweck** [comment]
Will it be possible for Thorium to ultimately rely on a *single* technology solution like Adobe Spectrum / React ARIA Components (which under the hood uses React Stately and React ARIA Hooks), and avoid mixing other keyboard/focus-handling components from Radix?
My understanding is that RACs are systematically and methodically tested with screen readers, with a great level of attention to detail. I am not sure that Radix focusses as hard on solving the finer issues. Maybe I am wrong though, not speaking from experience, just from listening / reading other developers' feedback.

**Comment by danielweck** [comment]
Duplicate: https://github.com/edrlab/thorium-reader/issues/2147
