### ISSUE TITLE
click outside dialog modal does not close it (works with publication info, not with reader modals)

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2149]
<img width="1171" alt="Screenshot 2024-05-06 at 18 44 59" src="https://github.com/edrlab/thorium-reader/assets/625201/cc02107a-44f5-4f01-bc27-9c8250818a2c">
<img width="1171" alt="Screenshot 2024-05-06 at 18 45 29" src="https://github.com/edrlab/thorium-reader/assets/625201/c158b695-5588-4467-848e-d8331f05e1f4">

**Comment by panaC** [comment]
will be fixed by #2143

**Comment by danielweck** [comment]
Works:

<img width="1244" alt="Screenshot 2024-05-14 at 09 12 17" src="https://github.com/edrlab/thorium-reader/assets/625201/0c91f0ce-74c3-4d9f-937c-09fb641c21a0">


<img width="1244" alt="Screenshot 2024-05-14 at 09 12 44" src="https://github.com/edrlab/thorium-reader/assets/625201/b3b8780e-26f2-43a8-a2fc-02df7232409b">


Does not work:

<img width="1244" alt="Screenshot 2024-05-14 at 09 12 26" src="https://github.com/edrlab/thorium-reader/assets/625201/28c10681-ac7f-4679-a526-3b27b2706b5b">


<img width="1244" alt="Screenshot 2024-05-14 at 09 12 22" src="https://github.com/edrlab/thorium-reader/assets/625201/ac94faba-c5ef-41ba-aaca-0e9b2d73e1d9">
