### ISSUE TITLE
tab keyboard is completely stuck in docked TOC (not in settings docked)

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2150]
<img width="1171" alt="Screenshot 2024-05-06 at 18 48 58" src="https://github.com/edrlab/thorium-reader/assets/625201/a26f43ec-23fc-46ab-9bb4-0439643d1e6d">

**Comment by danielweck** [comment]
This happens after opening the settings docked panel (works fine before)

**Comment by panaC** [comment]
seems fixed by #2143

**Comment by panaC** [comment]
fixed by #2143

**Comment by danielweck** [comment]
confirmed too.

however, reverse-tabbing is broken (stuck) in popup modal:

<img width="1244" alt="Screenshot 2024-05-14 at 18 05 16" src="https://github.com/edrlab/thorium-reader/assets/625201/1490a4a0-22a5-42bc-a9a0-bd07f92b759f">
<img width="1244" alt="Screenshot 2024-05-14 at 18 03 16" src="https://github.com/edrlab/thorium-reader/assets/625201/1e13593d-9f93-423d-ba89-171c5979256c">
