### ISSUE TITLE
keyboard focus outline is barely visible with some GUI controls 

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2155]
<img width="800" alt="Screenshot 2024-05-06 at 20 22 14" src="https://github.com/edrlab/thorium-reader/assets/625201/20609e1c-1cb4-41f3-891e-13c86081ce37">

**Comment by danielweck** [comment]
<img width="800" alt="Screenshot 2024-05-06 at 20 22 18" src="https://github.com/edrlab/thorium-reader/assets/625201/e1a4e1ce-17f7-42bd-9cb8-966d162786a2">

**Comment by danielweck** [comment]
My personal wish is that the bright contrasted blue outline which was displayed in Thorium2 during keyboard interactions (not mouse / pointing device) will come back in Thorium3. I appreciate that the design decisions will naturally not please everybody, but in this case I think Thorium is loosing a quality of interaction that was appreciated by keyboard users: clear indication of focus with an outline that differentiates itself from the rest of the GUI, much like screen reader focus rings. The contrasted blue outline looks less "pretty" (more out of place) in Thorium2, but it has a very utilitarian value which does not affect mouse users, only benefits keyboard users. See screenshot below (the navigator continues to use the blue focus ring, it works well in both dark and light modes):

<img width="439" alt="Screenshot 2024-05-06 at 20 22 58" src="https://github.com/edrlab/thorium-reader/assets/625201/a47d8ccf-708d-41fb-95b3-b03b35d8ce64">

I am adding @llemeurfr here as this is a "product owner" decision, ultimately.

**Comment by danielweck** [comment]
another invisible keyboard focus outline:

<img width="459" alt="Screenshot 2024-05-10 at 18 39 02" src="https://github.com/edrlab/thorium-reader/assets/625201/8dbdb9b2-8dd7-4125-9086-d7384ffaf291">

**Comment by panaC** [comment]
seems fixed : 

<img width="273" alt="image" src="https://github.com/edrlab/thorium-reader/assets/3198865/b964b697-5f37-4482-ba26-edc66fd7be81">

I'm closing
