### ISSUE TITLE
[New GUI] Comparison Figma Designs/Alpha – Light mode

### ISSUE THREAD

**Issue by Hoppipollala** [edrlab/thorium-reader#2156]
Comparaison maquettes/version alpha (WIP).

### Navigation principale

La couleur des icônes ne correspond pas à celle des maquettes.

Alpha version : 
![Capture d’écran 2024-05-06 à 14 18 57](https://github.com/edrlab/thorium-reader/assets/22544556/6edddfab-015a-40f3-8a9a-0bfa210f779d)

Figma version : 
![Capture d’écran 2024-05-06 à 14 19 53](https://github.com/edrlab/thorium-reader/assets/22544556/457e4bb4-508b-4b27-945a-d812ccaf27e4)

### Bouton Importer
Les états survol/focus ne correspondent pas.

Alpha version : 
![Capture d’écran 2024-05-07 à 08 39 43](https://github.com/edrlab/thorium-reader/assets/22544556/7966bf8f-4efc-49c6-93d7-665b3f0a5901)

Figma version : 
![Capture d’écran 2024-05-07 à 08 38 44](https://github.com/edrlab/thorium-reader/assets/22544556/d9be665a-e795-4942-af56-14a3a0e8c600)

### Menus contextuels
Le survol/focus des options du menu contextuel ne correspond pas

Alpha version : 
![Capture d’écran 2024-05-07 à 08 36 41](https://github.com/edrlab/thorium-reader/assets/22544556/04aa32a5-c259-4e41-a6f9-9ed5efbdd929)

Figma version : 
![Capture d’écran 2024-05-07 à 08 36 32](https://github.com/edrlab/thorium-reader/assets/22544556/3b26dd45-74e0-476b-b03a-6e674b2eca84)

### Mots-clefs
Alpha version : 
![Capture d’écran 2024-05-07 à 08 57 59](https://github.com/edrlab/thorium-reader/assets/22544556/a11e2f42-3ab2-4fbf-99a0-0a469ea0e23c)

Figma version : 
![Capture d’écran 2024-05-07 à 08 56 10](https://github.com/edrlab/thorium-reader/assets/22544556/fa2c2f66-905c-488f-9952-d465a10dfa63)

### Home – Empty state
L'icône du bouton collapse ne correspond pas aux maquettes : 

Alpha version : 
![Capture d’écran 2024-05-06 à 14 27 07](https://github.com/edrlab/thorium-reader/assets/22544556/d3dfe627-b9f2-4708-9899-4b5b44947f51)

Figma version : 
![Capture d’écran 2024-05-06 à 14 39 22](https://github.com/edrlab/thorium-reader/assets/22544556/2f9bbe56-2bb9-4e23-a4fb-0c8102d63356)

### Settings – Dropdown
Le survol/focus des options des dropdown ne correspond pas.

Alpha version : 
![Capture d’écran 2024-05-07 à 08 29 39](https://github.com/edrlab/thorium-reader/assets/22544556/22e7a9d2-b53a-4a25-be45-1359924391f9)

Figma version : 
![Capture d’écran 2024-05-07 à 08 28 27](https://github.com/edrlab/thorium-reader/assets/22544556/0b97b551-d634-45e7-8b77-2dd28ce77437)

### Raccourcis clavier
La prise de focus ne s'affiche pas sur les boutons 

Alpha version : 
![Capture d’écran 2024-05-07 à 08 32 43](https://github.com/edrlab/thorium-reader/assets/22544556/3ea72ecc-a876-4ab9-8a17-4c3ca57dc623)

**Comment by rahaaatul** [comment]
Slick. Add dark mode too.

**Comment by danielweck** [comment]
Will all be fixed via https://github.com/edrlab/thorium-reader/pull/2159  (to be confirmed point-by-point)
