### ISSUE TITLE
annotations: Thorium says "no selection" but there is one

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2162]
To reproduce:
1) select text with mouse cursor
2) click on the annotations icon in the top toolbar => the popout editor is displayed
3) press escape (cancel / close the popout)
4) click on the icon again ... Thorium says "no selection" yet it is still here, unchanged

<img width="1058" alt="Screenshot 2024-05-10 at 18 41 16" src="https://github.com/edrlab/thorium-reader/assets/625201/97b2398f-2331-4d7e-a05d-59ea09e44216">

**Comment by danielweck** [comment]
PS: note the poor contrast ratio between selection and foreground colours ... this will be fixed by https://github.com/edrlab/thorium-reader/pull/2106

**Comment by panaC** [comment]
culprit : https://github.com/edrlab/thorium-reader/blob/97cd820bce2bef818c735021d2175508a5de4f24/src/renderer/reader/redux/sagas/annotation.ts#L127 
need to re-loop on
https://github.com/edrlab/thorium-reader/blob/97cd820bce2bef818c735021d2175508a5de4f24/src/renderer/reader/redux/sagas/annotation.ts#L183-L183
