### ISSUE TITLE
Double click to open a EPUB on Windows?

### ISSUE THREAD

**Issue by seaspeak** [edrlab/thorium-reader#2163]
Windows or Store version Thorium.Setup.2.4.1 won't open the clicked EPUB.
I am always using Thorium.Setup.2.3.0-alpha.1.3658607447.exe, It is the only version I konw, could open the double-clicked EPUB.

**Comment by panaC** [comment]
Isn't a registry issue ? could you clear your registry epub file association, to let the window store make the association again. 
I'm on mac, not a windows user

**Comment by seaspeak** [comment]
Not an association problem, I guess. 2.4.1 brings up the main window (as below), but not open the epub. 
![image](https://github.com/edrlab/thorium-reader/assets/8821870/0e994544-b2d8-4ca7-a2fd-b2405c7e40a3)

**Comment by panaC** [comment]
You cannot import an epub and open it in Thorium 2.4.1 at all ?

**Comment by seaspeak** [comment]
If I double-click a new epub, Version Thorium.2.3.0-alpha.1.3658607447 will import the new epub and open it in a seperated window. But 2.4 just open the main window, and doesn't even import the new epub.

 And yes, I can import a new epub by drag&drop or add in the main window.

**Comment by panaC** [comment]
Ok i will check on my side

**Comment by danielweck** [comment]
We will not be able to debug/troubleshoot this from Thorium APPX deployed to the Microsoft Windows Store, but hopefully we will be able to reproduce with the NSIS executable which installs Thorium for either all users or the current local one (i cannot remember what the Electron Builder does)

**Comment by panaC** [comment]
It works on my windows 11 pro machine.
I remove by security any application associated with epub file association in Registry Editor.
I tested both with a local Thorium build ` npm run prepackage:win && npm run package:win` and Official Github Release 2.4.1 (https://github.com/edrlab/thorium-reader/releases/download/v2.4.1/Thorium.Setup.2.4.1.exe)

File association (double click, or open with) works with Thorium already open or not.

I should be abble to reproduce to help you.
I keep the issue open

**Comment by danielweck** [comment]
Thank you for testing @panaC 
You don't have to manually invoke the "pre" (or "post") build scripts, they are automatically resolved by NPM when calling `npm run package:win`

**Comment by danielweck** [comment]
So could the problem experienced by some users be limited to the Windows Store version? Or maybe the NSIS executable installer is affected when users install the Windows Store version in parallel too?

**Comment by danielweck** [comment]
just out of interest, are you able to test with Windows 11?

**Comment by seaspeak** [comment]
Just tested on my colleague's notebook running Windows 11. It works.
I tested release 2.4.1 on Windows 10 Sandbox and a fresh virtual machine, all are not working. So I may be 'confident' to say it is really not working on Window 10.  Am I really the only one still using Windows 10? Why isn't anyone feedback this question?

**Comment by panaC** [comment]
Surely a breaking change with Electron, sorry !

**Comment by danielweck** [comment]
Thorium, just like other apps built with Electron, doesn't control at a low-level how file associations are created. I guess Electron Builder broke some Windows 10 backward compatibility ... or maybe the NSIS installer which probably is responsible for configuring the registry.

**Comment by panaC** [comment]
I think it's a duplicate with https://github.com/edrlab/thorium-reader/issues/2693
I'm closing the issue for the moment, feel free to reopen it.
