### ISSUE TITLE
minor(?) GUI nitpick, the LCP passphrase text input field has an icon on the left hand side, visually looks just asterisks => confusing

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2165]
<img width="890" alt="Screenshot 2024-05-09 at 15 38 48" src="https://github.com/edrlab/thorium-reader/assets/625201/1d5d7ca2-2dc4-436d-b04a-5f4fe0fa4b9b">

**Comment by danielweck** [comment]
I'm used to it now, but at first I immediately found this icon confusing, I had not come across this design choice before (websites or apps). Would it be possible to use an icon that looks less like if it was part of the text input field?

**Comment by danielweck** [comment]
PS: also note the low-contrast popup modal dialog perimeter, as mentioned in other issues in this tracker. Needs harmonization / consistency across library and reader windows.

**Comment by panaC** [comment]
This issue is not actionnable, more a discussion

**Comment by llemeurfr** [comment]
![Capture d’écran 2024-07-02 à 12 58 39](https://github.com/edrlab/thorium-reader/assets/14943186/ffbcc550-c70b-4a14-a686-592ed8178da8)

Here is an alternative proposal, the key hole expressed the concept we need.
