### ISSUE TITLE
GUI: search color 

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#2167]
![image](https://github.com/edrlab/thorium-reader/assets/3198865/6fea31dc-177b-4f5e-913a-6ff1abfc53d9)

**Comment by panaC** [comment]
api app secondary button
![image](https://github.com/edrlab/thorium-reader/assets/3198865/3f1f44be-a8ed-4780-bb45-799e31e38b55)

**Comment by danielweck** [comment]
@panaC feel free to merge this PR if it fixes the bug you filed. I haven't tested myself, just so you know
