### ISSUE TITLE
keyboard focus outline clipped

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2172]
<img width="256" alt="Screenshot 2024-05-14 at 08 58 09" src="https://github.com/edrlab/thorium-reader/assets/625201/049396a9-3aa8-4afe-a0e6-88fda4160287">
<img width="225" alt="Screenshot 2024-05-14 at 08 58 26" src="https://github.com/edrlab/thorium-reader/assets/625201/4aec68c0-44f5-4030-a308-e89dfc51a121">

**Comment by danielweck** [comment]
for reference:

<img width="230" alt="Screenshot 2024-05-14 at 08 57 47" src="https://github.com/edrlab/thorium-reader/assets/625201/a86ea342-15e3-40b0-b374-c4f73cb7f6e2">

**Comment by panaC** [comment]
The issue persist on `develop`
