### ISSUE TITLE
active tab styling discrepancy

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2173]
<img width="650" alt="Screenshot 2024-05-14 at 09 00 02" src="https://github.com/edrlab/thorium-reader/assets/625201/dfff9c90-062c-4475-aca7-7328c358db31">

**Comment by danielweck** [comment]
reference:

<img width="230" alt="Screenshot 2024-05-14 at 08 57 47" src="https://github.com/edrlab/thorium-reader/assets/625201/31f79b44-be88-4c76-844b-40b30e494386">

**Comment by panaC** [comment]
cf figma primary / secondary button

**Comment by danielweck** [comment]
> cf figma primary / secondary button

just to clarify, does this mean that the current rendering is correct, or that the active tab button style must be consistent regardless of base app layer vs. popup dialog modal layer? (sorry, I am not familiar with the Figma details)

**Comment by panaC** [comment]
The reference seems wrong, no ? @arthur-lemeur 
The outline focus is not the same

**Comment by panaC** [comment]
fixed in develop
