### ISSUE TITLE
broken ui when reverse-tabbing onto the pagination popover list

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2174]
step 1: forward-tab onto the "next" arrow

<img width="1244" alt="Screenshot 2024-05-14 at 09 08 19" src="https://github.com/edrlab/thorium-reader/assets/625201/01c81d29-b970-4626-9009-72d1cef8c471">

step 2: reverse-tab onto the popover trigger (no need to activate the pull down list)

<img width="1244" alt="Screenshot 2024-05-14 at 09 07 47" src="https://github.com/edrlab/thorium-reader/assets/625201/55d619e4-ef91-4e04-86e9-a0d358c3a312">

**Comment by panaC** [comment]
Appears on bookmark too !
![image](https://github.com/edrlab/thorium-reader/assets/3198865/a05335bc-e02b-4188-bc2a-86a133cf90b7)

**Comment by danielweck** [comment]
Reverse-tabbing is broken (stuck) in popup modals (fine in docked):

<img width="1244" alt="Screenshot 2024-05-14 at 18 05 16" src="https://github.com/edrlab/thorium-reader/assets/625201/1490a4a0-22a5-42bc-a9a0-bd07f92b759f">

<img width="1244" alt="Screenshot 2024-05-14 at 18 03 16" src="https://github.com/edrlab/thorium-reader/assets/625201/1e13593d-9f93-423d-ba89-171c5979256c">
