### ISSUE TITLE
"customize text formatting" in docked mode is very confusing (disabled tab / select items ... but still some work)

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2179]
<img width="400" alt="Screenshot 2024-05-14 at 10 18 34" src="https://github.com/edrlab/thorium-reader/assets/625201/d426b650-1b76-4321-a39c-e6eee5a78b04">

**Comment by arthur-lemeur** [comment]
This was supposed to be fixed. I'll have a look

**Comment by arthur-lemeur** [comment]
It's fixed in the branch "dev/dockedSettings"

**Comment by danielweck** [comment]
I see, thank you. Could you please cross-reference the Pull Request so we can track status updates :)
(I hope I didn't post a duplicate issue, I searched but couldn't find a previous identical one)

**Comment by panaC** [comment]
> It's fixed in the branch "dev/dockedSettings"

fixed by #2141
