### ISSUE TITLE
 [New GUI] Comparison Figma Designs/Alpha – Catalogs – Light mode #2186 

### ISSUE THREAD

**Issue by Hoppipollala** [edrlab/thorium-reader#2187]
Comparaison maquettes/version alpha.

### Icône OPDS Feed

L'icône de ce bouton est beaucoup plus fin que celui de l'autre, il est assez peu lisible.

Version alpha
<img width="405" alt="Capture d’écran 2024-05-14 à 18 41 32" src="https://github.com/edrlab/thorium-reader/assets/22544556/cf9e4991-2a8c-4e42-b45d-92f0d6a8ea0c">

Version Figma
![Capture d’écran 2024-05-14 à 18 43 28](https://github.com/edrlab/thorium-reader/assets/22544556/904cd649-e730-4e43-947d-9383defc96f3)

### Vue Table

La vue table correspond à l'ancienne vue liste qui a été abandonnées sur les maquettes.
<img width="1226" alt="Capture d’écran 2024-05-14 à 18 44 30" src="https://github.com/edrlab/thorium-reader/assets/22544556/6754d968-6f74-4ab9-80b8-fdfca602de16">

**Comment by danielweck** [comment]
Also `NaN` in your screenshot (pagination control)

**Comment by danielweck** [comment]
I agree, the whole "view mode" cluster of GUI controls should be removed when browsing OPDS feeds.
