### ISSUE TITLE
 [New GUI] Comparison Figma Designs/Alpha – Home + Settings – Dark mode

### ISSUE THREAD

**Issue by Hoppipollala** [edrlab/thorium-reader#2190]
Comparaison maquettes/version alpha.

### Navigation principale

La couleur des icônes ne correspond pas à celle des maquettes.

Alpha version
![Capture d’écran 2024-05-14 à 19 33 09](https://github.com/edrlab/thorium-reader/assets/22544556/bc8bfb2f-ac81-4a74-b05a-58f0bc363a24)

Figma Version
![Capture d’écran 2024-05-14 à 19 35 30](https://github.com/edrlab/thorium-reader/assets/22544556/98271ae5-4a35-482a-ab49-541c1f48a015)

### Boutons texte

Les états survol/focus ne correspondent pas.

Alpha version :
![Capture d’écran 2024-05-14 à 19 36 52](https://github.com/edrlab/thorium-reader/assets/22544556/41e3ae72-571f-4355-a665-e6c9584ad317)

Figma version : 
![Capture d’écran 2024-05-14 à 19 36 46](https://github.com/edrlab/thorium-reader/assets/22544556/51c67368-e682-41b7-b86f-ac7999c20756)

### Menus contextuels

Le survol/focus des options du menu contextuel ne correspond pas

Alpha version :
![Capture d’écran 2024-05-14 à 20 32 38](https://github.com/edrlab/thorium-reader/assets/22544556/c3245d64-b56b-4be4-8dee-8895d2e8ce0b)

### Home – Empty state

Le SVG est peu visible sur la couleur de fond

Alpha version :
<img width="865" alt="Capture d’écran 2024-05-03 à 17 19 51" src="https://github.com/edrlab/thorium-reader/assets/22544556/01d2e326-74b1-4549-adab-6de4defafeca">

Figma version :
![Capture d’écran 2024-05-14 à 20 35 27](https://github.com/edrlab/thorium-reader/assets/22544556/3727968b-4a30-419c-bf98-ff166979e340)

### Settings – Dropdown

Le survol/focus des options des dropdown ne correspond pas.

Alpha version :
![Capture d’écran 2024-05-14 à 20 36 27](https://github.com/edrlab/thorium-reader/assets/22544556/9e08e99e-3848-4ee8-8006-a9550256f0f0)

Figma version :
![Capture d’écran 2024-05-14 à 20 37 31](https://github.com/edrlab/thorium-reader/assets/22544556/be1542e7-b670-4ba6-b47b-d75ad008069b)

**Comment by panaC** [comment]
Hello Mylène, can you please make one issue at a time :) ?

For the color button in Home menu is fixed here 6b60b1c 

For the focus/hover/default/current issue on the primary/secondary button Daniel has already made issue and partially fixed with 6b60b1c

For the Home – Empty state, need to be fixed as far as i know

For the language combobox 
![image](https://github.com/edrlab/thorium-reader/assets/3198865/a752857f-fe3f-484c-8ab5-881ec3aec5f3)

Partially fixed in 6b60b1c

list box border is white and need to be 'grey'

**Comment by Hoppipollala** [comment]
Yes, sorry, I did this by "zone" and not by issue 😬

 (I'm done with the reviewing of the Figma files, anyway)

**Comment by panaC** [comment]
The new combobox is fixed in https://github.com/edrlab/thorium-reader/commit/2e03ea32000cd147ca0708e33777a97e1ce934f5

**Comment by panaC** [comment]
fixed in https://github.com/edrlab/thorium-reader/commit/2e03ea32000cd147ca0708e33777a97e1ce934f5
