### ISSUE TITLE
[New GUI] Orphan book at the end of the grid – All books – Grid view

### ISSUE THREAD

**Issue by Hoppipollala** [edrlab/thorium-reader#2193]
A lone book is left at the end of the grid, even if I have 2 other books on page 2. Is there a reason for that ?

![Capture d’écran 2024-05-14 à 21 07 12](https://github.com/edrlab/thorium-reader/assets/22544556/f93c73aa-5285-45bc-9aec-8d851352b0ac)

![Capture d’écran 2024-05-14 à 21 07 15](https://github.com/edrlab/thorium-reader/assets/22544556/c43b8be3-3472-4c82-8d37-6e77df75c6bb)

**Comment by panaC** [comment]
All books - grid view is paginated to 50 items max

**Comment by danielweck** [comment]
Ah ok, so pagination limits are not dictated by actual available space, but by an arbitrary number...I wonder how hard this is to improve?

**Comment by Hoppipollala** [comment]
I get there is a limit, I'm just wondering if there is a way to avoir the lone book in a row, if there are more book on the following page ?

**Comment by panaC** [comment]
not an issue, more a discussion
