### ISSUE TITLE
GUI overflow: tags in publication info modal

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2201]
<img width="1244" alt="Screenshot 2024-05-15 at 11 17 54" src="https://github.com/edrlab/thorium-reader/assets/625201/71054e73-a2b4-4443-ab21-c4fec509bc96">

**Comment by danielweck** [comment]
I suggest the low-contrast black text in the edited tag is fixed too (otherwise I can post a separate issue if you want)

**Comment by arthur-lemeur** [comment]
![Capture d’écran 2024-05-15 à 13 08 28](https://github.com/edrlab/thorium-reader/assets/113124595/65864a75-f859-471f-a64e-49c48a2f1980)

That's odd, this is not happening on my end. I can change the color of the text to white if you think it's best though

**Comment by danielweck** [comment]
to reproduce, do not include whitespace characters in the tag

**Comment by danielweck** [comment]
Fixed

<img width="812" alt="Screenshot 2024-05-16 at 11 08 11" src="https://github.com/edrlab/thorium-reader/assets/625201/91dbafd1-7d02-477a-b4b5-bb59848f2893">
