### ISSUE TITLE
background on input field labels

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2222]
<img width="912" alt="Screenshot 2024-05-17 at 18 09 57" src="https://github.com/edrlab/thorium-reader/assets/625201/00a1be26-f482-4a9a-a2d8-ff8a0be746da">

<img width="912" alt="Screenshot 2024-05-17 at 18 16 47" src="https://github.com/edrlab/thorium-reader/assets/625201/0f1ef3d5-5172-494c-be45-35d301014a21">

**Comment by panaC** [comment]
cf end of the issue https://github.com/edrlab/thorium-reader/issues/2192 (figma comparaison)
