### ISSUE TITLE
light scrollbar should be dark

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2223]
I mentioned this in another discussion thread, but it would be better if the common styles of scrollbars, modal outline / drop shadow, etc. were factored-out (mix ins?) in order to deliver a consistent look and feel throughout the application without copy-pasting CSS snippets all over components. I think this is why we are seeing inconsistencies.

<img width="912" alt="Screenshot 2024-05-17 at 18 15 46" src="https://github.com/edrlab/thorium-reader/assets/625201/391bee3a-b180-4503-9e0e-60ddf5d21017">

**Comment by panaC** [comment]
I agree
