### ISSUE TITLE
text areas background seems incorrect? (not 100% sure if intentional)

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2225]
<img width="912" alt="Screenshot 2024-05-17 at 18 11 02" src="https://github.com/edrlab/thorium-reader/assets/625201/a6ad046f-c030-4c33-8b79-487e3ddfdf6a">

**Comment by panaC** [comment]
cf figma : 

![image](https://github.com/edrlab/thorium-reader/assets/3198865/635d93f2-4b7c-474a-aa01-1f069f29b197)

issue #2192

**Comment by danielweck** [comment]
so the second text area down from the top is not supposed to be lighter, I think
