### ISSUE TITLE
scroll area is clipped, making bottom GUI innacessible

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2226]
<img width="912" alt="Screenshot 2024-05-17 at 18 15 10" src="https://github.com/edrlab/thorium-reader/assets/625201/3cbcd587-d3b2-43a1-8a61-c9806048e175">
<img width="912" alt="Screenshot 2024-05-17 at 18 14 45" src="https://github.com/edrlab/thorium-reader/assets/625201/d38ccd71-c290-4ec8-bf2a-47c8c6e91524">

**Comment by panaC** [comment]
It seems it was fixed in https://github.com/edrlab/thorium-reader/commit/2e03ea32000cd147ca0708e33777a97e1ce934f5
good catch
