### ISSUE TITLE
GUI meta-issue (multiple problems reported) => need to verify all addressed in develop branch

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2227]
* https://github.com/edrlab/thorium-reader/issues/2190
* https://github.com/edrlab/thorium-reader/issues/2189
* https://github.com/edrlab/thorium-reader/issues/2192
* https://github.com/edrlab/thorium-reader/issues/2191
* https://github.com/edrlab/thorium-reader/issues/2187
* https://github.com/edrlab/thorium-reader/issues/2186

**Comment by danielweck** [comment]
From now on, please let's file granular issues with actionable problem descriptions, and let's create one PR per problem solved ... otherwise code reviewers and patch testers have a really hard time validating proposed changes :)
Thank you all for the hard work though! We just need to break down large chunks into more digestable snacks ;)

**Comment by panaC** [comment]
The issue with css it's when you patch the head the tail breaks :) 
It's not so easy

**Comment by danielweck** [comment]
well, in principle CSS modules solve this, or any component-level scoping mechanism ... but composability and reusable styles mean that with raw CSS, selectors and cascade leak all over the place very quickly when scaling up the number of components :)
(even worse when retrofitting, as we are doing now)
Libraries like Vanilla Extract (or more modern incarnations) help compose styles, strict build-time checks with no runtime penalty (unlike css-in-js)...but this would have been a huge undertaking in Thorium, even bigger than this one.
Tailwind solves DX problems in its own way, but also a complete massive refactor in Thorium (not realistic)
So, here we are ... ;D

**Comment by arthur-lemeur** [comment]
I think we can close this issue, I just walked through the app to check these points and everything looks good to me.
