### ISSUE TITLE
GUI: readerSettings checkbox not tabbable 

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#2228]
<img width="779" alt="image" src="https://github.com/edrlab/thorium-reader/assets/3198865/bf0c2e67-0d2b-45d2-9021-b4f11eddedda">

I cannot focus with Tab Key on checkboxes

**Comment by danielweck** [comment]
@panaC external contribution to review: https://github.com/edrlab/thorium-reader/pull/2232
