### ISSUE TITLE
checkboxes are not selectable with space bar (they seem to be tickable with enter instead)

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2246]
the enter key is for form submission, not selecting / activating items
(hyperlink with enter, button with enter or space bar ... see W3C WCAG)

<img width="912" alt="Screenshot 2024-05-20 at 09 34 10" src="https://github.com/edrlab/thorium-reader/assets/625201/59ac9958-29c8-4ee1-a53a-1eed7b5eeeb4">

**Comment by danielweck** [comment]
@panaC I assigned you due to https://github.com/edrlab/thorium-reader/commit/a9979365ee6c79f135d230a2dc805661056428d7

**Comment by panaC** [comment]
@danielweck pressing space key on annotation checkboxes causes scrolling how to avoid this?

**Comment by danielweck** [comment]
> @danielweck pressing space key on annotation checkboxes causes scrolling how to avoid this?

the solution is an automatic behaviour with native checkboxes, but of course if we hack a non-native solution we then have to use preventDefault/stopPropagation tricks...

**Comment by panaC** [comment]
Yes i remove preventDefault to test and not instantly thought that this is the issue. Many thanks 
I already merge The PR in develop

**Comment by danielweck** [comment]
Please see follow up: https://github.com/edrlab/thorium-reader/pull/2269
