### ISSUE TITLE
selection/option control causes keyboard focus loss after activation of list item

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2250]
keyboard tab into the selector, arrow down to pop out and reach item, press spacebar or enter => focus goes to window root (I noticed that other selectors like the font options retain focus)

<img width="1595" alt="Screenshot 2024-05-20 at 09 56 45" src="https://github.com/edrlab/thorium-reader/assets/625201/bf5cf538-01da-4788-bd6c-0aca4006ccdd">

**Comment by arthur-lemeur** [comment]
This component is the Select from react-aria, the same we had issue with the pagination in annotations and bookmarks that I replaced with the Combobox. Something seems broken in its behavior but I haven't been able to fix it for the moment.

**Comment by danielweck** [comment]
I see. the font selector works because it is a combo box with user-editable text input.
my take is: even though a combo box is overkill (unnecessary user input) for the tabs menu, it is still better than breaking keyboard focus which introduces a ton of UX friction and frustration for keyboard users (including screen readers)
so, should we just replace all occurrences of broken selectors with the variant that works?

**Comment by arthur-lemeur** [comment]
I think for now it would be the easiest fix to this issue. @panaC ?

**Comment by danielweck** [comment]
To be fair, Adobe Spectrum / React ARIA Components "Select" works well in all the demos / test pages I tried:

https://react-spectrum.adobe.com/react-aria/Select.html

...is there something we do in Thorium with respect to keyboard focus or React lifecycle that corrupts the state of current keyboard focus?
