### ISSUE TITLE
wizard keep reappearing when switching tabs

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2253]
the wizard should reappear at next app launch, not constantly during usage of the current application launch

<img width="912" alt="Screenshot 2024-05-20 at 10 53 09" src="https://github.com/edrlab/thorium-reader/assets/625201/6ac6b3ef-6147-46e7-ae5d-bca8ebb7091d">

<img width="912" alt="Screenshot 2024-05-20 at 10 53 23" src="https://github.com/edrlab/thorium-reader/assets/625201/5d651788-832f-4e09-8d1f-a7da080d83f5">

**Comment by danielweck** [comment]
... actually, not just when switching tabs, also when adding OPDS feed etc. (GUI state refresh?)

**Comment by arthur-lemeur** [comment]
Doesn't happen on my end, still on yours?

**Comment by danielweck** [comment]
yes. make sure the checkbox is not ticked. then click outside the wizard modal or click the cross icon or press escape.
Continue to use Thorium, change tabs ... the wizard keeps coming back which forces me to tick the "do not show again" checkbox, which was not my original intent (I WANTED to see the wizard again at next launch ... I don't want to see it popup every time I navigate my current application session :)

**Comment by arthur-lemeur** [comment]
Oh yes I see what you mean, I just fixed that in the latest PR (moved the wizard component from LibraryHeader.tsx to App.tsx)

**Comment by danielweck** [comment]
Ok will try :)
