### ISSUE TITLE
OPDS publication info modal, missing gap at bottom of left content column (padding or margin)

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2255]
<img width="823" alt="Screenshot 2024-05-20 at 11 08 04" src="https://github.com/edrlab/thorium-reader/assets/625201/cde20c41-95dc-4751-9eab-960763bcbaa2">

**Comment by arthur-lemeur** [comment]
![Capture d’écran 2024-05-20 à 14 13 58](https://github.com/edrlab/thorium-reader/assets/113124595/80d09b27-7822-4f71-9fbe-5d17d9719788)

There should be a margin to prevent that from happening.
