### ISSUE TITLE
OPDS navigation trail is prematurily condensed / shortened

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2256]
<img width="2672" alt="Screenshot 2024-05-20 at 11 02 09" src="https://github.com/edrlab/thorium-reader/assets/625201/0322c24f-9684-4574-8121-59a18d83ba50">

click on current category / philosophy ...

<img width="2672" alt="Screenshot 2024-05-20 at 11 02 19" src="https://github.com/edrlab/thorium-reader/assets/625201/a9eff455-41b1-43b9-adb1-cd6909d9a1c6">

**Comment by danielweck** [comment]
As you can see, there is plenty of free space in the navigation trail, so I guess there is a hard-coded limit?

**Comment by arthur-lemeur** [comment]
Yes, it's five elements : https://github.com/edrlab/thorium-reader/blob/develop/src/renderer/library/components/layout/BreadCrumb.tsx#L51

**Comment by danielweck** [comment]
given that each segment has a max width with text ellipsis overflow, would it be easy to approximate how many segments fit inside the available width? there is plenty of screen real estate wasted with the current heuristics, it would be nice to show more than 5 segments.

**Comment by panaC** [comment]
Fixed by https://github.com/edrlab/thorium-reader/commit/c7b68af85bc1372e3ebc505266824206ff9a00ca
