### ISSUE TITLE
like keyboard shortcut editor, annotation editor should tab-cycle and lock keyboard, otherwise confusing screen reader experience

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2260]
<img width="833" alt="Screenshot 2024-05-20 at 11 46 22" src="https://github.com/edrlab/thorium-reader/assets/625201/5bb4bcc8-e30c-440c-a4ba-c200639c4bf8">

**Comment by danielweck** [comment]
there's very little UX benefit in allowing concurrent annotation edit, in fact I can only see negatives :)

**Comment by danielweck** [comment]
compare with keyboard shortcuts editor exclusive mode:

<img width="801" alt="Screenshot 2024-05-20 at 11 48 41" src="https://github.com/edrlab/thorium-reader/assets/625201/3ff7b41e-28b0-4619-b344-62045a304c0c">

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/blob/fe6304225d644d446b7f71ed94c2c4dbc071234e/src/renderer/reader/components/ReaderMenu.tsx#L471-L476

https://github.com/edrlab/thorium-reader/blob/fe6304225d644d446b7f71ed94c2c4dbc071234e/src/renderer/reader/components/ReaderMenu.tsx#L708-L728

**Comment by panaC** [comment]
Issue appear when I click on edit icon after scrolling in the modal, If i not scrolling the click on edit works.
