### ISSUE TITLE
Avatar.svg encoded as iso

### ISSUE THREAD

**Issue by gautierchomel** [edrlab/thorium-reader#2261]
XML documents must be encoded in UTF-8, but ISO-8859-1 was detected.

https://github.com/edrlab/thorium-reader/blob/9317229b35d5d4324df916ea45d7ccc38e76f3ec/src/renderer/assets/icons/avatar.svg#L1

**Comment by danielweck** [comment]
also, what the hell? :)

![Screenshot_20240520-134347.png](https://github.com/edrlab/thorium-reader/assets/625201/15895d64-3440-40ac-b867-20c93a80bc20)
