### ISSUE TITLE
annotations editor should be unique, no concurrent edits

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2270]
follow-up to:
https://github.com/edrlab/thorium-reader/issues/2260

note that the keyboard shortcuts editor properly handles mouse-driven actuation of another editor (closes the current editor)

<img width="820" alt="Screenshot 2024-05-20 at 15 02 33" src="https://github.com/edrlab/thorium-reader/assets/625201/d460bba2-331e-4374-aa15-68263fedd284">

**Comment by panaC** [comment]
not just annotation, bookmark too
