### ISSUE TITLE
There is a problem with the "TTS voice" option menu of thorium-reader alpha3.0 version.

### ISSUE THREAD

**Issue by vstephenzhou** [edrlab/thorium-reader#2283]
Developers, hello. I encountered an issue while using Thorium.3.0.0-alpha.1.9165190563 and previous versions. When I start to play TTS, if I use the mouse to click the "TTS voice" option menu, select another TTS voice, and then reopen the menu to expand it, the menu keeps collapsing automatically.
Hope this problem can be fixed, thank you very much.

![bug GIF](https://github.com/edrlab/thorium-reader/assets/7257533/acfb9206-d99e-494d-8018-f2dd5c9a994e)

**Comment by arthur-lemeur** [comment]
Related to issue #2128

**Comment by danielweck** [comment]
duplicate: https://github.com/edrlab/thorium-reader/issues/2128
