### ISSUE TITLE
slightly broken layout in modal

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2302]
<img width="812" alt="Screenshot 2024-05-21 at 18 08 06" src="https://github.com/edrlab/thorium-reader/assets/625201/6b3c3924-c789-4e6c-98d3-b777cf892989">
<img width="812" alt="Screenshot 2024-05-21 at 18 08 00" src="https://github.com/edrlab/thorium-reader/assets/625201/f293198e-ffec-46af-bd49-80a40c8cfeda">

**Comment by arthur-lemeur** [comment]
![Image](https://github.com/edrlab/thorium-reader/assets/113124595/da99bb8e-3f7a-438c-ae6d-4655f5d72e36)

I don't see it on my end (I'm on develop, up to date). As it been fixed ?

**Comment by panaC** [comment]
I can't reproduce. It seems you override the thorium min-width with your screen manager.

**Comment by danielweck** [comment]
I cannot reproduce, closing.
