### ISSUE TITLE
annotations editor "save" button is default/highlighted, yet hitting the ENTER key cancels the edit instead of submitting the form

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2310]
<img width="1244" alt="Screenshot 2024-05-22 at 13 17 40" src="https://github.com/edrlab/thorium-reader/assets/625201/7a21603f-5fac-41db-beae-e02cfb903787">

**Comment by danielweck** [comment]
Related ESCAPE key issue https://github.com/edrlab/thorium-reader/issues/2309

**Comment by panaC** [comment]
fixed in https://github.com/edrlab/thorium-reader/commit/a487c4de2331d2609f68d96fc26b50a29e7d891a
