### ISSUE TITLE
delete single bookmark in list (while in edit mode or not) causes crash (works fine with annotations editor)

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2329]
<img width="1001" alt="Screenshot 2024-05-23 at 14 40 59" src="https://github.com/edrlab/thorium-reader/assets/625201/df1b3455-dadd-4b99-af76-2d20c3644c8d">

**Comment by arthur-lemeur** [comment]
I can't reproduce this bug. On my end it works fine either with the mouse or with the keyboard

**Comment by danielweck** [comment]
To reproduce, make sure there is only a single bookmark in the list. No need to enter edit mode (actually), simply press the delete icon

**Comment by arthur-lemeur** [comment]
It seems the problem comes from " dispatch(readerActions.bookmark.pop.build(bookmark));" (ReaderMenu.tsx, line 678). 
If you comment it there is not error but I don't know the cause of it.. @panaC can you have a look ?

**Comment by panaC** [comment]
culprit : 

https://github.com/edrlab/thorium-reader/blob/daebd059121cc0fe10dfcb7eb8794d15d245f9ba/src/renderer/reader/components/ReaderMenu.tsx#L879C1-L881C6

**Comment by panaC** [comment]
same here : 

https://github.com/edrlab/thorium-reader/blob/daebd059121cc0fe10dfcb7eb8794d15d245f9ba/src/renderer/reader/components/ReaderMenu.tsx#L568C1-L570C6

**Comment by danielweck** [comment]
`if (!r2Publication || !annotationsQueue)`

...this should be

`if (!r2Publication || !annotationsQueue?.length)`

**Comment by danielweck** [comment]
just need to hoist conditional early render() exit AFTER all hooks called?

**Comment by danielweck** [comment]
https://legacy.reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level
