### ISSUE TITLE
docked state is not preserved, always goes back to centered modal when closing and re-opening publication

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2330]
is this a feature or a bug?

**Comment by arthur-lemeur** [comment]
At this moment it is voluntary, we didn't preserved it but if I'm not mistaken this state can be changed

**Comment by llemeurfr** [comment]
If we want to change this behavior we have to decide if this would be a per-publication state or a global state. 
As a user, I may prefer that Display Settings are always docked on the right of the screen, while Navigation Settings (ToC..) are always on the left, whatever book I read. 

This is pure UX issue, I'd like Mylene advice on this. @arthur-lemeur can you ask please?

**Comment by Hoppipollala** [comment]
I think it's preferable to keep the last state the user has selected, for all publications. This will avoid a little friction (the cognitive load of having to change the docked/modal state for every publication).

So if I open a book, display the Table of content, set the Toc as docked and close the book. When i'll open the same book, or another book, I'll get the same result – the settings/toc/etc. will be docked until I decide I want to change the dock from right to left or get back to the modal.

**Comment by danielweck** [comment]
I agree (personal preference) about making this global state instead of publication-specific.
