### ISSUE TITLE
In the language settings, Chinese Simplified and Chinese Traditional are reversed

### ISSUE THREAD

**Issue by Leroy-X** [edrlab/thorium-reader#2357]
![image](https://github.com/edrlab/thorium-reader/assets/13515498/7f80669f-47d8-4f00-b0c5-8b67b3b71982)

Hi, In the language settings, Chinese Simplified and Chinese Traditional are reversed.

Just turn the English part upside down. 

Thanks

**Comment by danielweck** [comment]
Could you please respond here: https://github.com/edrlab/thorium-reader/issues/2367#issuecomment-2133676304
Thank you :)
