### ISSUE TITLE
Regression : Highlight annotation not drawn on startup

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#2360]
culprit : https://github.com/edrlab/thorium-reader/commit/0dfbd187aa802bdb12ac07a44a4a53207b4166bf ?

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/blob/develop/src/renderer/reader/redux/sagas/annotation.ts#L203-L207

**Comment by panaC** [comment]
yes on Accessible Epub3

**Comment by danielweck** [comment]
ah yes, Divina exists even for non-Divina publications. Let me investigate...
