### ISSUE TITLE
Suggestion regarding info for Chinese locales in README

### ISSUE THREAD

**Issue by antermin** [edrlab/thorium-reader#2367]
https://github.com/edrlab/thorium-reader/blob/4f0a1ba0305b2d5a864c55a64bed3c778cda88cf/README.md?plain=1#L22-L23

The list of locales uses the format `(Language code) Native name (English name)`.

For zh-CN, the native name field should be in Simplified Chinese characters.
For zh-TW, the native name field should be in Traditional Chinese characters.

Therefore it is redundant to mix both sets of characters (中國/国 and 台湾/灣) and it can be simplified to:
```
* (zh-CN) 中文 - 中国 (Chinese simp.)
* (zh-TW) 中文 - 台灣 (Chinese trad.)
```

There are also some other ways depending on how you want to list the Chinese locales.

Match native name to English name:
```
* (zh-CN) 简体中文 (Chinese simp.)
* (zh-TW) 繁體中文 (Chinese trad.)
```

Match English name to native name:
```
* (zh-CN) 中文 - 中国 (Chinese - China)
* (zh-TW) 中文 - 台灣 (Chinese - Taiwan)
```

Be very detailed (stating both the character set and the variant:
```
* (zh-CN) 简体中文 - 中国 (Simplified Chinese - China)
* (zh-TW) 繁體中文 - 台灣 (Traditional Chinese - Taiwan)
```

**Comment by danielweck** [comment]
Thank you, we will update the README based on your recommendations.

Could you please check that the description that appears in Thorium's language selector is correct:

https://github.com/edrlab/thorium-reader/blob/81b1e93e51c6ae95594dc1c05f49afe7ff4fab8a/src/common/services/translator.ts#L179-L180

**Comment by danielweck** [comment]
Comment from @Leroy-X 

![image](https://github.com/edrlab/thorium-reader/assets/13515498/c18c074b-a3d7-4742-a8e1-e73933ecb34d)

Hi, there is still a problem in 3.0. The Chinese characters marked by the red line are upside down. :P

Correct should be:
简体中文 - 中国（Chinese Simp.）
繁體中文 - 台灣（Chinese Trad.）

**Comment by danielweck** [comment]
Hello @arthur-lemeur I made the combobox a little wider to accommodate longer locale names, I tested with Thorium's minimum window dimensions, and I checked all other occurrences of shared combobox styles (I was worried about the usual CSS side effects / leakage). All seems ok, but just wanted to let you know:
https://github.com/edrlab/thorium-reader/commit/01b0fda311e46abdc33fa3daddae82896e94f8cb#diff-9ac427bfb77c4b749bc13b74dab53c7aa1ca76246b2864c23e1f132f8a5bf77c
