### ISSUE TITLE
focus steal by navigator (I think) when switching between docked panel and centred dialog using the keyboard

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2378]
<img width="1792" alt="Screenshot 2024-05-27 at 18 06 34" src="https://github.com/edrlab/thorium-reader/assets/625201/75979c4c-05f6-49c6-b959-943d0185be7c">

<img width="1792" alt="Screenshot 2024-05-27 at 18 07 14" src="https://github.com/edrlab/thorium-reader/assets/625201/c2204afe-d9ba-44c6-87d5-a601089f39e0">

**Comment by danielweck** [comment]
I wonder if the resize event of the publication document viewport is causing this focus steal?

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/blob/d3d154efb40f71286e361cd681fd50745f65bb63/src/renderer/reader/components/ReaderHeader.tsx#L1004 culprit I guess. react rendering lifecycle

**Comment by danielweck** [comment]
Same issue as https://github.com/edrlab/thorium-reader/issues/2379
