### ISSUE TITLE
French slash in wizard

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2385]
GitLocalize:

<img width="794" alt="Screenshot 2024-05-27 at 20 26 34" src="https://github.com/edrlab/thorium-reader/assets/625201/4f9fe436-6d35-46b3-92dd-d13346955db8">

https://github.com/edrlab/thorium-reader/pull/2364

https://github.com/edrlab/thorium-reader/pull/2364/files#diff-c83eb4d9821cecc3b006c2c6b1c4209baa5c21c9a119fe35e36773e304d7a20dR507

**Comment by danielweck** [comment]
ping @llemeurfr

**Comment by llemeurfr** [comment]
Fixed via #2448.
