### ISSUE TITLE
The settings for voice and speech rate cannot be saved.

### ISSUE THREAD

**Issue by Leroy-X** [edrlab/thorium-reader#2388]
After restarting the software, the voice and speech rate will revert to their default settings, even if I clicked the save configuration button.

Btw, It would be even nice with a volume button. 

Thanks.

**Comment by danielweck** [comment]
Thank you for reporting this. This is not a bug, it is a missing feature. This is simply not implemented in Thorium, currently :)

**Comment by danielweck** [comment]
could you please re-open the issue? we do need to implement this missing feature. you are correct, it would be very useful :)

**Comment by danielweck** [comment]
Discussed today:
1) user runs Thorium for the first time (default settings), on their French computer
2) user imports and opens English EPUB, user selects speed 2x and TTS voiceA, user closes reader window (back to library / bookshelf)
2) user imports and opens French EPUB, TTS speed and voice are default (1x and system default, no preferred TTS voice), user selects speed 3x and TTS voiceB,
3) user imports and opens another English EPUB, TTS speed and voice are the memorised settings from step (2): speed 2x and TTS voiceA (the regional locale is ignored, so en-UK and en-US for example match), but now user switches to speed 3x, user closes reader window
4) user re-opens English EPUB from step (2), the same settings memorised in step (3) are restored: 3x speed and TTS voiceA
etc.

As you can see, there is a mapping based on publication language (top-level locale declared in metadata and HTML document, not XML fragments inside documents such as paragraphs that can have different languages than the primary declared top-level locale)
