### ISSUE TITLE
OPDS authentication dialog (HTML + CSS form) looks ... different :)

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2396]
(and the horizontal / vertical scrollbars are redundant)

![Screenshot 2024-05-29 at 12 29 58](https://github.com/edrlab/thorium-reader/assets/625201/f94eb5f6-37e2-48f7-8f85-24c3a3799799)
![Screenshot 2024-05-29 at 12 29 50](https://github.com/edrlab/thorium-reader/assets/625201/c0937a0c-a1ea-4b2a-9c2f-9c0c1683b19f)

**Comment by arthur-lemeur** [comment]
Hello Daniel, if you're talking about the look that is different from the rest of the app, this was Laurent decision to have this window inspired by the new google authentication window and then arranged with Mylène. That being said I'll have a look about the scrollbars.
