### ISSUE TITLE
Translations updates

### ISSUE THREAD

**Issue by gautierchomel** [edrlab/thorium-reader#2404]
There were 4 words added to the EN local, to be updated in the already done translations. They define how annotations are visually marked. Those are:
* Outline (reader.annotations.type.outline)
* Solid background (reader.annotations.type.solid)
* Strikethrough (reader.annotations.type.strikethrough
* Underline (reader.annotations.type.underline)

@horus68 @tofi86 @llemeurfr @peaceroad @milliet @Modeo147 @ThanatosDi @nvdaes

**Comment by danielweck** [comment]
hello, the annotations editor includes a styled radio selector (i.e. only a single value can be picked by the user, unlike a set of checkboxes which accept multiple ticks) that represents the 4 different kinds of visual highlights that annotations can have, using the given colour: solid background, outline, strikethrough, and underline.

**Comment by gautierchomel** [comment]
A screenshot for visual context 
![image](https://github.com/edrlab/thorium-reader/assets/107039498/ef142ae2-1e59-41f8-9186-ba30fc9e02c1)

**Comment by tofi86** [comment]
Done

**Comment by llemeurfr** [comment]
This issue will now be closed. Not every langage has a full set of localization ready, we'll wait for feedback from users  and finalize translations with volunteers in v3.1.
