### ISSUE TITLE
bottom offset gap appears after navigating to the publications table view

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2421]
...not sure how I managed to put the GUI in this state, but there is clearly a potential for some "scroll":
<img width="1792" alt="Screenshot 2024-05-31 at 14 39 56" src="https://github.com/edrlab/thorium-reader/assets/625201/2f1999f3-6fb0-4436-83f3-77898716a949">
<img width="1792" alt="Screenshot 2024-05-31 at 14 21 26" src="https://github.com/edrlab/thorium-reader/assets/625201/693fb879-ca56-40ed-a4e1-3b7c8e38bd5e">

**Comment by arthur-lemeur** [comment]
<img width="1470" alt="Capture d’écran 2024-06-05 à 15 10 59" src="https://github.com/edrlab/thorium-reader/assets/113124595/9f56ecf6-ba44-4509-816f-20e17c03b0c8">

I just replicated it by deactivating the "overflow: hidden" on the css class "dropzone", were you working on that element ?

**Comment by panaC** [comment]
I found the issue : 

![image](https://github.com/edrlab/thorium-reader/assets/3198865/b1dd4c4c-ed1b-46de-8903-2bedd20d454e)

To reproduce go to table view mode and select a tag to filter on it, the window will shift up.

**Comment by danielweck** [comment]
ah great, thanks for finding a way to reproduce the bug :)
