### ISSUE TITLE
Add into bookshelf when opening file

### ISSUE THREAD

**Issue by Refrain69** [edrlab/thorium-reader#2441]
I hope when I double-clicked a file(like epub,already associated with Thorium Reader),Thorium Reader will add it into the bookshelf automatically.

**Comment by danielweck** [comment]
Hello, this is normal behaviour, Thorium always adds publications to the local bookshelf (if they don't already exist) so that the application can load books and open the reader view. Are you seeing duplicates in your publication library?

**Comment by danielweck** [comment]
I am closing this issue now, please feel free to re-open if you are seeing duplicates of already-imported publications (Thorium computes a unique hash for each imported publication so this should not happen)
