### ISSUE TITLE
32bits build for Windows

### ISSUE THREAD

**Issue by luqui1989** [edrlab/thorium-reader#2444]
Hello! I have an old x86 tablet for reading, I tried [this way](https://github.com/edrlab/thorium-reader/issues/165) and does not work anymore. Can anyone help me please?

**Comment by danielweck** [comment]
If the command line fails, you could also try modifying the `package.json` file:

```
"build": {
  "win": {
    "target": [
      {
        "target": "nsis",
        "arch": [
          "ia32"
        ]
      }
    ]
  }
}
```

https://www.electron.build/cli#targetconfiguration
