### ISSUE TITLE
sometimes (not 100% repro), deleting an annotation results in empty paginated list

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2467]
...the annotations list repopulates when I click on a highlight in a document, or close and re-open the book (in other words, this is a mistmatch of the internal data model state and the GUI).
Sometimes the delete action works just fine (backend always work, but frontend seems to fail to refresh correctly), I think it depends on if a highlight is currently "active"? (clicked UUID?)

**Comment by panaC** [comment]
fixed https://github.com/edrlab/thorium-reader/commit/85ce17049f4d00a3da6881356271445b65050810
