### ISSUE TITLE
Annotations should be compatible with touchscreens

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#2473]
From an early user of Th3: 

I am playing with Thorium 3 for Windows on a touchscreen "tablet" (specifically, it's a Surface Pro 9, but the behavior I describe below reproduces on my Dell laptop with a touch screen).

If I select text with my *mouse*, I can add annotations.  If I select text with my finger or my stylus and then try to add an annotation, I get a "No selection" error (even though text is very clearly selected).

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/blob/794cfac6c7b1c2291964e657b0f87bda57d3fde6/src/renderer/reader/components/Reader.tsx#L534

https://github.com/edrlab/r2-navigator-js-dist/blob/9276a12b27a7410168e44d46652dc10f1fa71288/README.md?plain=1#L672

`setReadingLocationSaver` callback is not called on selection touch press (Win11) , so it's an issue on r2-navigator-js.


mouse selection screen capture : 
![Image](https://github.com/user-attachments/assets/c5d85a3b-7002-44af-8eab-50848fb787f7)

touch selection screen capture : 
![Image](https://github.com/user-attachments/assets/3ba33280-3613-447d-acc9-7d1e56e963e3)

**Comment by danielweck** [comment]
on Windows, traditional single-cursor pointing devices (mouse, trackpad), capacitive multi touch (finger), and active stylus interaction trigger different events.
I still have an old Microsoft Surface Pro 3 which I could revive to launch Thorium/navigator in development mode and debug unified DOM PointerEvents (currently we rely mostly on click or mouse down/up, touch handling only for swipe and image zooming if I remember correctly).

**Comment by danielweck** [comment]
PS: DOM text selection is another use-case, we don't track atomic cursor events, we just capture the native DOM selection event (in fact we recently fixed an edge case with double-click which causes text selection but was not captured correctly as a change of text selection)

**Comment by panaC** [comment]
I tried this: 

`document.addEventListener("selectionchange", (e) => { console.log("###selectStart", e, "selectEnd###"); console.log("###Selection", window.getSelection(), "###EndSelection); })` 

It works well on my Windows Machine

**Comment by panaC** [comment]
`selectionchange` is not fired after touch event like `touchstart` and `touchend` so I have to trigger a 100ms interval to poll for the text selection change.

**Comment by danielweck** [comment]
Fixed via https://github.com/readium/r2-navigator-js/commit/c17df631b743600e3e9124c889914292d26b4e85
(publishing package updates now)
