### ISSUE TITLE
Thorium Reader Forgets Its Settings

### ISSUE THREAD

**Issue by planetkalpesh** [edrlab/thorium-reader#2475]
I have installed Thorium Reader 3.0.0. It forgets its settings and every time I open an ebook I have to apply the settings again.

**Comment by panaC** [comment]
Hello, sorry to hear that, can you please make a video about it or a set of screen capture. It's works on my side, i need to understand your process.

**Comment by llemeurfr** [comment]
We'll need more precisions about the exact behavior you see and the behavior you're expecting, but the current situation is that each book has its own settings (font, font size, spaces overrides, position of the settings menu ...).

By "each time I open an ebook", do you mean "each time I open the same ebook" or "each time I open a different ebook"?

**Comment by panaC** [comment]
I think this is rely to this https://github.com/edrlab/thorium-reader/issues/2532 

I'm closing the issue.
