### ISSUE TITLE
EDRlab LCP example catalog problem

### ISSUE THREAD

**Issue by DaveLPG** [edrlab/thorium-reader#2477]
Moby Dick, one of the 3 example books will not open. File not found error flashes for a few seconds, then disappears. New user of Thorium 3 I should add.

**Comment by panaC** [comment]
Hello, I just tested on my side and it's works, can you be more explicit with some screen capture.
I downloaded the 3 publications from https://www.edrlab.org/readium-lcp/testing-readium-lcp-compliant-devices/

**Comment by danielweck** [comment]
maybe the problem is specific to the OPDS feed? http://edrlab.org/public/feed/opds-lcp.json

**Comment by DaveLPG** [comment]
Was able to capture this (luckily) when I tried to import Moby Dick:

[cid:218963ee-c6dd-46b1-9fff-310e817814ff]

And here's the link used: (from page 7 of Thorium v3 doc.)

[cid:0ef02201-ee33-4c37-8702-f7d245e27ea4]


Just checked the other two example books. They give similar results - download error.

The two error messages flash for a second or two then disappear. I'm lucky to have captured what you see above.



________________________________

**Comment by panaC** [comment]
can you please respond from the Github GUI :)

**Comment by DaveLPG** [comment]
![image](https://github.com/edrlab/thorium-reader/assets/131614438/695c6f0d-97c3-47ae-a5d9-c272494fbc3c)

![image](https://github.com/edrlab/thorium-reader/assets/131614438/0ed78a6e-f0d9-464f-8286-4953b1c3a445)

**Comment by DaveLPG** [comment]
Done. Hopefully correctly. 😉

Dave...
________________________________

**Comment by panaC** [comment]
OK ! the EDRLab lcp test feed has not be updated since the upgrade of the LCP test server, the lcpl link is not the same between the opds feed and edrlab website https://www.edrlab.org/readium-lcp/testing-readium-lcp-compliant-devices/

**Comment by DaveLPG** [comment]
Thanks for the quick fix!  👍

**Comment by llemeurfr** [comment]
OK this is now solved. The OPDS feed was updated.
