### ISSUE TITLE
What is the Disable Right-to-Left in Library Settings 

### ISSUE THREAD

**Issue by DaveLPG** [edrlab/thorium-reader#2486]
What does this mean? 
![image](https://github.com/edrlab/thorium-reader/assets/131614438/e68a014f-dbc0-43f7-a8cc-3127eb5f8814)

Doesn't seem to do anything-yet?

Also swipe action screen/page motion seems opposite than expected. Right to left swipe causes page to "turn" in opposite direction than swiping in all other apps. Might above setting have something to do with this?

**Comment by danielweck** [comment]
When a Right To Left (RTL) document is open, some controls in the user interface switch sides. However, we received feedback from Japanese users that some may prefer to preserve the LTR direction for some UI controls.

**Comment by danielweck** [comment]
Swipe configuration should be configurable in my opinion.
For example on MacOS the default "natural" direction is totally unnatural for me :)
(learned habits)

**Comment by khalid-hussain** [comment]
The Arabic language is read from right to left. Here is a demonstration with an Arabic EPUB file:

https://github.com/user-attachments/assets/b4c9170f-4865-4e2d-a36e-b10a447782e0

I hope it provides some clarification.

**Comment by panaC** [comment]
I'm closing the issue
