### ISSUE TITLE
GUI Freeze when Deleting Book

### ISSUE THREAD

**Issue by dazrand** [edrlab/thorium-reader#2488]
Mac OS 14.5, M2 chip, Thorium 3.0.0.
 
Changing to 'All publications' and deleting a book in either Grid or Table view leaves the interface frozen in a grey out state, with the menu options open for the next title in the display (the deleted book disappears).  Deleting the last book in the library does not cause this issue, nor does deleting from the 'Home' view.
![Screenshot 2024-07-05 at 08 23 32](https://github.com/edrlab/thorium-reader/assets/45215370/2770f694-b9b5-4d53-9a5a-d0a8dfe2657a)

I can quit Thorium via keyboard and restart without issue.

**Comment by danielweck** [comment]
duplicate: https://github.com/edrlab/thorium-reader/issues/2479

**Comment by danielweck** [comment]
fixed via https://github.com/edrlab/thorium-reader/commit/0edc73d1ccc252227215bdcf4f5ab6263c511930
