### ISSUE TITLE
Ability to Use Tabs Instead of Windows

### ISSUE THREAD

**Issue by Marc2p** [edrlab/thorium-reader#2493]
Hi,
It would be interesting to have the option to configure Thorium so that when opening a book, it opens in a tab instead of a separate window. Currently, when a book is opened, the main window remains open. If it is closed, the entire program closes, including the window of the current book. This would be more convenient for those of us who prefer to avoid having many windows open, and it could be configurable so that each person can set it to their preference.
Thank you very much,
Best regards

**Comment by panaC** [comment]
Hello, it's not plan in the roadmap, I'm closing the issue
