### ISSUE TITLE
Books and Catalogs Not Added When Opened Directly

### ISSUE THREAD

**Issue by Marc2p** [edrlab/thorium-reader#2494]
Hi,
When opening an epub file with Thorium from the file explorer, or when opening an OPDS link, such as the one in the Thorium 3 documentation (opds://rawcdn.githack.com/edrlab/publications/main/feeds/thorium3_documentation.json), they are not added to Thorium. The process has to be done manually by importing a book or catalog from within the application.
I have tried reinstalling the application and have asked other people who do not seem to have this issue, so I am unsure why this is happening to me.
Thank you very much,
Best regards

**Comment by panaC** [comment]
Do you see this https://github.com/edrlab/thorium-reader/issues/2163 ?

**Comment by Marc2p** [comment]
Yes, definitely this issue is similar to #2163, But it happens to me both with the Microsoft store version and with the installer of the latest release.
I solved it by compiling and installing Thorium from source, version v3.1.0-alpha.1.
I'm using Windows 11 23H2 (AMD64) build 22631.4112

**Comment by danielweck** [comment]
This is likely fixed by https://github.com/edrlab/thorium-reader/pull/2666 @panaC ?
