### ISSUE TITLE
Navigating feeds using keyboard arrows

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#2495]
From a user: "In the OPDS Thorium catalog version 3, I cannot move pages using the keyboard (Next button), if I use the mouse click it can work fine."

It is true that for many people, using the left / right arrow key to browse "My books" or an OPDS catalog would be useful.

**Comment by llemeurfr** [comment]
Additional comment from the user, who is a **screen reader** user: he was speaking about ODPS feeds especially. 

On OPDs feeds, next/previous affordances are on the bottom of the screen. When I tabulate to these icons, I see something strange: I need two tabs to move from the Previous or Next arrow to the following icon, and the return key only works after the extra tab. This is not the case with the arrows on the "My Books" page. 
Could it signal something wrong?

**Comment by panaC** [comment]
#2554
