### ISSUE TITLE
font-size is not applied

### ISSUE THREAD

**Issue by civodulab** [edrlab/thorium-reader#2496]
Hello,
When I apply a `font-size` in my CSS it is not applied.

**Comment by civodulab** [comment]
Hello,
Is this a bug or an error on my part?

**Comment by panaC** [comment]
Hello civodulab, Thorium reader rely on [readium-css](https://github.com/readium/readium-css). I suppose that you speak about the html headings. In the current version there are overloaded and the next version it will be more flexible.

Thanks you to reporting this issue, I invite you to write an issue on the specific readium-css repository instead.

**Comment by civodulab** [comment]
Thank you for your reply.
It's not just for html headings, it's for text in general.
