### ISSUE TITLE
[ Functional Request ] Expect the window to be smaller

### ISSUE THREAD

**Issue by Leroy-X** [edrlab/thorium-reader#2499]
The minimum window limit is still a bit large. Hopefully it can be smaller, like half the current minimum.

This is probably to accommodate the button display. I think the buttons could be smaller, or scrollable, like holding down the middle mouse button to drag the button panel left or right to display it in a smaller window.

Thanks.

**Comment by panaC** [comment]
Hello Leroy-X, sorry to said that but the new thorium design doesn't allow to reduce the size of the window. It's a designer choice. I'm closing the issue, feel free to reopen it if needed.
