### ISSUE TITLE
Version 3 Line Spacing

### ISSUE THREAD

**Issue by salasnet** [edrlab/thorium-reader#2500]
My apologies for a duplicate of my post at thorium-reader-doc, but was not sure where to post it:

Thorium 3 has a change in functionality from Version 2 that renders Version 3 not usable for me.

In the Line Spacing options, the increments have changed to only 0.5, 1, 1.5, etc. This does not offer the fine control for Line Spacing that Version 2 did. In Version 2 you could change the Line Spacing in smaller increments. 1.13, 1.25, 1.35, 1.5. As it turns out, a Line Spacing of 1.35 was ideal for me and the ebooks I own, and that Line Spacing option is now gone. In Version 3, Line Spacing "1" is too tight, and the next one up "1.5" is too wide.

Would it be possible to re-enable the Line Spacing options from Version 2 in Version 3?

Everything else about Version 3 is an improvement over Version 2, and I would love to switch, but not with the regression in Line Spacing options. This change alone has made me revert to Version 2 for the time being.

**Comment by danielweck** [comment]
good point.

in Thorium 2.x (before the Thorium V3 refactor), the values were mapped as follows:

https://github.com/readium/r2-navigator-js/blob/60d585929ed98abe672a3c6c3d91e3298df3f4a7/src/electron/common/readium-css-settings.ts#L122

 https://github.com/edrlab/thorium-reader/blob/e828405e8d80e5e19e083c50da0d1a08c346bf17/src/renderer/reader/components/Reader.tsx#L2600

https://github.com/edrlab/thorium-reader/blob/e828405e8d80e5e19e083c50da0d1a08c346bf17/src/renderer/reader/components/options-values.ts#L80

**Comment by salasnet** [comment]
Is this something I can fix myself in the config, or does it need to be fixed at source?
