### ISSUE TITLE
The title bar is still visible in full-screen mode.

### ISSUE THREAD

**Issue by jellebakker96** [edrlab/thorium-reader#2517]
Windows version V3.0.0.

The title bar is still visible in full-screen mode.

My current solution is to downgrade to version 2.3.0.

**Comment by panaC** [comment]
To go fullscreen on Chromium webview : `Ctrl + Cmd + f` on Mac or `F11` on PC. 

I'm closing the issue, feel free to reopen it.

**Comment by jellebakker96** [comment]
Maybe add a button for this? Or at least give a hint when hovering over the full-screen button that this shortcut exists? Maybe some other solution.

I, for example, did not know that Thorium runs on Chromium and if I was confused about this behaviour then other people are likely also confused by this.

For me, this is now solved. I only re-opened this issue to see if there was some solution such that other people do not run into the same problem. Feel free to close it if you disagree :).

**Comment by jellebakker96** [comment]
@panaC I could not reopen the issue so I am using the @.. option to let you know there is a new message.

**Comment by panaC** [comment]
Hello, 

We already bind a generic keyboard shortcut on reader window : `ctrl` + `F11` , works on the 3 OS (Linux, MacOS and Windows).

See the documentation : https://thorium.edrlab.org/fr/docs/400_ressources/402_keyboard-shortcuts/

https://github.com/edrlab/thorium-reader-doc/blob/9c43fe070fc14ed4b97c79a72bc33ad4815e02cb/content/en/th3/400_ressources/402_Keyboard-shortcuts.md?plain=1#L56-L57

**Comment by DeltaGarnet** [comment]
I don't know if it changed, but now on Windows F11 does nothing but ctrl+f11 works
