### ISSUE TITLE
[CSS] scrollbar arrow right remain white in dark mode

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#2522]
OS: Linux manjaro gnome

need to double check with macos

![image](https://github.com/user-attachments/assets/48f7c97b-a81a-4f35-bd4f-6ac5a19049dc)

**Comment by arthur-lemeur** [comment]
![Capture d’écran 2024-09-05 à 12 05 52](https://github.com/user-attachments/assets/7c1b10cc-2ad7-40c5-bbd9-512bd663ca7e)

It seems this white square is inherent to the html scrollbar when horizontal AND vertical, I haven't found any way around it yet.
