### ISSUE TITLE
[CSS] Input label background is over the input text outline 

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#2523]
![image](https://github.com/user-attachments/assets/36f76191-0324-4d74-b668-31142c296b03)
![image](https://github.com/user-attachments/assets/ac3ca5fa-5ce8-42c5-9158-929cf77f1232)

**Comment by panaC** [comment]
![image](https://github.com/user-attachments/assets/0d8052f7-2ce7-4ccf-9754-16318fa4416f)

"Tag" should be centered instead ?

**Comment by arthur-lemeur** [comment]
After verification I noticed that we should have already fixed the background colour difference, so I can lower the label for it to be centered with the input border (see screenshot). So I don't understand from where comes your first screenshot.

<img width="297" alt="Capture d’écran 2024-09-05 à 09 55 05" src="https://github.com/user-attachments/assets/9ae8ec20-c0e0-4cc6-8e31-a0833da42103">
