### ISSUE TITLE
Slow loading on 3.0.0 AppImage on Linux (OpenSUSE)

### ISSUE THREAD

**Issue by p-kenny** [edrlab/thorium-reader#2525]
I am using Thorium 3.0.0 AppImage on OpenSUSE Tumbleweed and Gnome 46.

Since starting to use this version I have noticed that loading an epub file is taking a very long time. I have tried several files that worked well on previous versions so can discount the files themselves.

Great new look by the way!

Thanks
Paul

**Comment by gautierchomel** [comment]
Several memory issues affect Linux packages, most probably related to this electron issue https://github.com/electron/electron/issues/42019

**Comment by danielweck** [comment]
Duplicate of https://github.com/edrlab/thorium-reader/issues/2519
