### ISSUE TITLE
Bug : Thorium Reader 3.0.0 is closing without opening the LCPL file - W10

### ISSUE THREAD

**Issue by yves-git-hub** [edrlab/thorium-reader#2531]
Hello,

I'm using W10 V 22H2 with Thorium Reader V 3.0.0.

First time I uploaded the file, I was able to read the file. Now, I can see the file in the list of publications, but when I try to double click, Thorium is closing directly.

So I tried to upload on an another PC, I downloaded the same Thorium version (on same W10 V 22H2) and when I upload (or double click) the LCPL file, the application is closing spontaneously; I d'ont get any error code.

Any idea to fix this ?

Thanks a lot.

Yves

**Comment by llemeurfr** [comment]
Hi, we'll need to reproduce the issue. I wrote you in PM.

**Comment by yves-git-hub** [comment]
Dear,

Sorry, I just understood, I don't know why, but my PC set me in France instead of Belgium so this is why the Thorium reader was closing (without message).
This is solved, I set my VPN on Belgium and is working now.

So this can be closed.

Thanks for your help.

**Comment by panaC** [comment]
Bonjour, est-ce possible de vous contactez directement par mail ? Est-ce possible de me partager secrètement le fichier .lcpl avec sa passphrase ? Ce n'est effectivement pas normal que Thorium se ferme lors de l'import. Je suppose que la publication est protégée par géolocalisation IP, Thorium devrais cependant afficher un message d'erreur et non se fermer brusquement.
