### ISSUE TITLE
Crash: opds publicationInfoA11y Component crash with strictNullChecks issue

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#2537]
https://github.com/edrlab/thorium-reader/commit/1d48f88691134b8d0f53bbe5a0f70b7f0d3d6904#diff-c5ec05104b3b03043bf6ce4a94909efdf62885f1d6799649fe183076a3ee6cd2R59-R60

https://rawcdn.githack.com/edrlab/thorium-reader-epub-tests/main/EPUB_Feeds_for_testing_purpose/opds-rare-epub-suit.json

**Comment by panaC** [comment]
https://edrlab.github.io/publications/feeds/thorium3_documentation.json

**Comment by danielweck** [comment]
the OPDS link above does not trigger the bug because the accessModeSufficient was removed.

**Comment by danielweck** [comment]
this link points to an invalid OPDS feed (not conforming to the JSON Schema) where accessModeSufficient is not an array.
(in this case, the crash isn't in Thorium, it is in the low-level  parser which doesn't tolerate non-array property value)

**Comment by danielweck** [comment]
see: https://github.com/edrlab/publications/commit/c4f20192e70cc6361e3281f453fcafd3927c855b

**Comment by danielweck** [comment]
accessModeSufficient is an array of string arrays ... but the string arrays with a single item can be reduced to a string value.

JSON Schema:
    https://github.com/readium/webpub-manifest/blob/03d7681cf1ff689bad76efaabc9c77423296a94c/schema/a11y.schema.json#L54-L82

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/commit/7eae5aa61f0fb26ddce35e78688582a856d400aa

**Comment by panaC** [comment]
It was fixed with this commit : https://github.com/edrlab/thorium-reader/commit/7eae5aa61f0fb26ddce35e78688582a856d400aa

Works with https://rawcdn.githack.com/edrlab/thorium-reader-epub-tests/main/EPUB_Feeds_for_testing_purpose/opds-rare-epub-suit.json

I'm closing the issue, feel free to reopen it @gautierchomel 
Thanks

**Comment by danielweck** [comment]
can we please test with a real world example like this:

accessModeSufficient: [ ["textual", "visual"], "textual" ]

and 

accessModeSufficient: [ ["textual", "visual"], ["textual"] ]

http://kb.daisy.org/publishing/docs/metadata/schema.org/accessModeSufficient.html

thank you :)

(ps: instead of hand-crafting an OPDS feed for each case, maybe just force the values in Thorium post-parsing, pre-JSX?)
