### ISSUE TITLE
[BUG] OPDS Previous Page Keyboard Shortcut with no previous page redirect to the next page from the current page

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#2554]
From https://github.com/edrlab/thorium-reader/pull/2501

> I just tested on the Blbliomedia feed (https://bm.ebibliomedia.ch/v1/home.opds2), which has no "previous page" information:
Shift + Ctrl + ArrowLeft leads to the NEXT page, like Shift + Ctrl + ArrowRight.
To be decided it we consider it a bug (but in this case should Shift + Ctrl + ArrowLeft be inactive or display an error message?) or a feature.

**Comment by llemeurfr** [comment]
I consider it as a bug. 
The bast UX would be to emit a sound in such a case (Shift + Ctrl + ArrowLeft with no previous page, same for Shift + Ctrl + ArrowRight with no next page), but I'm not sure we have the proper tools for that.
