### ISSUE TITLE
Custom font is not understood

### ISSUE THREAD

**Issue by gautierchomel** [edrlab/thorium-reader#2558]
As described in the [documentation](https://streamer.edrlab.org/readerNYPL/?url=https%3A%2F%2Fstreamer.edrlab.org%2Fpub%2FaHR0cHM6Ly9naXRodWIuY29tL2VkcmxhYi9wdWJsaWNhdGlvbnMvcmF3L21haW4vdGhvcml1bTMtZG9jdW1lbnRhdGlvbi9zb3VyY2VzL2VuLmVwdWI%3D%2Fmanifest.json), in the font selection menu one can enter the name of the font he wants to use.

Thorium 2 has a ... menu entry that was not very well understood but that was triggering user curiosity. 

In Thorium3 This feature is indicated after the menu in an info box but users don't understand the message as it is not Inside the dropdown menu. 

Different solutions are possible, I  suggest the following: 
* add a line to the menu, something like _"enter you own font"_
* change the info box text to something clearer like: _"By selecting the  "enter you own font" you can enter the name of the font you want to use. The font must be present on your operating system and you must know its exact name as it is set for the operating system."_

**Comment by llemeurfr** [comment]
We will
- use a placeholder to display the chosen font in the input field
- adapt dynamically the text below as "You have chosen a personal font".
