### ISSUE TITLE
Feature: Show page numbers visually

### ISSUE THREAD

**Issue by ddfreiling** [edrlab/thorium-reader#2567]
A highly requested feature from our study-book users is being able to visually see the page numbers of the book.

Could this be made as a togglable feature? We'd love to give the implementation a shot, if EDRLab is onboard with having this feature in Thorium Reader.

Somewhat related to https://github.com/edrlab/thorium-reader/issues/1958

**Comment by gautierchomel** [comment]
This is related to discussion https://github.com/edrlab/thorium-reader/discussions/1799.

The main difficulty for a reading system is that forcing display of page numbers will result in strange patterns as they can be in the middle of a phrase or a word.

**Comment by gautierchomel** [comment]
The best UX would probably be to have a margin display.

**Comment by danielweck** [comment]
Moved to discussion https://github.com/edrlab/thorium-reader/discussions/1799#discussioncomment-11425125
