### ISSUE TITLE
Add .fb2 support

### ISSUE THREAD

**Issue by Korb** [edrlab/thorium-reader#2595]
Currently, when dragging an [.fb2](https://en.wikipedia.org/wiki/FictionBook) file onto the application window, an error message appears:

```
An error occurred, verify the file extension
([([fb2].lcpl.epub.epub3.audioebook
..web pub.lcp.lcp audiobook.lc pdf.pdf.pdf
.divina .daisy.zip .opf ncc.html)
```

Thorium.Setup.3.0.0.exe
Microsoft Windows 10.0.19045.4957

**Comment by danielweck** [comment]
this publication format is not supported, sorry :(
