### ISSUE TITLE
[crash] browserWindow win.webContents when destroyed

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#2602]
[win.webContents](https://github.com/edrlab/thorium-reader/blob/ff1f46bf4ddf03ced453c78ee6aff596228c6d33/src/main/redux/sagas/app.ts#L87)

**Comment by danielweck** [comment]
Hello Pierre, please see my comments and review request for:
https://github.com/edrlab/thorium-reader/pull/2640
