### ISSUE TITLE
Request: change Appimage package naming convention

### ISSUE THREAD

**Issue by BBBalls** [edrlab/thorium-reader#2604]
I utilize the Linux application [Gear Lever](https://github.com/mijorus/gearlever) to manage Appimages. It has a feature for updating Appimages by checking and downloading from GitHub. The updating feature requires providing a slightly altered release url, with the variable parts replaced with an `*`.

The current naming convention amd64 version of the Appimage doesn't allow for the updating feature to work properly. The modified release url for the amd64 Appimage is `https://github.com/edrlab/thorium-reader/releases/download/*/Thorium-*.AppImage`, but the arm64 version also fits the variable, and is what is downloaded as an update.

It would be appreciated if the amd64 Appimage release filename convention is changed to include the processor architecture, e.g. ` Thorium-3.0.0-amd64.AppImage`. This would allow for creating a more specific release update link, e.g. `https://github.com/edrlab/thorium-reader/releases/download/*/Thorium-*-amd64.AppImage`.

Thank you for the great reading application.

**Comment by danielweck** [comment]
Hello, we too have to work around this inconsistent naming convention, which we inherit from Electron Builder https://github.com/electron-userland/electron-builder

I am afraid I am not willing to change this convention as this would break our build scripts and processes. Sorry.
