### ISSUE TITLE
Heading issue in epub

### ISSUE THREAD

**Issue by najibullah073** [edrlab/thorium-reader#2605]
When I adjust the heading sizes in the EPUB—setting H1 to 30pt, H2 to 25pt, and H3 to 20pt—they don’t display correctly in Thorium Reader. All the headings appear as if they are styled like H3, with no visible distinction between the heading levels.

Can you help identify why Thorium is rendering them incorrectly, despite the adjustments in the EPUB file?

**Comment by llemeurfr** [comment]
Thanks for the message. 
This is a known limitation of the current Readium CSS (it was too hard at normalizing headings), that will be addressed in the next version of Thorium Reader, v3.1.
