### ISSUE TITLE
Daisy2.02 issue with several audio tags in <seq>

### ISSUE THREAD

**Issue by oscarlcarlsson** [edrlab/thorium-reader#2624]
If a Daisy2.02 file includes sequence tags with more than one audio-tag, the first audio-tag is played and the following are ignored. This leads to audio glitches in the played file.

In the example below you only get the first half second of the audio, then it jumps to the following par-tag.

Example:
`<par endsync="last" id="par_fixgen_893">
	<text src="ca68998.html#dol_1_26_id_fixgen_893" id="txt_fixgen_893"/>
	<seq>
		<audio src="026_2_1_A_Note_on_Python_Versi.mp3" clip-begin="npt=7.319s" clip-end="npt=7.863s" id="audio_0004"/>
		<audio src="026_2_1_A_Note_on_Python_Versi.mp3" clip-begin="npt=7.863s" clip-end="npt=10.083s" id="audio_0005"/>
		<audio src="026_2_1_A_Note_on_Python_Versi.mp3" clip-begin="npt=10.083s" clip-end="npt=12.970s" id="audio_0006"/>
		<audio src="026_2_1_A_Note_on_Python_Versi.mp3" clip-begin="npt=12.970s" clip-end="npt=14.289s" id="audio_0007"/>
		<audio src="026_2_1_A_Note_on_Python_Versi.mp3" clip-begin="npt=14.289s" clip-end="npt=17.759s" id="audio_0008"/>
	</seq>
</par>`

As per the daisy 2.02-specification, this should be allowed.

See attached file for reference.
[epub_testfil_camabo_daisy_source.zip](https://github.com/user-attachments/files/17570243/epub_testfil_camabo_daisy_source.zip)

**Comment by danielweck** [comment]
Thank you very much for reporting this. Fixed via:
* https://github.com/edrlab/thorium-reader/commit/03f39d952236d74ed9573515045671e02e7f5667
* https://github.com/readium/r2-shared-js/commit/094d99d538c117dcdc5bdad0132725707bb01299
