### ISSUE TITLE
privacy issue: annotations "creator" is a person's name / nickname

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2628]
Suggestion: somehow inform Thorium user that personal information is stored only the user's local database, and user can opt-in (not opt-out) to include personal information when exporting annotations.

**Comment by llemeurfr** [comment]
interesting yes. the creator's name is optional but really useful, and Thorium should export it when the user agrees. 
@panaC, can we add a flag to the Settings / General? 
Label EN: "Do you want your name to be included in your annotations when exported?" (yes/no), no default.  
Same look as the session flag, below this one.

**Comment by llemeurfr** [comment]
The creator id will be automatically generated as a UUID if the flag is set to Yes, and stored.

**Comment by panaC** [comment]
Hello @llemeurfr @danielweck , i'm suggestiing to not set the creator name from the Operating System username info and let user define it. The creator name is only useful on annotation export. So That didn't make sense to save it locally in db when the creator name in annotation set is not exported and shared to everyone.

**Comment by llemeurfr** [comment]
@panaC in a previous comment, I proposed a process to ask the user if he wanted to have his name stored in the db and exported with his notes. Did you take it into account?

**Comment by panaC** [comment]
@llemeurfr yes I did

**Comment by panaC** [comment]
@llemeurfr  I will working with Arthur to add a description message below creator title section to explain to user, as said by Daniel, that this information will be shared with the annotation set export format. As I understand the original Daniel issue is more to explain to the user what is the purpose of the creator name than to add a new key/value flag in db to enable or not an another db state value. May I'm wrong

**Comment by panaC** [comment]
@llemeurfr if the user doesn't want/can shared personnal info to the annotation set export file, it is better to include a checkbox in the export confirmation modal below the  textedit title and above the save as confirmation button.

**Comment by panaC** [comment]
@llemeurfr 2 solutions : The first, the user choose a name that can be shareable and not private, and choose to export any annotation set with this nickname. The second, the user want to secretly share a specific annotation set with his specific notes taken during his lecture. He wish to specify a name of the export and uncheck a box to not copy his nickname to this special annotation set export, and now share it anonymously to everyone for this special occasion only. In this case an export form modal with an anonymity checkbox is more useful than a checkbox in settings.

**Comment by llemeurfr** [comment]
ok so let's implement a simple solution: 
- in the Settings / General, there is a new text field labelled "User name". 
- Below is this file an explanation: "This will be used as the creator of the notes you may export; enter a nickname or leave it empty if you prefer.".
- When exporting notes, if not empty, the value is used as value for "creator". In this case the creator type is always "Person" (we do not deal with Organizations in Thorium). If empty, the creator property is not included.

We don't need to add a check box at export to allow the user to "anonymize" his export. This is an opt-in functionality: most of the time, the creator field in the settings will be left empty, therefore there will be not creator.
