### ISSUE TITLE
Daisy2.02 issue footnotes cannot be turned off

### ISSUE THREAD

**Issue by oscarlcarlsson** [edrlab/thorium-reader#2630]
For Daisy2.02-titles, skipability/disable footnotes does not allow footnotes to be skipped.
The attribute `system-required="footnote-on"` is used in the smil-files, but it still plays the footnotes. See attached file for examples (example in smil-file ca111111_241030_tts_0012.smil)
[CA111111_241030_TTS.zip](https://github.com/user-attachments/files/17585774/CA111111_241030_TTS.zip)

**Comment by danielweck** [comment]
Fixed via:
* https://github.com/readium/r2-shared-js/commit/4f43518b39720b951a37a036790c6e79a11038d4
* https://github.com/edrlab/thorium-reader/commit/827e2b890a67687f2b7ea3c7ca17baa5365ac21e
