### ISSUE TITLE
Search bar displayed on top of publication information/navigation/reader settings window in reader window

### ISSUE THREAD

**Issue by naglis** [edrlab/thorium-reader#2661]
Tested with Thorium v3.0.0 AppImage on Arch Linux (running under Wayland).

Steps to reproduce:

1. Open some publication.
2. Reduce the size of the reader window.
3. Click on the "search publication" button (<kbd>Ctrl+F</kbd>).
4. Click on the publication information button (<kbd>Ctrl+I</kbd>), navigation button (<kbd>Ctrl+N</kbd>) or reader settings button (<kbd>Ctrl+S</kbd>).
5. The search bar is displayed over the information/navigation/reader settings window.

Below is a demo video displaying the issue:

https://github.com/user-attachments/assets/c431e9ce-e452-424b-8c5a-791c7a27d152

**Comment by danielweck** [comment]
zindex strikes again :)

@arthur-lemeur ?
