### ISSUE TITLE
electron33 : protocol.registerFileProtocol is deprecated !?!

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#2672]
https://www.electronjs.org/docs/latest/api/protocol#protocolregisterfileprotocolscheme-handler-deprecated

https://www.electronjs.org/docs/latest/api/protocol#protocolregisterschemesasprivilegedcustomschemes

https://www.electronjs.org/docs/latest/api/protocol#protocolhandlescheme-handler

**Comment by panaC** [comment]
https://github.com/edrlab/thorium-reader/blob/57a79dda7bc83fbbfdae5b1b3e33887212eb3a40/src/main/redux/sagas/app.ts#L143

https://github.com/edrlab/thorium-reader/blob/57a79dda7bc83fbbfdae5b1b3e33887212eb3a40/src/main/redux/sagas/app.ts#L163C14-L163C34

https://github.com/edrlab/thorium-reader/blob/57a79dda7bc83fbbfdae5b1b3e33887212eb3a40/src/main/redux/sagas/app.ts#L178

**Comment by danielweck** [comment]
`npm run package:mac:skip-notarize`
==>
`npx @electron/fuses read --app ./release/mac-arm64/Thorium.app`

```
Analyzing app: Thorium.app
Fuse Version: v1
  RunAsNode is Disabled
  EnableCookieEncryption is Disabled
  EnableNodeOptionsEnvironmentVariable is Disabled
  EnableNodeCliInspectArguments is Disabled
  EnableEmbeddedAsarIntegrityValidation is Disabled
  OnlyLoadAppFromAsar is Disabled
  LoadBrowserProcessSpecificV8Snapshot is Disabled
  GrantFileProtocolExtraPrivileges is Enabled
```

https://github.com/edrlab/thorium-reader/blob/a8e7da9e9d5b3901601c4d356b91a6c2eb267a52/scripts/afterPack.js#L52-L84

===> `[FuseV1Options.GrantFileProtocolExtraPrivileges]: true`

> TODO: make this FALSE! (file://)
