### ISSUE TITLE
GUI: search bar causes content reflow (viewport vertical shrinking), AND top margin/padding removal

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#2683]
<img width="1840" alt="Screenshot 2024-12-01 at 00 04 16" src="https://github.com/user-attachments/assets/5a722472-fa2c-42ad-af9c-37d021d51b60">
<img width="1840" alt="Screenshot 2024-12-01 at 00 05 02" src="https://github.com/user-attachments/assets/91694198-cbf9-429c-b9fa-3a7b0266a792">

**Comment by danielweck** [comment]
I wonder if it is possible to EITHER / OR:
1) shrink vertical viewport, cause reflow, BUT preserve top whitespace
2) do not modify viewport height, no content reflow, BUT sacrifice top whitespace

**Comment by panaC** [comment]
Fixed by #2685
