### ISSUE TITLE
Reading window behavior

### ISSUE THREAD

**Issue by manuellagrand** [edrlab/thorium-reader#271]
when a book is detached and we want to open a book again. it shouldn't open in detach mode by default

**Comment by llemeurfr** [comment]
Steps: 
- Open a book. 
- Detach the reading window; the main window re-appears
- Open a second book: it appears in a detached window; it should not. It should be detached only if the user decides so.

**Comment by llemeurfr** [comment]
After discussion, the current process is not so bad: if we open a second book and detach is, then a third book that we don't detach, the user is facing 2 detach reading windows and 1 attached one: where is the "back to catalog" button? the user will have to search. 

But in this case, the "detach" button should not be in the reading window, but in the catalog window, as a toggle: off by default, on when the user wants to detach its reading window. 

We can make this modification quite easily I guess.

**Comment by llemeurfr** [comment]
Move the "detach" button to the Bookshelf view. It's a toogle, grey if active. If active and a book is open, its windows is detached.

**Comment by Scarsniik** [comment]
What should happen if a reader is already opened and the user disable the detached readers ?

**Comment by llemeurfr** [comment]
Good question @Scarsniik. 
My first reaction was: let the user disable the "detach" button, take this new status into account the next time he opens an ebook. But that would mean he could have N windows open + 1 replacing the bookshelf, which is not logical.
Therefore the only solution seems to be: activate the "detach" button only if no window is detached. Once a window has been detached, the button is blocked in "detach" state. When all windows have been closed, then the toggle button can be used again. I hope the UX will be clear enough ...
Do you see a better solution?

**Comment by Scarsniik** [comment]
Yes, I think it's ok like that

**Comment by Scarsniik** [comment]
fixed in ##638

**Comment by llemeurfr** [comment]
As discussed in the comment of issue 638, the UX proposed by iBooks maybe less confusing: 
in iBooks, there is no "detach" button in the reader view but rather a "show the library" button. Each reader view contains such a button (where in our implementation only a non-detached reader view contains a detach button). 

I propose to let this issue in the discussion section for some time, gather feedbacks from users and react accordingly.

**Comment by danielweck** [comment]
Specific issue about the "obscured" library window when detaching (which users/testers are probably going to report): https://github.com/readium/readium-desktop/issues/494
