### ISSUE TITLE
Feature Suggestions for Thorium Reader

### ISSUE THREAD

**Issue by RonnyG2121** [edrlab/thorium-reader#2719]
Dear Thorium Reader Development Team,  

First of all, thank you for your excellent work on Thorium Reader. It’s an outstanding tool for reading books in various formats, and I deeply appreciate its focus on accessibility.  

I would like to suggest two enhancements for the text-to-speech (TTS) feature:  

1. **Support for More Installed Voices**: It would be great if Thorium Reader could allow users to access and select from a wider range of voices installed on their Windows system. Thorium Reader Thorium Reader only reads books with Microsoft voices.
2. 
3. This would provide greater flexibility and a more personalized reading experience for users.  
4. **Page-Turn Sound Effect**: Adding an optional sound effect when turning pages could enhance the reading experience by providing an auditory cue, making it feel more interactive and immersive.  

I believe these features would further improve the accessibility and usability of Thorium Reader for a broader audience.  

Thank you for considering these suggestions, and please let me know if there’s anything I can do to help test or provide additional feedback.  
Thank you.

**Comment by llemeurfr** [comment]
Hi, this falls in Discussions more than Issues. 

In short, what limits the use of more voices on Windows is that many installed voices are not exposed to Chromium. We cannot do much about this. We are still looking for ways to get more voices "seen" by the app. 

Page-turn sound effect is a personal preference, not shared by the developers of this application, sorry :-)
