### ISSUE TITLE
Issues regarding performance and customisation.

### ISSUE THREAD

**Issue by TheShiningBoots** [edrlab/thorium-reader#2734]
I recently installed Thorium for managing my ever growing collection of books. I have two problems with this app they are:
1) There is no customisation for the installation or data storage directory during installing but it can easily be overcome and 
2) Importing a folder of pdfs causes the programs to spawn tons and tons of processes which can crash your pc, because whenever you try to import a pdf the app also decides to open it. There should be a way to prevent this.

I am using Thorium 3.0

**Comment by TheShiningBoots** [comment]
Tried on Windows 10.

**Comment by danielweck** [comment]
hello, yes the PDF import system extracts the cover image from the file by loading and rendering the contents (first page) which can be very resource-intensive. This process must be improved / made lighter.

**Comment by danielweck** [comment]
What would you advise users to do regarding the installation directory and data folder? Any tips worth sharing?

**Comment by TheShiningBoots** [comment]
Thanks for the quick reply.
The installation directory can be changed by simply following the path from the start menu(Open file location) and moving it over to the desired location, the shortcut then needs to be changed to match the new location of the exe. This can be done by opening the properties of the shortcut.(You need to change both the `target` and `start in` fields, also if in case the throium icon does not appear on the taskbar you will need to press the `Change Icon` button in the properties and point to the new exe). You can also use the mklink command here on windows which will save you the above hassles.  

Also on windows you can open regedit and make changes to the default before installing throium and then reverting it after install but I dont recommend it.

**Comment by TheShiningBoots** [comment]
I am pretty sure the symlink method would also work for the data.

**Comment by TheShiningBoots** [comment]
I switched over to arch Linux today and I am now using zathura.
