### ISSUE TITLE
"go fullscreen" button doesn't actually make thorium-reader take up the full screen (Windows 10)

### ISSUE THREAD

**Issue by e-martinsson** [edrlab/thorium-reader#2735]
Platform: Windows 10

When pressing the "go fullscreen" button at the top right, only the UI buttons inside the reader are hidden. This is not actually a fullscreen mode - the windows UI elements are still there. This is distracting and unintuitive. See screenshot.

![image](https://github.com/user-attachments/assets/38caa8b8-c9ac-47f1-882f-ce4369520771)

**Comment by panaC** [comment]
Hello e-martinsson, to go fullscreen press `Ctrl + Cmd + f` on MacOS or `F11` on PC or `ctrl + F11` from Thorium internal shortcut.

**Comment by llemeurfr** [comment]
The remark is right, this feature is called internally "Zen mode". Let's surface it in the UI labels.
