### ISSUE TITLE
Select word to get definition

### ISSUE THREAD

**Issue by e-martinsson** [edrlab/thorium-reader#2736]
Coming from Aquile Reader, a neat feature I miss is being able to select a word in the epub I'm reading and being able to immediately get the definition of the world looked up for me in a small box that pops up next to the word. See screenshot for how that looks like in Aquile reader (Windows 10)

![image](https://github.com/user-attachments/assets/d9381e31-e0ee-496f-ae92-c829175f26ea)

**Comment by panaC** [comment]
duplicate with https://github.com/edrlab/thorium-reader/discussions/2615
I'm closing the issue
