### ISSUE TITLE
Allow searching by author

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#298]
Currently the search is limited to the book title. The name of the author should also be a search token.

**Comment by danielweck** [comment]
Related issue:
https://github.com/readium/readium-desktop/issues/594
(I am concerned about using a very old version of `lunr` which seems buggy ... and we cannot update it because it is a transitive dependency of `pouchdb-quick-search`)

**Comment by danielweck** [comment]
Re-assigning this lower-priority issue to Leo, as it is totally related to this one:
https://github.com/readium/readium-desktop/issues/594

**Comment by llemeurfr** [comment]
The authors are currently not stored separately and cannot be indexed in the publication document.

As we have a plan to move from pouchdb to sqlite, I propose to ice this issue and develop search on sqlite FTS during this port.

**Comment by danielweck** [comment]
Code reference: https://github.com/readium/readium-desktop/blob/develop/src/main/db/repository/publication.ts
