### ISSUE TITLE
Cannot go to next page / Japanese-vertical-writing

### ISSUE THREAD

**Issue by toshiakikoike** [edrlab/thorium-reader#327]
Version: v1.0.0-alpha.2(Release Version)
Sample EPUB:
https://github.com/toshiakikoike/epub_file/blob/master/mymedia.epub
Sample Source:
https://github.com/toshiakikoike/epub_file/tree/master/mymedia

Problem: Cannot go to next page after Page3(https://github.com/toshiakikoike/epub_file/blob/master/mymedia/OEBPS/text/book_0002.xhtml)

Images:
Page1: OK(Only one Image)
<img src="https://github.com/toshiakikoike/epub_file/blob/master/readium002.png?raw=true">
Page:2: OK(Only one line)
<img src="https://github.com/toshiakikoike/epub_file/blob/master/readium003.png?raw=true">
Page:3: NG(Many Paragraphs) Cannot go to next page by clicking left triangle icon.
<img src="https://github.com/toshiakikoike/epub_file/blob/master/readium004.png?raw=true">

**Comment by danielweck** [comment]
Hello, the current support for Japanese left-to-right + vertical-writing-mode is broken (documents render at the first page / CSS column, but it is impossible to turn the pages / move to the next column).

I filed an issue: https://github.com/readium/r2-navigator-js/issues/42

**Comment by danielweck** [comment]
Merging into: https://github.com/edrlab/thorium-reader/issues/959
