### ISSUE TITLE
When detaching reader window with unchanged dimensions / position, library view restored "behind" without obvious visual feedback

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#494]
... when the reader window dimensions or position is changed, then the library view is restored with the original saved dimensions, so it is usually visible (unless the reader window is larger / overlaps the library view)

So, how could we ensure better visual feedback for this feature?

**Comment by danielweck** [comment]
Re-opening, as the problem persists.

**Comment by Scarsniik** [comment]
Does someone has an idea to do that ? I really have no idea

**Comment by panaC** [comment]
i believe that is fixed

**Comment by Scarsniik** [comment]
Is this issue fixed ? @danielweck

**Comment by danielweck** [comment]
I disagree about closing the issue, but I totally agree about not rushing to a design "fix", but instead think more carefully about the "window management" UX (comparing it with established reading systems on desktop platforms, like MacOS Books.app)

**Comment by danielweck** [comment]
"meta issue" (more general UX discussion):  https://github.com/readium/readium-desktop/issues/271

**Comment by danielweck** [comment]
bug triage: obsolete.
