### ISSUE TITLE
Publication search (currently by title only) does not yield consistent / logical results with partial words

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#594]
![ThoriumSearch1](https://user-images.githubusercontent.com/625201/63061992-1dec5700-beef-11e9-9853-83892bf6c47c.png)
![ThoriumSearch2](https://user-images.githubusercontent.com/625201/63061995-20e74780-beef-11e9-9e9b-3365f1bd851d.png)
![ThoriumSearch3](https://user-images.githubusercontent.com/625201/63061998-22b10b00-beef-11e9-98ac-50a768ae9129.png)

**Comment by danielweck** [comment]
Code references:

https://github.com/readium/readium-desktop/blob/03bcef7d5161814ab285e15f11f1922d05265a8d/src/main/db/repository/publication.ts#L53-L59

=>

https://github.com/readium/readium-desktop/blob/03bcef7d5161814ab285e15f11f1922d05265a8d/package.json#L191

=>

https://www.npmjs.com/package/pouchdb-quick-search
https://github.com/pouchdb-community/pouchdb-quick-search

The actual search engine is Lunr:

https://github.com/pouchdb-community/pouchdb-quick-search/blob/ec2ce7b75f07ea5c3a3216eff20e84621e9ce4e1/package.json#L40

=>

https://www.npmjs.com/package/lunr
https://github.com/olivernn/lunr.js

...but `pouchdb-quick-search` uses a very old version!

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/298

**Comment by llemeurfr** [comment]
The search is using PouchDB-quick-search and an English stemmer. The English stemmer certainly processes "accessible" as "access-ible" -> "access" is a way to find it; but not "accessi". 

In https://github.com/pouchdb-community/pouchdb-quick-search#building-the-index we see that there is no way to deactivate the Porter stemmer, only ways to change the language if some plugins are added.

Also, the authors are currently not stored separately and cannot be indexed in the publication document. 

As we have a plan to move from pouchdb to sqlite, I propose to close this issue and develop search on sqlite FTS during this port.

**Comment by danielweck** [comment]
I disagree with closing this issue. At the moment, the described problem exists in the codebase, so there should be an issue filed for it (irrespective of how / when the problem will be solved, for example by migrating to a different database backend).
What do you think Laurent?

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/173

**Comment by peaceroad** [comment]
This problem also occurs in languages like Japanese where there are no spaces between words. So, I hope it will be fixed if possible.

**Comment by danielweck** [comment]
Solved by replacing the limited DB search with fuzzy text matching in the new bookshelf data grid (table view with sortable and filterable columns + global search)
