### ISSUE TITLE
Create a meta-catalog of interesting OPDS feeds / design the new modal "add an opds feed"

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#608]
In the context of the addition of an OPDS feed to the application, we could create a catalog of OPDS feeds, which would be available when users are online (logical when accessing OPDS feeds).
The meta-catalog would have sections (could be per language).

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/274
(duplicate?)

**Comment by llemeurfr** [comment]
Not a duplicate, more a complementary feature.  

Such a meta-catalog would be burnt inside the application (e.g. for Thorium, a loooong list maintained by EDRLab), as a discovery mechanism for user. 

 #274 issue is about adding some feeds at setup time (e.g. in a school) -> as "forced" feeds.

**Comment by panaC** [comment]
1) design the new modal "add opds feed"
2) add an opds list feed with an api request on serverless service
3) create a serverless script to return an opds2 feed list
 - https://www.cloudflare.com/fr-fr/products/cloudflare-workers/
 - https://cloud.google.com/functions/

**Comment by danielweck** [comment]
Reminder of (badly-curated) list of OPDS feeds:
https://github.com/readium/r2-streamer-js/blob/develop/docs/opds.md#a-selection-of-public-opds-feeds
(some of them are good for testing, not so much for promoting)

**Comment by llemeurfr** [comment]
Some remarks for discussion:
1- this belongs more to the app level (Thorium Reader) than to the toolkit level (Readium Desktop)
2- It is difficult to get an universal registry of OPDS catalogs, as it would be culture and language oriented, or a real bazaar.
3- We could select feeds corresponding to free ebooks only, but this would be a limited offer. We could get feeds with of public libraries, but the authentication schemes of different libraries is far from being standardized. We could offer feeds with buyable goods, but the UX of much bookstores is still "highly perfectible" when it come to buying ebooks via OPDS feeds.

**Comment by danielweck** [comment]
Yes indeed. Note however than some OPDS feeds (well, their server) take into account the HTTP header accept-language to serve locale-sensitive content.

**Comment by danielweck** [comment]
Related issue: https://github.com/edrlab/thorium-reader/issues/1336

**Comment by llemeurfr** [comment]
An issue with this feature request is that either:
- we integrate in Thorium an EDRLab controlled catalog of OPDS feeds, which is quite impossible to maintain for us and would never cover the international usages of the app.
- we select an existing and specific catalog of OPDS feeds, like the one managed by De Marque which covers public libraries, which is problematic also for the same reason (plus the selection of a specific partner).
- we offer to the user a way to select a catalog of OPDS feeds via a copy/paste of some URL, which is still a geek feature.
- we use a URL scheme / protocol handler in Thorium. Anybody can add to its website a "Browse our meta-catalog in Thorium" button. 

The last solution seems to be the best (please advise). 

If the "Browse our meta-catalog in Thorium" button is selected, Thorium opens an "Add one or more OPDS feeds" window in which the user can select the feeds he want to add to the app. 

Is it something easily feasible?

**Comment by llemeurfr** [comment]
I agree to close this issue in favor of #1336.
