### ISSUE TITLE
(dev, code style) CSS files have mixed tabs and space identation

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#624]
I would personally prefer *not* using tab indentation (4-space or 2-space is guaranteed to be consistent with monospace font faces).

https://github.com/readium/readium-desktop/tree/develop/src/renderer/assets/styles

Opinions?

**Comment by llemeurfr** [comment]
I personally prefer tabs in code, because easier to type and can be adapted to personal tastes in editor settings. Not sure CSS is a specific beast regarding this issue.

**Comment by JayPanoz** [comment]
FYI, that’s a question I asked myself (for ReadiumCSS, and others) recently after [I came across this discussion from Twitter](https://www.reddit.com/r/javascript/comments/c8drjo/nobody_talks_about_the_real_reason_to_use_tabs/).

**Comment by danielweck** [comment]
We use spaces everywhere else.

**Comment by danielweck** [comment]
The current TSLint configuration:
https://github.com/readium/readium-desktop/blob/9b875fef09e1504c46441c57b8d689f8defe920c/tslint.json#L2
=>
https://github.com/palantir/tslint/blob/05cfde7c6eb53c373ea0d6ae1e793cc2dc639dc3/src/configs/recommended.ts#L51-L53

**Comment by danielweck** [comment]
Note that Prettier also defaults to spaces instead of tabs:
https://prettier.io/docs/en/options.html#tabs

**Comment by danielweck** [comment]
Note that TSLint will be deprecated at some point, so our setup will probably migrate to ESLint with Prettier rules.
References:
https://github.com/typescript-eslint/typescript-eslint#what-about-tslint
https://github.com/prettier/eslint-config-prettier/blob/master/%40typescript-eslint.js
https://dev.to/robertcoopercode/using-eslint-and-prettier-in-a-typescript-project-53jb

**Comment by danielweck** [comment]
Let's close this issue. There will be a total refactor the the CSS stylesheets at some point. https://github.com/edrlab/thorium-reader/issues/410

**Comment by danielweck** [comment]
Note that Prettier is now integrated ... but disabled for TypeScript source tree due to significant codebase disruption if consistent opinionated formatting is applied (which would cause many merge conflicts in PRs and forks).

https://github.com/edrlab/thorium-reader/pull/1374
