### ISSUE TITLE
Developer note: old "ping" lib from GitHub, badly-maintained NPM package

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#636]
NPM package `ping` version `0.2.2` is 3 years old:
https://www.npmjs.com/package/ping

Because of a problem on Windows with this particular version, the NPM dependency in `readium-desktop` is in fact frozen to a GitHub commit hash. See:
https://github.com/readium/readium-desktop/issues/115
and:
https://github.com/readium/readium-desktop/blob/84c1252dc8855f888acddfe46e925881caa69561/package.json#L187

The `ping` project's release and tags do not match the NPM versions:
https://github.com/danielzzz/node-ping/releases
https://github.com/danielzzz/node-ping/tags

The version used by `readium-desktop` is:
https://github.com/danielzzz/node-ping/commits/1601458126cc1dd0c31db8150f2e6b2a40570a7f

...but interestingly, there have been Windows-related fixes since them:
https://github.com/danielzzz/node-ping/compare/1601458126cc1dd0c31db8150f2e6b2a40570a7f...master

**Comment by danielweck** [comment]
So, given the state of development and releases of the `ping` project, perhaps it would be safer to use a different package, such as:
https://github.com/qawemlilo/ping-monitor
https://github.com/nospaceships/node-net-ping

...or use a different strategy in order to detect the "online" status (i.e. not reliant on UDP and IP address, maybe just HTTP GET/HEAD with no-cache):

https://github.com/readium/readium-desktop/blob/84c1252dc8855f888acddfe46e925881caa69561/src/main/redux/sagas/net.ts#L15-L66

**Comment by danielweck** [comment]
See:
https://github.com/sindresorhus/is-online/blob/master/index.js

**Comment by panaC** [comment]
@panaC remove the ping package

**Comment by panaC** [comment]
https://github.com/panaC/thorium/blob/d967604cd4766f54ebbd9dc06f6db09d86008881/src/main/redux/sagas/net.ts

**Comment by danielweck** [comment]
Indeed. It is time to remove this now-unused dependency.
