### ISSUE TITLE
improvement: TOC hierarchical link-headings, ARIA role tree[item], screen reader compability (depends on Electron Chromium?)

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#679]
Follow-up to:
https://github.com/readium/readium-desktop/issues/569

The solution implemented is not ideal (wrapping div with forced ARIA heading role + level, around hyperlink). Ideally, screen readers would consistently pick-up the hierarchy level from the ARIA role tree/treeitem/group arrangement, and the link would be announced with its heading depth/level.

Resources:

https://www.w3.org/TR/wai-aria-1.1/#aria-level

https://www.powermapper.com/tests/screen-readers/headings/aria-role-heading/

https://www.powermapper.com/tests/screen-readers/headings/aria-role-heading-nested/

https://www.bbc.co.uk/guidelines/futuremedia/accessibility/mobile/text-equivalents/roles-traits-and-properties

https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html

http://w3c.github.io/aria-practices/#TreeView

https://www.w3.org/TR/wai-aria-practices/examples/treeview/treeview-2/treeview-2a.html

http://www.oaa-accessibility.org/examplep/treeview1/

https://www.scottohara.me/blog/2018/05/26/aria-lists.html

https://github.com/lissitz/react-accessible-treeview

**Comment by benjaminhobbs** [comment]
@danielweck just wanted to help you out by saying that https://bbc-news.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html is now at https://bbc.github.io/accessibility-news-and-you/accessibility-and-testing-with-voiceover-os.html

**Comment by danielweck** [comment]
Thank you very much for the heads-up, I correct the link :)

**Comment by danielweck** [comment]
The current TOC / tree technique works fine, according to user testing. Closing.
