### ISSUE TITLE
Reader config data structure, TypeScript interface with arbitrary fields

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#717]
https://github.com/readium/readium-desktop/blob/1d46e2f6f108b6172e9b1ed146c094c098d84ba9/src/common/models/reader.ts#L31-L45

This line is problematic: `[key: string]: any;`. Instead, this line should be removed and there should be a strict typed definition for `letterSpacing`, `wordSpacing`, `pageMargins`, `paraSpacing` etc. (`lineHeight` is already defined).

The `getButtonClassName()` function in `ReaderOption.tsx` breaks because of  `const property = this.props.settings[propertyName];`, but this is easy to fix (just a static mapping between string class names and well-defined data structure fields):

https://github.com/readium/readium-desktop/blob/1d46e2f6f108b6172e9b1ed146c094c098d84ba9/src/renderer/components/reader/ReaderOptions.tsx#L464-L474

Same with `handleSettingsValueChange()` (`settingsValues[name] =  value;`) and `handleIndexValueChange()` (`settingsValues[name] = optionsValues[name][value];`) in `Reader.tsx`:

https://github.com/readium/readium-desktop/blob/1d46e2f6f108b6172e9b1ed146c094c098d84ba9/src/renderer/components/reader/Reader.tsx#L688-L726

What this fix also reveals is the strange use of a `value` field, which I do not quite understand:

https://github.com/readium/readium-desktop/blob/1d46e2f6f108b6172e9b1ed146c094c098d84ba9/src/renderer/components/reader/Reader.tsx#L280

https://github.com/readium/readium-desktop/blob/1d46e2f6f108b6172e9b1ed146c094c098d84ba9/src/renderer/components/reader/Reader.tsx#L76-L78

This also reveals that the `darken` filter is used nowhere in Thorium (i.e. no user interface to activate this ReadiumCSS feature):

https://github.com/readium/readium-desktop/blob/1d46e2f6f108b6172e9b1ed146c094c098d84ba9/src/renderer/components/reader/Reader.tsx#L92

**Comment by panaC** [comment]
the Reader Config interfaces have been updated since. @danielweck ?

**Comment by danielweck** [comment]
Yes, I fixed this a while back, during a larger refactor, but I forgot to came back to this issue. Closing.

https://github.com/edrlab/thorium-reader/blob/bee2de14c0f3b3536ff72bef9b0c6c08fe461727/src/common/models/reader.ts#L33-L67
