### ISSUE TITLE
Support on-screen touch swipe gesture to change pages

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#725]
Primary actions should be enabled by directly interacting with content. For example, tap to open, swipe to select, pinch to zoom, and drag to pan/paginate. If a panorama or pivot control contains other controls which use the same left / right flick gestures, this may result in a poor user experience due to gesture overlaps. UI elements, controls or other parts of an application should not interfere with Windows edge gesture.
Steps to Reproduce:

1 Launch the application.
2 Select a book.
3 Attempt to swipe to change the page.
4 Notice page change via swipe gesture is not supported.
 
Expected results:

- The application should fully support touch input. For example, the user should be able to navigate or interact with commands using touch input only.
- Touch gestures should only be used for actions that match the Windows touch language.
- Pivot and/or panorama controls do not have controls with competing gestures and can be used reliably.
- If the hub, panorama or pivot reacts by scrolling then the child control should not trigger.
- Any UI elements, controls, or other parts of the application should not interfere with Windows edge gestures.
 
More Information:

Gesture interaction guidance: Gestures, manipulations, and interactions

**Comment by danielweck** [comment]
Windows "touch language":
https://docs.microsoft.com/en-us/windows/win32/uxguide/inter-touch#the-windows-touch-language

**Comment by danielweck** [comment]
@llemeurfr said (https://github.com/readium/readium-desktop/issues/780):

Many computers have now a touch screen (Surface for instance, but also MacPro or Inspiron ...).

It would be good to be able to move "from page to page" using tap or swipe gestures.
Either a tap on the left of right of the reader window,
Or a swipe in the center of the reader window.

We need to be careful bout avoiding issues with html hyperlinks present in the content. Should we allow tap in the margins only? they are a bit too slim...

We may be able to use https://developer.mozilla.org/en-US/docs/Web/API/Touch_events

**Comment by Scarsniik** [comment]
After se tests, I can't use swipe events on the reader. It works good but when I swipe directly on the navigator, the event is not called

**Comment by danielweck** [comment]
Chromium, just like every other web browser engine, captures DOM events in `iframe` containers (we use an Electron `webview` but this is effectively a custom element with a shadow DOM that wraps an Out Of Process Chromium `iframe`)

This is the same reason why we currently capture keyboard events from both the local BrowserWindow HTML/DOM, as well as events originating from the sandboxed `webview`/`iframe` (which the `r2-navigator-js` API exposes):
https://github.com/readium/readium-desktop/blob/80dbecabf4d8ea453c0917bb590020b32655744d/src/renderer/components/reader/Reader.tsx#L365-L396

So, we (I) need to implement additional touch / gesture handling in `r2-navigator-js`, in order to forward events to the app host.

Note that this is kinda similar to the Readium2 "GlueJS" experiment:
https://github.com/evidentpoint/r2-glue-js/blob/master/src/modules/keyHandling/handler.ts

**Comment by danielweck** [comment]
PS: note that back in the no-so-distant days when `readium-desktop` was using Electron v1 (we're now on v3, and we are migrating to v6), keyboard events did in fact "bubble" up into the iframe container, which was wrong.

**Comment by MaskyS** [comment]
Swipe gestures on touchpads (two-finger swipe-right/left) as well as on touch screens would be a phenomenal addition.

**Comment by mutterback** [comment]
Just checking back to see if anyone has looked into this issue since the move to Electron 6.

**Comment by llemeurfr** [comment]
We'll have to wait until v1.7 before tackling this enhancement.

**Comment by danielweck** [comment]
> Swipe gestures on touchpads (two-finger swipe-right/left) as well as on touch screens would be a phenomenal addition.

Please see:
https://github.com/edrlab/thorium-reader/issues/1436#issuecomment-817530971

**Comment by danielweck** [comment]
To summarize, there are now two separate but related issues:

* this one - for on-screen touch gestures, Pointer events
* another one (https://github.com/edrlab/thorium-reader/issues/1436 ) - for mouse wheel / touchpad gestures, scroll events

**Comment by RCAPSN** [comment]
I'm not sure if this function (screen touch gestures) is available now. 
I just use the latest version (v1.7.3) of this app on windows tablet, seems it don't work, neither finger touch nor finger swipe. 
Thanks a lot.

**Comment by RCAPSN** [comment]
I'm not sure if this function (screen touch gestures) is available now. 
I just use the latest version (v1.7.3) of this app on windows tablet, seems it don't work, neither finger touch nor finger swipe. 
Thanks a lot.

**Comment by danielweck** [comment]
Hello @RCAPSN this is not implemented yet but we are discussing technical solutions.

**Comment by danielweck** [comment]
Additional comment from @quiquegurdiel

https://github.com/edrlab/thorium-reader/issues/1676

> It seems there is no way to make zoom from a touch screen using a gesture, at least in v1.8.0 on windows 10.
> I used a medion (akoya p2211t) that works both as a laptop and as a tablet because the touch screen is detachable (same as a microsoft surface), running version 1.8.0 on windows 10. I've seen that I can control the zoom from a laptop using the touchpad as usual, which is very practical, but I can not do the same using the touch screen (as when you zoom in a mobile phone) so when it's used as a tablet there's no way to zoom efficiently. Just in case, it seems something related with touch screens in general, not with the fact that in my case it can be detached. In other programs that the zoom control works fine from the screen it acts indepently of being attached or not.

**Comment by Jaifroid** [comment]
Having just installed Thorium (Microsoft Store version), I was a little surprised that page flip back and forward with swipes does not work, as it does, for example, with the Calibre built-in epub reader. Since you're using Electron, it shouldn't be too hard to trap touch events which are now pretty standard in JavaScript: https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Using_Touch_Events.

**Comment by Jaifroid** [comment]
PS Maybe you could take a look at how [Koodo Reader](https://github.com/troyeguo/koodo-reader/) -- also an Electron app -- supports swipe/touch gestures. It's open source.

**Comment by llemeurfr** [comment]
Thanks for the information @Jaifroid. We will definitely study this evolution (but it will not be developed in the short term).

**Comment by danielweck** [comment]
This was implemented and tested on Windows (Thorium 2.3)
