### ISSUE TITLE
Detection of network connectivity, global application state for internet-dependent features, e.g. OPDS, LCP-LSD, etc.

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#728]
There is already a `netActions.ActionType.Offline|Online` ReduxSaga NetWatcher, for the `main` process:

https://github.com/readium/readium-desktop/blob/f5942e2946db9495ab417116f5d3302328e980ad/src/main/redux/sagas/net.ts#L34-L64

Alternatively, we could use the off-the-shelf `navigator.onLine` web browser feature, and/or the `offline` / `online` DOM events. In this case we will need to instantiate a "watcher" in the `renderer` process (i.e. library / bookshelf `BrowserWindow`) and forward the event to the `main` process so that the global application state can be updated.

When the library / bookshelf BrowserWindow is not displayed, there needs to be a "watcher" in the reader view(s) too.

Full example:
https://electronjs.org/docs/tutorial/online-offline-events

But note:

>  we cannot assume true value necessarily means that Electron can access the internet. Such as in cases where the computer is running a virtualization software that has virtual ethernet adapters that are always “connected.” Therefore, if you really want to determine the internet access status of Electron, you should develop additional means for checking.

... which is why the `ping` at regular intervals may be useful too.

**Comment by danielweck** [comment]
Just to be clear: the OPDS message has been fixed. See:
https://github.com/readium/readium-desktop/issues/726#issuecomment-534613167

This present issue is a more general UX problem (toast notification when connection is interrupted / restored?)

**Comment by panaC** [comment]
any though of this issue ? @danielweck
may i close it ?

**Comment by danielweck** [comment]
This is not an actionable issue, at this juncture, because the network layer in Thorium has improved quite a bit since this was filed (better detection and surfacing of network errors). Closing.
