### ISSUE TITLE
Font face selector: add system fonts?

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#765]
https://www.npmjs.com/package/system-font-families

This library (NPM package) is currently used in `r2-testapp-js` to expose system-wide fonts:

![R2-testapp_system-fonts](https://user-images.githubusercontent.com/625201/66221600-37c44200-e6c7-11e9-93de-8e905eb3996b.png)

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/766

**Comment by divenex** [comment]
Is there any plan to implement system font support in Thorium Reader? Font choice is currently quite poor. There are just two serif fonts and there is no way to access to some of the best fonts like e.g. [Bookerly, Literata or Merryweather ](https://medium.com/productivity-revolution/10-best-fonts-for-improving-reading-experience-6171ce199e97)

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/pull/1373
