### ISSUE TITLE
Popup menu (library view), keyboard focus only returns to menu button with "about this book" (not "delete" and "export"))

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#773]
![ThoriumMenuPopupFocusBack](https://user-images.githubusercontent.com/625201/66415348-4b3b1a00-e9f3-11e9-943a-6e0c03ab34d4.png)

**Comment by danielweck** [comment]
This issue still exists in Thorium 2.1.0

**Comment by panaC** [comment]
It's works on Thorium 2.1.1-alpha.0 



![Image](https://user-images.githubusercontent.com/3198865/196211466-dd6d4ea0-6bb5-42d2-87c6-e71a80fd578e.png)
