### ISSUE TITLE
Bug on the opds catalog publication page

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#821]
the page number is blocked on 2.

When i press 'next' button the counter restart from page 1.

![image](https://user-images.githubusercontent.com/3198865/67396490-fa592300-f5a7-11e9-8d39-f030fedd14e5.png)

I tested with feedbooks

**Comment by panaC** [comment]
I found only feedbooks provider with the 'NumberOfItems' and 'ItemPerPages' filled. 

Opds is not adapted to simply display the 'currently page / numberOfPages'.
We have only metadata information and next, previous, last, first LInks. These links don't allow access to the page ID (page id is merge with the href). each provider implements its own url logic.

moreover mostly provider doesn't add any metadata.

The display of a logic number pages is very complex and is not an exact science.

I propose to remove : 'currently page / numberOfPages' ..
We can display this information only when we have the number of pages and the page id extract from href link. But not from an local subjective calculus.

in my opinion is the safest way.

We have to fit with the provider implementation of the opds standard to adapt to each

**Comment by danielweck** [comment]
@panaC is this fixed now?

**Comment by panaC** [comment]
yes is it
