### ISSUE TITLE
READER : chapter jump when I click several times on next page

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#829]
book: https://tools.wmflabs.org/wsexport/tool/book.php?lang=fr&format=epub&page=L%C3%A0-bas

![image](https://user-images.githubusercontent.com/3198865/67641276-72ee1580-f901-11e9-8c73-0870ddb6c900.png)

![image](https://user-images.githubusercontent.com/3198865/67641277-80a39b00-f901-11e9-859a-d96c68fe4988.png)

it's a bug, or my PC that is too slow ?

**Comment by panaC** [comment]
i'm closing the issue

**Comment by danielweck** [comment]
I am not able to reproduce this bug. Agree to close.
