### ISSUE TITLE
Reader crash on manybooks epub

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#854]
http://readium2.herokuapp.com/opds-v1-v2-convert/http%3A%2F%2Fmanybooks.net%2Fopds%2Ftitle_detail.php%3Ftid%3Ddoderleinl3319733197-8

http://srv.manybooks.net/send/1:epub:.epub:epub/doderleinl3319733197-8/doderleinl3319733197-8.epub

works on IBooks

In thorium : 
![image](https://user-images.githubusercontent.com/3198865/69876326-9836c080-12bf-11ea-9c1d-22a68e160ad4.png)

Even if the manybooks epubs may aren't very compliant

**Comment by danielweck** [comment]
http://srv.manybooks.net/send/1:epub:.epub:epub/doderleinl3319733197-8/doderleinl3319733197-8.epub
=>
`doderleinl3319733197-8epub.epub`

Just 12 errors in EPUB-Check, not sure why it fails in R2?

![EPUBCHeck](https://user-images.githubusercontent.com/625201/69878437-db436480-12bc-11ea-8c23-3ffc688fb828.png)

**Comment by danielweck** [comment]
Interestingly, the EPUB fails to open in `Books.app`:
![iBooks](https://user-images.githubusercontent.com/625201/69878517-1a71b580-12bd-11ea-96c7-6e368c85e61f.png)

**Comment by danielweck** [comment]
`r2-streamer-js` seems to stall with this EPUB:

```
  r2:streamer#http/server-pub  +2ms
  r2:utils#zip/zip2 http://srv.manybooks.net/send/1:epub:.epub:epub/doderleinl3319733197-8/doderleinl3319733197-8.epub +0ms
  r2:utils#zip/zip2 {
  r2:utils#zip/zip2   'x-amz-id-2': 'Bmi8ArIISqmDOU477Wii+n+qTHJrf3FnBJpKqAPe7xibNmCEHFVx20b0tUbXV4BV7IjaUZWann0=',
  r2:utils#zip/zip2   'x-amz-request-id': 'CD263821E87AB77E',
  r2:utils#zip/zip2   date: 'Fri, 29 Nov 2019 15:31:54 GMT',
  r2:utils#zip/zip2   'last-modified': 'Thu, 29 Sep 2011 02:13:27 GMT',
  r2:utils#zip/zip2   etag: '"6333f8c316f9af37238a008abbcb348c"',
  r2:utils#zip/zip2   'accept-ranges': 'bytes',
  r2:utils#zip/zip2   'content-type': 'application/epub+zip',
  r2:utils#zip/zip2   'content-length': '272618',
  r2:utils#zip/zip2   server: 'AmazonS3',
  r2:utils#zip/zip2   connection: 'close'
  r2:utils#zip/zip2 } +0ms
  r2:utils#zip/zip2 Content-Length: 272618 +1ms
  r2:utils#zip/zip2RandomAccessReader_Http streamToBufferPromise: 65557 +0ms
  r2:utils#zip/zip2 yauzl END +14s
```

**Comment by danielweck** [comment]
Ah, it was VERY slow, but finally `r2-streamer-js` managed to load the EPUB (super slow server?):

![streamer](https://user-images.githubusercontent.com/625201/69878793-c61b0580-12bd-11ea-8acd-9b85b29f28b1.png)

**Comment by panaC** [comment]
it works now
