### ISSUE TITLE
LCP / UX: check existing passphrases (from the same provider)

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#888]
Each time one imports a new LCP license, the passphrase is requested. 
Thorium UX would be much better if the passphrases already stored in the app were checked against the license, with a filter on the license provider.

**Comment by danielweck** [comment]
> with a filter on the license provider

I assume you mean the `provider` JSON property in LCP licenses?

**Comment by danielweck** [comment]
Note to devs: the "LCP secrets" DB is currently key'd by publication identifier, no information is stored about "providers":

https://github.com/readium/readium-desktop/blob/aacfe6bbd33db5623a01cfb2939713b6015c8790/src/main/db/repository/lcp-secret.ts#L17-L45

**Comment by llemeurfr** [comment]
> I assume you mean the provider JSON property in LCP licenses?

yes. Note that the mobile implementations don't use such a filter and test all available passphrases in a row, which in a normal case will not slow the process.

**Comment by danielweck** [comment]
Note to devs: `findByPublicationIdentifier()` should be replaced with complete set of "LCP secrets" regardless of publication ID:

https://github.com/readium/readium-desktop/blob/aacfe6bbd33db5623a01cfb2939713b6015c8790/src/main/services/lcp.ts#L577-L597

**Comment by llemeurfr** [comment]
There will be no per-provider filter, which is not a real problem as checking keys is really fast. 
This should be done for v1.5.
