### ISSUE TITLE
LCP: remove un-needed status requests

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#890]
When one imports a license, opens the ebook and is asked for a passphrase, there a 3 status requests. 

“Etes-vous sûr de vouloir importer ces fichiers EPUB : ….”
“Oui” -> status + register 
Open -> status puis présentation modale mot de passe 
“Cette publication a besoin d’un mot de passe” 
bon mot de passe -> status et ouverture

Would it be possible to:
- register at the moment the passphrase is recognized as ok, so that people who don't have the passphrase do not see their device registered? 
- remove at least one of the status requests?

**Comment by danielweck** [comment]
Thorium checks the LSD status at key points in the UX flow, for example before displaying the "publication info" modal dialog box (so that the rendered information is correct: LCP start/end dates, as well as return/renew links), or immediately before attempting to open a LCP-protected publication (so that this can be prevented in case the LCP license has been revoked, etc.)

Furthermore, when a LCP license has been updated following a LSD check, another LSD check takes place based on the LSD link advertised in the newly-updated LCP license. In principle, this ensures that LSD changes are captured following LCP updates ... but in practice I think this is a waste of HTTP request, as the edge-cases are non-existant in the current LCP/LSD server implementations, as far as I know.

**Comment by danielweck** [comment]
> register at the moment the passphrase is recognized as ok, so that people who don't have the passphrase do not see their device registered?

This is an interesting suggestion. I will look into it.

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/996

**Comment by llemeurfr** [comment]
Let's take a new license, with a new passphrase (unknown from the reading app). 
1/ I import the license -> 
1.a/ status request. This one is useful, as we could have an expired license. Better to know asap.  
1.b/ register. This is too early. I'd like register to come after the passphrase has been accepted. 
2/ I open the book -> status request. Please suppress this one. 
3/ I enter the (good) passphrase -> status request. To be replaced by a register. The response to the register is a status, therefore not need for another status request at this step.

**Comment by danielweck** [comment]
> I open the book -> status request.

Shouldn't the LSD request occur every time a user attempts to open a LCP-protected publication to read it?

...I would prefer to review the existing implementation based on a comprehensive state chart. I am worried that the above example is just one specific branch in the graph, not representative of all possible flows.

**Comment by danielweck** [comment]
PS: in the state chart, each isolated node is only aware of its input(s) in order to produce output(s). There is no notion of execution context, such as whether this is a first attempt to unlock a license with a passphrase, or a subsequent attempt with a stored passphrase hash. Other examples of possible context: standalone LCP license vs. full protected EPUB, authenticated OPDS with hashed passphrase vs. user passphrase input, etc.

**Comment by llemeurfr** [comment]
ok let's design a state chart and check. I wrote [this doc ](https://github.com/readium/architecture/tree/master/other/lcp)a long time ago, which represents the equivalent of a state diagram as text.

**Comment by llemeurfr** [comment]
I think you're right about
> Shouldn't the LSD request occur every time a user attempts to open a LCP-protected publication to read it?
From my text this status request should stay.

**Comment by danielweck** [comment]
Mermaid to the rescue: https://mermaid.live/edit#pako:eNpNjk8LgkAQxb-KDAgGbmDeBD2UHQKhwKCD22Fw11zyT6wrEup3byXT5jTv9948poe0Zhw8yIq6S3OUyrjuaWXoEcyxkuhwuW9-eqd1HK7atZLb6c93DEKCKbccGGRLgqFT2TDZa873g0Hlopmwu9TNGNWwlphmdI7AhpLLEgXTn_aTQUHlvOQUPL0ylE8KtBp1rn0xVPzIhKoleBkWDbcBW1XH7ypdwDcVCnxILGc6fgDZpFG_

**Comment by llemeurfr** [comment]
Na na na ... 

[![](https://mermaid.ink/img/pako:eNqNVF1v2jAU_SuWX6ASsISOr2jqtEJL-abrpGmMPZjkplhK4swfdAz473McAs60h-XJuTn3nHOPr3LAPgsAe_iVk3SLvgzWCdLPp--LFBIkt4Cm_SWKqA-JgB-oXr9D94eRMF_OVfQGUVQPGY8h-HjK--8Nsl99BOlvDVhIIpVAAfNVDIm8yXH9DHf8BuKIBgXtX8gPG_7ujuwIjcgmAkSS4F-CgyvRQ0ZEJeLwU1EOAZIMhZmPnAmFHMS2MF_0PxjDOcGjZbsEPpt-NNhh4bcE-T-3Q0vtqfoZ0oj4YMhYFJSoNntLgyWFhSdDMDrQ8k1UOJBgXzGdjKMK8SXdQaWQHVmy4-oQpGlOiRDplhPdr0_Mp0Tq0N6o3NrcZ-GxoZgUs1u9PuMcfFloTSytaQG_GN2RiF7SmFrQ2eErybEB7DQ4zzMyc-kbfaVCAr8GObNa59XLzqZqo5WIpCzRvq2VPM7ZEa2qcyZpmCerBHB9INIe1qjqbFWixOUehWRpLc8lAKlvWNzYu5cxj0vLlFVGpQu3KqNrZVVKLKtMSsFYmNm1stB7k8dhxXWZdmGAy0uaeXTcRGKmE8r3QYhQRUWWSyvL5-qLZBws5hLDefBn0zEvtWfW8gqu4Rh4TGigfy-HrLTGmi-GNfb0MYCQqEiu8To5aShRkr3sEx97kiuoYZUGeg8HlOgfU4y9kERCV1OSrBiLC5B-xd4B_8Ke23Eb3Vbn1m25XafrOG67hvfYq_cct-G4nZ7ba952ml2ndarh34bBbbQ7zm277bSdXrfb7DXfn_4AXkOZDA?type=png)](https://mermaid.live/edit#pako:eNqNVF1v2jAU_SuWX6ASsISOr2jqtEJL-abrpGmMPZjkplhK4swfdAz473McAs60h-XJuTn3nHOPr3LAPgsAe_iVk3SLvgzWCdLPp--LFBIkt4Cm_SWKqA-JgB-oXr9D94eRMF_OVfQGUVQPGY8h-HjK--8Nsl99BOlvDVhIIpVAAfNVDIm8yXH9DHf8BuKIBgXtX8gPG_7ujuwIjcgmAkSS4F-CgyvRQ0ZEJeLwU1EOAZIMhZmPnAmFHMS2MF_0PxjDOcGjZbsEPpt-NNhh4bcE-T-3Q0vtqfoZ0oj4YMhYFJSoNntLgyWFhSdDMDrQ8k1UOJBgXzGdjKMK8SXdQaWQHVmy4-oQpGlOiRDplhPdr0_Mp0Tq0N6o3NrcZ-GxoZgUs1u9PuMcfFloTSytaQG_GN2RiF7SmFrQ2eErybEB7DQ4zzMyc-kbfaVCAr8GObNa59XLzqZqo5WIpCzRvq2VPM7ZEa2qcyZpmCerBHB9INIe1qjqbFWixOUehWRpLc8lAKlvWNzYu5cxj0vLlFVGpQu3KqNrZVVKLKtMSsFYmNm1stB7k8dhxXWZdmGAy0uaeXTcRGKmE8r3QYhQRUWWSyvL5-qLZBws5hLDefBn0zEvtWfW8gqu4Rh4TGigfy-HrLTGmi-GNfb0MYCQqEiu8To5aShRkr3sEx97kiuoYZUGeg8HlOgfU4y9kERCV1OSrBiLC5B-xd4B_8Ke23Eb3Vbn1m25XafrOG67hvfYq_cct-G4nZ7ba952ml2ndarh34bBbbQ7zm277bSdXrfb7DXfn_4AXkOZDA)

**Comment by llemeurfr** [comment]
plus d'excuse :-)

**Comment by llemeurfr** [comment]
pour mémoire : 

graph TD
    A[Open the LCP license] --> B{Is the license well-formed?}
    B --> C(Fetch the status document)
    C -->|Yes| D{Is the status document<br/>available and well-formed?}
    D -->|Yes| E{Is it required to fetch<br/>a fresh license?}
    E --> |Yes| F(Fetch the fresh license)
    F --> G{Is the fresh license<br/>available and well-formed?}
    G --> |Yes| H(Replace the old license<br/>by the fresh one)
    H --> I{is the license 'ready'<br/>or 'active'?}
    I --> |Yes| J(Get the passphrase associated with the license)
    J --> K{Is the passphrase correct?}
    K --> |Yes| L{Is the  license valid?}
    L --> |Yes| M{Was the device<br/>already registered?}
    M --> |Yes| N(Open the publication)

    B -->|No| Z(Notify the user that the license<br/>is unusable and stop, with details)
    D -->|No| J
    E --> |No| I
    G --> |No| I
    I --> |No| Z
    K --> |No| K
    L --> |No| Z
    M --> |No| O(Register the device)

    O --> P{Was the registration<br/>successful?}
    P --> |Yes| Q(Store the device registration)
    Q --> N
    P --> |No| N

**Comment by danielweck** [comment]
Fixed in Thorium 3
