### ISSUE TITLE
readerActions.closeError and streamerActions.stopError is linked to nothing

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#914]
https://github.com/readium/readium-desktop/blob/aacfe6bbd33db5623a01cfb2939713b6015c8790/src/main/redux/sagas/reader.ts#L239

https://github.com/readium/readium-desktop/blob/aacfe6bbd33db5623a01cfb2939713b6015c8790/src/main/redux/sagas/streamer.ts#L73

**Comment by danielweck** [comment]
Is this still a problem, is this fixed in a pending PR?

**Comment by panaC** [comment]
No it isn't yet fixed in pending PR

**Comment by panaC** [comment]
I close this issue, it's not a bug it's a feature
