### ISSUE TITLE
the internal link appear when you click and drag a link on production mode

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#918]
![image](https://user-images.githubusercontent.com/3198865/72606252-8ae09e80-391e-11ea-9630-683bd5a8dffe.png)

**Comment by panaC** [comment]
an idea to fix this bug @danielweck ?

**Comment by danielweck** [comment]
Something like:

```
*, *::after, *::before {
	-webkit-user-select: none;
	-webkit-user-drag: none;
	-webkit-app-region: no-drag;
}
```

**Comment by danielweck** [comment]
Needs to apply to links inside EPUB HTML documents as well. I will push a fix shortly.

**Comment by danielweck** [comment]
Fixed via https://github.com/edrlab/thorium-reader/commit/414b730128217e791c0cdcabc35d681cea574743

**Comment by danielweck** [comment]
PDF-specific fix via: https://github.com/edrlab/thorium-reader/commit/bee2de14c0f3b3536ff72bef9b0c6c08fe461727

**Comment by danielweck** [comment]
Follow-up issue: https://github.com/edrlab/thorium-reader/issues/1599
