### ISSUE TITLE
Check if it's better to send a return request before fetching the updated license 

### ISSUE THREAD

**Issue by llemeurfr** [edrlab/thorium-reader#92]
Currently, the license is injected twice in the zip 1/ when the user click on "view", "return" or "renew" 2/ after the "return" or "renew", with the updated license.
It would be better to make a direct "return" or "renew" and check the status  -> 1 injection.

**Comment by panaC** [comment]
What do you mean ?

**Comment by danielweck** [comment]
moving to: https://github.com/edrlab/thorium-reader/issues/890
