### ISSUE TITLE
dev: incorrect code folder location HTTP utils (main dependency)

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#923]
https://github.com/readium/readium-desktop/blob/8311af1f9980981b0a317d5829ca2d10b218876a/src/common/utils/http.ts#L9

**Comment by danielweck** [comment]
Related: https://github.com/readium/readium-desktop/issues/922

**Comment by panaC** [comment]
I think it's fixed @danielweck

**Comment by danielweck** [comment]
Agreed.
