### ISSUE TITLE
audiobooks: human-friendly presentation of elapsed / remaining time, duration

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#951]
...currently, the syntax is `hh:mm:ss` or `mm:ss` (no milliseconds), maybe use `15mn 5s remaining` instead of `-15:05`? (for example)

Related issues:
https://github.com/readium/readium-desktop/issues/955
https://github.com/readium/readium-desktop/issues/956

Follow-up to PR https://github.com/readium/readium-desktop/pull/938

**Comment by llemeurfr** [comment]
Is there a time format a screen reader can interpret and "speak" clearly?

**Comment by danielweck** [comment]
I think we should stick to our current simple model. Works just fine. Localisation / internationalisation of other UI labels in the audiobooks experience may trigger the need to refactor number display as well. But for now this issue is not necessary, let's focus on more important / urgent issues.
