### ISSUE TITLE
audiobooks: book-wide (instead of track-local) time information

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#955]
For example, "18% complete, 15hrs 44mn 36s left"

Related issues:
https://github.com/readium/readium-desktop/issues/951
https://github.com/readium/readium-desktop/issues/956

Follow-up to PR https://github.com/readium/readium-desktop/pull/938

**Comment by llemeurfr** [comment]
The total time seems mostly useful in the information panel IMO, extracted from metadata.

**Comment by danielweck** [comment]
The current "publication information panel" works fine as it is. Closing.
