### ISSUE TITLE
Code signing for Mac

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#97]
As reported by @CircularKen : 

By default Mac will show

<img width="532" alt="Screenshot 2020-04-24 06 56 09" src="https://user-images.githubusercontent.com/17338941/80179800-2c038300-85f9-11ea-9fc9-5e25c80da77a.png">

Right Click on the app and Open to see

<img width="532" alt="Screenshot 2020-04-24 06 56 26" src="https://user-images.githubusercontent.com/17338941/80179791-2ad25600-85f9-11ea-9af1-012858f57d51.png">

**Comment by danielweck** [comment]
Let's close this. Thorium is now signed for deployment into the Windows10 app store.

**Comment by danielweck** [comment]
Actually, we still need to sign the code for MacOS and Windows NSI/MSI app installers (i.e. software not deployed through app store, that is to say via a trusted developer account with valid certificates).

So, @llemeurfr are there certificates for Thorium, for MacOS (which requires an Apple developer account), and for Windows (EV Code Signing Certificate, for example from DigiCert)?

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/125

**Comment by llemeurfr** [comment]
No, we didn't buy this; it is true that getting no user warning for the .DMG would be good, and in this case for a .MSI also (even if most Windows users will get Thorium from the MS store). 
I propose to address this issue at the same time we address multi-platforms automatic builds via Jenkins or alike, for each released version. -> from August.

**Comment by danielweck** [comment]
Useful links:

https://www.electron.build/code-signing

https://github.com/electron/electron-notarize
https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/
https://medium.com/@TwitterArchiveEraser/notarize-electron-apps-7a5f988406db

https://samuelmeuli.com/blog/2019-04-09-publishing-an-electron-app-on-the-mac-app-store/
https://david.dev/electron-cannot-build-mas-on-os-x-mojave

**Comment by danielweck** [comment]
> nb: we have an Apple dev account.

It would be interesting to see if you could export EDRLab's Apple certificate containing the private key for signing DMG apps, so that the developer in charge of creating the build artefacts (at this point in time: me) can import it into his/her KeyChain.

**Comment by danielweck** [comment]
Update: we now have a working setup for signing and notarizing Thorium for Mac OS, with LCP enabled. Next: Mac App Store deployment (which requires a different certificate and provisioning profile).

**Comment by danielweck** [comment]
Progress (sort of) for Mac App Store (MAS): https://github.com/readium/readium-desktop/pull/1018

**Comment by CircularKen** [comment]
Codesign missed off Thorium 1.3.1-alpha.1.2515
<img width="532" alt="image" src="https://user-images.githubusercontent.com/17338941/86605166-40bbaa00-bf9e-11ea-9436-15f846b7530d.png">

**Comment by danielweck** [comment]
Hello @CircularKen , the automated CI builds (from Travis and AppVeyor Continuous Integration servers) are not code-signed (Mac, Windows or Linux), and not notarised (Mac).
