### ISSUE TITLE
Avoid using blocking I/O operations in the main process

### ISSUE THREAD

**Issue by panaC** [edrlab/thorium-reader#982]
https://github.com/readium/readium-desktop/blob/9db3c94263e768ac61397727b398df6793ed0486/src/main/keyboard.ts#L83

https://www.electronjs.org/docs/tutorial/performance#how

What do you think ?
Why did we use the synchronised version of the readFile function ?

**Comment by danielweck** [comment]
I agree about considering this issue a non-issue :)
(no performance degradation because of this sync file read)

**Comment by panaC** [comment]
I still think there is a performance degradation
but let's close the issue. doesn't matter
