### ISSUE TITLE
LSD server latency => no UI indicator of inderminate progress => confusing UX

### ISSUE THREAD

**Issue by danielweck** [edrlab/thorium-reader#983]
Example UX: when opening a protected EPUB with slow LSD server, mouse click on thumbnail cover image gives impression that nothing is happening, user clicks several times, then finally the book opens in its reader view (from the very first click! ... not sure how subsequent clicks are handled?).

The same latency occurs when opening the "publication info" dialog, but in this case there is a circular indeterminate progress indicator, letting the user know that some background operation in ongoing.

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/readium-desktop/issues/996

**Comment by llemeurfr** [comment]
The http call to the LSD server should have a low timeout, e.g. 1.5 sc, after which the app should consider that the LSD server is down, and proceed with the opening process using the current license.  
During this time, a spinner should be displayed, so the user knows there is something happening. 
Multi-clicks must be avoided during this time.

**Comment by panaC** [comment]
The actual timeout to the lsd server is 2sec , https://github.com/readium/r2-lcp-js/commit/fea78805d8c7b2e0b596c40232950aed065b5c59 
That is pretty low, we can just add a little spinner in the top right of the publication cover to indicate an action.

In the top right corner we could imagine an lcp icon in front of the image which is replace with a spine loader when this publication tries to open.

**Comment by danielweck** [comment]
Closing issue, thanks to the removal of an unnecessary LSD request, and the recent refactoring of network stack
